### ISSUE TITLE
switch between account

### ISSUE THREAD

**Issue by mahyartb** [ohld/igbot#10]
hi bro thank u for the script
is there any way to switch between account?
log out from one account and login with another

**Comment by mahyartb** [comment]
https://github.com/ohld/instabot/blob/master/instabot/api/api.py#L50

**Comment by ohld** [comment]
Now you can do this:
```python
from instabot import Bot
bot = Bot()
bot.login("user1", "pass1")
...
bot.logout()
bot.login("user2", "pass2")
...
bot.logout()
```
