### ISSUE TITLE
Adding new line in caption when uploading photo

### ISSUE THREAD

**Issue by HappySeal** [ohld/igbot#1002]
---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

Is there any way to add new line to caption of some post like "\n" in python

**Comment by ivurs** [comment]
Can I ask why upload_photos success, but not caption though they do exists when print out

**Comment by unickorn** [comment]
bump?
