### ISSUE TITLE
Not using selenium?

### ISSUE THREAD

**Issue by alinakhay** [ohld/igbot#1006]
Hi ,Thanks for your bot! 
As far as I see , it does not use selenium, but how is it working otherwise? 
Does it mean I am less likely to be blocked using your bot (as oppose to one that relies on selenium browser) because instagram is less likely to detect bot-like behaviour?
Thank you.

**Comment by ohld** [comment]
It changes requests headers to look like Android app, read more here: https://medium.com/@okhlopkov/use-private-instagram-api-for-free-faaaa527274f
