### ISSUE TITLE
upload_photos.py doesn't work

### ISSUE THREAD

**Issue by bigmim** [ohld/igbot#1010]
Bot starts, logins successfully, finds the photo, tells the photo does not have a compatible aspect ratio (and it's true), so it's not uploaded....something went wrong.
Instead, I expected the photo was cropped and resized and then uploaded.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x ] Updated to the latest version
- [x ] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x ] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Help solving problem

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python 3.7`` here:

Code:

```python
bot.logger.info("Uploading pic `{pic}` with caption: `{caption}`".format(pic=pic, caption=caption))
        if not bot.upload_photo(os.path.dirname(os.path.realpath(__file__)) + "/media/" + pic, caption=caption):
            bot.logger.error("Something went wrong...")
            break


---

### Describe your issue

Explanation of your issue goes here. Please make sure the description is worded well enough to be understood with as much context and examples as possible.

**Comment by adp44** [comment]
@bigmim try examples/autopost/auto_post.py I had the same problem, auto_post.py works for me. I changed it to one photo. Maybe it's about imports? I'm sorry, I didn't have time to study the problem. The change in the aspect ratio, you can figure it out for yourself :)

**Comment by disayner** [comment]
where is the error text? And what is your photo called?

**Comment by bigmim** [comment]
The error is that the program stops and says: the photo does not have a compatible aspect ratio.
Photo is not uploaded ....something went wrong.

I'm referring to the upload_photos.py script and not to auto_upload.py.

I know that auto_upload.py can not upload photos not having compatible aspect ratio.
Instead, upload_photos.py should be able to manage photos, cropping and resizing, and upload with right aspect ratio. That's the matter.

**Comment by bigmim** [comment]
The error is that the program stops and says: the photo does not have a
compatible aspect ratio.
Photo is not uploaded ....something went wrong.

I'm referring to the upload_photos.py script and not to auto_upload.py.

I know that auto_upload.py can not upload photos not having compatible
aspect ratio.
Instead, upload_photos.py should be able to manage photos, cropping and
resizing,
and upload with right aspect ratio. But it doesn't and that's the matter.

Il giorno mer 21 ago 2019 alle ore 12:58 disayner <notifications@github.com>
ha scritto:

**Comment by phcamargo23** [comment]
I have same problem
