### ISSUE TITLE
How can I get a list of recent followers?

### ISSUE THREAD

**Issue by hosnas** [ohld/igbot#1011]
I dont want to download the complete list of followers and compare it with before. Is there another method to get a list of recent followers? for example for the last hour.

**Comment by ohld** [comment]
you can try to get feed updates - there you can find new fellowships, likes, and comments. But in that case you don't need to open this tab on your instagram app

**Comment by hosnas** [comment]
@ohld Ok so can you tell me how to get feed update and how to filter it to get followers?

I dont find it in docs and examples

**Comment by ohld** [comment]
https://github.com/instagrambot/instabot/blob/aa83c9a12cf17645bedd05c70cb97ed9f4c351c1/instabot/api/api.py#L538

**Comment by Abdulsamipy** [comment]
> https://github.com/instagrambot/instabot/blob/aa83c9a12cf17645bedd05c70cb97ed9f4c351c1/instabot/api/api.py#L538

is it possible to download the list of followers in the form of .csv?
