### ISSUE TITLE
Please add condition for filtering user if contain blacklist words

### ISSUE THREAD

**Issue by lenivyi** [ohld/igbot#102]
I want to filter username that contain blacklist word like "store", "shop", etc.
Please add this condition to check_user function in bot_filter.py and add stop_users to constructor in bot.py 

```
stop_users = []

if 'username' in user_info:
        test = user_info['username'].lower()
        for stop_user in self.stop_users:
            if stop_user in test:
                return False
```

thank you

**Comment by ohld** [comment]
will be added in 0.3.3.4
