### ISSUE TITLE
how to not skip any profiles

### ISSUE THREAD

**Issue by ghost** [ohld/igbot#1020]
hello, how do I stop the bot from skipping private accounts, no profile picture pic accs, etc... ?

**Comment by disayner** [comment]
When you create a bot variable, the following settings are automatically assigned
`        whitelist_file='whitelist.txt',
        blacklist_file='blacklist.txt',
        comments_file='comments.txt',
        followed_file='followed.txt',
        unfollowed_file='unfollowed.txt',
        skipped_file='skipped.txt',
        friends_file='friends.txt',
        base_path='',
        proxy=None,
        max_likes_per_day=1000,
        max_unlikes_per_day=1000,
        max_follows_per_day=350,
        max_unfollows_per_day=350,
        max_comments_per_day=100,
        max_blocks_per_day=100,
        max_unblocks_per_day=100,
        max_likes_to_like=100,
        min_likes_to_like=20,
        max_messages_per_day=300,
        filter_users=True,
        filter_private_users=True,
        filter_users_without_profile_photo=True,
        filter_previously_followed=False,
        filter_business_accounts=True,
        filter_verified_accounts=True,
        max_followers_to_follow=2000,
        min_followers_to_follow=10,
        max_following_to_follow=2000,
        min_following_to_follow=10,
        max_followers_to_following_ratio=10,
        max_following_to_followers_ratio=2,
        min_media_count_to_follow=3,
        max_following_to_block=2000,
        like_delay=10,
        unlike_delay=10,
        follow_delay=30,
        unfollow_delay=30,
        comment_delay=60,
        block_delay=30,
        unblock_delay=30,
        message_delay=60,
        stop_words=('shop', 'store', 'free'),
        blacklist_hashtags=['#shop', '#store', '#free'],
        blocked_actions_protection=True,
        verbosity=True,
        device=None`

Change them to change the filtering conditions. eg:
`bot = Bot(filter_users=False, filter_private_users=False, filter_users_without_profile_photo=False)`

**Comment by ghost** [comment]
> When you create a bot variable, the following settings are automatically assigned
> ` whitelist_file='whitelist.txt', blacklist_file='blacklist.txt', comments_file='comments.txt', followed_file='followed.txt', unfollowed_file='unfollowed.txt', skipped_file='skipped.txt', friends_file='friends.txt', base_path='', proxy=None, max_likes_per_day=1000, max_unlikes_per_day=1000, max_follows_per_day=350, max_unfollows_per_day=350, max_comments_per_day=100, max_blocks_per_day=100, max_unblocks_per_day=100, max_likes_to_like=100, min_likes_to_like=20, max_messages_per_day=300, filter_users=True, filter_private_users=True, filter_users_without_profile_photo=True, filter_previously_followed=False, filter_business_accounts=True, filter_verified_accounts=True, max_followers_to_follow=2000, min_followers_to_follow=10, max_following_to_follow=2000, min_following_to_follow=10, max_followers_to_following_ratio=10, max_following_to_followers_ratio=2, min_media_count_to_follow=3, max_following_to_block=2000, like_delay=10, unlike_delay=10, follow_delay=30, unfollow_delay=30, comment_delay=60, block_delay=30, unblock_delay=30, message_delay=60, stop_words=('shop', 'store', 'free'), blacklist_hashtags=['#shop', '#store', '#free'], blocked_actions_protection=True, verbosity=True, device=None`
> 
> Change them to change the filtering conditions. eg:
> `bot = Bot(filter_users=False, filter_private_users=False, filter_users_without_profile_photo=False)`

thanks sir
