### ISSUE TITLE
error on loading cookie file when you set base_path

### ISSUE THREAD

**Issue by elmissouri16** [ohld/igbot#1021]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x ] Updated to the latest version
- [ x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x ] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

Code:

```python
# Example code that will produce the error reported
from instabot import Bot

bot = Bot()
bot.login(username="user", password="pass")
followers = bot.get_user_followers(bot.user_id)
```

Error/Debug Log:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: integer division or modulo by zero
```

---

### Describe your issue

[https://github.com/instagrambot/instabot/blob/94d271520e84641d1391bcf25bdad0dd547cf62e/instabot/api/api_login.py#L188]()
on this, its should  read `self.cookie_fname` instead of `fname`

**Comment by elmissouri16** [comment]
@Tkd-Alex  is the fix available on the repo and pip  ??

**Comment by ohld** [comment]
yes, try `pip install -U instabot` to update

**Comment by elmissouri16** [comment]
> 
> 
> yes, try `pip install -U instabot` to update

ok thank you
