### ISSUE TITLE
Request returns 400 error!

### ISSUE THREAD

**Issue by LongTalent** [ohld/igbot#1025]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here: Python 3.4.2 

Code:

```python
python3 watch_user_likers_stories.py
```

Error/Debug Log:

```python
Request returns 400 error!
2019-08-31 17:13:45,581 - INFO - 
            Going to get your likers and watch their stories (and stories of their likers too).
            You can specify username of another user to start (by default we use you as a starting point).
        
Traceback (most recent call last):
  File "watch_user_likers_stories.py", line 41, in <module>
    user_to_get_likers_of = bot.user_id
  File "/usr/local/lib/python3.4/dist-packages/instabot/bot/bot.py", line 286, in user_id
    return self.api.user_id
  File "/usr/local/lib/python3.4/dist-packages/instabot/api/api.py", line 502, in user_id
    return self.cookie_dict["ds_user_id"]
KeyError: 'ds_user_id'
```

---

### Describe your issue

I tried out instabot today first time. I wanted to use it to view stories of other users. When I try it I'm asked for account first and then I get the error above. I have the same problem with another example python scripts. I think the problem could be that I'm on vacation in another country now (Instagram knows where I am) and I'm trying to run the statement above from a remote server in my home country. After every run Instagram website asks me if I just tried to login in my home country (Germany):
<img width="483" alt="Bildschirmfoto 2019-08-31 um 14 01 38" src="https://user-images.githubusercontent.com/29812394/64065740-c4379c80-cc11-11e9-94bb-0715dd57afee.png">
I can commit that it was me, but after the next run of python script I see this question again.

Can anyone tell me what I'm doing wrong?

Best regards

**Comment by vladpolyanskiy** [comment]
Same here.

**Comment by TheProOfficial** [comment]
Same.

**Comment by powderblock** [comment]
Same here. USA

**Comment by powderblock** [comment]
Fixed!

**Solution:** _Check your username and pass_
Business accounts will not work for this type of login.

**Comment by TheProOfficial** [comment]
> Fixed!
> 
> **Solution:** _Check your username and pass_
> Business accounts will not work for this type of login.

Well, I didn't know business accounts wouldn't work. But now I can't delete the original username and pass because of this error _(yes I tried restarting my PC)_: PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'secret.txt'

**Comment by LongTalent** [comment]
I deleted my username and entered it again. After that it seems to work. The password was definitely right. Don't ask me what have changed. Try it also. I will close the issue.

**Comment by ghonchesefidi** [comment]
> Fixed!
> 
> **Solution:** _Check your username and pass_
> Business accounts will not work for this type of login.

I had changed my profile to personal but still no luck.

**Comment by mar71ns** [comment]
Same problem here!
After trying to log in instagram detected an atypical login attempt and asked me if I tried.

**Comment by steffanjensen** [comment]
This is a common problem happens to 2 out of 5 accounts, this can be fixed 90% of the time by using challenge required.
