### ISSUE TITLE
EXAMPLE: follow hashtag's likers

### ISSUE THREAD

**Issue by ulyssesmurgia** [ohld/igbot#103]
Is it possible to follow users who have liked media with a particular hashtag?
For example, I define which hashtags and the bot will fetch the medias with this hashtag and follow the users who like them.

**Comment by romeumellobr** [comment]
After some likes by hashtag, the bot drops 400 error and mess counting of total liked media.

2017-03-23 11:43:14,824 Going to like 75 medias.
2017-03-23 11:56:01,440 Request return 400 error!
2017-03-23 11:56:11,440 DONE: Total liked 145 medias.
