### ISSUE TITLE
Running follow and likes 24/7

### ISSUE THREAD

**Issue by lxknvlk** [ohld/igbot#1031]
Hi all! What would be the easiest way to run the bot 24/7? I'm thinking about pm2, but which script should I run? O want it to follow and unfollow users, and like posts. Is there such a script, or do I have write my own?

**Comment by Skeyelab** [comment]
@lxknvlk examples/ultimate_schedule

**Comment by hhamed1989** [comment]
> @lxknvlk examples/ultimate_schedule

Dears,
we want follow user list for ultimat, but haven't any arg like nfollow to force stop ...

is there any option for ultimate foloow users by list ?

**Comment by yuricroci** [comment]
I use this script but after 3 likes actions I was blocked
