### ISSUE TITLE
getting account followers with pagination

### ISSUE THREAD

**Issue by lxknvlk** [ohld/igbot#1034]
How to get account followers with pagination? Like get followers 0-500. Separate request to get 500-1000 followers. Then separate request to get next 500 followers. How to implement this?

Lets say an account has 10k followers. 

I want to get 500 followers, process them. Then the script will sleep for 2 hours.

Then i want to get next 500 followers, and process them, etc like that. 

For a 10k account i could just get all followers, persist them, and then process batch by batch as needed. But for a 1m followers account this wont work.

**Comment by juhorichard** [comment]
Good idea
