### ISSUE TITLE
disable file creation in root dir

### ISSUE THREAD

**Issue by lxknvlk** [ohld/igbot#1035]
Whenever i run my main.py file where i use instabot, it creates lots of different files in the directory. How can i disable this?

**Comment by lxknvlk** [comment]
setting bot.base_path does not work. I have tried next variants, none worked:

bot.base_path = "libfiles"
bot.base_path = "libfiles/"
bot.base_path = "/libfiles"
bot.base_path = "/libfiles/"
bot.base_path = "./libfiles/"

**Comment by lxknvlk** [comment]
also setting next params does not stop the bot from creating the files

    bot.blacklist_file = ""
    bot.whitelist_file = ""
    bot.comments_file = ""
    bot.unfollowed_file = ""
    bot.skipped_file = ""
    bot.followed_file = ""

**Comment by lxknvlk** [comment]
also setting files like this does not help:

    base_dir = "libfiles/"
    bot.base_path = base_dir
    bot.blacklist_file = base_dir + "blacklist.txt"
    bot.whitelist_file = base_dir + "whitelist.txt"
    bot.comments_file = base_dir + "comments.txt"
    bot.unfollowed_file = base_dir + "unfollowed.txt"
    bot.skipped_file = base_dir + "skipped.txt"
    bot.followed_file = base_dir + "followed.txt"

There must be some kind of a bug

**Comment by ohld** [comment]
... or some kind of shitcode. We need a contributor to implement a more elegant way to solve this.

**Comment by noxevolution** [comment]
I have the same problem. I managed to create the other files in a different folder but the config & log folder & 2 other files are still getting created on the root folder.

```
bot = Bot(
            whitelist_file=util_path + '/whitelist.txt',
            blacklist_file=util_path + '/blacklist.txt',
            comments_file=util_path + '/comments.txt',
            followed_file=util_path + '/followed.txt',
            unfollowed_file=util_path + '/unfollowed.txt',
            skipped_file=util_path + '/skipped.txt',
            friends_file=util_path + '/friends.txt',
)  
```
Whenever i try to use the parameter base_path here i am getting "No such file or directory" error.

**Comment by bruvv** [comment]
Since this is very old issue I am going to close this. If this is still an issue please reopen a new issue.
