### ISSUE TITLE
welcome_message.py receiving feedback_required error

### ISSUE THREAD

**Issue by jeffbruchado** [ohld/igbot#1036]
Hi guys, when I'm trying to run the script 'welcome_message.py' I'm receiving the next error message 

`2019-09-08 14:28:21,562 - ERROR - Error checking for `feedback_required`, response text is not JSON` 

and I don't know how to resolve that, has anyone had this problem before?

**Comment by ohld** [comment]
This is because of Instagram blocking out tools. I know that https://github.com/mgp25/Instagram-API/ has a working version of this endpoint. Can someone test it?

**Comment by bruvv** [comment]
This has been fixed.
