### ISSUE TITLE
how to disable bot parameters check

### ISSUE THREAD

**Issue by lxknvlk** [ohld/igbot#1037]
How to make bot ignore default parameters?

    bot.min_followers_to_follow
    bot.min_following_to_follow
    bot.max_following_to_follow
    bot.max_followers_to_follow

And all others? I want to manage those limits manually.

**Comment by yemreak** [comment]
You can change them in class creation with keyword params like:

```py
import instabot
bot = instabot.Bot(min_followers_to_follow=0, max_followers_to_follow=9000, ...)
```

**Comment by ohld** [comment]
The default values should be ok for most cases. But if you want to ignore them, you can just change them as @yedhrab suggested. Or we can ask contributors to create a more elegant way to do it.
