### ISSUE TITLE
how to disable bot logs

### ISSUE THREAD

**Issue by lxknvlk** [ohld/igbot#1038]
how do i disable the default bot logs?

**Comment by ingmferrer** [comment]
Hello, try:

`bot = Bot(save_logfile=False)`

I hope this help.

**Comment by ohld** [comment]
Can you also please share why do you want to disable logs? Which situation can force you to disable them?

**Comment by mbbroberg** [comment]
Hey @ohld, what would be helpful to resolve this issue? My initial idea is to add an example where `save_logfile=False` is set, but I'm not sure if that's what you'd like to see. Lmk 👌
