### ISSUE TITLE
auto_post.py Not Working, Selecting Account and Does Nothing

### ISSUE THREAD

**Issue by milesdunkley** [ohld/igbot#1043]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here: 

**python -V** =  Python 2.7.15+
**python3 -V** = Python 3.6.8

Code: 

```python

Which account do you want to use? (Type number)
1: instagram_name
0: add another account.
-1: delete all accounts.

```

### Describe your issue

Having a problem with the python auto_post.py script. I execute the command `python auto_post.py`, and it brings me to the menu to select my Instagram account ("Which account do you want to use?" 1, 2, 3, etc.) but when I select the account (by entering 1) it does nothing but displays the value I have just typed.

![image](https://user-images.githubusercontent.com/54372721/64697664-3b362600-d499-11e9-96cf-4b9774ed375c.png)

As you can see, after I have entered "1" the machine does nothing just relays the number I have entered.

**Comment by bruvv** [comment]
please update the bot, if you still have issues reopen a new issue please.
