### ISSUE TITLE
Does the proxy not work?

### ISSUE THREAD

**Issue by disayner** [ohld/igbot#1048]
### Before submitting an issue, make sure you have:
- [ x] Updated to the latest version
- [x ] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [ x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

Python v 3.7.1

I updated the instabot version from 52 to 58. I pass the values from the proxy to the script (the script did not change, it remains the same):
`bot.login(username='login', password='pass', proxy='http://host@ip:pass', use_cookie=False)`
As a result, the script went online on my IP and not through a proxy ... With all the sad consequences((( Please check if anyone else has this problem?

**Comment by ingmferrer** [comment]
Try:
`bot = Bot(proxy='ip:port')`

**Comment by disayner** [comment]
> 
> 
> Try:
> `bot = Bot(proxy='ip:port')`

thank

**Comment by steffanjensen** [comment]
same issue
