### ISSUE TITLE
Get list of users who subscribed to hashtag

### ISSUE THREAD

**Issue by python-vlad** [ohld/igbot#1050]
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

Purpose of your issue?

- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

```
from instabot import Bot
bot = Bot()
bot.login(username='login', password='pass', proxy='111.111.111.111:2222')
users = bot.get_hashtag_users('Tag')
print(users)
```

This way I get a list of id users who published media with this hashtag. But this is not what I need to know. **How to get a list of users who subscribed to hashtag?**

**Comment by elmissouri16** [comment]
I don't think this possible since they are no way on Instagram to get users who follow a specific hashtag
