### ISSUE TITLE
How to update photo description

### ISSUE THREAD

**Issue by yapizza** [ohld/igbot#1052]
Hi, сan I update the description of the photo after uploading?

**Comment by ohld** [comment]
Right now we don't have this endpoint implemented. But this library:
https://github.com/mgp25/Instagram-API/
has it. We need a contributor to implement it in Instabot. I think it would be very useful for all users.

**Comment by areebahmed04** [comment]
Hi @ohld I am willing to work on it.

**Comment by bruvv** [comment]
This has been done now in the new version.
