### ISSUE TITLE
How can I selectively unfollow people who don't engage with by posts ?

### ISSUE THREAD

**Issue by ishandutta2007** [ohld/igbot#1053]
I want to selectively unfollow people who are not active especially with respect to engaging with my posts.

**Comment by ohld** [comment]
You can just download the lists of likers of all your posts. And all commenters. And then compare them with your followers list.

**Comment by ishandutta2007** [comment]
Basically we need to do a union for all posts and then substract followers set from that huge set. that pretty hard word. let us know if there is an api close to that.
Besides there are various aspects to it, it's lot complex than that,
- We need to spare the recent followers, we have to give them time before we can conclude if they are active engager or not.
- We not just need a union we need union with frequency, we may also like to unfollow a user who is following me for a long time but may have hardly liked once or twice vs someone who has liked hundreds of  my posts. so in other words maximising the ratio ```( N<likes> + N<comments> ) / T<following>``` People with low value of this ratio should be unfollowed.

**Comment by ohld** [comment]
there is no API for that because you can't see this data inside the instagram app

**Comment by ishandutta2007** [comment]
Yes you need to cached the data periodically locally.
