### ISSUE TITLE
send welcome message to General Inbox

### ISSUE THREAD

**Issue by EduardKov** [ohld/igbot#1057]
When using the welcome message to new followers script, is there a way to send welcome message to General Inbox? I’m getting 100+ new followers per day so my Primary Inbox gets massive.

**Comment by ohld** [comment]
I don't know how to make it, but a future contributor can find the right way to do it in PHP library: https://github.com/mgp25/Instagram-API/

**Comment by AKwoKWH** [comment]
logic:
1) extract current followers to save in file1 < this is the history followers list
2) extract current followers to save in file2 < this is the latest followers list
3) for followers in file2 not in file1: send welcome msg
4) save file2 as file1 
5) repeat step2 to step5 at specific time
