### ISSUE TITLE
Username placeholder?

### ISSUE THREAD

**Issue by Skeyelab** [ohld/igbot#1061]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

In GramUp, we can do `[[username]]` to use the username of the account we are commenting on in a comment.  Is there a way to do this with instabot?

**Comment by ohld** [comment]
Hi! Not yet, but maybe someone will add this to instabot.

**Comment by danomaj** [comment]
Hello, can I start working on this? Thanks.
