### ISSUE TITLE
Any way to get full muted users list?

### ISSUE THREAD

**Issue by ckrl** [ohld/igbot#1062]
### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### Describe your issue

Is there a way to get a list of users I've muted (both stories and posts)?

api.send_request('friendships/muted_reels') - gets a list of users with muted stories only.

I suggested that there should be an endpoint 'friendships/muted' similar to 'friendships/blocked' and 'friendships/blocked_reels' pair, but it's not.

**Comment by naeem91** [comment]
I'm trying to address this in #1080 Not sure how to get list by muted posts? or by both stories or posts.

**Comment by bruvv** [comment]
Merged so I am closing this. If this is still an issue please open a new issue :)
