### ISSUE TITLE
Can we make this PEP8 compliant?

### ISSUE THREAD

**Issue by jontymorris** [ohld/igbot#1069]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

### Describe your issue
Most, if not all, files are non compliant with the PEP8 style guide. While this is not a major issue, I think it would make the code cleaner and easier to maintain if everything were compliant with the PEP8 guidelines. Future contributors would also have a clear set of guidelines to follow, so they couldn't submit messy code!

Should I make all the files PEP8 compliant?  😄

**Comment by ohld** [comment]
Hi. The project has CI that checks the PEP8, you can find all instructions in Travis-CI config (.travis.yml). If for some reason some of the files become uncompliant, feel free to create a pull request with code style fixes, but also make sure to add the auto-pep8-check to the current CI pipeline to check the code style of all future pull requests.

**Comment by jontymorris** [comment]
I'm making a start on this now #1072
