### ISSUE TITLE
No Handlers Could be Found in Logger Error

### ISSUE THREAD

**Issue by sudo-judo** [ohld/igbot#1070]
![Screenshot_20191004-090850](https://user-images.githubusercontent.com/34294096/66176561-65d66180-e688-11e9-8b86-88085b336ac0.png)

Does anyone having same issue here?  I'm running instabot on vps with python 2.7.6 and i got this error "like action has been blocked" but watching stories is working charm, what should i do???

**Comment by ohld** [comment]
What script are you trying to launch? And with what params?

**Comment by sudo-judo** [comment]
I used default infinity_feedliker... I just edit the bot params in local and make some to be "false" 
It is fresh install and im using VPS

**Comment by sudo-judo** [comment]
I found that i could get this error "No Handlers Could be Found in Logger" and "Action Blocked Immediately"
If i sets the def get_timeline_medias to "False"  because if i leave this setting to "True" then i couldnt liking my timeline feeds.... Is there any ways to solve this???

**Comment by Pitti1981** [comment]
Hi...are there any news about this issue? Can't like, follow, etc. for a while... :-(

thx a lot!

**Comment by avishaan** [comment]
I think i'm having the same issue

**Comment by ghost** [comment]
I have the same issue.

**Comment by avishaan** [comment]
still having the same issue

**Comment by Abassina** [comment]
Same issue for me ...

**Comment by RETROXD** [comment]
ye same here.......... PLZ fix or help

**Comment by fighterii** [comment]
Logging is fixed with #1223 and #1205 . @bruvv : think we can close this.

**Comment by bruvv** [comment]
Closed. Reopen a new issue if someone still has issues.
