### ISSUE TITLE
 unfollow requests to follow

### ISSUE THREAD

**Issue by gvmturl** [ohld/igbot#1073]
Hello guys how are you_ Is here any script to unfollow my requests to follow?

Thank you

**Comment by elmissouri16** [comment]
you mean cancel the pending follow requests ??

**Comment by gvmturl** [comment]
> you mean cancel the pending follow requests ??

Yes, that is it!

**Comment by elmissouri16** [comment]
the unfollow function on the API cancel the follow request if the user did not accept  if keep list of users you followed or try to follow you cam iterate throw them and cancel the follow request of users you did not follow

**Comment by gvmturl** [comment]
> the unfollow function on the API cancel the follow request if the user did not accept if keep list of users you followed or try to follow you cam iterate throw them and cancel the follow request of users you did not follow

Thank you for replying bro.

If i use unfollow non followers on multi_script_CLI didnt take the list from pending follow requests.

**Comment by elmissouri16** [comment]
this not implemented to any of the examples provided you have to code the way suit and you the list of users you target later to check of the one non followed and cancel the pending request

**Comment by gvmturl** [comment]
There is no examples to unfollow from file and to take the list could be something hard if you have a lot of contacts that didnt acept you... i followed this steps to take the list:
Go to Instagram.com
Click on your profile then the settings icon
Click ‘Privacy and security’
Under ‘Account data’, Click on ‘View account data’
Under ‘Connections’, click on ‘View all current follow requests’

But have to click on "MORE" more than 100 times...

Thats why i asked for some example that do that, i dont have 
knowledge to code that.

**Comment by gvmturl** [comment]
Any help? Thank you!

**Comment by gvmturl** [comment]
Anyone could help me with this action please?
