### ISSUE TITLE
getting blocked

### ISSUE THREAD

**Issue by gvmturl** [ohld/igbot#1074]
Hello guys. always being blocked even using the default config on bot. Get "resquest action" than blocked by instagram. I always try to maintain the bot update. Is there any way to automate the bot update?
Any idea about that blocks?

Please, let me know if i m doing something wrong.

Thank you guys.

**Comment by Hoefnix** [comment]
have no solution, but i'm getting blocks everytime too... any help would be appreciated

**Comment by ohld** [comment]
Blocks depend on the account age and in-app activity.

**Comment by Hoefnix** [comment]
could you elaborate on that... I have a rather old account blocked now ...and one I made to test. The dummy account lasted a while longer but got also blocked after a while

**Comment by gvmturl** [comment]
Same here... News and olds acc getting blocked.

Any solution @ohld ?

Thanks a lot!

**Comment by roberterzen** [comment]
@ohld mentioned that higher in-app activity would lower incidence of blockages. Or at least I understood him that way.
Does anyone knows is it enough to scroll down your post feed to accumulate "in-app activity" or should activity be more diverse?
