### ISSUE TITLE
404 in docs website

### ISSUE THREAD

**Issue by rmant** [ohld/igbot#1075]
### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Describe your issue

I'm not sure this should be an issue since it's not directly code-related, but I didn't know here else to send it.

I'm getting a 404 when accessing the documentation website (https://instagrambot.github.io/docs/home.html). I went through by clicking the "Read the Docs" button on the main page.

**Comment by ohld** [comment]
This link should be changed to `https://instagrambot.github.io/docs/`

**Comment by komish** [comment]
I'm not able to replicate. This looks solved to me?

**Comment by rmant** [comment]
> I'm not able to replicate. This looks solved to me?

It's still throwing a 404. Go to https://instagrambot.github.io/home.html and click the "Read the Docs" button under the features section. 

The right url is the one @ohld said.

**Comment by komish** [comment]
Ah, I was looking in the wrong place. PR submitted to the pages repository.

Thanks for participating in Hacktoberfest 2019!
