### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by deadcyph3r** [ohld/igbot#1077]
I am getting AssertionError error, what should I do?

>   File "instabot/examples/multi_script_CLI.py", line 686, in <module>
    bot.login()
  File "/root/Desktop/bots/insta/lib/python3.7/site-packages/instabot/bot/bot.py", line 364, in login
    if self.api.login(**args) is False:
  File "/root/Desktop/bots/insta/lib/python3.7/site-packages/instabot/api/api.py", line 201, in login
    if (self.load_uuid_and_cookie(load_cookie=use_cookie, load_uuid=use_uuid) is True):
  File "/root/Desktop/bots/insta/lib/python3.7/site-packages/instabot/api/api.py", line 161, in load_uuid_and_cookie
    return load_uuid_and_cookie(self, load_uuid=load_uuid, load_cookie=load_cookie)
  File "/root/Desktop/bots/insta/lib/python3.7/site-packages/instabot/api/api_login.py", line 199, in load_uuid_and_cookie
    assert cookie_username == self.username.lower()
AssertionError

**Comment by ohld** [comment]
Delete txt files in your folder and try again, don’t forget to enter your username with lowercase.

**Comment by Gordon0918** [comment]
> Delete txt files in your folder and try again, don’t forget to enter your username with lowercase.

Deleting the username.checkpoint and the username _uuid_and_cookie.json can be solved, but how to use the last cookie when logging in again, the use_cookie option is True

**Comment by Gordon0918** [comment]
> > Delete txt files in your folder and try again, don’t forget to enter your username with lowercase.
> 
> Deleting the username.checkpoint and the username _uuid_and_cookie.json can be solved, but how to use the last cookie when logging in again, the use_cookie option is True

I know, I use the phone number + password to log in, but the ds_user field in the cookie file is my username, login with the user name + password will work normally.
