### ISSUE TITLE
'ds_user_id'

### ISSUE THREAD

**Issue by cala095** [ohld/igbot#1092]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here: 

Python 3.7.2

Code:

sudo python like_hashtags.py dog

Error/Debug Log:

2019-10-19 12:29:01,381 - INFO - Instabot Started
Which account do you want to use? (Type number)
1: mad_mango95
2: black_book000
0: add another account.
-1: delete all accounts.
2
No handlers could be found for logger "[instabot_black_book000]"
2019-10-19 12:29:07,368 - INFO - Going to like media with hashtag #dog.
Traceback (most recent call last):
  File "like_hashtags.py", line 26, in <module>
    bot.like_hashtag(hashtag)
  File "/usr/local/lib/python2.7/dist-packages/instabot/bot/bot.py", line 687, in like_hashtag
    return like_hashtag(self, hashtag, amount)
  File "/usr/local/lib/python2.7/dist-packages/instabot/bot/bot_like.py", line 235, in like_hashtag
    medias = self.get_total_hashtag_medias(hashtag, amount)
  File "/usr/local/lib/python2.7/dist-packages/instabot/bot/bot.py", line 535, in get_total_hashtag_medias
    return get_total_hashtag_medias(self, hashtag, amount, filtration)
  File "/usr/local/lib/python2.7/dist-packages/instabot/bot/bot_get.py", line 139, in get_total_hashtag_medias
    medias = self.api.get_total_hashtag_feed(hashtag, amount)
  File "/usr/local/lib/python2.7/dist-packages/instabot/api/api.py", line 1475, in get_total_hashtag_feed
    self.get_hashtag_feed(hashtag_str, next_max_id)
  File "/usr/local/lib/python2.7/dist-packages/instabot/api/api.py", line 1134, in get_hashtag_feed
    hashtag=hashtag, max_id=max_id, rank_token=self.rank_token
  File "/usr/local/lib/python2.7/dist-packages/instabot/api/api.py", line 556, in rank_token
    return "{}_{}".format(self.user_id, self.uuid)
  File "/usr/local/lib/python2.7/dist-packages/instabot/api/api.py", line 552, in user_id
    return self.cookie_dict["ds_user_id"]
KeyError: 'ds_user_id'

---

### Describe your issue
i get this 'ds_user_id' error for everything i try to do with the bot, i think is a login problem but 'm not sure cause i don't fully understand it :(

**Comment by taylorturner** [comment]
Having the same issue.

**Comment by ghonchesefidi** [comment]
Same here

**Comment by DeadmauZ** [comment]
same issue help

**Comment by avishaan** [comment]
same issue, slightly related I thought if I could just log in again I might be able to solve the problem. Unfortunately, even when I do `use_cookies=False, force=True` and delete the cookie file (the default in the documentation seems to be wrong) it no longer logs in and just hangs now

**Comment by silvanarmbruster** [comment]
Someone figured out whats the problem? Would be soooo nice!

**Comment by leoccyao** [comment]
Duplicate of #860 . First check your username and password, if they are correct, you received an instagram checkpoint challenge. Use 
```
bot.login(ask_for_code=True)
```

Also see #1140

**Comment by KadabrahG** [comment]
> Duplicate of #860 . First check your username and password, if they are correct, you received an instagram checkpoint challenge. Use
> bot.login(ask_for_code=True)
> 
> Also see #1140

Hey, where should this line of code be inserted ? Thanks <3

**Comment by bruvv** [comment]
Closing since this question has been answer many times now.if the issue is still here open a new one.

**Comment by ghost** [comment]
@bruvv i still get the issue tried everything even inserting `ask_for_code=True` but still doenst work

**Comment by janvarsa** [comment]
bot.login(ask_for_code=True) results in same error after the prompt for username and password.
