### ISSUE TITLE
Error 400, feedback_required , this action was blocked

### ISSUE THREAD

**Issue by Comizzz** [ohld/igbot#1105]
I'm not a software engineer. I don't know much about software. Please help me.
![2019-10-27_01-12-51](https://user-images.githubusercontent.com/45639672/67626673-6b723200-f857-11e9-9751-497fc655f421.png) This photo is the error code I received.

**Comment by F-W-D** [comment]
Hey if your looking to automate your account, but are uninterested in software development then I would suggest this free Chrome extension it will be a lot more user-friendly:

https://chrome.google.com/webstore/detail/gram-up-–-free-instagram/njonkbhnmmjgancfbncekpgkmidhbbpo?hl=en

**Comment by fighterii** [comment]
400 error usually indicates, that login doesn't work correctly

**Comment by bruvv** [comment]
Please search before posting this has been asked and answered  many times.
