### ISSUE TITLE
Is it still working?

### ISSUE THREAD

**Issue by ExileBit** [ohld/igbot#1112]
It doesn´t seem to work for anyone anymore. If it is working for someone please tell me

**Comment by malignantz** [comment]
Using a relatively "fresh" account, I got banned pretty quick, short ban (1-2 days) not a shadowban. Web interface notifies of action block. I did not experience any issues with multiple other "established" accounts.

**Comment by damir-sh** [comment]
@malignantz which scripts have you been using? 

I just tested with a new account with basically no posts etc. Got banned after after about 2-3 hrs using the ultimate.py script.

**Comment by malignantz** [comment]
With the fresh account, I used follow_user_followers of a popular account so requesting all the followers was massive and probably the issue. After ban went away, got banned again almost immediately doing something with less requests - like_hashtags
