### ISSUE TITLE
400 Error (Traceback)

### ISSUE THREAD

**Issue by vinversapub** [ohld/igbot#1115]
![image](https://user-images.githubusercontent.com/51090447/67961778-ed0ceb80-fbda-11e9-8f19-9a0e635781fa.png)

Anyone know how to fix this?!

**Comment by TheScriptingVajra** [comment]
Perhaps login id/password is wrong. Please check and see.

**Comment by leoccyao** [comment]
Duplicate of #860 . First check your username and password, if they are correct, you received an instagram checkpoint challenge. Use 
```
bot.login(ask_for_code=True)
```

Also see #1140

**Comment by viktorvexacious** [comment]
@leoccyao You need to state where to place this piece of code. I figured it out myself, but others might have a harder time.

**Comment by philippklak** [comment]
@vinversapub could you please tell me where to place it?

**Comment by KadabrahG** [comment]
> @leoccyao You need to state where to place this piece of code. I figured it out myself, but others might have a harder time.

Hey ! Where do we have to apply this piece of code ? Thanks

**Comment by bruvv** [comment]
In all the example files there is this line `bot.login` look it up and add the `ask_for_code=True` part.
if this is still an issue please open a new issue.
