### ISSUE TITLE
Q about Suspicious Login Attempt behaviour (#1551, #842, #1581)

### ISSUE THREAD

**Issue by RKeyQQ** [ohld/igbot#1123]
- [x] Updated to the latest version
- [x] Read the [README] and [docs]
- [x] [Searched] the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Question

### Describe your issue
Thanks for the bot :) 

I faced "Suspicious Login Attempt" with "We detected As Unusual Login Attempt" and found few closed issues (#1551, #842 and  #1581) also with fixes. However, I cannot write in closed issues and solutions from 2018 are not working :)
these are:
- fix with user_agent = ("" "")
- fix with  self.user_agent = ("PASTE YOUR USER_AGENT HERE")

The question: is there any chance to extend logging or undestand what exact is wrong? IG is working fine from the browser on the machine where the bot is running.

Probably this might be helpful: 
I used it as described in docs and run only ultimate and multi_script. I run them in PyCharm. However, I noticed that second run is impossible until I delete cookie file. Some errors in the terminal.
Now, when I faced the issue, the cookie file is not creating at all.

Not sure if I should provide any details as it seems that something simple I missing. Anyway, please let me know if I should add something.
Win 10, python 3.7.5

Console log:
D:\.....\instabot-master\examples>python multi_script_CLI.py
2019-11-07 16:02:37,134 - INFO - Instabot Started
Which account do you want to use? (Type number)
1: #############
0: add another account.
-1: delete all accounts.
1
Request returns 400 error!
        1.Follow
...
        7.Exit

What would you like to do?
2
        1. Like from hashtag(s)
        2. Like followers
...
        6. Main menu
How do you want to like?
1
            1.Insert hashtag(s)
            2.Use hashtag database
1
Insert hashtags separated by spaces
Example: cat dog
what hashtags?
###mytagishere###
2019-11-07 16:02:59,720 - INFO - Going to like media with hashtag ####mytagishere###.
2019-11-07 16:02:59,728 - INFO - error, read exception bellow
2019-11-07 16:02:59,730 - INFO - 'ds_user_id'

Thanks in adnvace.

**Comment by RKeyQQ** [comment]
probably "resolved"
I have changed INSTAGRAM_VERSION = in devices.py
Probably IG is banning by device/client infomration

**Comment by danwigrizer** [comment]
@RkeyQQ 

Can you elaborate on your solution? Having the same problem

**Comment by RKeyQQ** [comment]
What is needed to be elaborated?
IG is banning user agent. I just changed INSTAGRAM_VERSION = in devices.py to the latest one. Bot worked few hours and again user agent is banned.

**Comment by RKeyQQ** [comment]
and todays solution is change your
IG_SIG_KEY  in config.py
have no idea how to generate the proper one, so just took one from the google :) and bot is again working
