### ISSUE TITLE
The script stopped working on one pc, but continues to work on another.

### ISSUE THREAD

**Issue by EightShift** [ohld/igbot#1127]
### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

Hello.

Does anyone know what to do when on one pc instabot do not publish stories, but does on another. Although the first pc always had a stories publishing script and suddenly it stopped working. The same script publishes stories on another pc on the same account.

Please, help.

**Comment by steffanjensen** [comment]
have you tried to delete your cookies inside instabot folder?

**Comment by EightShift** [comment]
@reliefs sure. 
I deleted the "__pycache__" directory, but I do not have a cookie file in the script folder. Any other ideas?
😖

**Comment by EightShift** [comment]
I completely reinstalled python. but it did not help...

**Comment by negswell** [comment]
ip ban ?

**Comment by EightShift** [comment]
@negswell, i have a dynamic ip...

**Comment by bruvv** [comment]
Very low on information but I am quessing that you are soft banned, closing in favor of this issue: https://github.com/instagrambot/instabot/issues/1194
