### ISSUE TITLE
Request returns 429 error!

### ISSUE THREAD

**Issue by steffanjensen** [ohld/igbot#1129]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

Code:

```python
# Example code that will produce the error reported
from instabot import Bot

bot = Bot()
bot.login(username="user", password="pass")
followers = bot.get_user_followers(bot.user_id)
```

Error/Debug Log:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: integer division or modulo by zero
```

---

### Describe your issue

2019-11-19 14:39:17,167 - ERROR - Request returns 429 error!
2019-11-19 14:39:17,167 - WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes.

IG updated their api request limit or flow a few days ago, which means that after scraping users a few times and I will get blocked.

The amount does not matter, the block happens if it's 500 or 2000+ users.

The block is also longer than 5 min. I feel it is for hours.

**Comment by ohld** [comment]
What method have you used?

**Comment by steffanjensen** [comment]
These two:
bot.get_user_following(user_id) 
bot.get_user_followers(user_id) 

I also seen other repo like mgp had the same issues a few days ago. 

Here are some news from other bots:
HyperVote
All api limit will bypassed with our new algorithm. But you can use all version of Hypervoter once algorithm update with this recommend.

Omg minimum 1000 follower collect per request? Yeah we did it. Lets test and release. No limit for Hypervoter customer. Lol.  :heart_eyes::zap:🥳

**Comment by steffanjensen** [comment]
Some other info:
Also using the scrapper without login gets 429 if less than 60 seconds is added between operations.

Edit:
Tried did not work, it's pretty easy to get blocked.. The block can be going on for hours. Will debug more.. Pretty bad block.

**Comment by Luke050** [comment]
I think it is because new Instagram algorithm.   I am able to scrap  about 30000 users and then error 429 is shown.  I know there is  200 request per hour limitation

I tried to increase the delay after every 20,000 I added an hour break so as not to exceed 200 requests per hour but 429 error is  here 

Maybe there is some extra limit.  I know that scraping requests are sent very quickly
Is  it possible to add delay after every request ?

**Comment by steffanjensen** [comment]
yeah i have fixed it

**Comment by Luke050** [comment]
@reliefs How

**Comment by fighterii** [comment]
I'm struggeling with this problem too. Any ideas?

**Comment by Luke050** [comment]
@steffanjensen how can I fix that ?
