### ISSUE TITLE
Request returns 400 error!

### ISSUE THREAD

**Issue by proxzi** [ohld/igbot#1130]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [ x] Updated to the latest version
- [x ] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x ] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
I have this problem:
C:\Users\usr\Desktop\instabot-master\examples>python multi_script_CLI.py
2019-11-20 20:02:11,241 - INFO - Instabot Started
Which account do you want to use? (Type number)
1: xxxxxxx
0: add another account.
-1: delete all accounts.
1
Request returns 400 error!

        1.Follow
        2.Like
        3.Comment
        4.Unfollow
        5.Block
        6.Setting
        7.Exit

I used your bot before and everything was fine, I recently changed my password and now I can’t log in through the console. in secret file login and password is correct. I get a message in the intagram: "Verify your identity", I confirm, after that I try to log in again through the console, but the problem remains.

**Comment by reliefs** [comment]
yeah easy fix, this repo is pretty broken..

**Comment by simonasr** [comment]
same here

**Comment by windgan** [comment]
I have the same problem using `multi_script_CLI.py` on a remote server (another country).

**Comment by reliefs** [comment]
https://github.com/instagrambot/instabot/issues/1141#issuecomment-560955472

**Comment by fighterii** [comment]
Have you tried to add `ask_for_code=True` to the bot.login() call in the CLI script. Then the code challenge will be shown if it's necessary?

**Comment by bruvv** [comment]
Could also be related to a soft ban: https://github.com/instagrambot/instabot/issues/1194
