### ISSUE TITLE
close thread

### ISSUE THREAD

**Issue by craigslong** [ohld/igbot#1133]
---

### Before submitting an issue, make sure you have:
- [x ] Updated to the latest version
- [ x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [ x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

Paste the output of ``python -V`` here:
Python 3.7.5rc1

---

### Describe your issue

I installed the bot via CMD line [Windows 10] (python install -U instabot) and went to /site-packages/instabot however, I don't see an examples folder. I'm a little confused on how I'm actually supposed to start the bot from CMD.

**Comment by EightShift** [comment]
just take examples from [here](https://github.com/instagrambot/instabot/tree/master/examples)

**Comment by craigslong** [comment]
Okay, but then how exactly do I start it…?

________________________________

**Comment by leoccyao** [comment]
```
pip install -U instabot
git clone https://github.com/instagrambot/instabot
cd examples
python multi_script_CLI.py
```

Please close issue and ask further questions in Telegram group: https://t.me/instabotproject
