### ISSUE TITLE
The response is `200` but the photo is not getting uploaded

### ISSUE THREAD

**Issue by sleebapaul** [ohld/igbot#1135]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
`python -V`: `Python 3.6.8`
Instabot VersionL: `instabot-0.74.0` 

Code:

```python
# Example code that will produce the error reported
from instabot import Bot
import os

bot = Bot()
bot.login(username="myusername", password="mypassword", proxy=None)
caption = "My ting"
print("upload: " + caption)
options = {"rename":False}
bot.upload_photo(os.path.join("/path/to/my/image", "test.jpeg"), caption=caption, options=options)
print("Response: ", bot.api.last_response)
```

Error/Debug Log:

```python
2019-11-24 21:13:16,093 - INFO - Instabot Started
upload: My ting
FOUND: w:1024 h:1024 r:1.0
2019-11-24 21:13:27,810 - INFO - Photo /path/to/my/image/test.jpeg' is not uploaded.
Response:  <Response [200]>
2019-11-24 21:13:27,811 - INFO - Total requests: 21
```

---

### Describe your issue

The response is `200` but the photo is not getting uploaded. The script stopped working since six days back.

**Comment by AKwoKWH** [comment]
#1134

**Comment by untitled3000** [comment]
I'm having a similar issue. Both photos and videos stopped uploading about a week ago. 

I'm receiving this error: "Something is wrong. Please check your input and try again." 

Seems to be related to this issue [#1111 ](https://github.com/instagrambot/instabot/issues/1111), but it doesn't seem like it was ever resolved.

**Comment by voron434** [comment]
Same issue

**Comment by voron434** [comment]
@AKwoKWH not fixed, still having that issue :(

**Comment by ohld** [comment]
We definitely need someone to find a way to upload a photo via script. And then fix Instabot for all our community. I think it is possible to find a working solution here, in Github.

**Comment by voron434** [comment]
@ohld is this done or not yet?

I'm getting 429 too many requests all the time :(

**Comment by voron434** [comment]
Oh, changed account and now success :)

**Comment by sleebapaul** [comment]
Is it fixed? There's an update?

**Comment by bruvv** [comment]
I am closing this in favor of this post: https://github.com/instagrambot/instabot/issues/1194 please continu the ban discussion there Thanks for the issue btw!
