### ISSUE TITLE
Like, follow, command action block

### ISSUE THREAD

**Issue by 5sfayas** [ohld/igbot#1141]
Instagram finds out after every 10 likes that I am using bot. because my like, follow and comment activities are blocked. 

---

### Before submitting an issue, make sure you have:
- [x ] Updated to the latest version
- [x ] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x ] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ x] Feature request (request for a new functionality)
- [ x] Question
- [ ] Other

**Comment by leoccyao** [comment]
Known issue, not a problem with the codebase. Use higher delay settings or randomize actions more.

See #926

**Comment by reliefs** [comment]
it is a problem with a codebase.

**Comment by reliefs** [comment]
no api needs to be updated

https://github.com/instagrambot/instabot/issues/1131

**Comment by reliefs** [comment]
but these settings should be different default for each user. So this should not be something api needs to fix the end user should know what to fix. It will take a newcomer a few days to see what is too much default.

**Comment by reliefs** [comment]
We need to seperate the block issues from the api. This package should focus on getting endpoints, we still only have like 20-30%. If we look at other we are pretty behind. I have thought about migrating or build my own because we need some fundamental endpoints and many new one. 

I also think there need to be a project folder system like here, because we are really lacking behind in endpoints:
https://github.com/tensorflow/tensorflow/projects
https://github.com/tensorflow/tensorflow/projects/1

**Comment by truff77** [comment]
Hi all, 

I'm pretty new to this but I was thinking of the same thing. To avoid being detected by the ML algorithms we should act like the real app being used by a real human. 
I wanted first to look like the real app and was thinking about a way to extract my phone and app data so as to fill it in the https://github.com/instagrambot/instabot/blob/master/instabot/api/devices.py file. Do you know how I could do this ? 

Then it will be about launching the bot directly from the smartphone (or using a proxy) so as to have the same IP as the real app. 
Finally, the workflows must look like real humans. 
Doing so will replicate real human and real app behavior and there won't be any way for the ML to detect.

**Comment by reliefs** [comment]
Sure just do that..

**Comment by truff77** [comment]
Hi @reliefs 
I managed to get the right user-agent (same as my phone) and use the same IP. I'm just trying to like hashtags (no follow or anything else) and it works pretty well for a period of time but as soon as I try to like a new hashtags it blocks after a few likes. 
I also commented out the section " TODO: commented out simulation "open link in app" in bot_like.py and made it be used by using the right container_module. I wanted to make it as close as real app as possible. Still no luck.
To come back to the last part of my initial message what I would require now is to capture traffic (and decypt it) from the real app so as to better understand a real work flow. Then it should be easy to replicate. Is there any documentation that could help me ? 
I can code in Python and help implementing this into this project. 

thanks in advance

**Comment by reliefs** [comment]
you are using the premade bot. script.. as long you dont write it yourself from scrath you will try to fix this from now on to the end of time.

**Comment by truff77** [comment]
Actually I'm not using the full bot script, just the like_hashtag() function but I assume this is the problem with the ML. 
I've found ways to analyze real app traffic so I can script exact same behavior using low level API calls.

**Comment by reliefs** [comment]
you should only use the api to avoid problems, but still this is not the main cause of issue for blocks only important when other is fixed.

**Comment by truff77** [comment]
Hi @reliefs 
thank you for the hints. I'll keep you updated.

**Comment by reliefs** [comment]
you can just fork me version most of the changes has already been made there.

**Comment by truff77** [comment]
I'll give a try

**Comment by bruvv** [comment]
I am closing this in favor of this post: https://github.com/instagrambot/instabot/issues/1194 please continu the ban discussion there Thanks for the issue btw!
