### ISSUE TITLE
Error after the MFA token request

### ISSUE THREAD

**Issue by stevealexandre** [ohld/igbot#1142]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here: Python 3.5.1

Code:

```First use of multi_script_CLI.py from example directory
```

Error/Debug Log:

```Two-factor authentication request returns 400 error with message {"message": "Invalid Parameters", "status": "fail", "error_type": "invalid_parameters"} !
Traceback (most recent call last):
  File "menu.py", line 700, in <module>
    bot.login()
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/instabot/bot/bot.py", line 439, in login
    if self.api.login(**args) is False:
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/instabot/api/api.py", line 288, in login
    if two_factor_auth(self):
NameError: name 'two_factor_auth' is not defined
```

---

### Describe your issue

At the first time of login, the method two_factor_auth seems not defined or have a trouble.

**Comment by negswell** [comment]
i checked api.py ,  two_factor_auth() is declared after login(),when call to two_factor_auth() is being made it is yet to be defined  , therefore it is throwing an error i presume , fix suggested : declare two_factor_auth before login() in api.py  ?

**Comment by leoccyao** [comment]
Should have been fixed in https://github.com/instagrambot/instabot/pull/1153

Close if still broken after update.

**Comment by bruvv** [comment]
no reply. closing this
