### ISSUE TITLE
No like delay if an account is private

### ISSUE THREAD

**Issue by ermiyaeskandary** [ohld/igbot#115]
Currently the bot cannot follow private accounts

>This is a closed account.
 INFO - None medias recieved: account is closed or medias have been filtered.

**Comment by ohld** [comment]
Yes it can. But it can not receive medias from it - because the account is closed. That's what this issue about.

**Comment by ermiyaeskandary** [comment]
@ohld If it cannot receive media, then there should be no like delay. That's what I meant.

**Comment by ohld** [comment]
Done on 0.3.3.8
