### ISSUE TITLE
Follow action has been BLOCKED but it works on my phone

### ISSUE THREAD

**Issue by muygd** [ohld/igbot#1155]
Code:

```python
# Example code that will produce the error reported

bot = instabot.Bot()
bot.login()
bot.follow_followers("user_id")
```

Error/Debug Log:

Follow action has been BLOCKED
blocked_actions_protection ACTIVE

---

### Describe your issue

I've installed instabot recently and used it without any issue at first 15 followings. then I received action blocked error. Ive tested my follow action from my phone and it works normally.

**Comment by leoccyao** [comment]
Not an issue with codebase.

Try longer action delays or randomizing actions more. 

Also can ask on telegram: https://t.me/instabotproject

**Comment by bruvv** [comment]
I am closing this in favor of this post: https://github.com/instagrambot/instabot/issues/1194 please continu the ban discussion there Thanks for the issue btw!
