### ISSUE TITLE
Welcome Menssage does not work

### ISSUE THREAD

**Issue by eroslico** [ohld/igbot#1158]
Hi

When I try to run Welcome Menssage I log into the account and it throws me the following error

"{'user_info': {'id': xxxx, 'username': 'xxxx', 'is_private': True, 'profile_pic_url': 'https://scontent-eze1-1.cdninstagram.com/v/t51. 2885-19 / s150x150 / 72406449_1247276762119025_5060125306149404672_n.jpg? _Nc_ht = scontent-eze1-1.cdninstagram.com & oh = b6a91591e5b439fef6dbac777499beb4 & oe} 5 '70se: 5 '70se:
None "

Please help me

**Comment by uzairzia** [comment]
> "{'user_info': {'id': xxxx, 'username': 'xxxx', 'is_private': True, 'profile_pic_url': 'https://scontent-eze1-1.cdninstagram.com/v/t51. 2885-19 / s150x150 / 72406449_1247276762119025_5060125306149404672_n.jpg? _Nc_ht = scontent-eze1-1.cdninstagram.com & oh = b6a91591e5b439fef6dbac777499beb4 & oe} 5 '70se: 5 '70se:
> None "

I don't get the above part but I get the last line that you wrote: **None**. 
I also wrote a comment in the pull request which involves this welcome message feature.
[See this](https://github.com/instagrambot/instabot/pull/1150#issuecomment-570771174)

Not sure if the feature is not working properly or there's something wrong on our end.

@ohld , @art-vasilyev  Would it be possible for you to have a look at this, please?
