### ISSUE TITLE
error auto_post.py

### ISSUE THREAD

**Issue by Joostavontuur** [ohld/igbot#1163]
## when try the autopost.py
I tried to run the autopost.py script in the examples folder, but every time i trie it it says 

FOUND: w:834 h:720 r:1.1583333333333334
2019-12-14 19:49:31,520 - INFO - Photo './pics\1 First test.jpg' is not uploaded.

This was a try after a fresh clone of instabot.

Error:

```python
upload:
FOUND: w:834 h:720 r:1.1583333333333334
2019-12-14 19:47:27,889 - INFO - Photo './pics\1 First test.jpg' is not uploaded.
```

- [ x] Bug report (encountered problems/errors)
- Python 3.7.2
---

**Comment by EightShift** [comment]
+

**Comment by EightShift** [comment]
➕

**Comment by pranav-x** [comment]
have you found solution to it??
i am same problem!!

**Comment by bruvv** [comment]
Please test with the new bot and let us know what the error message is. Also make sure you are not banned.

**Comment by emreozen** [comment]
I am also getting info messages such as '/...../instagram/photos/hptogngso_2223622393852065610_316449526_0.jpg' is not uploaded 3 out of every 4 upload attempts. Is there any way to see a longer error message?
