### ISSUE TITLE
Clear Cache?

### ISSUE THREAD

**Issue by dangell7** [ohld/igbot#1169]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [ X] Updated to the latest version
- [X ] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [X ] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [X ] Bug report (encountered problems/errors)
- [X ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

Code:

```python
# Example code that will produce the error reported
from instabot import Bot

bot = Bot()
bot.login(username="user", password="pass")
followers = bot.get_user_followers(bot.user_id)
```

Error/Debug Log:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: integer division or modulo by zero
```

---

### Describe your issue

I'm using a file structure:
```
self.bot = Bot(base_path=ACCOUNT_DIR, filter_business_accounts=False)
self.bot.login(username=self.username, password=self.password, use_cookie=True)
```

 and I was wondering how I can clear the cache of the bot? It seems that after I deleted the log files and cookie cache, it gives this error. 

```
No such file or directory: '~/datasets/accounts/Yy6QoOJ113Qc1D3mj3Wg/instagram/log/instabot_4994823568.log'
```

I already uninstalled and reinstalled and it still shows the error. Any Ideas? The cookie file still exists in the directory.

**Comment by bruvv** [comment]
The coockie can befound in the exact same folder where the file is that you ran. Delete that. Next time please read the issue template before submitting the issue.
