### ISSUE TITLE
Problems with bot

### ISSUE THREAD

**Issue by thegamemd** [ohld/igbot#1171]
Hi guys, 
I have a problem while I'm using examples scripts. 
1. Unfollow non followers script, action says "following blocked and in a few sec switching to another user and notice same block message. 
Feels like there's limit, about 300 unfollows a day and after block starts. But how to reset it? Because if I'm trying to run script in a day or two I got the same message of blocking. But instagram on smartphone works well!

2. I'm using two accounts, second account always error on starts, I guess its verification form stops the process, but how to skip it and make bot work? 

P.S I'm don't know how syntax of python works, unfortunately I can't sit too long at PC, my eyes recovers now. 

Please give me an advice how to fix that? Would be cool if you'll record guide for me. 
Thanks

**Comment by derens99** [comment]
Getting the same issue with the unfollow_non_followers script. I have been blocked from unfollowing people through the script.

**Comment by thegamemd** [comment]
Feels like bot activity is desd

**Comment by bruvv** [comment]
I am closing this in favor of this post: https://github.com/instagrambot/instabot/issues/1194 please continu the ban discussion there Thanks for the issue btw!
