### ISSUE TITLE
Only some posts receive likes 

### ISSUE THREAD

**Issue by jamescavallo** [ohld/igbot#1174]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [ ] Updated to the latest version
- [ ] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [ ] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [X] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

Code:

```python
logger.info("checking post")
    for key in credict:
        newid = botlist[0].get_user_id_from_username(key)
        mediaids = botlist[0].get_user_medias(newid, filtration = False) #gets recent media with username id
        if len(mediaids) > 0:
            lastmedia = mediaids[0]
        print(lastmediacheck)
        if key in lastmediacheck and len(mediaids) > 0:
            if lastmediacheck[key] != lastmedia:
                print(botlist)
                for i in botlist:
                    i.like(lastmedia)
                lastmediacheck[key] = lastmedia
                print("here")
        else:
            if len(mediaids) != 0:
                lastmediacheck[key] = lastmedia
            else:
                print("No media detected")

```

Error/Debug Log:

```python
2019-12-25 21:18:25,285 - __main__ - INFO - /like
```

---

### Describe your issue

The bot.like() function only works for certain posts and there seems to be no pattern to it.

**Comment by bruvv** [comment]
Retry with the new update and let us know if the issue still exists. please open a new issue if the issue is still there
