### ISSUE TITLE
> https://github.com/instagrambot/instabot/blob/aa83c9a12cf17645bedd05c70cb97ed9f4c351c1/instabot/api/api.py#L538

### ISSUE THREAD

**Issue by Abdulsamipy** [ohld/igbot#1177]
is it possible to download the list of followers in the form of .csv?

_Originally posted by @Abdulsamipy in https://github.com/instagrambot/instabot/issues/1011#issuecomment-569202012_

**Comment by Abdulsamipy** [comment]
No actually my issue is not solved :)

**Comment by bruvv** [comment]
Please create a normal title... and why do you keep posting this?
