### ISSUE TITLE
type object 'Bot' has no attribute 'watch_user_reels'

### ISSUE THREAD

**Issue by OmarMuSt** [ohld/igbot#1179]
type object 'Bot' has no attribute 'watch_user_reels' 

Why this is error ??

**Comment by fighterii** [comment]
Could you provide your code and relevant logging file? Or at least (if applies) the used example, so that we can reproduce or investigate this error?

**Comment by fighterii** [comment]
I think the function is named watch_users_reels (with plural of user). So just using the correctly spelled function will work. If not, then open a new issue with relevant code and logging.

@bruvv : can be closed

**Comment by bruvv** [comment]
I agree. If there is still an issue feel free to post an new issue.
