### ISSUE TITLE
preferences written to file without separation

### ISSUE THREAD

**Issue by bestrocker221** [ohld/igbot#1188]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x ] Updated to the latest version
- [x ] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [ x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:
Python 3.8.1

Code:

multi_script_CLI

Error/Debug Log:

it is writing the preferences to file one after another, like blacklist/whitelist

ex hello and world, he is writing helloworld into the files.. this make it not working
I just did a pull request fixing another error.. 
Is someone actually testing the script before pushing?

---

### Describe your issue

it is writing the preferences to file one after another, like blacklist/whitelist

ex hello and world, he is writing helloworld into the files.. this make it not working
I just did a pull request fixing another error.. 
Is someone actually testing the script before pushing?

**Comment by bruvv** [comment]
Please reeopen the issue if this still persists and please try and be as clear as possible.
