### ISSUE TITLE
Cant Login

### ISSUE THREAD

**Issue by sminato27** [ohld/igbot#1190]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:
Python 3.8.1
Code:

```python
# Example code that will produce the error reported
from instabot import Bot

bot = Bot()
bot.login(username="user", password="pass")
followers = bot.get_user_followers(bot.user_id)
```

Error/Debug Log:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: integer division or modulo by zero
```

---

### Describe your issue

After write "python scriptname.py param" and select my account, it gives "Exception: Not logged in!".

**Comment by bruvv** [comment]
I guess you used the wrong account details than ;) dubble check

**Comment by sminato27** [comment]
> I guess you used the wrong account details than ;) dubble check

unfortunately i used the correct account details and in my device appears a message that says something like "a new device tried to login in this account". 
after this i can't do anything

**Comment by bruvv** [comment]
You are probably banned than. Linking to this issue: https://github.com/instagrambot/instabot/issues/1194

**Comment by scretr** [comment]
Maybe 2 step verif is interfering?

**Comment by bruvv** [comment]
@scretr that also could be the deal. @sminato27 check this please: https://github.com/instagrambot/instabot/issues/1224
