### ISSUE TITLE
Error : the following arguments are required: -user, -get, -file

### ISSUE THREAD

**Issue by Abdulsamipy** [ohld/igbot#1191]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [ x] Updated to the latest version
- [ x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x ] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

Code:

```python
# Example code that will produce the error reported
from instabot import Bot

bot = Bot()
bot.login(username="user", password="pass")
followers = bot.get_user_followers(bot.user_id)
```

Error/Debug Log:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: integer division or modulo by zero
```

---

### Describe your issue
so when im running the file it's giving following error 

```
[-h] [-u U] [-p P] [-proxy PROXY] -user USER -get GET -file FILE [-amount AMOUNT] [-overwrite]
                        [-usernames] [-filter_private] [-filter_business] [-filter_verified]
follower2file.py: error: the following arguments are required: -user, -get, -file


```

**Comment by Abdulsamipy** [comment]
nope not the same a

> Hey @Abdulsamipy,
> 
> We did a quick check and this issue looks very darn similar to
> 
> * [#1190 - Cant Login](1190)
> * [#1189 - TypeError: watch_users_reels() missing 1 required positional argument: 'user_ids'](1189)
> * [#1188 - preferences written to file without separation](1188)
> 
> This could be a coincidence, but if any of these issues solves your problem then I did a good job 😄
> 
> If not, the maintainers will get to this issue shortly.
> 
> Cheers,
> Your Friendly Neighborhood ProBot

no not the same error

**Comment by fighterii** [comment]
And what about providing these arguments when calling the script? Shouldn't be that hard. I don't see how this could be a bug in the code?

**Comment by Abdulsamipy** [comment]
> And what about providing these arguments when calling the script? Shouldn't be that hard. I don't see how this could be a bug in the code?

Thanks for your kind reply .. Can you actually tell me where i can edit those arguments?

**Comment by fighterii** [comment]
Sorry, my fault. I assumed people using scripts like this have some knowledge about python / programming.

You can start your script from the command line just as the help text indicates:

`python follower2file.py -user USER -get GET -file FILE`
Of course you have to replace the uppercase words with your actual values.

**Comment by Abdulsamipy** [comment]
> Sorry, my fault. I assumed people using scripts like this have some knowledge about python / programming.
> 
> You can start your script from the command line just as the help text indicates:
> 
> `python follower2file.py -user USER -get GET -file FILE`
> Of course you have to replace the uppercase words with your actual values.

Thanks alot .. One more question
what do we have to input in FILE
Does it have to be .txt? 
And what info do we have to provide in that .txt file
And Do we have to leave GET as it is or add something else there 

Once again appreciate your work :)

**Comment by fighterii** [comment]
@Abdulsamipy : follower2file.py is not a filename from the examples, so i assume you get it from somewhere else or created it your own. If you are using a file from the examples, you didn't say what example you are trying to get work.
Because you didn't provide the code itself in the issue description we can't help you with this. 
If you get the file from somewhere else, maybe they can help you with what the arguments should be.

FILE normally is just a path to file, you can name it whatever you want. Typically it doesn't have to exist and will be created, e.g.: "C:\temp\test.txt" or "filename.extension"

GET could be anything, no idea. The best would be to look into the code and watch out what is done with the get argument, maybe there is meaningful documentation in the code.

**Comment by Abdulsamipy** [comment]
> @Abdulsamipy : follower2file.py is not a filename from the examples, so i assume you get it from somewhere else or created it your own. If you are using a file from the examples, you didn't say what example you are trying to get work.
> Because you didn't provide the code itself in the issue description we can't help you with this.
> If you get the file from somewhere else, maybe they can help you with what the arguments should be.
> 
> FILE normally is just a path to file, you can name it whatever you want. Typically it doesn't have to exist and will be created, e.g.: "C:\temp\test.txt" or "filename.extension"
> 
> GET could be anything, no idea. The best would be to look into the code and watch out what is done with the get argument, maybe there is meaningful documentation in the code.

pardon me .. i actually edited the name ... so it is **get_followers_or_followings_to_file.py** its from example 
https://github.com/instagrambot/instabot/blob/master/examples/get_followers_or_followings_to_file.py

**Comment by fighterii** [comment]
@Abdulsamipy : And did you take a look into that code?

``` 
parser.add_argument(
    "-user",
    type=str,
    help="username whose followers or followings you want to get",
    required=True,
)
parser.add_argument("-get", type=str, help="followers or followings", required=True)
parser.add_argument("-file", type=str, help="speficy filename", required=True)
```
I think the help text is quite self explanatory. 

Don't get me wrong, we have no problems to help people or explain even simple things to newbies, but when I have the feeling, that the other user is not doing anything to solve the problem by himself, its quite frustrating.

To close this "issue": Just type in "follower" or "following" after -get to tell the script what you want to save.

**Comment by Abdulsamipy** [comment]
> @Abdulsamipy : And did you take a look into that code?
> 
> ```
> parser.add_argument(
>     "-user",
>     type=str,
>     help="username whose followers or followings you want to get",
>     required=True,
> )
> parser.add_argument("-get", type=str, help="followers or followings", required=True)
> parser.add_argument("-file", type=str, help="speficy filename", required=True)
> ```
> 
> I think the help text is quite self explanatory.
> 
> Don't get me wrong, we have no problems to help people or explain even simple things to newbies, but when I have the feeling, that the other user is not doing anything to solve the problem by himself, its quite frustrating.
> 
> To close this "issue": Just type in "follower" or "following" after -get to tell the script what you want to save.

Oh i get it .. I have to specify the follower and following in help section .. I have been edting it

**Comment by Abdulsamipy** [comment]
> > @Abdulsamipy : And did you take a look into that code?
> > ```
> > parser.add_argument(
> >     "-user",
> >     type=str,
> >     help="username whose followers or followings you want to get",
> >     required=True,
> > )
> > parser.add_argument("-get", type=str, help="followers or followings", required=True)
> > parser.add_argument("-file", type=str, help="speficy filename", required=True)
> > ```
> > 
> > 
> > I think the help text is quite self explanatory.
> > Don't get me wrong, we have no problems to help people or explain even simple things to newbies, but when I have the feeling, that the other user is not doing anything to solve the problem by himself, its quite frustrating.
> > To close this "issue": Just type in "follower" or "following" after -get to tell the script what you want to save.


 Oh i get it .. I have to specify the follower and following in help section .. I have been editing it inside "-user"
Thanks for your kind help and reallu appreciate your time
Have a blessed day :)

**Comment by bruvv** [comment]
I closed it because I am asuming your issue is fixed, if that is not the case let me know.
