### ISSUE TITLE
Reply comment limitaion

### ISSUE THREAD

**Issue by mohamad171** [ohld/igbot#1212]
### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

Hi anyone know reply comment in my post has limitation? i want to reply everyone comment on my post

**Comment by bruvv** [comment]
I am sorry but I am not following the question you are asking. Can you try and rephrase it?
