### ISSUE TITLE
Can't comment on posts: code 200?

### ISSUE THREAD

**Issue by romzamir** [ohld/igbot#1213]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [X] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:
<Response [200]> but won't comment
Code:

```python
import os
import sys
import argparse
import time
from tqdm import tqdm

sys.path.append(os.path.join(sys.path[0], "../../"))
from instabot import Bot  # noqa: E402

parser = argparse.ArgumentParser(add_help=True)
parser.add_argument("-u", type=str, help="username")
parser.add_argument("-p", type=str, help="password")
parser.add_argument("-proxy", type=str, help="proxy")
parser.add_argument("-track", type=str, help="user_to_track")
args = parser.parse_args()
comments_file_name = "comments.txt"
bot = Bot(comments_file=comments_file_name)
bot.login(username=args.u, password=args.p, proxy=args.proxy)
if not args.track is None:
    track = args.track
else:
    #track = input("Enter a username to track >>\t")
    track = "pubity"

while True:
    medias = bot.get_user_medias(track, False)
    for media in tqdm(medias):
        if not bot.is_commented(media):
            text = bot.get_comment()
            bot.logger.info("Commented with text: %s" % text)
            time.sleep(3)
    time.sleep(1)
```

Error/Debug Log:

```python
DEBUG - <Response [200]>
```

---

### Describe your issue

I try to comment but when I run the code it gives the 200 code and doesn't post the comment.

**Comment by bruvv** [comment]
This probably related to a soft ban. Try again within a few hours/days.If it works please let us know.

crosslinking: https://github.com/instagrambot/instabot/issues/1219

**Comment by bruvv** [comment]
There is a new update, please run that and report back what the message is. Thanks
