### ISSUE TITLE
Instagram blocks actions and finally accont

### ISSUE THREAD

**Issue by iamtorsten** [ohld/igbot#1222]
IG blocks after a short period every action and finally the account.

Is there a way to hide my ass using the bot?

**Comment by ryanbrewster124** [comment]
I’m just coming back to this after a couple of months, is there no fix yet with the bot and Instagram? Or are the devs working on it do you know?

Thanks in advance for any info

**Comment by fighterii** [comment]
Seems like more and more people are having these problems in the past few days. I would guess that IG applies their bot detection rules much more strictly now.

**Comment by ryanbrewster124** [comment]
Oh on that’s a shame, I have a brand new account. Have to grow it the old fashioned way then I guess! 😢

**Comment by bruvv** [comment]
I am closing this in favor of this post: https://github.com/instagrambot/instabot/issues/1194 please continu the ban discussion there Thanks for the issue btw!
