### ISSUE TITLE
I cannot login my account

### ISSUE THREAD

**Issue by ResulBulbul** [ohld/igbot#1224]
```

2020-01-11 23:17:31,975 - INFO - Instabot Started
2020-01-11 23:17:33,941 - ERROR - Request returns 400 error!
2020-01-11 23:17:33,941 - INFO - Instagram's error message: challenge_required
2020-01-11 23:17:33,941 - INFO - Error type: checkpoint_challenge_required
2020-01-11 23:17:33,941 - INFO - Username or password is incorrect.
2020-01-11 23:17:33,941 - INFO - Bot stopped. Worked: 0:00:01.970563
2020-01-11 23:17:33,945 - INFO - Total requests: 
```

That is the problem I have. When I try to login by myself on either my phone or my computer, there is no problem but when it comes to run the script on vs code, it gives me the error. What should I do??

**Comment by bruvv** [comment]
What's the code you're running and do you've 2fa enabled ?

**Comment by ResulBulbul** [comment]
> What's the code you're running and do you've 2fa enabled ?

import instabot
Bot = instabot.Bot()
Bot.login(username="*******",password="*******")
users = set(users)
Bot.send_message("message",users)
Bot.logout()

I am simply trying to send message to people via the bot. Sorry but I don't know "2fa" couldyou please give me more information about that

**Comment by bruvv** [comment]
Did you enable sms code verification when login in via your phone ?

**Comment by ResulBulbul** [comment]
> Did you enable sms code verification when login in via your phone ?

yes i did

**Comment by bruvv** [comment]
You should add: `ask_for_code=True`
Similar: https://github.com/instagrambot/instabot/issues/1192

**Comment by ResulBulbul** [comment]
> You should add: `ask_for_code=True`
> Similar: #1192

To Bot.login() ? I tried and got `
TypeError: login() got an unexpected keyword argument 'ask_for_code'`

**Comment by ResulBulbul** [comment]
> You should add: `ask_for_code=True`
> Similar: #1192

Just figured out that I had to upgrade version. Sorry for wasting your time. Have a good one sir
