### ISSUE TITLE
Media owner mention in caption

### ISSUE THREAD

**Issue by Gurp1272** [ohld/igbot#1230]
Is there a way to source a bunch of images that will be stored to a folder, and have the owner id stored with the image? Also, a way to grab that owner id, and use it to mention them via caption in the re-post?

**Comment by bruvv** [comment]
Why not use the repost example in this case ?

**Comment by Gurp1272** [comment]
@bruvv I thought about that. If you let the program choose an image to post, there's not really any human quality control. But maybe I should give it a try?

**Comment by bruvv** [comment]
It's getting the best photo from a user account (calculated from the most likes and comments)

**Comment by Gurp1272** [comment]
Alright @bruvv I will go ahead and give that a shot. Is there a simple way to post a custom caption to the photo with the media author mentioned?
