### ISSUE TITLE
Does any one know here how to create instagram accounts using this api??

### ISSUE THREAD

**Issue by Manjit2003** [ohld/igbot#1231]
Guys someone please reply as I have been struggling to find code to create instagram accounts since weeks.. Please someone help..

**Comment by bruvv** [comment]
This is not a support section. It's for issues. Closing.

**Comment by Manjit2003** [comment]
Sorry but i was just asking if creating instagram accounts using python requests is possible. If yes then is it implemented in this project??Maybe you misunderstood what I am trying to ask. That is my issue..

**Comment by bruvv** [comment]
It is not implemented, feel free to open a PR ;)
