### ISSUE TITLE
[BUG] Uploading Video with Caption doesn't Upload the Caption

### ISSUE THREAD

**Issue by ConnorVO** [ohld/igbot#1233]
**Describe the bug**

When uploading a video with a description, the video uploads but the comment doesn't (it just uploads with no description).

From the log below, it shows that the caption is in the POST Data that is sent with send_request.

**Screenshots**

log:

> POST Data: {"upload_id": "1579150034267", "source_type": 4, "poster_frame_index": 0, "length": 59.95, "audio_muted": false, "filter_type": 0, "date_time_original": "2020:01:15 20:48:19", "timezone_offset": "10800", "width": 720, "height": 406, "clips": [{"length": 59.95, "source_type": "4"}], "extra": {"source_width": 720, "source_height": 406}, "device": {"instagram_version": "105.0.0.18.119", "android_version": 28, "android_release": "9.0", "dpi": "420dpi", "resolution": "1080x2260", "manufacturer": "OnePlus", "device": "GM1903", "model": "OnePlus7", "cpu": "qcom"}, "caption": "{caption is here}", "_uuid": "a066ba0d-fc5f-4f59-b097-31127d6f945b", "_uid": "11107877141", "_csrftoken": "hDzkQU1b5XBzaIjbixBXF9zIdxfKdodU"}

**To Reproduce**

1. login and run the bot.upload_video() function while passing in a caption

**Expected behavior**

It should upload the video to Instagram with a caption.

**Screenshots/logs**

**Additional context**

**Comment by bruvv** [comment]
https://github.com/instagrambot/instabot/issues/1194
You're soft banned. I've had this happen too. Closing this in favor of the issue that I linked.
