### ISSUE TITLE
Delay on the bot is not working 

### ISSUE THREAD

**Issue by Abdulsamipy** [ohld/igbot#1234]
**Describe the bug**

hi, so I'm setting the follow/comment/like delay to 120 seconds in Bot, **multi_script_cli.py**
the bot comments on all selected post within like 20 -30 sec .. i've tried editing the delay inside the script but still the same 

my delay settings 

Like delay: 120

Unlike delay: 120

Follow delay: 120

Unfollow delay: 120

Comment delay: 120

Proxy: None

**Screenshots**

log:
```
**Here is the video**

```
[bandicam 2020-01-16 15-39-27-698.zip](https://github.com/instagrambot/instabot/files/4070764/bandicam.2020-01-16.15-39-27-698.zip)

**To Reproduce**

1. Edit '...'
2. Run '....'

**Expected behavior**

comment on the post with provided delay 

**Screenshots/logs**
video of the bot commeting 

[bandicam 2020-01-16 15-39-27-698.zip](https://github.com/instagrambot/instabot/files/4070764/bandicam.2020-01-16.15-39-27-698.zip)

**Additional context**

can any expert tell me how i can  solve this delay error

**Comment by bruvv** [comment]
Please fill the template in as described otherwise it is going to be closed.

**Comment by Abdulsamipy** [comment]
> Please fill the template in as described otherwise it is going to be closed.

is this fine? pardon me in kinda new to github and programming

**Comment by bruvv** [comment]
I asume english is not your main language but you should really read.  But anyway I will look into this. I am not using the script you are using so I have no idea what the issue could be.

**Comment by Abdulsamipy** [comment]
> I asume English is not your main language but you should really read. But anyway I will look into this. I am not using the script you are using so I have no idea what the issue could be.

yes, English is not my main language.....  i have attached a video .. for better understanding 
i have set the delay to 120sec but the bot is commenting on all 82 post within the span of 1 min

**Comment by bruvv** [comment]
The video doesn't work nor will I download it out of my own safety online ;) just a simple copy paste of the log will be fine next time.

**Comment by Abdulsamipy** [comment]
`2020-01-16 21:06:46,089 - INFO - LOGIN FLOW! Just logged-in: False

2020-01-16 21:06:53,961 - INFO - Logged-in successfully as 'my username'!
2020-01-16 21:07:00,574 - INFO - Going to comment medias by pewdiepie hashtag
2020-01-16 21:07:04,664 - INFO - Going to comment 78 medias.
2020-01-16 21:08:34,788 - INFO - DONE: Total commented on 0 medias. 
.`

**my comment .txt file has 2 comments per line**

**Comment by Abdulsamipy** [comment]
cmd log 

what?pewdiepie
2020-01-16 21:23:30,142 - INFO - Going to comment medias by pewdiepie hashtag
Getting hashtag media.: 0it [00:00, ?it/s]2020-01-16 21:23:35,038 - DEBUG - <Response [200]>
2020-01-16 21:23:35,069 - INFO - Going to comment 83 medias.
  0%|                                                                                           | 0/83 [00:00<?, ?it/s]2020-01-16 21:23:35,714 - DEBUG - <Response [200]>
2020-01-16 21:23:36,136 - DEBUG - <Response [200]>
2020-01-16 21:23:36,624 - DEBUG - <Response [200]>
  1%|█                                                                                  | 1/83 [00:01<02:07,  1.55s/it]2020-01-16 21:23:37,057 - DEBUG - <Response [200]>
2020-01-16 21:23:37,448 - DEBUG - <Response [200]>
2020-01-16 21:23:37,886 - DEBUG - <Response [200]>
  2%|██                                                                                 | 2/83 [00:02<01:58,  1.47s/it]2020-01-16 21:23:38,305 - DEBUG - <Response [200]>
2020-01-16 21:23:38,695 - DEBUG - <Response [200]>
2020-01-16 21:23:39,070 - DEBUG - <Response [200]>
  4%|███                                                                                | 3/83 [00:04<01:50,  1.38s/it]2020-01-16 21:23:39,461 - DEBUG - <Response [200]>
2020-01-16 21:23:42,201 - DEBUG - <Response [200]>
2020-01-16 21:23:42,654 - DEBUG - <Response [200]>
  5%|████                                                                               | 4/83 [00:07<02:41,  2.04s/it]2020-01-16 21:23:43,091 - DEBUG - <Response [200]>
2020-01-16 21:23:43,647 - DEBUG - <Response [200]>
2020-01-16 21:23:44,102 - DEBUG - <Response [200]>
  6%|█████                                                                              | 5/83 [00:09<02:25,  1.86s/it]2020-01-16 21:23:44,603 - DEBUG - <Response [200]>
2020-01-16 21:23:44,988 - DEBUG - <Response [200]>
2020-01-16 21:23:45,367 - DEBUG - <Response [200]>
  7%|██████                                                                             | 6/83 [00:10<02:09,  1.68s/it]2020-01-16 21:23:45,749 - DEBUG - <Response [200]>
2020-01-16 21:23:46,154 - DEBUG - <Response [200]>
2020-01-16 21:23:46,544 - DEBUG - <Response [200]>
  8%|██████▉                                                                            | 7/83 [00:11<01:56,  1.53s/it]2020-01-16 21:23:46,966 - DEBUG - <Response [200]>
2020-01-16 21:23:47,360 - DEBUG - <Response [200]>
2020-01-16 21:23:47,715 - DEBUG - <Response [200]>
 10%|████████                                                                           | 8/83 [00:12<01:46,  1.42s/it]2020-01-16 21:23:48,105 - DEBUG - <Response [200]>
2020-01-16 21:23:48,496 - DEBUG - <Response [200]>
2020-01-16 21:23:48,952 - DEBUG - <Response [200]>
 11%|█████████                                                                          | 9/83 [00:13<01:41,  1.37s/it]2020-01-16 21:23:49,339 - DEBUG - <Response [200]>
2020-01-16 21:23:49,768 - DEBUG - <Response [200]>
2020-01-16 21:23:50,532 - DEBUG - <Response [200]>
 12%|█████████▉                                                                        | 10/83 [00:15<01:44,  1.43s/it]2020-01-16 21:23:50,979 - DEBUG - <Response [200]>
2020-01-16 21:23:54,195 - DEBUG - <Response [200]>
2020-01-16 21:23:54,602 - DEBUG - <Response [200]>
 13%|██████████▊                                                                       | 11/83 [00:19<02:40,  2.22s/it]2020-01-16 21:23:55,023 - DEBUG - <Response [200]>
2020-01-16 21:23:55,445 - DEBUG - <Response [200]>
2020-01-16 21:23:55,805 - DEBUG - <Response [200]>
 14%|███████████▊                                                                      | 12/83 [00:20<02:16,  1.92s/it]2020-01-16 21:23:56,211 - DEBUG - <Response [200]>
2020-01-16 21:23:56,623 - DEBUG - <Response [200]>
2020-01-16 21:23:57,277 - DEBUG - <Response [200]>
 16%|████████████▊                                                                     | 13/83 [00:22<02:04,  1.78s/it]2020-01-16 21:23:57,667 - DEBUG - <Response [200]>
2020-01-16 21:23:58,024 - DEBUG - <Response [200]>
2020-01-16 21:23:58,707 - DEBUG - <Response [200]>
 17%|█████████████▊                                                                    | 14/83 [00:23<01:55,  1.68s/it]2020-01-16 21:23:59,239 - DEBUG - <Response [200]>
2020-01-16 21:23:59,608 - DEBUG - <Response [200]>
2020-01-16 21:24:00,233 - DEBUG - <Response [200]>
 18%|██████████████▊                                                                   | 15/83 [00:29<03:11,  2.82s/it]2020-01-16 21:24:04,552 - DEBUG - <Response [200]>
2020-01-16 21:24:04,944 - DEBUG - <Response [200]>
2020-01-16 21:24:05,459 - DEBUG - <Response [200]>
 19%|███████████████▊                                                                  | 16/83 [00:30<02:37,  2.35s/it]2020-01-16 21:24:05,935 - DEBUG - <Response [200]>

**Comment by Abdulsamipy** [comment]
Name: instabot
Version: 0.104.0
Summary: Instagram bot scripts for promotion and API python wrapper.
Home-page: https://github.com/instagrambot/instabot
Author: Daniil Okhlopkov, Evgeny Kemerov
Author-email: danokhlopkov@gmail.com, eskemerov@gmail.com
License: Apache Software License 2.0
Location: c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages
Requires: tqdm, requests, requests-toolbelt, schedule, pysocks, responses, future, six, huepy, pytz
Required-by:

**Comment by bruvv** [comment]
Alright I am closing this issue, please and please learn to use mark up. I keep editing your comments for others to keep a easy read out. If you refuse to learn basic markup I can't keep learning you python.
