### ISSUE TITLE
Viewing the status of limits

### ISSUE THREAD

**Issue by vkdg** [ohld/igbot#124]
At the moment, the script shows expired limits after completing its tasks, but it is not possible to see the status of the limits before starting any script:

> 2017-03-15 15:23:42,222 - INFO - Total liked: 29
> 2017-03-15 15:23:42,223 - INFO - Total followed: 24
> 2017-03-15 15:23:42,223 - INFO - Total unfollowed: 29

This could be useful.

**Comment by ohld** [comment]
I'll create the method to print current limits. And add this to CLI bot

**Comment by ohld** [comment]
Added `bot.print_counters()` method
