### ISSUE TITLE
Repeated comments in new windowa

### ISSUE THREAD

**Issue by muh-bazm** [ohld/igbot#1244]
I am trying to get all comments of a post, however, it takes so long and it downloads comments much more that what is given in post info. Further analysis (checking number of unique comments ) proved that after getting a few comments ( in multiple windows ) only one or two new comments are downloaded. I sincerely appreciate any help in this regards.

**Comment by bruvv** [comment]
I'll close this one and want to ask you to create a big report after testing the new version

**Comment by muh-bazm** [comment]
I hope the version works without any problem. For this problem, I developed
a new method and I believe it is working well. Thank you very much for your
help.
