### ISSUE TITLE
[BUG] SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by iMoein** [ohld/igbot#1245]
**Describe the bug**

After installation, I got the following error when trying to run the program with the "python multi_script_CLI.py" command

**Screenshots**

![Untitled-1](https://user-images.githubusercontent.com/13425551/72739251-859e8080-3bb8-11ea-8a86-36a47a6bd0d4.jpg)

log:
```
`
  File "multi_script_CLI.py", line 51
    f.write(f"{entered}\n")
                         ^
SyntaxError: invalid syntax
`
```

**To Reproduce**

1. Edit '...'
2. Run '....'

**Expected behavior**

**Screenshots/logs**

If applicable, add screenshots or logs to help explain your problem.

**Additional context**

I use:
Ubuntu 18.04 LTS & Ubuntu 16.04 LTS
Python3 & Python

I don't have this problem in instabot 0.85.

**Comment by iMoein** [comment]
None of the above was related to my problem

**Comment by bruvv** [comment]
Update the issue with the template that is given. If you do not do that I will close it.

**Comment by ghyath5** [comment]
I am facing same issue.
Did you find a solution  ?
@iMoein

**Comment by bruvv** [comment]
This has been fixed in the latest development branch. Closing this
