### ISSUE TITLE
Is there a way to post an image from a url?

### ISSUE THREAD

**Issue by xjxckk** [ohld/igbot#1250]
### Which example file are you using?
- upload_photo.py

---

### Describe your Question/Issue:

Is there a way to post an image from a url? I tried using bot.upload_photo() and got an error.

---

Code you are using:

```python
from instabot import Bot

bot = Bot()
bot.login()

bot.upload_photo("https://i.imgur.com/HXHJL5s.jpg", caption="Test")
```

Error/Debug Log:

```
OSError: [Errno 22] Invalid argument: 'https://i.redd.it/ymy6zh4z8ac41.jpg'
2020-01-22 14:33:19,076 - INFO - Total requests: 21
```

**Comment by bruvv** [comment]
No. At this moment it only is able to upload photos and not download other photos and upload them

**Comment by xjxckk** [comment]
Ah ok, thanks.

Do you know of any way to do this with another library?

**Comment by bruvv** [comment]
you can add a PR to our branch ;)
