### ISSUE TITLE
Upload Story Photo says photo ... is not uploaded

### ISSUE THREAD

**Issue by stephendisario** [ohld/igbot#1252]
Uploading photos is working for me, however, uploading photos to my Instagram story is not.  I am not getting any errors i am just left with the console telling me the photo was not uploaded.  Please let me know if this is a bug or if I am doing something wrong. I've tried both calling upload_story_photo.py directly from the console with the location of the photo and creating a bot and running bot.upload_story_photo.

**Comment by egyjs** [comment]
i have the same issue :(
![image](https://user-images.githubusercontent.com/12745270/73082381-6e260700-3eda-11ea-8d30-4bc662410817.png)
