### ISSUE TITLE
[BUG] ERROR - Request returns 429 error! too many requests

### ISSUE THREAD

**Issue by Abdulsamipy** [ohld/igbot#1262]
**Describe the bug**
hi guys ,so i noticed that when we  try to perform a task on big accounts ( 1M+) the bot gives the following log

**Screenshots**
![Capture](https://user-images.githubusercontent.com/58009877/73128411-d830d000-3ff0-11ea-8eec-b3d2e713906f.PNG)

log:
```
2020-01-26 04:01:03,830 - DEBUG - Responsecode indicates error; response content: b'{"message": "Please wait a few minutes before you try again.", "status": "fail"}'
2020-01-26 04:01:03,834 - ERROR - Request returns 429 error!
2020-01-26 04:01:03,835 - WARNING - That means 'too many requests'. I'll go to sleep for 2 minutes.
```

**To Reproduce**

1. Edit '...'
2. Run '....'

**Expected behavior**

Get followers of huge account and perform the task

**Comment by bruvv** [comment]
How many bots have been used on it? Are there multiple people connected to the account? Is it your own account? Is the script located in the same country as the owner of the account is?

**Comment by Abdulsamipy** [comment]
> How many boys have been used on it? Are there multiple people connected to the account? Is it your own account? Is the script located in the same country as the owner of the account is?

Using 1 bot on this  account .. No only i have access to this account .. I own the account and yes the script and account are on same IP

Bot used: multi_script.py

**Comment by Abdulsamipy** [comment]
> > How many boys have been used on it? Are there multiple people connected to the account? Is it your own account? Is the script located in the same country as the owner of the account is?
> 
> Using 1 bot on this account .. No only i have access to this account .. I own the account and yes the script and account are on same IP

Bot used: multi_script.py

**Comment by bruvv** [comment]
Than it is related to this issue and I'll close this one: https://github.com/instagrambot/instabot/issues/1194
