### ISSUE TITLE
Response 400 on autoposter!

### ISSUE THREAD

**Issue by ghost** [ohld/igbot#127]
I'm trying to use the autoposter with the example provided and I'm getting Response 400. Did Instagram change something?

**Comment by mpawlak2** [comment]
"You may also receive responses with an HTTP response code of 400 (Bad Request) if we detect spammy behavior by a person using your app. These errors are unrelated to rate limiting."

maybe thats why?

**Comment by ohld** [comment]
@ppleskov ??

**Comment by ghost** [comment]
@mpawlak2, I am not sure that is the problem. All other functions work just fine, the only thing that doesn't is the autoposter. Can anyone please confirm?

**Comment by cced3000** [comment]
I also encountered this problem，Response 400 on autoposter! Can anyone help me to solve the problem。

**Comment by ohld** [comment]
Autoposter was developed by @ppleskov. So i think he can solve this issue.
