### ISSUE TITLE
 NameError: global name 'settings' is not defined in multi_script_CLI.py setting.txt

### ISSUE THREAD

**Issue by juandapradam12** [ohld/igbot#1272]
**Example file**

```
multi_script_CLI.py 
```

**Describe the bug**
python multi_script_CLI.py 

**Log**

```
here
```

**To Reproduce**

Looks like setting are broken
Let's make new one

Traceback (most recent call last):
  File "multi_script_CLI.py", line 624, in <module>
    setting_input()
  File "multi_script_CLI.py", line 116, in setting_input
    with open(settings, "w") as f:

NameError: global name 'settings' is not defined

**Expected behavior**

Dont have an error in setting.txt file 

**Additional context**

setting.txt file is already in examples

**Version**

Python version (`python -v`): 3
OS: Linux

**Comment by bruvv** [comment]
Run the development branch

**Comment by juandapradam12** [comment]
bruvv cn you explain how is it done please ? I tried and still having the same problem
