### ISSUE TITLE
Information: mgp25's Instagram-API is down

### ISSUE THREAD

**Issue by Spixmaster** [ohld/igbot#1274]
This is not an issue rather information. https://github.com/mgp25/Instagram-API is down. I do not really know the reason. DMCA means stolen work which cannot be the case.

**Comment by ohld** [comment]
Thank you. We already know about this. FYI you can find more information here: https://github.com/github/dmca/blob/master/2020/01/2020-01-22-facebook.md

**Comment by Spixmaster** [comment]
@ohld Thanks. I read it. Can this happen to other repos like this one too?
