### ISSUE TITLE
What is Constants EXPERIMENTS and LOGIN_EXPERIMENTS

### ISSUE THREAD

**Issue by yaniferhaoui** [ohld/igbot#1275]
### Before submitting an issue, make sure you have:
- [X ] Updated to the lastest version
- [ X] Read the [README](https://github.com/instagrambot/instabot/README.md)
- [ X] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ X] Reviewed the sample code in [tests](https://github.com/instagrambot/instabot/tree/master/tests) and [examples](https://github.com/instagrambot/instabot/tree/master/examples)

### Which example file are you using?

```
config.py
https://github.com/instagrambot/instabot/blob/master/instabot/api/config.py
```

---

### Describe your Question/Issue:

Hello,

Someone know what is Constants EXPERIMENTS, LOGIN_EXPERIMENTS in the file constants.py ?
I guess that identify something in the emulated device, so how to modify them from my personal Phone datas ?

Thanks :)

**Comment by bruvv** [comment]
Can you link the file you're talking about

**Comment by yaniferhaoui** [comment]
> Can you link the file you're talking about

yes this is : https://github.com/instagrambot/instabot/blob/master/instabot/api/config.py

**Comment by bruvv** [comment]
Ah nog the constant.py file. May I ask why you are interested in this question?

**Comment by yaniferhaoui** [comment]
> Ah nog the constant.py file. May I ask why you are interested in this question?

Because I would like to change datas that could identify a device. I would like to emulate my personal device or another device to seems different than others instagram bots and less susipicious.

**Comment by bruvv** [comment]
It's being sent by the app to Instagram. That's why we added it.
