### ISSUE TITLE
Is there anyway of interacting with the poll stickers?

### ISSUE THREAD

**Issue by drsteve1998** [ohld/igbot#1278]
**Is your feature request related to a problem? Please describe.**

I know there is an api that can read users story. I am just wondering if it is possible to interact with the stickers like poll sticker.

**Describe the solution you'd like**

An api would be nice
**Describe alternatives you've considered**

**Additional context**

**Comment by bruvv** [comment]
It's not possible

**Comment by drsteve1998** [comment]
But I've seen bots like stellation media have this kind of feature
