### ISSUE TITLE
[BUG] Error

### ISSUE THREAD

**Issue by Noah-pixel** [ohld/igbot#1288]
**Example file**

```
If you ran an example file specify it here.
```

**Describe the bug**

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 9-10: truncated \UXXXXXXXX escape

**Log**

```
here
```

**To Reproduce**

(EXAMPLE:) Steps to reproduce the behavior:
1. Run file:
2. Edit '...'
3. Run '....'

**Expected behavior**

**Additional context**

**Version**

Python version (`python -v`):
OS: Win/Linux/MacOS

**Comment by Noah-pixel** [comment]
bruvv where can I contact you in private? I need to talk with you asap.

**Comment by bruvv** [comment]
And why is that?

**Comment by Noah-pixel** [comment]
I need your help.
