### ISSUE TITLE
Is there a way to remove the [DEBUG] messages from output?

### ISSUE THREAD

**Issue by javiersempere** [ohld/igbot#1295]
### Before submitting an issue, make sure you have:
- [X] Updated to the lastest version
- [X] Read the [README](https://github.com/instagrambot/instabot/README.md)
- [X] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X] Reviewed the sample code in [tests](https://github.com/instagrambot/instabot/tree/master/tests) and [examples](https://github.com/instagrambot/instabot/tree/master/examples)

### Which example file are you using?

like_users_from_file.py

### Describe your Question/Issue:

In the last versions the output is verbose with lots of DEBUG messages. Is it possible to remove the DEBUG messages?

**Comment by bruvv** [comment]
I rather have you not do that. There are a lot of issues currently.
