### ISSUE TITLE
[QUESTION] Saving DM photos/resending them?

### ISSUE THREAD

**Issue by adam-ristov** [ohld/igbot#1319]
### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version
- [x] Read the [README](https://github.com/instagrambot/instabot/README.md)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/instagrambot/instabot/tree/master/tests) and [examples](https://github.com/instagrambot/instabot/tree/master/examples)

### Describe your Question/Issue:

I couldnt find a lot of information regarding the DM functions of the bot, and i wanted to ask if it is possible to somehow save images that are received from DMs, and/or perhaps a way to resend the received photo back to the sender?

**Comment by bruvv** [comment]
At this moment it is not possible. we first have to fix the (soft)banns. feel free to develop it though and contribute to the project!
