### ISSUE TITLE
Tagging accounts

### ISSUE THREAD

**Issue by emreozen** [ohld/igbot#1324]
### Before submitting an issue, make sure you have:
- [x] Updated to the lastest version
- [x] Read the [README](https://github.com/instagrambot/instabot/README.md)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Reviewed the sample code in [tests](https://github.com/instagrambot/instabot/tree/master/tests) and [examples](https://github.com/instagrambot/instabot/tree/master/examples)

### Describe your Question/Issue:

Is there a way to tag accounts on the pictures we post via instabot?

**Comment by bruvv** [comment]
no not yet but feel free to make a pull request!
