### ISSUE TITLE
[BUG] Upload video

### ISSUE THREAD

**Issue by majda107** [ohld/igbot#1340]
Upload video function not working, throws no errors but video doesn't upload...

Log from logger...

```
2020-03-02 17:22:51,696 - INFO - Started uploading 'video.mp4'
Analizing `video.mp4`
FOUND w:720, h:900, rotation=0, ratio=0.8
Vertical video
2020-03-02 17:23:11,453 - INFO - Video 'video.mp4' uploaded
```

**To Reproduce**

1. Use any .mp4 video
2. Create simple program that logins to instabot and uploads video
3. use `upload_video()` function

Upload photo works fine...

**Comment by Hatchet-Harry** [comment]
Still have this issue here.
Any solution?
