### ISSUE TITLE
can you add a function to upload ablum that have 10 pictures? 

### ISSUE THREAD

**Issue by bobbybubble** [ohld/igbot#1345]
can you add a function to upload ablum that have 10 pictures?  many tks.

**Comment by bobbybubble** [comment]
could you please add a function to upload album that have 10 pics, many tks.   On Wednesday, March 4, 2020, 11:50:41 PM GMT+8, duplicate-issues[bot] <notifications@github.com> wrote:  
 
 
Hey @bobbybubble,

We did a quick check and this issue looks very darn similar to
   
   - #1343 - [QUESTION] Can't login, Instagram keep asking me if this was me and every time I click yes still won't login 
   - #1341 - Pics directory in autopost deletes files
   - #1329 - Crawl user.id by non-login/guest request

This could be a coincidence, but if any of these issues solves your problem then I did a good job 😄
 
If not, the maintainers will get to this issue shortly.

Cheers,
Your Friendly Neighborhood ProBot

**Comment by averypfeiffer** [comment]
@bruvv I've seen multiple issues related to this but most don't have responses. I don't mind helping to implement this feature if needed. Is this is a limitation of the api itself or just the manpower to implement?

**Comment by bruvv** [comment]
Of you can make a pr that will be great. There shouldn't be a limit on the api it's just that I don't have much time lately

**Comment by averypfeiffer** [comment]
Definitely willing to give it a go. Can you point me in the right direction of where to look? Maybe some instagram documentation to read up or the like? I know that this API is **not** affiliated with instagram, but is there something I can reference to find the correct endpoints? It seems that you need to create the post first, retrieve the carousel, and then start adding more photos to it. Is this correct as far as you know?
