### ISSUE TITLE
[BUG] Liking is very slow, even if you decrease like_delay

### ISSUE THREAD

**Issue by alexriedel1** [ohld/igbot#1348]
**Example file**

I checked this via different files, suchs as the multi scirpt CLI and also the simple like_users scirpts. 

**Describe the bug**

If I run likes on hashtags, timeline or whatever, the time between two like seems to be very long. Is this wanted to not make suspicious actions or is it actually a bug? 
**Log**

2020-03-05 16:09:44,218 - INFO - Going to like 81 medias.
  4%|████▌                                                                                                                       | 3/81 [06:05<2:09:16, 99.45s/it]2020-03-05 16:18:18,861 - INFO - Liked media 2258221282466562469_2056163780.
  6%|███████▌                                                                                                                   | 5/81 [14:16<3:51:16, 182.59s/it]

**Expected behavior**

Can you tell me where to set the delay time between two likes? It seems that the variable like_delay in the bot.py doesnt have any influence on it. 
**Additional context**

**Version**

Python version (`python -v`): 3.7
OS: Win

**Comment by alicnakar** [comment]
I can't log in yet. How did you solve this problem?

**Comment by alexriedel1** [comment]
I had Issues (checkpoint_challenge_required)  with my real instagram accounts so i created a new one and this one is working fine

**Comment by alexriedel1** [comment]
> I can't log in yet. How did you solve this problem?
I had Issues (checkpoint_challenge_required) with my real instagram accounts so i created a new one and this one is working fine

**Comment by alexriedel1** [comment]
> I can't log in yet. How did you solve this problem?

I had Issues (checkpoint_challenge_required) with my real instagram accounts so i created a new one and this one is working fine

**Comment by alicnakar** [comment]
> > Henüz giriş yapamıyorum. Bu sorunu nasıl çözdün?
> 
> Ben gerçek instagram hesapları ile sorunları (checkpoint_challenge_required) vardı, bu yüzden yeni bir tane oluşturdum ve bu iyi çalışıyor

thank you

**Comment by bruvv** [comment]
This is not a bug it's for a reason
