### ISSUE TITLE
Config bot from CLI

### ISSUE THREAD

**Issue by rasperepodvipodvert** [ohld/igbot#135]
Предлагаю сделать настройку всех параметров через CLI и вынести в отдельный файл:
bot = Bot(
            proxy=None,
            max_likes_per_day=1000,
            max_unlikes_per_day=1000,
            max_follows_per_day=350,
            max_unfollows_per_day=350,
            max_comments_per_day=100,
            max_likes_to_like=100,
            max_followers_to_follow=2000,
            min_followers_to_follow=10,
            max_following_to_follow=7500,
            min_following_to_follow=10,
            max_followers_to_following_ratio=10,
            max_following_to_followers_ratio=2,
            max_following_to_block=2000,
            min_media_count_to_follow=3,
            like_delay=10,
            unlike_delay=10,
            follow_delay=30,
            unfollow_delay=30,
            comment_delay=60,
            whitelist=False,
            blacklist=False,
            comments_file=False,
            stop_words=['shop', 'store', 'free']
)

**Comment by maxkrivich** [comment]
@rasperepodvipodvert  типа сделать JSON файл с настройками, а потом его просто пропарсить?

**Comment by rasperepodvipodvert** [comment]
Ага

5 мая 2017 г. 13:54 пользователь "Max Krivich" <notifications@github.com>
написал:

**Comment by maxkrivich** [comment]
@rasperepodvipodvert я сейчас попробую это сделать

**Comment by rasperepodvipodvert** [comment]
Вообще, я думал что это будет ini файл :) но можно и json не принципиально.

*При ответе на письмо, прошу включать в копию ВСЕХ получателей!*

С уважением,
<http://filatovz.ru>

2017-05-05 15:15 GMT+03:00 Max Krivich <notifications@github.com>:

**Comment by maxkrivich** [comment]
@rasperepodvipodvert в python я так понял конструкторы перегружать нельзя? Просто чтобы была обратная совместимость

**Comment by rasperepodvipodvert** [comment]
Без понятия!

Отправлено с iPad
