### ISSUE TITLE
[QUESTION] What does this request actully does??

### ISSUE THREAD

**Issue by Manjit2003** [ohld/igbot#1378]
I have seen instagram web sending this strange request many times...

`https://graph.instagram.com/logging_client_events`

The response contains this : 

`
{
   "checksum": "",
   "config": "",
   "config_owner_id": "",
   "app_data": "{}"
}
`
Can someone tell me what actully this does??
or does it is used to differenciate bots and real browsers??

**Comment by bruvv** [comment]
It's an analytics api that is saved to block. I have it blocked in my dns server.
