### ISSUE TITLE
400 error on like by hashtag

### ISSUE THREAD

**Issue by romeumellobr** [ohld/igbot#139]
After some likes by hashtag, the bot drops 400 error and mess counting of total liked media.

2017-03-23 11:43:14,824 Going to like 75 medias.
2017-03-23 11:56:01,440 Request return 400 error!
2017-03-23 11:56:11,440 DONE: Total liked 145 medias.

**Comment by ermiyaeskandary** [comment]
Are you sure you haven't reached the daily like limit?

**Comment by ermiyaeskandary** [comment]
It's around 200 per hour approx and if you're liking at the same time manually, you've probably hit the limit.

**Comment by ohld** [comment]
Should be fixed in current version.

**Comment by chrisspiegl** [comment]
@ohld is the system picking up even if it gets multiple 400 errors or does it need a manual restart?

**Comment by ohld** [comment]
Manual restart can help.
