### ISSUE TITLE
Некорректно работающая подписка

### ISSUE THREAD

**Issue by dankarization** [ohld/igbot#140]
Подписываясь на аккаунты (не важно, по хэштэгам, фолловерам или файлу), бот "недоподписывается". 

У меня есть файл аккаунтов (созданный этим же ботом). В нем 144 человека. Запуская подписку по нему, бот выдает "подписался на 40 человек", что уже меньше, чем было в файле. А на деле подписался он на 34 человека. Тот же недобор получается и при подписке любым другим способом.

**Comment by ohld** [comment]
Недобор - фильтрация аккаунтов. Почитай про нее в документации.
