### ISSUE TITLE
 Failed to establish a new connection: [Errno -2] Name or service not known'

### ISSUE THREAD

**Issue by streamel** [ohld/igbot#141]
Все время вылетает с такой ошибкой:
Getting followers:  99%|██████████████████████████████████████████████████████████████████████████████████████████▍| 271425/273085 [1:26:44<00:31, 52.46it/s]2017-03-23 17:13:36,926 - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/friendships/176890192/followers/?rank_token=4592671919_8606f047-f42a-4281-a49c-eeede7b7fd10&max_id=AQBId4QBOWRLUKaBqRBkvFklKRAFHvpCe7mJX0svV1qhuWW7QGI9D7ZSMbr3WWT89CIJW89q-AGMvM6RrmxVIfAFfVbsUFwOKlktaLuuoNvzfw (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f43e3263910>: Failed to establish a new connection: [Errno -2] Name or service not known',))
Getting followers: 273139it [1:27:26, 41.73it/s]                                                                                                             Killed

на самых разных этапах. Во время расстановки лайков или на этапе сбора людей для лайков.

update
Если у аккаунта пользователей которого фолловишь или лайкаешь очень большое количество подписчиков, то много запросов уходит на сбор фолловеров. Нужно как-то разбить на этапы сбор аккаунтов для фолловинга или лайкинга. 
Делать это порциями. может по 3000 за раз - после еще подгружать.

**Comment by ohld** [comment]
Update the bot. Reopen if have not solved yet.
