### ISSUE TITLE
Request - allow user selection from command line

### ISSUE THREAD

**Issue by gnesher** [ohld/igbot#142]
Hi,

During run the bot currently ask you to select the user to be used (which prevents me from using a cron job to run it). Any way to circumvent this?

Cheers

**Comment by ohld** [comment]
Yes. That was a mistake by me. I'll fix that as soon as i can.

**Comment by gnesher** [comment]
Cheers :)
I'll try to start contributing back, but have not touched python in ages

**Comment by ohld** [comment]
@gnesher Done! Check any example to find the solution.
