### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by alblz** [ohld/igbot#152]
I need help, how do I run the examples.
I can only run the like_example

**Comment by ohld** [comment]
Provide the screenshots and the commands that you have passed to the terminal

**Comment by alblz** [comment]
<img width="1280" alt="captura de pantalla 2017-03-29 a las 18 33 21" src="https://cloud.githubusercontent.com/assets/26446135/24465725/5da1cfc6-14ae-11e7-85f2-3d50cdc23c80.png">

**Comment by ohld** [comment]
You should pass a user which followers you want to like. 
For example for **ohld** user:
'''
python like_user_followers.py ohld
'''

**Comment by alblz** [comment]
thank you ohld
