### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by alblz** [ohld/igbot#157]
Getting following:  77%|███████████████▍    | 796/1031 [00:20<00:00, 612.65it/s]2017-03-31 18:30:37,933 - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/friendships/4491083/following/?max_id=AQA1I1BRjSGH6Uog43UKuyGDIGwyCFNePWPDRxmGvCJQvcJ5dO7MBYs7ESzfOC8TI1fUkjU3cqV-9EfBCitl3VgDesxy5amwp81qubS18YVmRA&ig_sig_key_version=4&rank_token=304711057_6f05280a-2931-4068-b222-0cc9fd3d64a5 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x100eea190>: Failed to establish a new connection: [Errno 65] No route to host',))

what´s wrong?¿?

**Comment by ohld** [comment]
You have unstable internet.
