### ISSUE TITLE
Commented with text: wow

### ISSUE THREAD

**Issue by gnesher** [ohld/igbot#159]
I've got a comment bot running for a few days and just noticed that (at least in the cli) I only get the following text:

"Commented with text: wow" which is odd as "wow" is not one of my comment options.

I'm not sure how to verify if this is just a logging error or if there's a larger problem here.

**Comment by ohld** [comment]
It will comment with "wow" then it can't find the file with comments. You should pass to the script the path to this file. If it can't find this file it will log out the info.
