### ISSUE TITLE
bot.login - request

### ISSUE THREAD

**Issue by gnesher** [ohld/igbot#160]
I've mentioned this before but maybe I'm missing something.
bot.login does not seem to accept any parameter which means that when I run the bot via cron it fails as I'm expected to pass in the account (1 for existing account, 0 for new one etc.)

Any way to pass that as a parameter?

**Comment by ohld** [comment]
In a week I hope the new version of instabot will be released. I made some architectural mistakes that should be fixed to continue bug fixing.
