### ISSUE TITLE
New Example like and follow user followers and question

### ISSUE THREAD

**Issue by Tassaczek** [ohld/igbot#166]
There should be example which likes (2-3 random photo) and start to follow a user followers, but in that order. :D 

So it take list of user followers, go to first: likes 2-3 photos, and start to follow that user. 

And question: 
I have seen somewhere in API config.py a device settings. Does Instagram check it somehow? Should we change it or it does not metter? Instagram let multiple users to show that they use same phone with the same IG_SIG_KEY?

**Comment by ghost** [comment]
Has anyone worked on this?

**Comment by ohld** [comment]
Reopen if you still have not found the solution (don't forget to update the bot).
