### ISSUE TITLE
BUG: Infinite inheritance

### ISSUE THREAD

**Issue by SecurityQQ** [ohld/igbot#170]
Hello.

## Bug
 You use `super(self.__class__, self).__init__()` in `Bot.py`. 

## Why it is bad
That is actually very bad, because of that issue: http://stackoverflow.com/questions/4235078/how-to-avoid-infinite-recursion-with-super. No one can inherit from Bot in cause of that issue.

## Solution:
Replace `super(self.__class__, self).__init__()` by `super(Bot.__init__, self).__init__()` or just` super()` for python 3

**Comment by ohld** [comment]
Thanks! I'll fix it in a next bot version.

**Comment by ohld** [comment]
@SecurityQQ Can you please make a pull request with that correction?

**Comment by ohld** [comment]
@SecurityQQ Can you please make a pull request with that correction?
