### ISSUE TITLE
Follow Users Followers - Long Load Times

### ISSUE THREAD

**Issue by ghost** [ohld/igbot#174]
Quick question, when I pull users followers, sometimes I pull from users with many thousands of followers. so the load time is crazy long, and it wouldn't matter because I'm trying to cap the amount of follows I perform to 500 a day. Is there a way to set the script to only scrape the first 800 or so users.

New to python and really enjoy the opportunity to learn more about the program :)

``` python
def follow_followers(self, user_id, nfollows=None):
    self.logger.info("Follow followers of: %s" % user_id)
    if not user_id:
        self.logger.info("User not found.")
        return
    follower_ids = self.get_user_followers(user_id)
    if not follower_ids:
        self.logger.info("%s not found / closed / has no followers." % user_id)
    else:
        self.follow_users(follower_ids[:nfollows])
```

**Comment by tayfunyasar** [comment]
Try to save each 800 followers into different csv files using examples/multi_script_CLI.py (command12)

Is there any better solutions?

**Comment by ohld** [comment]
The better solution will be released in a new Instabot version, which is already under development.

**Comment by octave** [comment]
Looking forward to it!

**Comment by ghost** [comment]
@ohld sounds awesome, when do you think the new version will drop :)

**Comment by ohld** [comment]
the new version is developing here https://github.com/instagrambot/instapro but this version is mostly for developers

**Comment by BobZombiE69** [comment]
an example: 

in ultimate_schedule\ultimate.py

`def job4(): bot.follow_followers(get_random(random_user_file),200) #only scan and follow 200 users`

in multi_script_cli.py

    elif ans == "2":
        print("""
        1.insert username
        2.use username database
        """)
        if "1" in sys.stdin.readline():
            user_id = input("who?\n").strip()
        else:
            user_id = random.choice(bot.read_list_from_file(users_file))
        bot.follow_followers(user_id,100)  #add nfollows ,100 only scan and follow 100 users
        menu_follow()

**Comment by ohld** [comment]
Reopen if you still have not found the solution (don't forget to update the bot).
