### ISSUE TITLE
How to create example.py and import examples/follow-users.py ?

### ISSUE THREAD

**Issue by tayfunyasar** [ohld/igbot#175]
I'm new with python and don't know how.

Can anyone help?

**Comment by ohld** [comment]
I don't understand what is `examples/follow-users.py` - there is no file in this directory.
You can run any script from examples folder without any code correction.

**Comment by tayfunyasar** [comment]
I meant, I want to override default bot/bot.py init function arguments and call another existing py function(examples/follow_users_by_hashtag.py)

**Comment by ohld** [comment]
You can change the code in example script and pass to bot `__init__` function parameters you want.
