### ISSUE TITLE
258 followed users from 1210

### ISSUE THREAD

**Issue by rebbu** [ohld/igbot#177]
> What would you like to do? 6
Who? XXXXXXXXXXX
2017-0x-xx 0x:x8:x3,xx8 - INFO - Follow followers of: XXXXXXXXXXX
2017-0x-xx 0x:x8:x7,xx6 - INFO - Going to follow 1210 users.
100%|####################################| 1210/1210 [3:15:28<00:00, 12.44s/it]
2017-0x-2x 1x:x3:x5,xx1 - INFO - DONE: Total followed 258 users.

Hi all, 
can someone explain - 258 followed users from 1210 users?
Thanks.

**Comment by ohld** [comment]
Other users was filtered. Read the filtration conditions and try to play with bot class construction arguments.

**Comment by rebbu** [comment]
Great, thanks
