### ISSUE TITLE
Unfollow_Everyone Ignoring Set Delay Time and Possibly Whitelist.txt

### ISSUE THREAD

**Issue by ghost** [ohld/igbot#179]
Hi! Still trying to get my bearings with these scripts, it seems that when I run Unfollow_Everyone I want it to unfollow accounts based on a 75 second delay to stay safe and not get banned. When I run, unfollow_everyone, in the first 10 seconds it unfollowed about 5 accounts, ignoring my set delay parameter.

Additionally, I have a set whitelist, but it seems it's possible that it's being ignored if my delay parameter is also being ignored.

Would love to hear feedback and thoughts. :) Definitely enjoy the learning opportunity! Screenshot attached, I can't copy and paste from my aws remote server.

<img width="400" alt="screen shot 2017-04-23 at 10 42 33 am" src="https://cloud.githubusercontent.com/assets/26857649/25314427/a3f85d3e-2811-11e7-9e76-286485e43f0b.png">

**Comment by ohld** [comment]
all seems to be coded correctly. I can't give the answer why it is not working. I'll test it by myself.

**Comment by Ivolvy** [comment]
I am also interested in how to make whitelist work. It seems to not read the file.

**Comment by ghost** [comment]
@ohld, okay, thank you!

**Comment by Brunya** [comment]
Did you fin the problem?
