### ISSUE TITLE
Using bot for 2 or more accounts from the same computer

### ISSUE THREAD

**Issue by rebbu** [ohld/igbot#180]
- what is the best way to use bot for 2 or more instagram accounts from the same computer - Win OS?
- how can i save instabot.log to folder on my choice?

Thanks

**Comment by simongomez95** [comment]
I guess the best and safest way to use more than 1 ig account at the same computer would be running each one in a separate docker container, and using a different proxy for each one.

**Comment by ohld** [comment]
You can use up to 5 accounts from the same computer
