### ISSUE TITLE
How to not re-follow people you have unfollowed?

### ISSUE THREAD

**Issue by rollbahn** [ohld/igbot#184]
Is there a way to store the usernames you've unfollowed in the past so they are not re-followed again the next day. I don't want to be unfollowing and re-following the same people over and over again if possible?

**Comment by simongomez95** [comment]
You would have to build your own script that blacklists users as you unfollow them. Or just modify the unfollow function on /instabot/bot/bot_unfollow.py to blacklist users.

**Comment by rollbahn** [comment]
Thanks - will try that

**Comment by ghost** [comment]
@rollbahn, did you script a solution? Would love to see an example. Picking up python and this is a cool way of learning pieces of the program 👍

**Comment by rollbahn** [comment]
@jessmike10011 Sorry I am a newbie too so not much help to you at this stage. I am working my way through a few different bits of code to try and learn it and also come up with something useful for myself.

**Comment by tayfunyasar** [comment]
Can we do this optional? It would be nice. All followed-requested-unfollowed usernames written in blacklist.txt

**Comment by thestation** [comment]
Has anyone figured out how to do this yet? I tried a bunch of different things but python is just not my specialty.

**Comment by ohld** [comment]
The only solution is to store anyway this users in file.
So you unfollow this users, and then follow them reading from file.

**Comment by thestation** [comment]
How about this ohld? Is there a way to make it so everyone followed goes on a dont_follow.txt? Then implement it in like the whitelist.txt and blacklist.txt, so it checks to make sure it will not follow those users.

**Comment by ohld** [comment]
If you found the solution please make the pull request.
