### ISSUE TITLE
get follower list in .txt

### ISSUE THREAD

**Issue by Kabal1** [ohld/igbot#188]
Hello, how can I get the followers of an user into an .txt ?

**Comment by s0kil** [comment]
@Kabal1 
Here is writing user followers to txt file, from what I see you can't currently convert user_id to a username, so you will get user_id .



"""
    instabot example

    Workflow:
        Write user's followers to .txt file.
"""

import sys
import os
import time
import random
from tqdm import tqdm
import argparse

sys.path.append(os.path.join(sys.path[0], '../'))
from instabot import Bot

parser = argparse.ArgumentParser(add_help=True)
parser.add_argument('-u', type=str, help="username")
parser.add_argument('-p', type=str, help="password")
parser.add_argument('-proxy', type=str, help="proxy")
parser.add_argument('users', type=str, nargs='+', help='users')
args = parser.parse_args()

bot = Bot()
bot.login(username=args.u, password=args.p,
          proxy=args.proxy)
f = open("user_followers.txt","w+")
for username in args.users:
    for followers in bot.get_user_followers(username):
        f.write("%d\r\n" % (int(followers)+1))

f.close()
