### ISSUE TITLE
ImportError: No module named_vendor

### ISSUE THREAD

**Issue by DataBass504** [ohld/igbot#189]
First off thank you for all your hard work, I'm having issues getting the script to run after installation on my RPi3 using Raspbian (Jessie) when I run the command in terminal:

pi@databass:~ $ cd instabot/examples
pi@databass:~/instabot/examples $ python multi_script_CLI.py
2017-05-05 10:41:35,557 - INFO - Instabot Started
2017-05-05 10:41:35,558 - INFO - Multi script run
Traceback (most recent call last):
  File "multi_script_CLI.py", line 131, in <module>
    print('INSTABOT VERSION: %s ' % bot.version())
  File "/usr/local/lib/python2.7/dist-packages/instabot/bot/bot.py", line 133, in version
    from pip._vendor import pkg_resources
ImportError: No module named _vendor

Everything appeared to install correctly, I have both python 2 & 3 installed on my system.

**Comment by sudoguy** [comment]
`pip install -U pip`

Maybe this will solves the problem.

**Comment by DataBass504** [comment]
@sudoguy This did not solve my issue, I actually tried this before posting.
pi@databass:~/instabot $ sudo pip install -U pip
Downloading/unpacking pip from https://pypi.python.org/packages/b6/ac/7015eb97dc749283ffdec1c3a88ddb8ae03b8fad0f0e611408f196358da3/pip-9.0.1-py2.py3-none-any.whl#md5=297dbd16ef53bcef0447d245815f5144
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB): 1.3MB downloaded
Installing collected packages: pip
  Found existing installation: pip 1.5.6
    Not uninstalling pip at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed pip
Cleaning up...
pi@databass:~/instabot/examples $ python multi_script_CLI.py
2017-05-05 12:16:17,861 - INFO - Instabot Started
2017-05-05 12:16:17,863 - INFO - Multi script run
Traceback (most recent call last):
  File "multi_script_CLI.py", line 131, in <module>
    print('INSTABOT VERSION: %s ' % bot.version())
  File "/usr/local/lib/python2.7/dist-packages/instabot/bot/bot.py", line 133, in version
    from pip._vendor import pkg_resources
ImportError: No module named _vendor
pi@databass:~/instabot/examples $

**Comment by sudoguy** [comment]
@DataBass504, perhaps [this](https://github.com/instagrambot/instabot/pull/190) can fixes your problem

**Comment by DataBass504** [comment]
I understand what you want me to do but i'm getting permission denied, how can i edit the file through terminal? Sorry I'm somewhat new too linux.

You want me to add:
>          try:
>             from pip._vendor import pkg_resources
>         except ImportError:
>             import pkg_resources
to the bot.py file on line 134 in the "/usr/local/lib/python2.7/dist-packages/instabot/bot" directory correct?
to the

**Comment by DataBass504** [comment]
I was able to get past premissions using sudo nano, here is what im getting now:
pi@databass:~/instabot/examples $ python multi_script_CLI.py
Traceback (most recent call last):
  File "multi_script_CLI.py", line 7, in <module>
    from instabot import Bot
  File "/usr/local/lib/python2.7/dist-packages/instabot/__init__.py", line 2, in <module>
    from .bot import Bot
  File "/usr/local/lib/python2.7/dist-packages/instabot/bot/__init__.py", line 1, in <module>
    from .bot import Bot
  File "/usr/local/lib/python2.7/dist-packages/instabot/bot/bot.py", line 134
    try:
       ^
IndentationError: unindent does not match any outer indentation level

**Comment by sudoguy** [comment]
Before `try` and `except` there must be 8 whitespaces. Check again pls

**Comment by DataBass504** [comment]
Ok, I went back & corrected the spacing now im getting this:

> pi@databass:~/instabot/examples $ python multi_script_CLI.py
> Traceback (most recent call last):
>   File "multi_script_CLI.py", line 7, in <module>
>     from instabot import Bot
>   File "/usr/local/lib/python2.7/dist-packages/instabot/__init__.py", line 2, in <module>
>     from .bot import Bot
>   File "/usr/local/lib/python2.7/dist-packages/instabot/bot/__init__.py", line 1, in <module>
>     from .bot import Bot
>   File "/usr/local/lib/python2.7/dist-packages/instabot/bot/bot.py", line 135
>     from pip._vendor import pkg_resources
>        ^
> IndentationError: expected an indented block

**Comment by sudoguy** [comment]
Must be like [here](https://github.com/sudoguy/instabot/blob/8ce19bd26cd9066d564217246c3731ad09d9f98a/instabot/bot/bot.py). 12 white spaces before `from` and `import`.

**Comment by DataBass504** [comment]
Ok, I did notice on the other lines I used tabs so I corrected that as well. That did the trick, everything is working correctly now! THANK YOU SO MUCH!!!
