### ISSUE TITLE
follow_user_followers & follow_user_followings not work

### ISSUE THREAD

**Issue by Nader-abdi** [ohld/igbot#192]
hi all
what this files not work??
follow_user_followers.py
follow_user_following.py
file run but not follow users only follow one user!!!

**Comment by watloejoegoan** [comment]
did you find a solution?

**Comment by Kabal1** [comment]
soltuibo ?

**Comment by ohld** [comment]
Reopen if you still have not found the solution (don't forget to update the bot).
