### ISSUE TITLE
return 400 error! after 4 comment

### ISSUE THREAD

**Issue by ernecati** [ohld/igbot#193]
`post_list = bot.get_hashtag_medias("hashtag")

for post in post_list:    
    bot.comment(post, "comment @someone")
    `
After forth comment it returns 400 error. is it too fast or something? How can i see error details or detailed error message?
by the way i'm not doing something manually.

2017-05-11 01:08:03,517 - INFO - Received 67 medias.
2017-05-11 01:08:03,520 - INFO - After filtration 64 medias left.
2017-05-11 01:13:17,358 - WARNING - Request return 400 error! (5. attempt)
2017-05-11 01:14:31,339 - WARNING - Request return 400 error! (6. attempt)

**Comment by ghost** [comment]
I am currently like banned and i get Error 400 no matter which script i run. Maybe you have the same issue?

**Comment by ernecati** [comment]
Maybe, i tried some other scripts and again same error. But theres no problem commenting manually with phone.

**Comment by ghost** [comment]
I generally get Error 400, already when logging in... But on Phone and Browser everything works...

**Comment by JoshTristram** [comment]
Please send the hole file

**Comment by ernecati** [comment]
all of codes are here.

from whatsapp import Client
phone_to = '90536726xxxx'
try:
    client = Client(login='905373647994', password='FM3l99IgCVEPkmyEn5+OSAaQ/a8=')
    client.send_message(phone_to, 'Hello Word!')
except Exception as E:
    print E

**Comment by ohld** [comment]
Please follow the issue template to have the proper help with your problem.
