### ISSUE TITLE
Unfollow less the white list

### ISSUE THREAD

**Issue by zsvendo** [ohld/igbot#195]
I need to give unfollow in followers but I want to preserve about 100 followers how to do is on the whitelist? Is this programmed already?

**Comment by maxkrivich** [comment]
@zsvendo try to use get_user_followers to get all followers and truncate this list kind a arr = arr[:100] after that use this list as "white list".

**Comment by alexauvray** [comment]
Hello, I have the whitelist of people not to unfollow, but when I execute Unfollow everyone, with (whitelist=True), it still unfollows whitelisted users. Any idea ? Thanks

**Comment by alcaporal** [comment]
How can i active whitelist for ultimate_schedule unfollow_non_follower?

**Comment by alexauvray** [comment]
```
def unfollow_non_followers(self):
    self.logger.info("Unfollowing non-followers")
    followings = set([item["pk"] for item in self.getTotalSelfFollowings()])
    self.logger.info("You follow %d users." % len(followings))
    followers = set([item["pk"] for item in self.getTotalSelfFollowers()])
    self.logger.info("You are followed by %d users." % len(followers))
    diff = followings - followers - whitelist('/friends.txt')
    self.logger.info("%d users don't follow you back." % len(diff))
    self.unfollow_users(list(diff))
```

Would this work : diff = followings - followers - whitelist('/friends.txt') ?

**Comment by zsvendo** [comment]
The whitelist.txt is not working anyone can have some idea:
I run the 4.unfollow option and then the 2. unfollow everyone option.

But it unfollow all does not respect the whitelist.txt

**Comment by ohld** [comment]
Should be fixed in current version.
