### ISSUE TITLE
WARNING - That means 'too many requests'. I'll go to sleep...

### ISSUE THREAD

**Issue by rebbu** [ohld/igbot#199]
> WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes!

Hi, can you please tell me why is this happening and is it sends some kind of signals to IG that something "strange" is going on? Should i stop and restart bot when i receive this message?

Thanks

**Comment by JoshTristram** [comment]
yeah, it makes it look like you bot :) Could you tell me what file this is happning in? I will make a fix

**Comment by rebbu** [comment]
i am using ultimate_schedule script....i am not a programmer but i think that script in some point tries to do to many operations...i mean it does not finish previous scheduled operation and it is time to start new one and so it does 2 or more operations at same time...is it possible?

**Comment by JoshTristram** [comment]
Cound you please post the file

**Comment by rebbu** [comment]
file?

**Comment by rebbu** [comment]
it is default ultimate.py file...i did not make changes

**Comment by JoshTristram** [comment]
Could you please run the file and post the log. I need to know what part of the script is doing this.

**Comment by a11b1ack5** [comment]
I also got this warning, but from running the file like_user_followers.py (unedited). The log says:

> WARNING - Requst return 429 error!
> WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes!

**Comment by ghost** [comment]
@a11b1ack5  @JoshTristram 

Anyone land on a solution? I think it gets triggered if there's too much activity from your bot. Any general guidelines for max stuff per day? I try to keep mine running conservatively.

**Comment by ohld** [comment]
Reopen if you still have not found the solution (don't forget to update the bot).
