### ISSUE TITLE
Как работать с лайками по локации?

### ISSUE THREAD

**Issue by Dimster1996** [ohld/igbot#200]
Здравствуйте! Спасибо за такой крутой продукт в открытом доступе.
Запускаю файл like_medias_by_location.py, выбираю нужный аккаунт, ввожу название локации, количество лайков. И выходит ошибка:
[Скрин](https://www.dropbox.com/s/o4u5qnpdb6lv2fw/%D0%91%D0%B5%D0%B7-%D0%B8%D0%BC%D0%B5%D0%BD%D0%B8-3.jpg?dl=0)

В чем может быть проблема?:

**Comment by ohld** [comment]
Запустите с Python 3

**Comment by Dimster1996** [comment]
Использовать Python 3.0 всмысле?)
