### ISSUE TITLE
cant start bot on multi_script_CLI.py

### ISSUE THREAD

**Issue by arshiay** [ohld/igbot#203]
i get this error 
any solution?

Traceback (most recent call last):
  File "./multi_script_CLI.py", line 607, in <module>
    setting_18 = lines[18]
IndexError: list index out of range

**Comment by arshiay** [comment]
solved setting need a empty line because of no proxy but it didn't create automatically

maybe a bug i don't know

**Comment by thestation** [comment]
I'm having this same problem. How did you fix it exactly

**Comment by arshiay** [comment]
hi
just put an empty line in very end of setting.txt file
