### ISSUE TITLE
Help... Python Newbie here..

### ISSUE THREAD

**Issue by chitomod** [ohld/igbot#206]
when I run any of the example scripts except "multi_script_CLI.py" i get an error.
e.g. If I run "like_and_follow_last_user_media_likers.py".... I got this error

> usage: like_and_follow_media_likers.py [-h] [-u U] [-p P] [-proxy PROXY]
>                                        media_id
> like_and_follow_media_likers.py: error: the following arguments are required: media_id
> 
Will I edit this example script, if I am going to edit it will tell me how to do that in details.

**Comment by paijwar** [comment]
You don't need to edit,
you need to provide username and password of Instagram to this script in the following format.
script.py -u username -p password

I hope this will solve your issue.

**Comment by chitomod** [comment]
My platform is windows and i am still getting an error. PLEASE HELP!!!
e.g. when I run the scripts like this
note: those are not my real instagram username or password

C:\Users\Googleboy\instabot\examples>like_and_follow_last_user_media_likers.py -u killerman -p kill008
usage: like_and_follow_media_likers.py [-h] [-u U] [-p P] [-proxy PROXY]
                                       media_id
like_and_follow_media_likers.py: error: the following arguments are required: media_id

**Comment by chitomod** [comment]
OK,  thanks now I have solved the problem
