### ISSUE TITLE
"Reset_following.py" crashes

### ISSUE THREAD

**Issue by alexauvray** [ohld/igbot#208]
Hello, here's what happen when reset_following.py is executed :

unbound method start() must be called with task instance as first argument (got nothing instead)

any idea ?

Thanks !

**Comment by ohld** [comment]
@sudoguy

**Comment by sudoguy** [comment]
@ohld, @alexsonnay, it's not my feature, but I'll make a fix today.

**Comment by sudoguy** [comment]
@alexsonnay @ohld this pull request #211 .

**Comment by alexauvray** [comment]
@sudoguy @ohld thanks !!

**Comment by alexauvray** [comment]
Now first step works, but second step doesn't :). Nothing happens when typing 1, 2, or 3.


```
        1
Type 1,2 or 3.

        Please select
        1) Create Friends List
            Make a list of the users you follow before you follow bot.
        2) Restore Friends List
            Unfollow all user accept for the users in your friends list.
        3) Exit
```

**Comment by sudoguy** [comment]
@alexsonnay, if you using instabot with pip, then you didn't have my update, because developer didn't make upgrade in pip. If you wanna have update right now, then you must uninstall instabot in pip
```
pip uninstall instabot
```
And download last version from repository.
Or just wait upgrade in pip.

**Comment by alexsonnay** [comment]
@sudoguy ok thx !!

**Comment by alexauvray** [comment]
@sudoguy ok thx ! however, I did not install instabot with pip 
`(Cannot uninstall requirement instabot, not installed)`
I just downloaded the ZIP. And I redownloaded the last one a few minutes ago. And I still can't get through the second step.

**Comment by alexauvray** [comment]
I managed to bypass first step by directly executing the step I want replacing Task.start(bot) by Task.two(bot). Seems to work ! Thanks for the script !
