### ISSUE TITLE
Bot likes more media than limit set by max_likes_per_day

### ISSUE THREAD

**Issue by a11b1ack5** [ohld/igbot#209]
The limit of max_likes_per_day (in the file instabot/bot/bot.py) as instructed in the readme to 500, but my bot just continued and I had to stop it at 570. There was no warning in the log.

If this happens, is there a way to let the bot pick up from when it left off when stopped?

**Comment by ohld** [comment]
Please use the issue template.
Reopen if have not solved yet.
