### ISSUE TITLE
DEVELOPERS: Get rid of "print" functions and use right logging

### ISSUE THREAD

**Issue by ohld** [ohld/igbot#21]
**Issue for future developers.** 
Logging using "print" function is not good. We should use special modules for logging. 
Try to use only standard Python libraries to prevent enlarging of the `requirements.txt`.
Python standart logging library: https://docs.python.org/3/library/logging.html

**Comment by DrCherry** [comment]
Everything but the interactive print() statements have been converted to logging.  Of course logging could be better organized and used but this is a good start.
