### ISSUE TITLE
WARNING - Request return 429 error!

### ISSUE THREAD

**Issue by zsvendo** [ohld/igbot#212]
Does this error next cause it?
2017-05-19 18:30:16,852 - INFO - Like followers of:
2017-05-19 18:41:52,638 - WARNING - Request return 429 error!
2017-05-19 18:41:52,638 - WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes.

**Comment by maverjk** [comment]
I had the same experience and I realized that is normal to have this warning from Instagram if we are going to exaggerate in the use of the bot. I do not know what is the threshold yet, but would be interesting to understand it, collecting the experiences of everyone.

**Comment by AlexBGoode** [comment]
https://www.instagram.com/developer/limits/

Response Codes
If your app exceeds any of these rate limits, you will receive a response with an HTTP response code of 429 (Too Many Requests). The body of the response will consist of the following fields:

FIELD	VALUE
code	429
error_type	OAuthRateLimitException
error_message	The maximum number of requests per hour has been exceeded.

You may also receive responses with an HTTP response code of 400 (Bad Request) if we detect spammy behavior by a person using your app. These errors are unrelated to rate limiting.

**Comment by ildarnm** [comment]
I get same error when start like followers from cli.

**Comment by ildarnm** [comment]
And I think it is happing because of  method check_user (line 40 bot_like.py)
It is work without this line
