### ISSUE TITLE
Follow_users_following

### ISSUE THREAD

**Issue by rawrsefi** [ohld/igbot#213]
Im trying to run this script but getting this error, been trying to find a users document but have been unable to do so

usage: follow_user_following.py [-h] [-u U] [-p P] [-proxy PROXY]
                                users [users ...]
follow_user_following.py: error: the following arguments are required: users
>>>

**Comment by Kabal1** [comment]
How did you fix it ?

**Comment by rawrsefi** [comment]
What's your issue exactly

**Comment by tah62k** [comment]
try this 
from instabot import Bot

b = Bot()
b.login(username ="username", password ="pass", proxy = "http://login:password@ip:port")
