### ISSUE TITLE
Setting up help

### ISSUE THREAD

**Issue by watloejoegoan** [ohld/igbot#215]
Hi guys,
I've some troubles with setting this instabot up.
I've also running a other bot without troubles that is working good, however this one has some awesome feautures that i need. Could someone help me with setting it up on skype?

would be fantastic.

**Comment by rawrsefi** [comment]
whats up dude, what do you need help with ?

**Comment by zsvendo** [comment]
The whitelist.txt is not working anyone can have some idea:
I run the 4.unfollow option and then the 2. unfollow everyone option.

But it unfollow all does not respect the whitelist.txt

**Comment by ohld** [comment]
Try to update the bot.
