### ISSUE TITLE
Delays don't seem to be working

### ISSUE THREAD

**Issue by troudae** [ohld/igbot#222]
I'm setting the follow delay to 100 seconds in Bot, and using Ultimate to run it.
Everything loads fine but as soon as it starts following, the number followed just keeps increasing every second. Sometimes it will stop on a certain number for a couple seconds longer.

I'm manually checking my following count and it is following someone like every 50 seconds.
I've used this script before and ran fine (the number followed increased according to my delay limits)

Am I doing something wrong?

**Comment by onkaraman** [comment]
Can you show us how you set the bot up?

**Comment by MarkoRogers** [comment]
Same problem here

**Comment by yungsat** [comment]
Same problem here too. Bot is following very fast using ultimate. No matter how I change the delays still following fast.

**Comment by drfm** [comment]
I tried to setup the delay in the bot.py and settings.txt and/or multi_script_CLI.py. But it does't changed anything?!? For example if you start the infinity_hastags.py ... it works with the 10 s initial delay.
Maybe someone has an idea :-)

**Comment by drfm** [comment]
The solution from andretg79. Thanks. Maybe you are interested. For me it works :-)))
https://github.com/instagrambot/instabot/issues/246
