### ISSUE TITLE
Getting followers only up to ~55k

### ISSUE THREAD

**Issue by onkaraman** [ohld/igbot#223]
When I am pulling the followers of a user with more than a million followers, the `get_user_followers` method only returns about 5-6%.

This seems to be the issue on any big account I am trying to get all followers from.

Am I missing a way to get all followers (a million) or is there a different way?

**Comment by s0kil** [comment]
Instagram Private Mobile API uses pagination to load followers/following of a user, That might be the issue.

**Comment by onkaraman** [comment]
Yeah whatever it is, it is not working properly. I guess the constant requests for the rest of the followers is causing an error of some kind. Maybe a sleep per every 20k fetched followers might help in the method.

**Comment by ohld** [comment]
This can easily be done with another project by Instabotproject: https://github.com/instagrambot/instapro
But there is not enough documentation, but still some examples are provided

**Comment by onkaraman** [comment]
I could "fix" it for this repo. After I am done you could review and accept my pull request.

**Comment by ohld** [comment]
Yes! That would be great
