### ISSUE TITLE
comment_hashtag missing amount in definition

### ISSUE THREAD

**Issue by maverjk** [ohld/igbot#229]
Hello

Placing some test I discovered that is missing the amount field in the sign function:

instabot/bot/bot.py
315   def comment_hashtag(self, hashtag):
316	        return comment_hashtag(self, hashtag)

Instead in implementation function:

instabot/bot/bot_comment.py
46   def comment_hashtag(self, hashtag, amount=None):
47	    self.logger.info("Going to comment medias by %s hashtag" % hashtag)

**Comment by sudoguy** [comment]
Thanks, @maverjk!
