### ISSUE TITLE
run the bot in Android

### ISSUE THREAD

**Issue by morenitodelnorte** [ohld/igbot#230]
Hi @ohld 
do you have experience in running the bot in an Android device?
Would it be possible to install it in Android?
thank you

**Comment by simongomez95** [comment]
The simplest solution would be for you to build a web GUI for it with Flask or Django and then access it through your mobile browser.

**Comment by morenitodelnorte** [comment]
@simongomez95 but then it would be something like VPN connection to my computer just with a GUI, no?

**Comment by onkaraman** [comment]
No, then it would be just access to a website you set up. I may be wrong, but I feel like you are rather unexperienced in these matters. Do you have programming skills?

**Comment by morenitodelnorte** [comment]
@onkaraman  you are right. I have 0 experience :(

**Comment by onkaraman** [comment]
This is not just a program you can simply use. You need to have some programming skills in Python to build a program around this project. Sorry.
