### ISSUE TITLE
error: too few arguments When run python 

### ISSUE THREAD

**Issue by Tonners15** [ohld/igbot#232]
usage: follow_user_followers.py [-h] [-u U] [-p P] [-proxy PROXY]
                                users [users ...]
follow_user_followers.py: error: too few arguments

How does it run? anyone?

**Comment by dwshepard** [comment]
I'm having the same issue when running using Docker. Please help.

**Comment by dwshepard** [comment]
figured it out.

Add a USER ID as argument after follow_user_followers.py
e.g. python follow_user_followers.py 1085521155
Where "1085521155" is the USER ID you want to use.

Did that work?

**Comment by ohld** [comment]
Reopen if you still have not found the solution (don't forget to update the bot).

**Comment by Ranjeet20** [comment]
usage: instagram.py [-h] username wordlist threads
instagram.py: error: too few arguments
 
what this mean?
