### ISSUE TITLE
Out of blocks/likes/.... for today.

### ISSUE THREAD

**Issue by AlexBGoode** [ohld/igbot#237]
As for now it only logs an informative message in case of going beyond of defined limits and keeps trying until I stop it manually 

Maybe it could be reasonable to throw a custom exception as well in order to stop the current activity, which is out of limit, and allow outer module to catch that exception and control further processing

It is an enhancement request from my side

**Comment by ohld** [comment]
For this purpose there is another repository. Take a look into instapro. Is it mush smarter but have less documentation and example in case of lack of time. https://github.com/instagrambot/instapro
