### ISSUE TITLE
to many 429 error use filter-user

### ISSUE THREAD

**Issue by Nader-abdi** [ohld/igbot#239]
hi all
i use follow-user-follower & enabled userfillter
Why do I receive a lot 429 error???
![screenshot_20170616193433](https://user-images.githubusercontent.com/11696156/27232317-e44d488e-52ca-11e7-92f7-cbf0a6896e04.png)
The solution to this problem? This will speed down the script

**Comment by Nader-abdi** [comment]
palse help

**Comment by ohld** [comment]
Read the screenshot. Thats why you do this too fast for your account. Change the speed of liking

**Comment by Nader-abdi** [comment]
not slove this problam!? speed top
