### ISSUE TITLE
DEVELOPERS: Find account's limits 

### ISSUE THREAD

**Issue by ohld** [ohld/igbot#24]
I want to know the limits of 
* like per day
* unlike per day
* follow per day
* unfollow per day
* comment per day
* something else.

I don't know how Instagram limits the accounts (may be even not per day, but per hour, etc.). If you have some current information about limits, please share.

**Comment by rsxgti** [comment]
Best suggestion i would make would be to allow users to input there own amounts example_follow_users(amount="1000")

**Comment by ohld** [comment]
We need to provide our limits if user don't know exactly what he wants
