### ISSUE TITLE
Unable to retrieve user's follower over 7000

### ISSUE THREAD

**Issue by Roylamer** [ohld/igbot#241]
I try to use the function of "get_user_followers" to get the follower of another user.

I found that I can only get around 7000 followers of the user and then the function will stop.

I look into the source code and this problem is due to the variable temp['big-list'] return false.

Is there any way to fix it? It seems like that it happens after ig update

Thank you very much

**Comment by andretg79** [comment]
I have the same issue here. 

But my use case is a bit different. I only need the first 20 followers of a user and would like to follow them and then move onto the next user on my list and follow the first 20 of his / hers and so on...

Any help would be much appreciated.

**Comment by ohld** [comment]
I'm having the same issue with that. I think that this is the limitation of Instagram.

**Comment by tayfunyasar** [comment]
I'm using instapro for this situations.

Thanks to @ohld ^^

**Comment by ohld** [comment]
@tayfunyasar does instapro give you more than 7000? I can't get it...

**Comment by ohld** [comment]
Make pull request if you found the solution.
