### ISSUE TITLE
examples/like_your_last_media_likers.py does nothing but sleep

### ISSUE THREAD

**Issue by AlexBGoode** [ohld/igbot#242]
def like_media_likers(bot, media, nlikes=3):
    for user in tqdm(bot.get_media_likers(media), desc="Media likers"):
        **time.sleep(10 + 20 * random.random())**
    return True

def like_your_feed_likers(bot, nlikes=3):
    last_media = bot.get_your_medias()[0]
    return like_media_likers(bot, last_media, nlikes=3)

**Comment by sudoguy** [comment]
@AlexBGoode thanks for an issue! I fixed this bug [here](https://github.com/instagrambot/instabot/commit/30ad2604d69f6e6e3abf6af8c11e7760a4614f13).
