### ISSUE TITLE
MULTIPLE HASHTAGS

### ISSUE THREAD

**Issue by Tonners15** [ohld/igbot#243]
How do you like multiple hashtags? none of these seem to be working for me! hm

**Comment by ohld** [comment]
there is an example Like_hastags.py

**Comment by Tonners15** [comment]
I get that but when i do "python like_hashtags.py

It spits this out! I also where are the hashtags stored? 
usage: like_hashtags.py [-h] [-u U] [-p P] [-proxy PROXY]
                        hashtags [hashtags ...]
like_hashtags.py: error: too few arguments"

**Comment by Tonners15** [comment]
why you closed it?

**Comment by ohld** [comment]
Just read what did it write.
You should pass hashtags you want to like via command line arguments
