### ISSUE TITLE
max_unfollows_per_day setting not working

### ISSUE THREAD

**Issue by andretg79** [ohld/igbot#245]
No matter what I do, I cannot get the bot to unfollow 999 users. 

When running unfollow_everyone.py the bot stops unfollowing at 350 (DONE: Total unfollowed 350 users.)

When unfollow everyone from multi_script_CLI.py it stops at 100 users.

My bot.py file looks like this:

    def __init__(self,
                 whitelist=False,
                 blacklist=False,
                 comments_file=False,
                 max_likes_per_day=1000,
                 max_unlikes_per_day=1000,
                 max_follows_per_day=999,
                 max_unfollows_per_day=999,
                 max_comments_per_day=999,
                 max_blocks_per_day=999,
                 max_unblocks_per_day=999,
                 max_likes_to_like=999,
                 filter_users=True,
                 max_followers_to_follow=2000,
                 min_followers_to_follow=10,
                 max_following_to_follow=2000,
                 min_following_to_follow=10,
                 max_followers_to_following_ratio=10,
                 max_following_to_followers_ratio=2,
                 min_media_count_to_follow=3,
                 max_following_to_block=2000,
                 like_delay=10,
                 unlike_delay=10,
                 follow_delay=30,
                 unfollow_delay=30,
                 comment_delay=60,
                 block_delay=30,
                 unblock_delay=30,
                 stop_words=['shop', 'store', 'free']):
        super(self.__class__, self).__init__()

My setting.txt looks like this:

999
999
999
999
100
150
2000
250
5000
10
10
2
7
30
10
30
30
60
None

I don't know what I am doing wrong.

Please help.

**Comment by ohld** [comment]
No description provided.

**Comment by andretg79** [comment]
Sorry. Mistyped the description. Opened a new one with the correct title now.
