### ISSUE TITLE
Resetting dropped connection: i.instagram.com

### ISSUE THREAD

**Issue by AlexBGoode** [ohld/igbot#249]
That kind of messages just overspam log file with no purpose

Easy solution to get rid of them:

class API(object):

    def __init__(self):
        # add following two lines
        logging.getLogger("requests.packages.urllib3.connectionpool").setLevel(logging.WARNING)
        logging.getLogger("urllib3").setLevel(logging.WARNING)

**Comment by ohld** [comment]
Thanks, can you please make a pull request with that fix?

**Comment by ohld** [comment]
Thanks, can you please make a pull request with that fix?
