### ISSUE TITLE
DEVELOPERS: Implement language packs for comment system

### ISSUE THREAD

**Issue by ohld** [ohld/igbot#25]
Since I've implemented the way to comment medias, we need to have a database of comments to use.
As an example I've created a small set of emoji comments [here](https://github.com/ohld/instabot/blob/master/examples/comments_emojie.txt). Emoji is cool way to comment because it is international. 

But this base is not large enough. We should enlarge it. 

Also there is a way to create **comments_english.txt** database with english comments. Also another languages packs can be added.

**Comment by DrCherry** [comment]
Nothing wrong with a flat file at this point.  Maybe we should make it yaml or json and then validate it as we read it in.

**Comment by DrCherry** [comment]
I've implemented a fairly crude one-language comment system.  This could be enhanced, shall we turn this into an enhancement?
