### ISSUE TITLE
how to limit the number of hastags, followers, unfollowers it scans?

### ISSUE THREAD

**Issue by stanley747** [ohld/igbot#250]
how do i limit the number of hashtags it searches, right now it gets 81 media after search, i want to make it to 10

**Comment by julien-h2** [comment]
you get a list of medias, say it's called "medias",
if you want the first 10 elements, I guess you can just do this:

`first_medias = medias[:10]`

**Comment by drfm** [comment]
Thank's for your reply, julien-h.
But could you be so nice and give an example. Maybe how can I modify the infinity_hashtag_liker.py that it will work :-)

**Comment by BobZombiE69** [comment]
in ultimate_schedule\ultimate.py

def job4(): bot.follow_followers(get_random(random_user_file),200)  #only scan and follow 200 users

------------------------------------------------------------------------------------------------------------
in multi_script_cli.py

        elif ans == "2":
            print("""
            1.insert username
            2.use username database
            """)
            if "1" in sys.stdin.readline():
                user_id = input("who?\n").strip()
            else:
                user_id = random.choice(bot.read_list_from_file(users_file))
            bot.follow_followers(user_id,100)  #add nfollows ,100 only scan and follow 100 users
            menu_follow()
