### ISSUE TITLE
get_likers stops at 999

### ISSUE THREAD

**Issue by Thicool** [ohld/igbot#255]
Hello there, great work!
I have problems getting data:
get_media_likers only gets me around 999 User IDs and then stops
get_media_commenters only gets me around 20 User IDs and then stops

any idea? I know that crawling thousands of IDs might cause 404 at some point...

Cheers
T

**Comment by mwargan** [comment]
Hi @Thicool!

Crawling, or rather liking, more than 1k per day is likely to get you banned, which would return a 400 error. The bot is performing as expected.
