### ISSUE TITLE
Setting a proxy returns error in Ultimate Schedule

### ISSUE THREAD

**Issue by mwargan** [ohld/igbot#262]
Hello! I'm trying to set a proxy in the Ultimate Schedule example, but I get the following error:
```
Traceback (most recent call last):
  File "ultimate.py", line 15, in <module>
    bot = Bot(proxy="138.204.145.39",comments_file="comments.txt")
TypeError: __init__() got an unexpected keyword argument 'proxy'
```
I've modified this one line in the ultimate.py file from the original to:
`bot = Bot(proxy="138.204.145.39",comments_file="comments.txt")`
I've tried both uppercase and lowercase "proxy" word - both return similar error.

Appending a port number (:3128) also returns the same error.

I'm using the master branch, but the other branches return the same error.

What did I mess up :P?

**Comment by sudoguy** [comment]
Hello! It's a mistake in README.md. Argument "proxy" need put in bot.login(). 
```bot.login(proxy="138.204.145.39:3128")```

**Comment by mwargan** [comment]
Cool - spasibo!
