### ISSUE TITLE
problem with infinity_hashtags_follower.py

### ISSUE THREAD

**Issue by damirqa** [ohld/igbot#266]
i get error
`File "infinity_hashtags_follower.py", line 33
    time.sleep(wait)
                   ^
TabError: inconsistent use of tabs and spaces in indentation`
How to fix it?

**Comment by Zharaskhan** [comment]
It means you have mixed up spaces and tabs in the indentation. You have to fix that to be consistent with either tabs or spaces.

**Comment by damirqa** [comment]
You want to tell the problem in the code?

**Comment by damirqa** [comment]
I do not know how much the strict language of the python, but I removed the space before `time.sleep(wait)` and earned! Thank you!
