### ISSUE TITLE
AttributeError: 'Bot' object has no attribute 'last_comment'

### ISSUE THREAD

**Issue by gnesher** [ohld/igbot#268]
I've been using the bot for a while now and recently pulled the latest updates from git.
After updating the code (I'm using the comment hashtag example) I tried to re-run the bot but I'm getting the following error: 
AttributeError: 'Bot' object has no attribute 'last_comment'

Please advise

**Comment by ohld** [comment]
Hmm, it looks like someone broke bot.py in full request. I reverted this commit. Try again please.
