### ISSUE TITLE
don't follow and like porn and kids

### ISSUE THREAD

**Issue by waque** [ohld/igbot#270]
Hey guys! 
Due to some hashtags that i use (ex: f4f l4l), sometimes i follow and like kids or porn. Is there any way do stop that for happing? 
For exemple, can i don't like videos? Can i just like photos?

**Comment by mwargan** [comment]
Hi @waque! Maybe you're looking for stop words? From the readme:
"A list of stop words: don't follow a user if they have any of these stop words in their description"

I did see somewhere else in the Issues that when this was implemented, it also looked at image captions, though another person to confirm this will be helpful...

**Comment by ohld** [comment]
Stopwords and safe hashtags are the solution to this problem.
