### ISSUE TITLE
Add support for `archive media` in API

### ISSUE THREAD

**Issue by julien-h2** [ohld/igbot#275]
Scrolling through the API, I notice that we have a function to delete a post, (`deleteMedia(self, mediaId)`). Instagram also offers the ability to archive a post, that is make it invisible for a limited or unlimited period of time.

**Archive** is very useful when one of your post has too many likes. You can archive it before boting and then unarchive it.

It is also very useful if you want to have some media to display only when you are boting a given set of hashtag... For instance, archive your nature media before boting against the `fashion` tag, and _vis versa_ (archive your fashion related posts when boting against the `nature` tag)

Anyone know how the support to archive a post and display archived posts can be implemented?

**Comment by sudoguy** [comment]
@julien-h From latest update, you can archive and unarchive medias. And get your archived medias. Now you can see [this example](https://github.com/instagrambot/instabot/blob/master/examples/unarchive_your_medias.py)
