### ISSUE TITLE
How to get list of users followed/unfollowed?

### ISSUE THREAD

**Issue by ershadjan** [ohld/igbot#278]
How can I get more detailed log to get name of users I followed on unfollowed!
I want to create a list of users I unfollow to blacklist them.

**Comment by ehthxC7x9D** [comment]
You would want to be maintaining a list yourself, either in a text file or a database of who you've followed/unfollowed. Once you own the data you can take action on the list.

**Comment by ershadjan** [comment]
Yes, that was my question. How can I create this list? Is there list of users followed stored or logged somewhere?

**Comment by ohld** [comment]
Reopen if you still have not found the solution.
