### ISSUE TITLE
like_hashtag() doesn't work like it used to.

### ISSUE THREAD

**Issue by DrCherry** [ohld/igbot#28]
I'd expect to be able to iterate through a list of hashtags like I could before the last pull:
```
hashtags_like = ['thing1','thing2']

for tag in hashtags_like:
 bot.like_hashtag(tag)

```

Perhaps we now need to populate get_hashtag_medias?

```
[root@drcherry examples]# python kd8qzz.py 
Login success!

Going to like medias by lolita hashtag
Traceback (most recent call last):
  File "kd8qzz.py", line 28, in <module>
    bot.like_hashtag(tag)
  File "/home/scherry/sandbox/instabot/instabot/bot/bot.py", line 170, in like_hashtag
    return like_hashtag(self, tag, amount)
  File "/home/scherry/sandbox/instabot/instabot/bot/bot_like_feed.py", line 23, in like_hashtag
    medias = bot.get_hashtag_medias(bot, hashtag)
AttributeError: 'Bot' object has no attribute 'get_hashtag_medias'
Bot stopped. Worked: 0:00:00.716074

```

**Comment by DrCherry** [comment]
Now I'm having trouble with data types in filter_not_liked().  It's as if the function gets a list instead of a proper object with keys.

**Comment by ohld** [comment]
#29 look at this conversation.
Your correction are great, but you should remove some printing.

**Comment by DrCherry** [comment]
I agree, that output has been removed.

**Comment by DrCherry** [comment]
I've fixed Issue 28.  I'll create a pull request.

**Comment by ohld** [comment]
I'm ready to merge pull request. But it writes that I can't do to: conflicts with master. To avoid this you should pull the original branch. Add your correction. And create another pull request.
