### ISSUE TITLE
Suggested: Remove microseconds so Excel can parse Date data as Date

### ISSUE THREAD

**Issue by mwargan** [ohld/igbot#280]
I've added an extra code bit to get_stats.py so that microseconds are removed and Excel can parse the date as a date when importing the tsv file as live data.

On line 39 I've changed it to:
`data_to_save["date"] = str(datetime.datetime.now().replace(microsecond=0))`

Hopefully this helps some!

**Comment by sudoguy** [comment]
@mwargan Great! Thanks! Added in repo -> https://github.com/instagrambot/instabot/commit/fca10fae79dc63d8be12a943b91496018f1604c6

**Comment by mwargan** [comment]
@sudoguy Strangely enough this isn't working as I expected, nor is any other suggestion from: https://stackoverflow.com/questions/7999935/python-datetime-to-string-without-microsecond-component

If you've got the time you think you could take a quick look?
