### ISSUE TITLE
my posts removed ?? 

### ISSUE THREAD

**Issue by fbocosta** [ohld/igbot#281]
I was testing instabot on my instagram and for some reason a lot of my posts have been removed ... how do I get them back? And what setting should I make so this does not happen again?

**Comment by analogshinobi** [comment]
First is, you might want to use a different account or create a new one to test it. I got banned for multiple logins and also all 3 images were all deleted. Make sure not to login multiple times in a row using the script if its not working. 

![19761456_809880272497029_1699360989562011648_n](https://user-images.githubusercontent.com/1365841/28220031-9671a056-68f0-11e7-8676-80d3ff1453ea.jpg)

If you can still login, it will show up eventually. Good luck!

**Comment by 1mahdimf** [comment]
my account is disabled. but not account on instabot.
my personal account disabled. i just use multi login in instagram app (personal account + instabot account)

**Comment by Nurlan199206** [comment]
how you got banned? you exceeded limits?

**Comment by ohld** [comment]
Reopen if you still have not found the solution (don't forget to update the bot).
