### ISSUE TITLE
Fix: Ultimate Schedule Comments

### ISSUE THREAD

**Issue by mwargan** [ohld/igbot#284]
Hey guys!

Looks like ultimate schedule isn't calling the job to comment.

Adding this in ultimate.py to the schedule should help (assuming you want comments), but it's untested:

`schedule.every(1).days.at("13:00").do(run_threaded, job5)   #comment`

And a question/fix, do we really need line 15:
`comments_file_name = "comments.txt"`
since "comments.txt" is already passed into the bot constructor, and looks to me like the variable "comments_file_name" isn't being called anywhere?

**Comment by ohld** [comment]
Thanks, can you please make a pull request with that fix?
