### ISSUE TITLE
follow_user_followers.py: error: the following arguments are required: users

### ISSUE THREAD

**Issue by usersm12** [ohld/igbot#285]
I am trying to run follow_user_followers.py but keep getting the following error.
`usage: follow_user_followers.py [-h] [-u U] [-p P] [-proxy PROXY]
                                users [users ...]
follow_user_followers.py: error: the following arguments are required: users`
Already checked previous issues. Did not figure out the solution. 
Please explain the solution in detail. (Explain it like I am 8)

**Comment by sudoguy** [comment]
@usersm12 Look at the same issue #191

**Comment by jerkcoder** [comment]
I use it as so `python follow_user_followers.py accname` where accname is the profile whose followers you want to follow. Try that if you haven't already.
