### ISSUE TITLE
Unfollow doesn't work

### ISSUE THREAD

**Issue by colellla** [ohld/igbot#287]
Hello,
I tried the script for a couple of weeks. Everything works fine besides the bot.unfollow() command. I am not sure but I think it worked some weeks ago. Now I recognized that when I typ to unfollow either the user_id oder the username. It does not unfollow. There is no error log. May it be possible that Instagram changed their api?

Thank you.

**Comment by sudoguy** [comment]
@colellla

**Comment by sudoguy** [comment]
@colellla 

Your issue report does not conform to the issue template that has been specified for this repo:
https://raw.githubusercontent.com/instagrambot/instabot/master/.github/ISSUE_TEMPLATE.MD

Please edit your issue to comply with the template requirement.

**Comment by ohld** [comment]
no template -> closed
