### ISSUE TITLE
bot.unfollow doesn't work anymore

### ISSUE THREAD

**Issue by colellla** [ohld/igbot#288]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

Code:

```python
# There is no error. It just doesnt make anything but says everything works fine

bot = Bot()
bot.unfollow(bot.user_id)
```

Error/Debug Log:

```python
There is no error. It just doesnt make anything but says everything works fine
```

---

### Describe your issue

Hello,
I tried the script for a couple of weeks. Everything works fine besides the bot.unfollow() command. I am not sure but I think it worked some weeks ago. Now I recognized that when I typ to unfollow either the user_id oder the username. It does not unfollow. There is no error log. May it be possible that Instagram changed their api?

Thank you.

**Comment by ohld** [comment]
@sudoguy

**Comment by hezide** [comment]
same here

**Comment by colellla** [comment]
@sudoguy do you know why? =) Thank you anyway

**Comment by simongomez95** [comment]
Are you trying to unfollow yourself or ???

**Comment by colellla** [comment]
I tried different things. I wrote a bot that follows people, write them into a text file and than unfollow the same people from the text file. It worked at the beginning. Than I recognized that the unfollow didn't work anymore. 
Then I tested just the bot.unfollow command without the whole code. With the user-id, the username and nothing happened. I tried different usernames and ids without success. Seems like Instagram may changed something in their api. I don't know. Does the unfollow function work for you? @simongomez95

**Comment by colellla** [comment]
I found the problem. It was due to the settings at the beginning:

filter_users=True (must be true) 

When changed to False it doesn't work. Thank you anyway. =)

**Comment by simongomez95** [comment]
Oh sorry, I was confused by your code example. 

Glad you could work it out! Have fun with the bot :)

**Comment by FunkyMonkeyCloud** [comment]
Thanks for the workaround @colellla I managed to get it working from my end.

Unfortunately for the purposes of my script I need filter_users = False so that I can follow private accounts. Is there a solution so that I can either:
- Follow private accounts with setting filter_users=True; or
- Unfollow users with setting filter_users=False

Any help is much appreciated :+1: @ohld @simongomez95

**Comment by popadiys** [comment]
for me the unfollow doesn't work either. I've checked the code and I found the reason - there is a  check_user() check on unfollow to see if it is inside the whitelist. however check_user() by default returns True. 
Please remove:

    if self.check_user(user_id):
        return True  # whitelisted user

from def unfollow(self, user_id) in bot_unfollow.py

**Comment by msarami** [comment]
hi
i use filter_users = False to follow business accounts and now bot.unfollow_everyone() doesn't work!!
how i can cancel private and business filter when filter_users is true?  
@ohld @simongomez95

**Comment by zayaerme** [comment]
@colellla i need help with unfollowing followed list. Can you help me on that ?

**Comment by bruvv** [comment]
Closing this since its a very old issue. If this is still an issue please open a new one.
