### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by snik123** [ohld/igbot#293]
## Please follow the guide below

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Python 3.6.2
Code:
"""
    instabot example
    Workflow:
        Follow user's following by username.
"""

import sys
import os
import time
import random
from tqdm import tqdm
import argparse

sys.path.append(os.path.join(sys.path[0], '../'))
from instabot import Bot

parser = argparse.ArgumentParser(add_help=True)
parser.add_argument('-u', type=str, help="#")
parser.add_argument('-p', type=str, help="#")
parser.add_argument('-proxy', type=str, help="proxy")
parser.add_argument('-users', type=str, nargs='+', help='#')
args = parser.parse_args()

bot = Bot()
bot.login(username=args.u, password=args.p,
          proxy=args.proxy)

for username in args.users:
    bot.follow_following('#') (<---- idk what to put here)

```python


Error/Debug Log:
Traceback (most recent call last):
  File "C:\Users\gebruiker\AppData\Local\Programs\Python\Python36\follow_user_following.py", line 28, in <module>
    for username in args.users:
TypeError: 'NoneType' object is not iterable

```

well it gives me this error, and im not sure what to put after bot.follow_following. Im sorry i'm a complete beginner at python.

**Comment by ohld** [comment]
in `bot.follow_following` you should put the user_id or username of a user which followings you want to follow

**Comment by snik123** [comment]
still isnt working :/

**Comment by snik123** [comment]
alright i got it to work, now my question is is how to add my own delay to it

**Comment by ohld** [comment]
There are a lot of arguments of `Bot` class, there are some of delays. You can take a loot at them at Readme.md file on the main repository page
