### ISSUE TITLE
Auto upload pics in ultimate_schedule no working

### ISSUE THREAD

**Issue by mravard** [ohld/igbot#294]
Hi
After start ultimate.py in " ultimate_schedule " folder,the bot show an error about yaml.

> Traceback (most recent call last):
>   File "ultimate.py", line 7, in <module>
>     import yaml             #->added to make
> ModuleNotFoundError: No module named 'yaml'

and you have to remove lines about upload pics ( job 8 )

another error is about " blacklist.txt "
this file is not in the folder and you have make it before start the bot

please fix this problems

**Comment by vits-swat** [comment]
Install PyYaml 

`sudo pip install pyyaml`

Then it will work.
