### ISSUE TITLE
не работает like single user

### ISSUE THREAD

**Issue by Nurlan199206** [ohld/igbot#296]
при запуске скрипта like_example.py не работают лайки для одного пользователя, для теста вставлял  ID случайного юзера

bot.like_user("352300017")

скрипт запускал так: python like_example.py

прогрессбар появляется на секунду и исчезает

как быть?

**Comment by ohld** [comment]
Для issues есть шаблон, который появляется, когда создаёшь issue. 
Следуйте шаблону. Язык английский
