### ISSUE TITLE
lost atribute

### ISSUE THREAD

**Issue by ghost** [ohld/igbot#301]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Python 2.7.12

Code:

```python
import sys
import os

sys.path.append(os.path.join(sys.path[0], '../'))
from instabot import Bot

bot = Bot()
bot.login()
medias = bot.get_total_user_medias(bot.user_id)
bot.download_photos(medias)

```

Error/Debug Log:

Traceback (most recent call last):
  File "examples/download_your_photos.py", line 17, in <module>
    medias = bot.get_total_user_medias(bot.user_id)
AttributeError: 'Bot' object has no attribute 'get_total_user_medias'

---

### Describe your issue

i've checked in all the data that 'get_total_user_medias' is exist, i tried to change it to 'get_user_medias' it worked, but there's another error 'Bot' object has no attribute 'download_photos'

**Comment by ohld** [comment]
Reopen if you still have not found the solution (don't forget to update the bot).
