### ISSUE TITLE
After unfollowing 350 ppl and changed max unfollow setting. It doesn't read latest settings

### ISSUE THREAD

**Issue by tayfunyasar** [ohld/igbot#304]
I think all clear in title.

* Opened bot with default settings
* Unfollowed everyone with (python examples/unfollow_everyone.py)
* Changed settings to 
"Max unfollows per day: 1000"
* Running script again (python examples/unfollow_everyone.py)
* Message is here;
2017-08-09 21:48:00,036 - INFO - Out of unfollows for today.
2017-08-09 21:48:10,037 - INFO - DONE: Total unfollowed 350 users.

**Comment by Walking111** [comment]
the same issue ... changed to 700 and still writing to me that limit is 350 ....

**Comment by DioLorenzo** [comment]
same issue i put 1500 limit and change delay, but limit is still 350 and normal delay.

**Comment by bruvv** [comment]
Closing this since its a very old issue. If this is still an issue please open a new one.
