### ISSUE TITLE
Limit Media Like Per User

### ISSUE THREAD

**Issue by thecube69** [ohld/igbot#306]
Hello guys,

I spent some time to check in "Issues" if I can find my solution but couldn't find anything.

Here is my problem:

When I launch the "multi_script_CLI", I choose "2. Like followers" and I choose a username database. Everything works well but the thing is that usually, for each users, the bot likes around 18 medias after filtration. What I want to do, is to limit the number of media like per users. Don't want to be 18 but less.

Thank you for your help

**Comment by killahmade** [comment]
I also have this problem

**Comment by FunkyMonkeyCloud** [comment]
On line 376 in "multi_script_CLI" you need to add "nlikes=2" if you only want to like 2 photo from the user.

So line 376 should read:

bot.like_followers(user_id, nlikes=2)

**Comment by thecube69** [comment]
Great! Thank you straylan for the answer, now it works perfectly 👍
