### ISSUE TITLE
At Follow followers mode max_follows_per_day and follow_delay doesn't work

### ISSUE THREAD

**Issue by volokonski** [ohld/igbot#312]
Hello, there is an issue:

The Follow followers feature works in its own mode (usually try to follow around 7000+ users in 3-5 seconds each).

Any digits in max_follows_per_day and follow_delay doesn't work at all. Not in bot.py, not in bot() area of all examples.

The server has all modules as in requirements.
The bot is installed in its folder and it is not about the issue with 2 folders of bot on server.

Does anyone had the same situation?
Thanks for asap answer.

**Comment by ohld** [comment]
Please update the bot and try again. Reopen if not solved.
