### ISSUE TITLE
Like your followers posts

### ISSUE THREAD

**Issue by bardascat** [ohld/igbot#316]
Hello,

What functionality do you use in order to like your own followers medias?
Currently I see only 1 option but it's not very optimum.

Get your entire list of followers and then for each follower use like_user functionality
Cons: this will take a lot of time and is not optimum, because  some of your own follower might not have new posts but you still get their feed.

Do you know a better approach?

**Comment by julien-h2** [comment]
Nah I think this is good enough, no need to optimize this... In any case, the delays inside the bot will take a greater time than retrieving and iterating through your follower list.
