### ISSUE TITLE
500 error at multi_script login

### ISSUE THREAD

**Issue by completelyAbsorbed** [ohld/igbot#317]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here: Python 2.7.13

Code: python multi_script_CLI.py

```python
# Example code that will produce the error reported
from instabot import Bot

bot = Bot()
followers = bot.get_user_followers(bot.user_id)
```

Error/Debug Log:
2017-08-26 14:13:02,410 - WARNING - Request return 500 error!
2017-08-26 14:13:02,410 - INFO - Login or password is incorrect.

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: integer division or modulo by zero
```

---

### Describe your issue

Explanation of your issue goes here. Please make sure the description is worded well enough to be understood with as much context and examples as possible.

I'm using the correct credentials, checked many times and was able to log in via browser with these credentials, but cannot log in the bot with them.

**Comment by ohld** [comment]
Does the issue appear now, after you update the bot? Reopen if yes.
If you found the solution please make the pull request.

**Comment by completelyAbsorbed** [comment]
I ended up using Lev Pasha's InstagramAPI instead
