### ISSUE TITLE
What is rank_token and ranked_content parameter

### ISSUE THREAD

**Issue by bardascat** [ohld/igbot#318]
Hello,
Let's have a look at the following function:

```
def getHashtagFeed(self, hashtagString, maxid=''):
        return self.SendRequest('feed/tag/' + hashtagString + '/?max_id=' + str(
            maxid) + '&rank_token=' + self.rank_token + '&ranked_content=true&')
```

I don't what is the purpose of the rank_token and the ranked_content  true, can somebody explain?
I tried searching for a hashtag using the web-browser and instagram returns the result split in 2 sections:
Top Posts, and Most recent.

Is somehow rank_token, and ranked_content parameters related to these 2 sections? 

Thanks,
Catalin

**Comment by barclaey** [comment]
Getting the top hashtag posts instead of (or in addition to) the most recent ones would be very nice. Is there any documentation on the "unofficial instagram" api? I'm willing to add it if I know how the API looks like...
