### ISSUE TITLE
Where are the general settings?

### ISSUE THREAD

**Issue by tbudd23** [ohld/igbot#32]
I am speaking in terms of liking/following/unfollowing/commenting on those that fall under specified #'s.  Thanks!

**Comment by DrCherry** [comment]
Currently they're found here: 
https://github.com/ohld/instabot/blob/master/instabot/bot/limits.py

```
MAX_LIKE_PER_DAY = 1000
MAX_FOLLOW_PER_DAY = 350
MAX_UNFOLLOW_PER_DAY = 350
MAX_COMMENT_PER_DAY = 100
MAX_LIKES_TO_LIKE = 80
```
