### ISSUE TITLE
the following arguments are required: users

### ISSUE THREAD

**Issue by morier** [ohld/igbot#321]
hi

i have this problen for any scipts work with users.
like example : like_users.py: error: the following arguments are required: users

how can i fix it?

**Comment by Killerherts** [comment]
this needs to be launched from command window. I use bats IE 
```like_users.py  -u "username" -p "password" user1 user2```

**Comment by morier** [comment]
like_users.py -u "mortezaer" -p "morison12390" user1 user2
Traceback (most recent call last):
  File "C:\Users\user\Desktop\bot4\instabot-master\examples\like_users.py", line 14, in <module>
    from instabot import Bot
  File "C:\Users\user\Desktop\bot4\instabot-master\examples\../instabot\__init__.py", line 1, in <module>
    from .api import API
  File "C:\Users\user\Desktop\bot4\instabot-master\examples\../instabot\api\__init__.py", line 1, in <module>
    from .api import API
  File "C:\Users\user\Desktop\bot4\instabot-master\examples\../instabot\api\api.py", line 11, in <module>
    from tqdm import tqdm
ImportError: No module named tqdm


this error will be show.i import tqdm
and i use python 3.6.2

**Comment by Killerherts** [comment]
Pip install -r requirements.txt

**Comment by palford7** [comment]
I'm running in the Python shell and I have the same issue. tqdm is installed with `sudo pip`, and I've also run `sudo pip install -r requirements` to double-check.
Dependancies are installed, but I get the same error above from @morier 

ImportError: No module named tqdm

**Comment by iransales** [comment]
me too

**Comment by ohld** [comment]
May be your pip and python was bonded to different python versions. Try to use e.g. pip2 and python2

**Comment by g0rx** [comment]
from .api import API
ImportError: No module named api
