### ISSUE TITLE
Repost?

### ISSUE THREAD

**Issue by pursuitdaily** [ohld/igbot#322]
Had a quick question, occasionally I use a third party app called "Repost" to copy another users photo/video, and repost it on my profile. Is there something I can do to try to make my own?

I am still learning Python, have used the Instagram bot, but wanted to see what I could really do. If you have any suggestions, let me know!

Thanks
Pursuit

**Comment by julien-h2** [comment]
Yes you can.
1) obtain media info using the bot, you'll get a json with some url
2) download the photo using the provided url, you need an external python library for this
     & copy caption if you want
3) use the bot to post the downloaded media

**Comment by maykbrito** [comment]
For dummies, how can I code? which external py lib?
I'll love to having this feature too!

tks all!!

*Mayk Brito*
+5567981743964
http://fb.com/maykbrito
http://mayk.brito.net.br

**Comment by sudoguy** [comment]
Actually we are have example
https://github.com/instagrambot/instabot/blob/master/examples/repost_photo.py

**Comment by pursuitdaily** [comment]
So how do we get this to work? I am having trouble, can you give me an example?

**Comment by pursuitdaily** [comment]
@maykbrito did you get it to work?
