### ISSUE TITLE
Limit media Coment per user

### ISSUE THREAD

**Issue by harisprananda** [ohld/igbot#325]
hello guys, 

I was try launch the "multi_script_CLI.py", and as I try the script everything works well, but the thing is usuallly, for each user, the bot coments around 18 medias after filtration. what I want to do is to limit the number of media coments per users. don't want to run usually at 18 but less.

bellow the image:
![git hub request](https://user-images.githubusercontent.com/31687590/30214296-0b6b2eb6-94d6-11e7-801c-91f3077abbb0.JPG)

Thank you for attention and your help

**Comment by abprince** [comment]
Even i am facing the same issue , is there any way to make script to just comment on recent or last post of user

**Comment by insightadam** [comment]
And when it does, only comment one time on that post instead of multiple times as I've encountered
Thanks for help.

Edit: please see my comment on https://github.com/instagrambot/instabot/issues/335 describing two bugs and one fix that may be related
