### ISSUE TITLE
DEVELOPERS: Follower queue experiment

### ISSUE THREAD

**Issue by DrCherry** [ohld/igbot#33]
Take a look at this branch:
https://github.com/DrCherry/instabot/commit/202f0253bc548d61f50d684e006dce17e22c6e15

I'm trying to start a queue for users_to_follow and I'm hoping to tackle the queue async and have the bot plow on to the next task, filling another like queue.

I've created the QueueFollow and have yet to write the worker.  Thoughts on this welcome.

**Comment by ohld** [comment]
The idea of adding queues to tasks is great. I will check this branch as soon as I can

**Comment by DrCherry** [comment]
I need to figure out how to start workers that'll just work a queue until it's empty and then wait.  What about two pieces of code?   Like one piece that runs all the time consuming queues and the other piece that fills the queues.

**Comment by ohld** [comment]
I've never worked with queues in python. If you know that it is a right way to implement it - do it.
But we should make bot easy runnable, may be add another script to run what the necessary scripts later.

**Comment by DrCherry** [comment]
Some links I've been looking at:

http://effbot.org/librarybook/queue.htm
https://pymotw.com/2/Queue/
https://docs.python.org/3/library/asyncio-dev.html

**Comment by DrCherry** [comment]
I've removed my fork and I'm re-evaluating how we should accomplish queues.

**Comment by ohld** [comment]
Reopen this with the new version
