### ISSUE TITLE
Question: Like "loop" is possible?

### ISSUE THREAD

**Issue by pedronader** [ohld/igbot#336]
Hello,

The program works fine in my computer, the best i've used for sure.
But i have a question

Is possible, or does it have an option (tried everything and hasnt found) that i can make a system that the bot can like in loops, x times on each hashtag? So it can be active 24/7.

For example:
Like Hashtag1 maximum 5 times.
Then like Hashtag2 maximum 5 times
Then like Hashtag3 maximum x times......
After it finishes, it restart the process.
Or even some way that it like the hashtags selected in a ramdom way.

I tried to use the Ultimate Schedule, but hasnt achieved some exactly as i Want.

I resume, i want something that i can run 24/7 to like in a random way (or kind of random) a list of multiple hashtags.

Thank you

**Comment by iransales** [comment]
Did you find any way to do this?

**Comment by sudoguy** [comment]
Write your own jobs in ultimate_schedule.

```python
def job1():
    likes_amount = 5
    hashtag_amount = 3
    for _ in range(hashtag_amount):
        bot.like_hashtag(get_random(random_hashtag_file), amount=likes_amount)
```
