### ISSUE TITLE
Filtration

### ISSUE THREAD

**Issue by JMnemonick** [ohld/igbot#34]
Filtering by number of followers and followed
For example: 
"followers_max = 1000
followers_min = 100"

**Comment by DrCherry** [comment]
It seems like these can be parameters we pass into functions from the examples.
Something like
```
bot.like_min_thresh = 10
bot.like_max_thresh = 40
```
This would tell the bot to only like media with between 10 and 40 likes.

We could use limits.* as a fallback for all of these in the object.  Then they could be over-ridden from examples.

**Comment by ohld** [comment]
added in 0.3.3.2
