### ISSUE TITLE
Night sleeping setting

### ISSUE THREAD

**Issue by luca-vix** [ohld/igbot#343]
### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

### Describe your issue

Hi, I'm new to python, so I apologize if my request may seem trivial or already applicable.
I want to make the script ultimate.py scheduled stops during the night, something like "sleeping from 23.30 to 06.30".
It's possible to do it? I think it can be a good thing for everyone.

Thank you very much

**Comment by Nader-abdi** [comment]
very nice plase check tish problme

**Comment by ProfAndreaPollini** [comment]
I think you can create a decorator that doesn't execute os sleep the function till it's the right time to execute it.
