### ISSUE TITLE
Error direct message

### ISSUE THREAD

**Issue by harisprananda** [ohld/igbot#347]
I getting error when I try to direct message using this template "message_users.py" , anyone can help me to solve the problem ?

> PS D:\Work\bussiness\instabot-master\examples> python message_users.py
  File "message_users.py", line 39
    print 'Messaging ' + row[0]
                     ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by peprog** [comment]
I think you are using python 3, in that you have to use parentheses  in calling print command, and you better use this format:
print ('Messaging  %s' % row[0])
