### ISSUE TITLE
unable to call new method from bot.py class.

### ISSUE THREAD

**Issue by yasirrose** [ohld/igbot#352]
First of all, i am very pleased with your efforts on this repository. 

I want to ask a question about an issue which i am facing while adding new function in bot.py class file.  I am new to python. I have add following new function at end of bot.py file. 
```
`from .bot_stats import get_user_stats_dict
class Bot(API):
         .......
         .......
        .......
        def get_user_stats_dict(self, username, path=""):
                return get_user_stats_dict(self, username, path=path)`
```

I have add the function in bot_stats file. Here is the code:
```
import os
import datetime

def get_user_stats_dict(self, username, path=""):
    if not username:
        username = self.username
    user_id = self.convert_to_user_id(username)
    infodict = self.get_user_info(user_id)
    if infodict:
        data_to_save = {
            "date": str(datetime.datetime.now().replace(microsecond=0)),
            "followers": int(infodict["follower_count"]),
            "following": int(infodict["following_count"]),
            "medias": int(infodict["media_count"]),
            "user_id": user_id
        }
        return data_to_save
    return False

```
I have create a new example file in examples folder and calling the function. J
```
    bot = Bot()
    bot.login(username='abc', password='abcpassword')
    resdict = bot.get_user_stats_dict('abc','')
```

It is not working for me. It is giving me following error: 
`AttributeError: 'Bot' object has no attribute 'get_user_stats_dict'`

Please let me know do i need to compile the file again some how?

**Comment by miranthajayatilake** [comment]
What was the solution for this?
Error - AttributeError: 'Bot' object has no attribute

Thanks.
