### ISSUE TITLE
Installation over pip have not some modules

### ISSUE THREAD

**Issue by andrezaycev** [ohld/igbot#356]
Tried use send_message method. 
Script show that this method is missing

I did installation over 
```pip3 install -U instabot```

Successfully installed instabot-0.3.3.21 (not sure about what number for last version)

if check directory we see:
```
/usr/local/lib/python3.6/site-packages/instabot/bot/
├── __init__.py
├── __pycache__
├── bot.py
├── bot_archive.py
├── bot_block.py
├── bot_checkpoint.py
├── bot_comment.py
├── bot_filter.py
├── bot_follow.py
├── bot_get.py
├── bot_like.py
├── bot_photo.py
├── bot_stats.py
├── bot_support.py
├── bot_unfollow.py
├── bot_unlike.py
├── bot_video.py
├── delay.py
└── limits.py
```

And have not bot_direct.py for example.

What are correct method for getting last version over pip?

**Comment by ohld** [comment]
We will soon upload the last version (from github) to pip. 
You can install the github version as said there: https://stackoverflow.com/questions/15268953/how-to-install-python-package-from-github

**Comment by andrezaycev** [comment]
FYI: method from stackoverflow use setup.py from your repo - it will download tarball with wrong version too. Now i can only manual import repo in project. Will wait your update
