### ISSUE TITLE
Feature to remove a comment

### ISSUE THREAD

**Issue by julien-h2** [ohld/igbot#357]
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Feature request (request for a new functionality)

### Feature request
Can we remove a comment? I'd like to keep the id of some posted comments and remove them afterward

**Comment by ohld** [comment]
If we find the API call that deletes the comment, we can make this feature.

**Comment by sudoguy** [comment]
Added method ```delete_comment(media_id, comment_id)```
https://github.com/instagrambot/instabot/commit/8f99021b1a63ac20acfa6f00c3ddb60e2521c5f3
