### ISSUE TITLE
error bot_fillter

### ISSUE THREAD

**Issue by Nader-abdi** [ohld/igbot#358]
def _filter_medias_not_commented(self, media_items):
    not_commented_medias = []
    for media in media_items:
        if media['comment_count'] > 0:
            my_comments = [comment for comment in media['comments'] if comment['user_id'] == self.user_id]
            if my_comments:
                continue
        not_commented_medias.append(media)
    return not_commented_medias

error not found key['comments']

**Comment by sudoguy** [comment]
Fixed in https://github.com/instagrambot/instabot/commit/27e39b1982a332426050be6f451d1a2c270245d8
