### ISSUE TITLE
follow back percentage

### ISSUE THREAD

**Issue by yasirrose** [ohld/igbot#359]
I need to find percentage of the users who have follow back me. 

For this purpose, i have saved the users in database(which i am following through bot). 

Now i need to know that how has follow or unfollow me in last day. Can any one have idea that how can i find this?

**Comment by ohld** [comment]
You can download all your followers. 
So the percentage will be:

```python
percentage = 1. * (set(followers) & set(users_in_database)) / len(users_in_database)
```

**Comment by yasirrose** [comment]
@ohld ... yes, i already using this formula. Sorry i haven't told you about it. But if a person has 732 k followers than it would be costly job to get followers and save into db every day. Is there is not any way to find the followers of last some days?

**Comment by ohld** [comment]
you can download just the last 100 users and calculate the ratio based in this data

**Comment by yasirrose** [comment]
@ohld .... thanks,
