### ISSUE TITLE
upload_photo error

### ISSUE THREAD

**Issue by heyton** [ohld/igbot#364]
Using this code in my upload_photo.py file
```
from instabot import Bot
bot = Bot()
bot.login()
path = "/Users/username/example.png"
text = "Hello!"
bot.upload_photo(path, text)
```

Got this error:

> Traceback (most recent call last):
>   File "upload_photo.py", line 12, in <module>
>     bot.upload_photo(path, text)
>   File "/usr/local/lib/python2.7/site-packages/instabot/bot/bot.py", line 351, in upload_photo
>     return upload_photo(self, photo, caption, upload_id)
>   File "/usr/local/lib/python2.7/site-packages/instabot/bot/bot_photo.py", line 9, in upload_photo
>     if super(self.__class__, self).uploadPhoto(photo, caption, upload_id):
>   File "/usr/local/lib/python2.7/site-packages/instabot/api/api.py", line 195, in uploadPhoto
>     return uploadPhoto(self, photo, caption, upload_id)
>   File "/usr/local/lib/python2.7/site-packages/instabot/api/api_photo.py", line 73, in uploadPhoto
>     m = MultipartEncoder(data, boundary=self.uuid)
>   File "/usr/local/lib/python2.7/site-packages/requests_toolbelt/multipart/encoder.py", line 119, in __init__
>     self._prepare_parts()
>   File "/usr/local/lib/python2.7/site-packages/requests_toolbelt/multipart/encoder.py", line 240, in _prepare_parts
>     self.parts = [Part.from_field(f, enc) for f in self._iter_fields()]
>   File "/usr/local/lib/python2.7/site-packages/requests_toolbelt/multipart/encoder.py", line 489, in from_field
>     return cls(headers, body)
>   File "/usr/local/lib/python2.7/site-packages/requests_toolbelt/multipart/encoder.py", line 482, in __init__
>     self.len = len(self.headers) + total_len(self.body)
> TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

**Comment by iamjagjeetubhi** [comment]
Please try this!
```

from instabot import Bot 
bot = Bot()
bot.login()
path = "xyz.jpg"
text = "Hello!"
bot.uploadPhoto(path, text)
```

**Comment by heyton** [comment]
@iamjagjeetubhi get error

> Traceback (most recent call last):
>   File "upload_photo.py", line 10, in <module>
>     bot.upload_photo(path, text)
>   File "/usr/local/lib/python2.7/site-packages/instabot/bot/bot.py", line 351, in upload_photo
>     return upload_photo(self, photo, caption, upload_id)
>   File "/usr/local/lib/python2.7/site-packages/instabot/bot/bot_photo.py", line 9, in upload_photo
>     if super(self.__class__, self).uploadPhoto(photo, caption, upload_id):
>   File "/usr/local/lib/python2.7/site-packages/instabot/api/api.py", line 195, in uploadPhoto
>     return uploadPhoto(self, photo, caption, upload_id)
>   File "/usr/local/lib/python2.7/site-packages/instabot/api/api_photo.py", line 73, in uploadPhoto
>     m = MultipartEncoder(data, boundary=self.uuid)
>   File "/usr/local/lib/python2.7/site-packages/requests_toolbelt/multipart/encoder.py", line 119, in __init__
>     self._prepare_parts()
>   File "/usr/local/lib/python2.7/site-packages/requests_toolbelt/multipart/encoder.py", line 240, in _prepare_parts
>     self.parts = [Part.from_field(f, enc) for f in self._iter_fields()]
>   File "/usr/local/lib/python2.7/site-packages/requests_toolbelt/multipart/encoder.py", line 489, in from_field
>     return cls(headers, body)
>   File "/usr/local/lib/python2.7/site-packages/requests_toolbelt/multipart/encoder.py", line 482, in __init__
>     self.len = len(self.headers) + total_len(self.body)
> TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

**Comment by jensw83** [comment]
I have the same problem.

**Comment by iamjagjeetubhi** [comment]
I fixed it by:
1: `$ pip uninstall instabot`
2: `$ pip install instabot==0.3.3.21`

**Comment by jensw83** [comment]
This solved the Problem.
There seems to be a commit with a bug

**Comment by sudoguy** [comment]
Fixed in https://github.com/instagrambot/instabot/commit/a84ea4a6d2f97c1b19ed515ea01342eb0f1a4bc5
