### ISSUE TITLE
bot.block not blocking

### ISSUE THREAD

**Issue by heyton** [ohld/igbot#366]
Trying to block users.
Using simple code:
`>>> bot.block('1390941222')`

In terminal get:
> True

User not blocked. May be I doing something wrong?

**Comment by ohld** [comment]
This function checks if this user is a bot. If yes - it blocks. If no - lefts

**Comment by heyton** [comment]
What should I do for blocking not bot?

**Comment by ohld** [comment]
```python
def block(bot, user_id):
    user_id = bot.convert_to_user_id(user_id)
    delay.block_delay(bot)
    if super(bot.__class__, bot).block(user_id):
        bot.total_blocked += 1
        return True
    return False
```

**Comment by marcelobocchi** [comment]
Não fui eu quem bloqueou
