### ISSUE TITLE
 No module named tqdm

### ISSUE THREAD

**Issue by iransales** [ohld/igbot#368]
Last login: Fri Oct 20 21:44:40 on ttys001
MBP-de-iran:~ iran$ cd '/Users/iran/Desktop/instabot-master/examples/' && '/usr/bin/pythonw'  '/Users/iran/Desktop/instabot-master/examples/like_hashtags.py'  && echo Exit status: $? && exit 1
Traceback (most recent call last):
  File "/Users/iran/Desktop/instabot-master/examples/like_hashtags.py", line 12, in <module>
    from tqdm import tqdm
ImportError: No module named tqdm

How do I solve this problem?

**Comment by heyton** [comment]
@iransales try it

> pip install tqdm

**Comment by jakubvos** [comment]
I'm also having this issue

pip install tqdm doesn't help (says already satisfied..)

**Comment by partTime-NeRD** [comment]
Same here
