### ISSUE TITLE
No module named requests - infinity feedlike

### ISSUE THREAD

**Issue by iransales** [ohld/igbot#369]
**when I try to run "infinity_feedlike" this error happens**

Last login: Sun Oct 22 20:28:10 on ttys001
MBP-de-iran:~ iran$ cd '/Users/iran/Desktop/instabot-master/examples/' && '/usr/bin/pythonw' -S  '/Users/iran/Desktop/instabot-master/examples/infinity_feedlike.py'  && echo Exit status: $? && exit 1
Traceback (most recent call last):
  File "/Users/iran/Desktop/instabot-master/examples/infinity_feedlike.py", line 14, in <module>
    from instabot import Bot
  File "/Users/iran/Desktop/instabot-master/examples/../instabot/__init__.py", line 1, in <module>
    from .api import API
  File "/Users/iran/Desktop/instabot-master/examples/../instabot/api/__init__.py", line 1, in <module>
    from .api import API
  File "/Users/iran/Desktop/instabot-master/examples/../instabot/api/api.py", line 1, in <module>
    import requests
ImportError: No module named requests
MBP-de-iran:examples iran$

**Comment by ohld** [comment]
have you tried `pip install -U instabot` or `sudo pip install -U instabot`?

**Comment by iransales** [comment]
Yes! I was already running, but when the macbook unloaded, and I tried to run again, gave this error

**Comment by iransales** [comment]
Can someone help me? PLEASE

**Comment by ohld** [comment]
All questions can be asked in Google. 
Just read the error that terminal gives you. It said:

> ImportError: No module named requests

That means that you should install `requests` module. 
So you should google: 
``` 
how to install python module
```

or 

```
python install requests module
```

It will answer you to type in terminal:
```
pip install requests
```
