### ISSUE TITLE
Instant with QPython (on Android devices)

### ISSUE THREAD

**Issue by KRgh** [ohld/igbot#370]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [X] Updated to the latest version
- [X] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [X] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

---

### Describe your issue

I'm trying to run "multi_script-CLI.py" on QPython (in an Android Device), but I have problems to install the requirements with QPython.
So my question is "Is it possibile run the bot on QPython (in an Android Device)?".

Thanks in advance

**Comment by stanleyhafeld** [comment]
You can run it with termux application you can find here: https://termux.com/
