### ISSUE TITLE
bot.searchUsers() just return True not the result

### ISSUE THREAD

**Issue by peprog** [ohld/igbot#376]
Python 2.7.10
Code:

```python
# Example code that will produce the error reported
from instabot import Bot

bot = Bot()
bot.login(username="my_username", password="my_password")
users = bot.searchUsers(query="game")
print "=====%s" % users
```

Error/Debug Log:

```python
2017-10-26 01:23:48,153 - INFO - Login success as my_username!
===== True
```

---
It always return True no matter what I search, I have tried with several different usernames and even python 3.6 but still the same issue, any idea why is that?

**Comment by sudoguy** [comment]
Added method for searching users by username https://github.com/instagrambot/instabot/commit/5318a7efdfaed17aa769c9fcd4832b5b73307f94
