### ISSUE TITLE
Multiple image upload

### ISSUE THREAD

**Issue by PromptlyDev** [ohld/igbot#377]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [X ] Updated to the latest version
- [X ] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [X ] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [X ] Feature request (request for a new functionality)
- [X ] Question
- [ ] Other

---

How is it possible to upload multiple images in one post? I've just found a function to upload one image in one post. 

Multiple images in one instagram post (swiping).

**Comment by PromptlyDev** [comment]
Maybe @ohld can you provide some information?

**Comment by kintaro1981** [comment]
I'm interested in this too. Is It already possible?

**Comment by KhaitovR** [comment]
Please help and suggest a solution to this problem :)

**Comment by wangbin-ouhin** [comment]
Does someone found the solution?

**Comment by bruvv** [comment]
Closing this since its a very old issue. If this is still an issue please open a new one.
