### ISSUE TITLE
Running Multiple Instances of bot() in a Threaded Application. 

### ISSUE THREAD

**Issue by furnacemfg** [ohld/igbot#388]
### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

### Describe your issue

Working on an application that will instantiate *n* number of instances of bot() in a single directory with multiple IG account credentials. 

However, I'm concerned that it will run into issues since the followed.txt, skipped.txt, and unfollow.txt don't contain a prefix to distinguish them from one account to another. For example in follow_users() you have: 

```
    followed_list = self.read_list_from_file(
        "followed.txt")   # Read followed.txt file
    skipped_list = self.read_list_from_file(
        "skipped.txt")  # Read skipped.txt file
```

**Questions:** 

- Am I correct that this will be an issue? 

- Is there an easy solution if this is an issue or do I need to do some work by extending the codebase with my own methods?

**Comment by BobZombiE69** [comment]
yes , you will have problem.
you have to run each instance from different directory.

**Comment by furnacemfg** [comment]
Thanks @BobZombiE69. I've been digging through the code and have come to this conclusion. I've been working on overriding the Bot class methods to support something like this.
