### ISSUE TITLE
send massage problem

### ISSUE THREAD

**Issue by morier** [ohld/igbot#393]
Traceback (most recent call last):
  File "C:\Users\user\Desktop\instabot-master (5)\instabot-master\examples\message_users.py", line 44, in <module>
    bot.send_message(directMessage, instaUsers)
AttributeError: 'Bot' object has no attribute 'send_message'

**Comment by morier** [comment]
I find the answer.should install instabot pip.

**Comment by morier** [comment]
And use python27

**Comment by onkaraman** [comment]
This functionality is only available for Python 2?

**Comment by morier** [comment]
I think so.it's not work on 3.
