### ISSUE TITLE
Question about purpose of code in bot_follow

### ISSUE THREAD

**Issue by pxtyr** [ohld/igbot#394]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- Question

### Describe your issue

I am working to make a small change to unfollow_non_followers to only unfollow those user which the only the bot has followed (as opposed to users that human has followed via instagram app, for example)

In the code below, I am wondering what is the purpose of calling the `followed.txt` here when it is also calling the followings from instagram directly via `get_user_following` 

`...
followed_file = "followed.txt"
followed_list = self.read_list_from_file(followed_file)
unfollow_list = []
unfollow_list += [x for x in followed_list if x in nonfollowerslist]
unfollow_list += [x for x in nonfollowerslist if x not in followed_list]
unfollow_file = self.read_list_from_file("unfollow.txt")
new_unfollow_list = []
new_unfollow_list += [x for x in unfollow_file if x in unfollow_list]
new_unfollow_list += [x for x in unfollow_list if x not in unfollow_file]
...`

Please let me know if I can offer any more detail. 
Thanks

**Comment by BobZombiE69** [comment]
I wrote this line.
the reason for this code is , to add new non-followers , to the "END" of unfollow_file , 
so this way , we keep track of non-followers by "ORDER" , so older non-followers will be unfollow first
