### ISSUE TITLE
DEVELOPERS: Group bot's method for better structure. 

### ISSUE THREAD

**Issue by ohld** [ohld/igbot#40]
Today structure of bot's class is not searchable and sometimes not readable. https://github.com/ohld/instabot/tree/master/instabot/bot

So i'm thinking about to regroup the methods even with renaming methods and files if necessary. It will help to write a clear documentation, not _just a one big list of all methods_ like we have now at Readme.md.

I suggest this groups:

- user getters (users from media likes, from hashtag posters, from user's followers, etc.)
- media getters (by hashtag, by user, by geotag, etc.)
- like methods (medias, user's medias, by hashtag, geotag, etc.)
- follow methods (users, users from hashtag, users from geotag, etc.)
- something that i forget
- something more

After we did that restructure task we can provide the bot with more clearer documentation and even create an **GitHub Pages** site to increase the bot's community. 

If you want to help with that issue please first comment there 
 - the file name with methods you suggest and
 - the list of methods that would be there

After we agreed with that renaming and moving you can do a pull request with the corrections.

**Comment by DrCherry** [comment]
I need to let this sink in a little more to see if it makes sense regarding how I want to use this.

**Comment by ohld** [comment]
Now I don't want to rename the methods, but just regroup them in source files.

**Comment by ohld** [comment]
I suggest these groups (files):
### `bot_like.py`
Actions to like something/someone
- like
- like_media(s)
- like_user(s)

### `bot_follow.py`
Actions to follow
- follow
- follow_users

### `bot_get.py`
Getters of medias or users
- get medias by hashtag
- get users by hashtag
- get media likers

### `bot_info.py`
Information getters for analysis
- get_user_info
- get_media_info
- get_hashtag_info (can be implemented for future analysis)
- get_geotag_info (can be implemented for future analysis)

**Comment by DrCherry** [comment]
Nice work @ohld !! Cheers!
