### ISSUE TITLE
Auth for private proxy

### ISSUE THREAD

**Issue by njhughes-01** [ohld/igbot#404]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [ X] Updated to the latest version
- [ X] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x ] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ X] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---
---

### Describe your issue
I see in the docs how to add a proxy.  But how do we pass a username and password for private proxies?
Login(proxy="user.pass.XXX.XX.XX.XX:8080" this doesnt seem to work

Explanation of your issue goes here. Please make sure the description is worded well enough to be understood with as much context and examples as possible.

**Comment by thejae** [comment]
have you tried the good old `user:pass@ip:port` method?

**Comment by njhughes-01** [comment]
We should add this information to the readme I was going ip:user:pass documents would be nice

**Comment by valentino-sm** [comment]
Hello!
Seems like `user:pass@ip:port` doesn't work.
`WARNING - Not supported proxy scheme **<user_login>**` error
Everything works if I fix api.set_proxy() method like this:
```
if self.proxy:
    proxies = {'http': 'http://'+self.proxy, 'https': 'https://'+self.proxy}
    self.session.proxies.update(proxies)
```

**Comment by bodrych** [comment]
use `http://user:pass@ip:port`
