### ISSUE TITLE
Request : Combine Follow + Like on same @user

### ISSUE THREAD

**Issue by jslm** [ohld/igbot#409]
Hi,

Is this possible to build a mode like:

infinity_hashtags_follower to follow AND like (1,2, 3 medias) of the same user, and then do the same for the next user .. ?

Thanks!

**Comment by sgxgsx** [comment]
i've made that, but now trying to combine follow + like in range (0,10) and + comment in range(0, 10)

**Comment by anrisovich** [comment]
Cool, where can we see the code?

**Comment by sgxgsx** [comment]
it is very raw. I hope to finish smth in 2 days.(don't have much time)

**Comment by jslm** [comment]
Would be great to share!

**Comment by jslm** [comment]
Anything up?
