### ISSUE TITLE
Selected Medias Limit Setting

### ISSUE THREAD

**Issue by dalostboy4** [ohld/igbot#416]
Can anyone point me to where the setting is to adjust the limit of medias selected per hashtag? The situation is I'm trying to like quite a few different hashtags, but I'll never reach the tail end of my list before I hit my daily limit. The default looks like it's about 80 medias selected. I'd like to lower that. Where can I find this setting? I'm using multi_script_CLI.py

**Comment by miranthajayatilake** [comment]
If you're using multi_script_CLI.py I believe you can increase the day limit in the beginning.

To reduce the likes per hashtag you can edit the below code in the file

`     else:
                hashtags.append(random.choice(bot.read_list_from_file(hashtag_file)))
            for hashtag in hashtags:
                bot.like_hashtag(hashtag)`

change `bot.like_hashtag(hashtag)` to `bot.like_hashtag(hashtag, amount=10)`
This should work to like only 10 pic from a hashtag.
