### ISSUE TITLE
how can run for several account in one time

### ISSUE THREAD

**Issue by kenshimokak** [ohld/igbot#423]
how can run for example like_example.py for several account ?

also 

how can run multi actions : for example doing 

`

   bot = Bot()
   bot.login(username, password)
   bot.unfollow_everyone()

`
thnaks

**Comment by miranthajayatilake** [comment]
To run on several accounts at once you can open several command prompt windows (I have tried on windows) and run two scripts separately. It should work.

Multi actions are possible. As I understand the actions will be performed serially. Which means after the first action is finished the second will start.
