### ISSUE TITLE
Ideas: Welcome message, unfollow last X following

### ISSUE THREAD

**Issue by stinsonmktg** [ohld/igbot#427]
Anyone know how we could implent an automatic welcome message? For example:

Check every X minutes for new followers, if new followers; send welcome message (from txt file)

Another thing I came across by mistake is to unfollow the last X following. I overwritted my white list with new unwanted following and since the list is created by userID I couldnt tell who really was my friends. So if you know you added 100 following then this function could be a lot of handy,

**Comment by Cwaldmann** [comment]
i wrote a script which is run once a day and it checks out all new followers and sends them a welcome message, dm me

**Comment by heyton** [comment]
@Cwaldmann can you give the code?

**Comment by Cwaldmann** [comment]
@heyton  sure can i send u a mail ?

**Comment by ohld** [comment]
@Cwaldmann You can share the code snippet here in comments

**Comment by Cwaldmann** [comment]
@ohld its not just one code snippet its in bot_direct and some other files

**Comment by gbergna2009** [comment]
@Cwaldmann Hi! Can we talk about it? If you sell this script I want to buy it. Please reply me in private.

**Comment by iransales** [comment]
PLEASE Share!!!!

**Comment by sudoguy** [comment]
I did write some script in examples. Welcome
https://github.com/instagrambot/instabot/blob/master/examples/welcome_message.py
