### ISSUE TITLE
500 and 404 error while follow

### ISSUE THREAD

**Issue by AfshinZlfgh** [ohld/igbot#428]
some times when i follow users from list i get 500 (just one time occured) and 404 (many time) error, i think 404 occures when target user account deactived or not exist, in this cases error number loged on the screen and program ends but i think the program must not do like that, maybe its better it returns error number and let bot user deside to handle it by own code or in case of 404 error it can go to follow next user from list, not ends the program!

**Comment by AfshinZlfgh** [comment]
i write a handler for this issue by myself and solve it, if ones teach me correct way of making pull requst i will do it (its my first time)
  <a href="http://uploads.im/dNrCb.png"><img src="http://sk.uploads.im/t/dNrCb.png" border="0" /></a>

**Comment by romankk** [comment]
@AfshinZlfgh 
Can you share your code for error handling here. 
I agree with you that on error bot should continue and not stop working.

**Comment by AfshinZlfgh** [comment]
@romankk i added the code in my fork and make pull request to this repo you can clone it from my repo or wait for merging my code with this repo
