### ISSUE TITLE
want to fetch only first media of user

### ISSUE THREAD

**Issue by amitchoudhary13** [ohld/igbot#429]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other
i have user list stored in userlist.txt
which then is used to fetch the user media (upto 12-18)
and then filter and all
i was trying to get user first media 
where i used place temp = media_items[0]
and also tried to replace media_items[0] in every function but it didnt workout
i a newbie to json and python
and i am not getting the this what does 
self.LastJson("items") return
---

Paste the output of ``python -V`` here:
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)] on win32
Code:

```python
# Example code that will produce the error reported
def filter_medias(self, media_items, filtration=True, quiet=False, is_comment=False):
    if filtration:
        temp = media_item[0]
        media_item = temp
        if not quiet:
            self.logger.info("Received %d medias." % len(media_items))
        if not is_comment:
            media_items = _filter_medias_not_liked(media_items)
            if self.max_likes_to_like:
                media_items = _filter_medias_nlikes(
                    media_items, self.max_likes_to_like)
        else:
            media_items = _filter_medias_not_commented(self, media_items)
        if not quiet:
            self.logger.info("After filtration %d medias left." %
                             len(media_items))
    return _get_media_ids(media_items)
```

Error/Debug Log:

```python
2018-01-02 21:11:49,070 - INFO - Received 12 medias.
2018-01-02 21:11:49,074 - INFO - After filtration 0 medias left.
2018-01-02 21:11:49,078 - INFO - Going to comment 0 medias.
0it [00:00, ?it/s]
2018-01-02 21:11:49,118 - INFO - DONE: Total commented on 0 medias.
2018-01-02 21:11:52,965 - INFO - Received 18 medias.
2018-01-02 21:11:52,972 - INFO - After filtration 4 medias left.
2018-01-02 21:11:52,980 - INFO - Going to comment 4 medias.
  0%|                                                    | 0/4 [00:00<?, ?it/s]2
018-01-02 21:11:54,385 - INFO - Commented with text: wow
 25%|###########                                 | 1/4 [00:20<01:02, 20.84s/it]2
018-01-02 21:12:15,678 - INFO - Commented with text: wow
 50%|######################                      | 2/4 [00:35<00:37, 18.99s/it]2
018-01-02 21:12:30,745 - INFO - Commented with text: haha
```

---

### Describe your issue
as you can see that after filter 
it fetch 4 medias
but what i want it should return only the latest or first media in items ( only one media per user)
so can any one tell me how to alter the media or get_media_id or filter function to get the it done

**Comment by njhughes-01** [comment]
use the del function to shorth the list
```del list[1:]```

**Comment by sudoguy** [comment]
@amitchoudhary13 Hello,
You can change received a list of media by deleting as said by Kiilerherts above.
Or you can add to end of function [1:].
Example:
```python
bot.get_user_medias("some_user")[1:]
```

**Comment by MrMdR** [comment]
@sudoguy , @Killerherts 

How would you implement this in a code like below (from like_and_follow_last_uers_media_likers.py)

`for username in users:
    medias = bot.get_user_medias(username, filtration=False)
    if len(medias):
        likers = bot.get_media_likers(medias[0])
        for liker in tqdm(likers):
            bot.like_user(liker, amount=2)
            bot.follow(liker)
`

` likers = bot.get_media_likers(medias[1:])` and ` likers = bot.get_media_likers(medias[0])[1:]` both gives an error.

**Comment by sudoguy** [comment]
@MrMdR 
```python
likers = bot.get_media_likers(medias[0])

likers = likers[0] if likers or []
```
