### ISSUE TITLE
Set cycle of running bot function

### ISSUE THREAD

**Issue by stanleyhafeld** [ohld/igbot#430]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [X] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

Code:

Error/Debug Log:

---

### Describe your issue

I'd like to have a feature to set a cycle of how many times a bot need to run.

Example: you want to run or call "bot.like_hashtag" and want to run this 5 times in a row.

This would be very handy to customize your own script and keep it all clean.
Is something like this possible?

**Comment by ohld** [comment]
You can write a simple python cycle:
```python
for i in range(ITERATION_AMOUNT):
    bot.like_hashtag("your_hashtag")
```
