### ISSUE TITLE
run 11 account on machine and get error feedback_required??how many account can run in one machine?

### ISSUE THREAD

**Issue by ArashSiar** [ohld/igbot#436]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue
i run the script on Win2008 and python 3.x
i run 10 account for follow users in my computer and when add 1 more account get erroe(challenge_... b) and other account error (feedback_requ...) ... how many account can run in one machine ?

**Comment by ordekalo** [comment]
Please reset your IP address and everything should work fine.

**Comment by cachebust** [comment]
Do we have any limitation on the number of account we can use per IP ? If yes, what is the threshold ?
