### ISSUE TITLE
The bot also likes my own fotos

### ISSUE THREAD

**Issue by mpuff** [ohld/igbot#442]
Hello,

the bot also likes my own fotos with the hashtages i have written in the like_hashtag.txt
how can i solve this?
 
thanks

**Comment by ivadenis** [comment]
add yourself to blacklist.txt

**Comment by sudoguy** [comment]
@mpuff Don't worry, I'll fix this.

**Comment by ordekalo** [comment]
Just Auto add yourself to black list

**Comment by mpuff** [comment]
Thank you
