### ISSUE TITLE
 ImportError: No module named api

### ISSUE THREAD

**Issue by srbalook** [ohld/igbot#444]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [ ] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

Error/Debug Log:

```orangepizero:~/instabot/examples$ python multi_script_CLI.py
Traceback (most recent call last):
  File "multi_script_CLI.py", line 10, in <module>
    from instabot import Bot
  File "/home/alexa/.local/lib/python2.7/site-packages/instabot/__init__.py", line 1, in <module>
    from .api import API
ImportError: No module named api

```

---

### Describe your issue

I followed tutorial but i get this error?

ImportError: No module named api

**Comment by sudoguy** [comment]
Try this command
```git clone https://github.com/instagrambot/instabot.git --recursive```

**Comment by FlamePZ** [comment]
I need help with this. I have the same error
