### ISSUE TITLE
INSTAGRAM API DEPRECATED BY JUNE 2018

### ISSUE THREAD

**Issue by levensworth** [ohld/igbot#445]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [ ] Updated to the latest version
- [ ] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [ ] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

---

### Describe your issue

I recently  read that instagram will start deprecating it's current API to move into a more business related one called instagram graph API. Does this affect in nay way the repository ? or is it based on the instagram.com end points?
ps: they'll start to deprecate the API in June 2018

**Comment by johanfuen9** [comment]
https://developers.facebook.com/blog/post/2018/01/30/instagram-graph-api-updates/

**Comment by levensworth** [comment]
thank you for the update

**Comment by melihevren** [comment]
What i understand is this repo will be useless after june 18, correct?

**Comment by hi-im-root** [comment]
can someone confirm this? will the current repo be useless after the 18? since they are removing relationships from the api on the june 18

**Comment by sudoguy** [comment]
Instabot doesn't use Instagram Graph API. Bot work only with private Instagram API. Repo will not be useless after 18 June.
