### ISSUE TITLE
unfollow only bots followed list ?

### ISSUE THREAD

**Issue by zayaerme** [ohld/igbot#446]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

Code:

```python
# Example code that will produce the error reported
from instabot import Bot

bot = Bot()
bot.login(username="user", password="pass")
followers = bot.get_user_followers(bot.user_id)
```

Error/Debug Log:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: integer division or modulo by zero
```

---

### Describe your issue

I want to make bot unfollow only who it followed and make my own list safe. I had issues with some "examples". I can just use multiscript since it sets up itself. How can I set its unfollow mode to ignore my own follows ?
Thanks

**Comment by zayaerme** [comment]
I want to make bot unfollow only who it followed and make my own list safe. I had issues with some "examples". I can just use multiscript since it sets up itself. How can I set its unfollow mode to ignore my own follows ?
Thanks

**Comment by levensworth** [comment]
you can use the followed.txt file. Unfollow all the users in that list and you'll be fine

**Comment by alatraxx** [comment]
@santiagobassani96 I would like to do what you said on my schedule_ultimate but I don't know how.
Can you help me please?

**Comment by levensworth** [comment]
@alatraxx  sure ,no problem!
the followed.txt file contains all the successful user_id that the bot followed. if you just need to make a function to read the file, create a set with that and just call bot.unfollow aver every user_id in that set. 
it will make a lot of requests and it's not the best way but at least it'll work.
If you want to discuss anything else, just email me at santiagobassani96@gmail.com

**Comment by adenisot** [comment]
@santiagobassani96 Hi guys, so do you have an idea of what is the best way ? For my side, I just want to unfollow people followed by the script. But I don't want that the script try to unfollow an account already successfully unfollowed...maybe put a condition who check in another file the successful_account_unfollowed.
