### ISSUE TITLE
Implement proxy

### ISSUE THREAD

**Issue by ohld** [ohld/igbot#45]
We need to implement proxy support because instagram ban sessions from "strange countries".

**Comment by maxkrivich** [comment]
I'm find link some with service who provide free proxies, but they not guaranteed stable connection.

**Comment by ohld** [comment]
Leave a link, please. Can we set there a country?

**Comment by maxkrivich** [comment]
@ohld  `http://proxy.tekbreak.com/{numberOfProxies}/json`

**Comment by ohld** [comment]
Done in 0.3.3.4
