### ISSUE TITLE
No module named api

### ISSUE THREAD

**Issue by Milkywayrules** [ohld/igbot#457]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [X ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [X ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

Code:

```python
from .api import API
```

Error/Debug Log:

```python
Traceback (most recent call last):
  File "like_users.py", line 13, in <module>
    from instabot import Bot
  File "C:\users\dio\documents\koding\python\instabot-master\examples\../instabot\__init__.py", line 1, in <module>
    from .api import API
ImportError: No module named api
```

---

### Describe your issue

I have follow all the instructions, but still this error showed up. requirements.txt also installed.
I am using python 2.7 and windows 10.
Any solution for this?

**Comment by hi-im-root** [comment]
use pip install instabot
