### ISSUE TITLE
DEVELOPERS: Bot class test script

### ISSUE THREAD

**Issue by ohld** [ohld/igbot#46]
We need to test our Instabot to prevent stupid misprints and make pull request checking easier. So we need to write the script that will check the main part of Instabot.

And later add it into **Travis**, may be special Instagram acc will be needed for that.

**Comment by DrCherry** [comment]
What testing framework do you think we should use?

**Comment by ohld** [comment]
We should use not heavy one. The best way is the built-in Python lib.
