### ISSUE TITLE
Duplicate debug messages when create two or more bot objects.

### ISSUE THREAD

**Issue by xSWIGx** [ohld/igbot#462]
### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:
user@Server:~/instabot$ python -V
Python 3.5.3
Code:

```python
 from instabot import Bot
bot = Bot()
2018-03-11 00:27:26,878 - INFO - Instabot Started
bot1 = Bot()
2018-03-11 00:27:32,613 - INFO - Instabot Started
2018-03-11 00:27:32,613 - INFO - Instabot Started
bot.login(username="lobanov.d.s", password="*******")
2018-03-11 00:27:39,787 - INFO - Login success as lobanov.d.s!
2018-03-11 00:27:39,787 - INFO - Login success as lobanov.d.s!
True
bot1.login(username="didzhitalpic", password="****")
2018-03-11 00:28:07,656 - INFO - Login success as didzhitalpic!
2018-03-11 00:28:07,656 - INFO - Login success as didzhitalpic!
True
```

---

### Describe your issue

Hello! Why the INFO messages duplicates when i create two or more objects?

**Comment by sudoguy** [comment]
Hello! Thank you for an issue. 
That bug fixed https://github.com/instagrambot/instabot/commit/dc32953a1e80b9cc0f0bc02e2e46c558cf5282b3
