### ISSUE TITLE
'ascii' codec can't encode character u'\u258b' in position 6: ordinal not in range(128)

### ISSUE THREAD

**Issue by harshvardhanmalpani** [ohld/igbot#465]
2018-03-15 00:56:14,585 - INFO - Going to like media with hashtag #artsy.
/usr/lib/python2.6/site-packages/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
2018-03-15 00:56:16,421 - INFO - Received 71 medias.
2018-03-15 00:56:16,430 - INFO - After filtration 67 medias left.
2018-03-15 00:56:16,431 - INFO - Going to like 67 medias.
                                                                               /usr/lib/python2.6/site-packages/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning

2018-03-15 00:56:16,919 - INFO - error, read exception bellow
2018-03-15 00:56:16,920 - INFO - 'ascii' codec can't encode character u'\u258b' in position 6: ordinal not in range(128)

**Comment by sudoguy** [comment]
Hi! As you see from the error message, you need to upgrade python to a newer version. Instabot support Python 2.7+ and Python 3+

**Comment by harshvardhanmalpani** [comment]
Yes, this issue was due to py2.6 default, I installed 3.6.4 yesterday and it worked flawlessly. Thanks a lot
