### ISSUE TITLE
KeyError: 'user'

### ISSUE THREAD

**Issue by Trothgar** [ohld/igbot#467]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

Code:

```bot = InstaBot(login="lmt", password="password",
               like_per_day=700,
               comments_per_day=0,
               tag_list=['cool'],
               max_like_for_one_tag=50,
               follow_per_day=0,
               follow_time=3*60*60,
               unfollow_per_day=0,
               unfollow_break_min=15,
               unfollow_break_max=30,
               log_mod=0,
               proxy='')
```

Error/Debug Log:

```15.03.2018_14:07 Instabot v1.2.0 started at 15.03.2018 14:07:

15.03.2018_14:07 Trying to login as lmt...

Traceback (most recent call last):
  File "/home/pi/Desktop/instabot.py-masterlmo/lm_tac.py", line 24, in <module>
    proxy='')
  File "/home/pi/Desktop/instabot.py-masterlmo/src/instabot.py", line 231, in __init__
    self.login()
  File "/home/pi/Desktop/instabot.py-masterlmo/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/home/pi/Desktop/instabot.py-masterlmo/src/userinfo.py", line 42, in get_user_id_by_login
    id_user = all_data['user']['id']
KeyError: 'user'
```

---

### Describe your issue

Hello, I have been running this script from my raspberry pi for a long time now, having to restart it every once in a while if it gets stuck or if my pi freezes up. A few days ago I restarted it after it crashed, and was greeted by this error code. I have rebooted the pi, left it unplugged for a few days and everything else I could think of hardware side, as well as re downloading the scripts. Basically I cannot run the script that has been working flawlessly for months now, wondering if instagram changed something or if I'm messed up somehow. Please advise, thank you.

**Comment by andreiafurbeis** [comment]
Same error , start yesterday .... I think that the "problem" is instagram , not you

**Comment by jtrimm007** [comment]
Same issue here....

**Comment by sudoguy** [comment]
Wrong repo

**Comment by mykolasm** [comment]
@sudoguy which repo is the right repo to clone and run? im having the same error:

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/nfs/2018/m/mmarcink/Desktop/instabot.py-master/src/instabot.py", line 231, in __init__
    self.login()
  File "/nfs/2018/m/mmarcink/Desktop/instabot.py-master/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/nfs/2018/m/mmarcink/Desktop/instabot.py-master/src/userinfo.py", line 42, in get_user_id_by_login
    id_user = all_data['user']['id']
KeyError: 'user'
