### ISSUE TITLE
checkpoint_challenge_required Error message when loging in. 

### ISSUE THREAD

**Issue by igisho** [ohld/igbot#470]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

2018-03-18 11:52:14,155 - ERROR - Request return 400 error!
2018-03-18 11:52:14,155 - INFO - Instagram error message: challenge_required
2018-03-18 11:52:14,155 - INFO - Error type: checkpoint_challenge_required
2018-03-18 11:52:14,156 - INFO - Login or password is incorrect.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here: Python 3.6.4, Python 2.7.14

Code:

```
python3 multi_script_CLI.py
```

Error/Debug Log:

```
2018-03-18 11:52:14,155 - ERROR - Request return 400 error!
2018-03-18 11:52:14,155 - INFO - Instagram error message: challenge_required
2018-03-18 11:52:14,155 - INFO - Error type: checkpoint_challenge_required
2018-03-18 11:52:14,156 - INFO - Login or password is incorrect.
```

---

### Describe your issue

When i try to unfollow i get exeption. Also on my mobile there is notification that android device tried to log in but was blocked. Cant use instapy at the moment.

**Comment by RobertoBrandini** [comment]
The same thing has happened to me for the last 2 days.

**Comment by gregyjames** [comment]
I am getting a slightly different issue:

`2018-03-24 17:46:51,921 - ERROR - Request return 400 error!
2018-03-24 17:46:51,922 - INFO - Instagram error message: Sorry, there was a problem with your request.
2018-03-24 17:46:51,922 - INFO - Error type: sentry_block
2018-03-24 17:46:51,922 - INFO - Login or password is incorrect.`

**Comment by Talebano** [comment]
Same problem but with sentry_block error.
I tried with different machines,different accounts and various ip addresses but it looks like the problem is in login.

**Comment by justanothergthbaccount** [comment]
+1 to Error type: sentry_block. Any solution or hint?

**Comment by gersanchez** [comment]
The same over here...

**Comment by rets85** [comment]
Same issue.

**Comment by johanfuen9** [comment]
Same issue. sentry_block

**Comment by BobZombiE69** [comment]
on 2 different machine , with 2 different IP , and 2 different accounts:

**Everything was working fine , until i stopped the bot and run it again** , 
then the same error here: 
Error type: sentry_block

**Comment by Brunya** [comment]
Same issue.

**Comment by kifirkin** [comment]
Working solution [here](https://github.com/instagrambot/instabot/issues/491#issuecomment-380574716)

**Comment by OverKilL013** [comment]
same problem here
