### ISSUE TITLE
Error type: sentry_block

### ISSUE THREAD

**Issue by johanfuen9** [ohld/igbot#482]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:
Python 2.7.11

Code:
```
bot.login(username=args.u,password=args.p=args.proxy)
```

Error/Debug Log:

```
2018-04-01 11:44:39,141 - ERROR - Request return 400 error!
2018-04-01 11:44:39,141 - INFO - Instagram error message: Sorry, there was a problem with your request.
2018-04-01 11:44:39,141 - INFO - Error type: sentry_block
```

---

### Describe your issue

Error trying to login,

**Comment by johanfuen9** [comment]
The error is generated when login repeatedly in a short time

**Comment by ahmadsl** [comment]
how can solve this error?
after get this error i wait for an hour, then try again and get this error again and again!

**Comment by ggirodda** [comment]
I have the same error, and I never repeatedly try to login, I'm on Ubuntu server.
I also try to use a VPN, the openvpn server was by home network from where I can access instagram without any problem, but I still got the same error.
