### ISSUE TITLE
Probable BUG in message_users.py for option of direct private message (n° 3 Message Each Your Follower)

### ISSUE THREAD

**Issue by gbergna2009** [ohld/igbot#483]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x ] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

Code:

```python
elif deliveryMethod == 3:
    followers = bot.get_user_followers(bot.user_id)
    for follower in tqdm(followers):
        bot.send_message(directMessage, follower)
    print('Sent An Individual Messages To Your Followers..')
else:
    print('Invalid Selection.')
```

Error/Debug Log:

```python
Which type of delivery method? (Type number)
0: Messages From CSV File.
1: Group Message All Users From List.
2: Message Each User From List.
3: Message Each Your Follower.
3
2018-04-01 21:47:00,320 - INFO - Instabot Started
Which account do you want to use? (Type number)
1: fukingnerd2018
0: add another account.
-1: delete all accounts.
1
2018-04-01 21:47:03,367 - INFO - Login success as fukingnerd2018!
  0%|                                                                                                                                                                                       | 0/5 [00:00<?, ?it/s]2018-04-01 21:47:03,898 - ERROR - Text must be an string, user_ids must be an list or string
2018-04-01 21:47:03,898 - ERROR - Text must be an string, user_ids must be an list or string
2018-04-01 21:47:03,898 - ERROR - Text must be an string, user_ids must be an list or string
2018-04-01 21:47:03,898 - ERROR - Text must be an string, user_ids must be an list or string
2018-04-01 21:47:03,898 - ERROR - Text must be an string, user_ids must be an list or string
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<?, ?it/s]
Sent An Individual Messages To Your Followers..
2018-04-01 21:47:04,226 - INFO - Bot stopped. Worked: 0:30:51.408623
2018-04-01 21:47:04,226 - INFO - Total requests: 7
```

---

### Describe your issue

Python version used: 3.6

Hello everyone, I wanted to report that by launching the functionality ... examples / message_users.py and choosing the last option (3: Message Each Your Follower), the bot does not send the message to my followers as it always responds with:

"ERROR - Text must be an string, user_ids must be an list or string"

If I use the 0 (0: Messages From CSV File) option, the bot correctly sends the message to the list of followers in the messages.csv file.

I wanted to ask this:

1) the function "No. 3 Message Each Your Follower" where it takes the list of my followers? Maybe from the file ... examples / followed.txt?

2) How can I correct this error "ERROR - Text must be an string, user_ids must be an list or string"?

It almost seems that if the script reads the file in .csv format then he sends the message. While with the function "No. 3 Message Each Your Follower" there is a file format / read error (ANSI instead of UTF-8)?

3) Does the function "No. 3 Message Each Your Follower" send direct messages ONLY to the new followers or to ALL the followers indistinctly when I launch the command?

**Comment by gbergna2009** [comment]
![bot](https://user-images.githubusercontent.com/37941830/38177080-f7b0a9d4-35fa-11e8-9e34-fdb4b963313d.png)

This is for error "ERROR - Text must be an string, user_ids must be an list or string" and doesn't send private message at my followers.

**Comment by Oyetomi** [comment]
@gbergna2009 its been fixed ,,close the thread

**Comment by gbergna2009** [comment]
@virginsince1997 many thanks for fix this issue! I try this new version and now it works. Only another little bug I think... messages was send to all users by the bot, but these messages are sent all together without respecting a minimum of timing. This way you really risk the ban! it seems that it does not follow the instructions in line 24 "banDelay = (86400 / messagesToSend)".

You could verify? I have tried and send messages all together right away.

![bug](https://user-images.githubusercontent.com/37941830/38442770-aba0a9ca-39e9-11e8-9f88-12733274622d.png)

**Comment by sudoguy** [comment]
@gbergna2009 @virginsince1997 What default delay I need to set for sending messages?
A delay between sending messages

**Comment by gbergna2009** [comment]
10 private messages up to one hour if we talk about a newly created instagram account with at least 6 images. This is the only data I can tell you to avoid the ban. Then I do not know exactly. However, this could be a reliable starting time, then everyone should be able to set it as they prefer by doing some tests.

**Comment by gbergna2009** [comment]
@sudoguy Hi boss! Did you check the operation of the delay parameter? at present the messages are sent correctly but are sent all together at once, as if they did not respect any timetable. This is important because otherwise send too many messages all at once, you risk the ban. Thanks so much.
