### ISSUE TITLE
High number of likes

### ISSUE THREAD

**Issue by Naramsim** [ohld/igbot#488]
### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here: Python 3.5.1 (Win10)

Code:

```python
import schedule
import time
import sys
import os
import random
import glob 
import threading 

from instabot import Bot

bot = Bot(comments_file='comments.lines')
bot.login(username='xxx', password='xxx')
bot.like_hashtag('italiainunoscatto', amount=1000)
bot.like_timeline(amount=1000)
```

No traceback, the script ends normally
---

### Describe your issue

Instabot likes only a few hashtags with respect to the requested ones. I've requested it to like 1000 but only 73 were liked.

![73likes](https://user-images.githubusercontent.com/8996268/38468188-f0799a8e-3b42-11e8-941f-d162c231765c.PNG)

When liking 1000 pics from the feed, only picked 10. It then says that it liked 84 :confused: medias

![liketimeline](https://user-images.githubusercontent.com/8996268/38468300-0d59df78-3b44-11e8-9822-a750ad29bae2.PNG)

Could be that the APIs returns only a few elements?

**Comment by sudoguy** [comment]
Hello! Thank you for an issue! Fixed in last commit (https://github.com/instagrambot/instabot/commit/a2907aa1de6b73318df40398be5d903165077c65)
