### ISSUE TITLE
Unable to login to my account with instabot (Sentry_block)

### ISSUE THREAD

**Issue by kantona80** [ohld/igbot#491]
### Before submitting an issue, make sure you have:
- [X] Updated to the latest version
- [X] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [X] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [X] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

python version user 2.7

Paste the output of ``python -V`` here:

Code:

```python
# Example code that will produce the error reported
from instabot import Bot

bot = Bot()
bot.login(username="user", password="pass")
followers = bot.get_user_followers(bot.user_id)
```

Error/Debug Log:

```python
```
2018-04-11 06:47:42,913 Instabot Started
2018-04-11 06:48:05,527 - ERROR - Request return 400 error!
2018-04-11 06:48:05,530 - INFO - Instagram error message: Sorry, there was a problem with your request.
2018-04-11 06:48:05,531 - INFO - Error type: sentry_block
2018-04-11 06:48:05,532 - INFO - Login or password is incorrect.
---

### Describe your issue

I suppose that something changed in Instagram authentication, so I'm unable to login to my account with instabot, on the other hand I can login without problem using official Instagram application with same password.
Until yesterday it worked like a charm!

**Comment by heyton** [comment]
Same story

**Comment by kantona80** [comment]
I verified that on windows platform with Python 2.7.9 and latest version of instabot (0.3.5.3) it works. The problem occurs when I use the library instabot on Ubuntu 16.04.4 LTS with Python 2.7.12

I tried with different public ip addresses and got same KO result with Ubuntu.

**Comment by kifirkin** [comment]
same here :worried: 

Some more info on this error:
when I first tried to sign in I've got this error
```
2018-04-11 19:56:02,925 - ERROR - Request return 400 error!
2018-04-11 19:56:02,926 - INFO - Instagram error message: challenge_required
2018-04-11 19:56:02,926 - INFO - Error type: checkpoint_challenge_required
2018-04-11 19:56:02,926 - INFO - Login or password is incorrect.
```
and only then got:
```
2018-04-11 19:56:35,247 - ERROR - Request return 400 error!
2018-04-11 19:56:35,654 - INFO - Instagram error message: Sorry, there was a problem with your request.
2018-04-11 19:56:35,654 - INFO - Error type: sentry_block
2018-04-11 19:56:35,655 - INFO - Login or password is incorrect.
```

100% WORKING SOLUTION!:
1. [Temporary deactivate account](https://www.instagram.com/accounts/remove/request/temporary/)
1. Select reason: `just need a break`
1. Wait 2-3 hours
1. Login directly with bot (It will activate account back without `sentry_block` or `checkpoint_challenge_required` errors)

**Comment by sudo-judo** [comment]
Deactivate for how long? And how to relogin? It is safe?

**Comment by armanlabs** [comment]
i have same error

**Comment by jasonwoodland** [comment]
+1

**Comment by kifirkin** [comment]
@sudo-judo I've edit my comment. Also you could read more about how instagram deactivation works [here](https://help.instagram.com/728869160569983)
