### ISSUE TITLE
get_user_followers(self) returns wrong amount

### ISSUE THREAD

**Issue by ghost** [ohld/igbot#493]
### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

The Method "bot.get_user_followers(my_username)" returns a wrong amount of followers. Currently the number is exactly 210 Followers off for my account (25383 instead of 25593 in Insights).

Extract from my Code (Python 3.6.3 & every pip install up-to-date):
```python
followers = bot.get_user_followers(args.u)
with open(followerfile, "w") as file:
    for user_id in followers:
        file.write(user_id + "\n")
        followercount=followercount+1
```
---

I usually scrape my own not_following_back users and i noticed that the bot unfollowed some people who I am sure where following me back. So i wrote the above script to write the followers into a File and voila: I saw that the exact number of 210 followers where missing. 

EDIT: There are no duplicates in this File and the Bot took the usual Pause when scraping more than 20000. The counter counting up, shows the right amount of Followers tho.

**Comment by davidhearnsmith** [comment]
Server lag 👍
