### ISSUE TITLE
Retrieve messages

### ISSUE THREAD

**Issue by Naramsim** [ohld/igbot#495]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other
---

### Describe your issue

Hello, thanks for the project! Would it be possible to retrieve user messages? Right now we only have the possibility to send messages, but we can't understand if the person actually has replied to the message.

Maybe this your line could be helpful:

https://github.com/instagrambot/instabot/blob/97465a71615c39544d037bca670b5eb4fc8b02c1/instabot/api/api.py#L317

**Comment by basnijholt** [comment]
See https://github.com/instagrambot/instabot/pull/509.

I added a method to the `Bot` class called `get_messages`.
