### ISSUE TITLE
max_followers_to_following_ratio and max_following_to_followers_ratio is the same

### ISSUE THREAD

**Issue by basnijholt** [ohld/igbot#499]
And one of them should just be the inverse of the other, e.g. `max_followers_to_following_ratio = 1/max_following_to_followers_ratio`. 

We should either deprecate one of them or make the arguments mutually exclusive.

**Comment by basnijholt** [comment]
This should be fixed.

**Comment by alessiofx** [comment]
hi, how to disable max_followers_to_following_ratio ?

**Comment by cldt-fr** [comment]
> hi, how to disable max_followers_to_following_ratio ?

max_followers_to_following_ratio=1000,
max_following_to_followers_ratio=1000,
