### ISSUE TITLE
Username to user_id converter

### ISSUE THREAD

**Issue by ohld** [ohld/igbot#50]
We need to implement function that returns user_id by username.

**Comment by penarubah** [comment]
refer to this?
https://github.com/CodeDotJS/Instagram-UserId
https://github.com/zeantsoi/django-instagram-uid

**Comment by ValBaturin** [comment]
penarubah, first link is definitely not valid because jelled is not working anymore. The second one uses dependencies like https://github.com/facebookarchive/python-instagram.

**Comment by ValBaturin** [comment]
We can get a user_id from this https://www.instagram.com/USERNAME/?__a=1

**Comment by maxkrivich** [comment]
I'm already do this, I can take it.

**Comment by ohld** [comment]
I think we should use already written Info getters - methods in API class.

**Comment by ohld** [comment]
Done in 0.3.1
