### ISSUE TITLE
Follow/unfollow by list of users from file

### ISSUE THREAD

**Issue by maxkrivich** [ohld/igbot#51]
Follow/unfollow by all users who contains in file(by id or user_name). In bot already have this function but for lists

**Comment by DrCherry** [comment]
@ohld , do we want to read from files?  I can cook up an example that does this really quickly.   I suppose we'll want to do some sort of input checking.

**Comment by ohld** [comment]
We have already this script at examples. https://github.com/ohld/instabot/blob/master/examples/follow_users_from_file.py
But it needs the file with user_ids, not usernames. That's why the very important task is #50

**Comment by ohld** [comment]
reimplemented in 0.3.1. See examples.
