### ISSUE TITLE
Proxy ?

### ISSUE THREAD

**Issue by lasododo** [ohld/igbot#513]
Hello I just have a quick question how to set up a proxy while using the bot ... i noticed that this is in __init__ : proxy=None, 

and then i found this part of a code : 

 def login(self, **args):
        if self.proxy:
            args['proxy'] = self.proxy
        if self.api.login(**args) is False:
            return False
        self.prepare()
        signal.signal(signal.SIGTERM, self.logout)
        atexit.register(self.logout)
        return True

I am kinda newbie in proxies etc. so I would like to ask how to set it up, thank you

**Comment by heyton** [comment]
```
from instabot import Bot

b = Bot()
b.login(username ="username", password ="pass", proxy = "http://login:password@ip:port")
```

**Comment by tah62k** [comment]
try this 
b.login(username ="username", password ="pass", proxy = "http://login:password@ip:port")
