### ISSUE TITLE
Bot detection?

### ISSUE THREAD

**Issue by kintaro1981** [ohld/igbot#516]
https://help.instagram.com/519522125107875

> Device operations: information about operations and behaviors performed on the device, such as whether a window is foregrounded or backgrounded, or mouse movements (which can help distinguish humans from bots).

Is this going to impact instabot?

**Comment by Naramsim** [comment]
Instabot could fake mouse movement requests, they are simple API requests

**Comment by kintaro1981** [comment]
It’s a default behavior or have to be enabled every time a script run?
