### ISSUE TITLE
Unfollow error 404 and 429 in ultimate_schedule 

### ISSUE THREAD

**Issue by angeloiaia** [ohld/igbot#535]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

Code:

```# -*- coding: utf-8 -*-

from glob import glob
import os
import sys
import threading
import time

sys.path.append(os.path.join(sys.path[0], '../../'))
import schedule
from instabot import Bot, utils

import config

bot = Bot(
			filter_users=False,
			
			#--- proxy ---
			proxy=None,
			
			#--- delays ---
			like_delay=15,
			follow_delay=50,
			unfollow_delay=60,
			comment_delay=60,
			
			#--- max ---
			max_likes_per_day=900,
			max_unlikes_per_day=300,
			max_follows_per_day=120,
			max_unfollows_per_day=400,
			#max_likes_to_like=100,
			#max_followers_to_follow=2000,
			min_followers_to_follow=50,
			max_following_to_follow=5000,
			#min_following_to_follow=10,
			#max_followers_to_following_ratio=10,
			#max_following_to_followers_ratio=2,
			max_following_to_block=5000,
			min_media_count_to_follow=20,
			
			#--- files ---
			comments_file=config.COMMENTS_FILE,
			blacklist_file=config.BLACKLIST_FILE,
			whitelist_file=config.WHITELIST_FILE,
			
			stop_words=['travel']
)

bot.login(username="", password="")
bot.logger.info("ULTIMATE script. 24hours save")

#fn to return random value for separate jobs
def get_random(from_list):
    _random=random.choice(from_list)
    print("Random from ultimate.py script is chosen: \n" + _random + "\n")
    return _random

#--- JOBS ---
def job3():
	bot.unfollow_non_followers(n_to_unfollows=config.NUMBER_OF_NON_FOLLOWERS_TO_UNFOLLOW)	

# function to make threads -> details here http://bit.ly/faq_schedule
def run_threaded(job_fn):
    job_thread=threading.Thread(target=job_fn)
    job_thread.start()

#--- TIMELINE ---
#UNFOLLOW
schedule.every(1).days.at("15:00").do(run_threaded, job3)

while True:
    schedule.run_pending()
    time.sleep(1)
```

Error/Debug Log:

<img width="1079" alt="schermata 2018-05-06 alle 14 43 34" src="https://user-images.githubusercontent.com/32001281/39673476-63f0b33e-513d-11e8-9d6f-71c3d4c83726.png">

---

### Describe your issue

Hi, I'm having a problem with the "ultimate_schedule" script.
I can not do the unfollow due to error 404 and 429. I have also lowered the number of unfollow to 2 but it does not work the same.
Thank you.

**Comment by jacekmichalski** [comment]
I have the same issue. Everything works fine in ultimate_schedule except unfollow_non_followers
