### ISSUE TITLE
How to upload random photo in ultimate_schedule.py

### ISSUE THREAD

**Issue by zeroyjk** [ohld/igbot#537]
Hello, how to upload random photo in ultimate_schedule.py
What code do i need to add?

**Comment by callum8004** [comment]
I'm also struggling with this as I'm not sure where to add the photos

Confif files states:

PICS_PATH = "/Path/to/pics/folder/"
# The path of the directory containing the photos the bot will upload
# NOTE: Being a directory, it must end with '/'

but where in ultimate.py would I add this?

Callum
