### ISSUE TITLE
Comment my own post several times

### ISSUE THREAD

**Issue by TheLegno** [ohld/igbot#539]
Hi, everybody
I tryed to comment my own medias, selecting myself as the user I want to comment, but the bot just return with 0 comments(works fine for other users).
I'd like to know how could be possible to comment only one of my medias (not 18) something like 1000 times using the comment list I have in the .txt
Thanks in advance

**Comment by AizenSousuke** [comment]
why would anyone do that if I may ask?

**Comment by TheLegno** [comment]
to mention people
