### ISSUE TITLE
Change txt files path

### ISSUE THREAD

**Issue by pconin** [ohld/igbot#543]
Hello there,
all the .txt file (friends, followed, etc...) are located on server root by default.
I'm looking to centralize it in a folder. Is there a way to change that from a config file? Or do I need to change all the occurences in the code?

Thank you

**Comment by basnijholt** [comment]
Please search for this next time.

https://github.com/instagrambot/instabot/issues/518

tl;dr (again):
`bot = Bot(whitelist_file=..., blacklist_file=..., followed_file=...)`
