### ISSUE TITLE
FEATURE REQUEST: Ability to tag users on photos using upload_photo

### ISSUE THREAD

**Issue by kantona80** [ohld/igbot#547]
### Before submitting an issue, make sure you have:
- [X] Updated to the latest version
- [X] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [X] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [X] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Describe your issue
I need to upload some photos and tag on the photos the original author of the photos. 
I have to put the tag in one of the corners no matter where in particular.
It is very useful for the reposts.

Is it possible to do this?
Thanks

**Comment by ivadenis** [comment]
Up vote! I see it implemented here https://github.com/mgp25/Instagram-API/blob/master/src/Request/Usertag.php

maybe we can work on a port

**Comment by kantona80** [comment]
UP!
