### ISSUE TITLE
bot.save_user_stats() does not save updated stats

### ISSUE THREAD

**Issue by 1326570** [ohld/igbot#548]
### Before submitting an issue, make sure you have:
- [ x] Updated to the latest version
- [x ] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x ] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Code:

```python
in 'ultimate.py'
def stats():
    bot.save_user_stats(bot.username)

schedule.every(1).hours.do(run_threaded, stats)

but this saves the first value over and over. Probably because in get_user_info() there is a check to see if user stats were already asked for. 

def get_user_info(self, user_id):
    user_id = self.convert_to_user_id(user_id)
    if user_id not in self._user_infos:
        self.api.get_username_info(user_id)
        if 'user' not in self.api.last_json:
            return False
        user_info = self.api.last_json['user']
        self._user_infos[user_id] = user_info
    return self._user_infos[user_id]
```

Error/Debug Log:

```python

```

---

### Describe your issue
In the ultimate file we save the usere stats every hour, however bot.save_user_stats() does not save updated stats, but the ones when the function was first run. 
This saves the same value over and over. Probably because in get_user_info() there is a check to see if user stats were already asked for. 

--> add check to see if user stats are requested from own user ID, or remove check altogether and always overwrite when function is called.

**Comment by orcunbaslak** [comment]
Same issue here

**Comment by lubislutfi** [comment]
same issue too...

**Comment by basnijholt** [comment]
https://github.com/instagrambot/instabot/pull/556 should fix it ;)

**Comment by 1326570** [comment]
Need to add the use_cache part to the bot.py file as well. Seems to work well otherwise

**Comment by basnijholt** [comment]
Thanks for using it. I've reopened the issue. Could you be a bit more specific about where you added the use_cache?

**Comment by lubislutfi** [comment]
In **bot/bot.py**
Change:
`def get_user_info(self, user_id):
 return get_user_info(self, user_id)`
To:
`def get_user_info(self, user_id, use_cache):
 return get_user_info(self, user_id, use_cache)`

**Comment by basnijholt** [comment]
Good point! I've just changed ithttps://github.com/instagrambot/instabot/commit/b7404c645b31c4424dbdf8beb4035d25307a484a
