### ISSUE TITLE
Can not find username_database.txt file

### ISSUE THREAD

**Issue by Tankr3d** [ohld/igbot#551]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

I'm not familiar with Python and English is not my mother tongue so please be confused! I use Python 3.3.6 and get the following error when starting repost_best_photos_from_users.py:
1
2018-05-18 12: 22: 37,085 - INFO - Logged-in successfully as 'machine4meme' using the cookie!
Can not find 'username_database.txt' file.
Getting media info: 0it [00:00,? It / s]
Reposting photos: 0it [00:00,? It / s]
2018-05-18 12: 22: 37.489 - INFO - Bot stopped. Worked: 2 days, 22: 08: 19.947692
2018-05-18 12: 22: 37,490 - INFO - Total requests: 3

I have already reinstalled the bot once before I tried to copy the filled username_database file into the example directory then the script apparently got a step further but it then displayed a new error...

**Comment by sudoguy** [comment]
You need to create a file ```username_database.txt``` and write to the file those users whose pictures you want to repost.
One user - one line

**Comment by Tankr3d** [comment]
But where I have to drag username_database.txt  and whats  about followers info? (What I have to input?)

**Comment by Tankr3d** [comment]
If I drag username_database.txt in examples i got this error: 

Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Can't find 'posted_medias.txt' file.
Getting media info: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 72/72 [00:22<00:00,  3.34it/s]
Reposting photos:   0%|                                                                                                                                                                                               | 0/1 [00:00<?, ?it/s]Can't find 'posted_medias.txt' file.

Traceback (most recent call last):
  File "C:\Users\Tom\Downloads\instabot-master\examples\repost_best_photos_from_users.py", line 94, in <module>
    repost_best_photos(bot, users, args.amount)
  File "C:\Users\Tom\Downloads\instabot-master\examples\repost_best_photos_from_users.py", line 28, in repost_best_photos
    repost_photo(bot, media)
  File "C:\Users\Tom\Downloads\instabot-master\examples\repost_best_photos_from_users.py", line 69, in repost_photo
    with open(photo_path[:-3] + 'txt', 'r') as f:
TypeError: 'bool' object is not subscriptable
2018-05-26 15:24:35,508 - INFO - Bot stopped. Worked: 11 days, 1:10:17.967552
2018-05-26 15:24:35,509 - INFO - Total requests: 371

**Comment by Vladislas** [comment]
any update this issues?

**Comment by Tankr3d** [comment]
@Vladislas I still need help!

**Comment by EightShift** [comment]
just create missed files

**Comment by Tankr3d** [comment]
If I create the missed file ( posted_medias.txt ) and drag it in examples I got this error:

2018-06-08 12:38:30,593 - INFO - Logged-in successfully as 'machine4meme' using the cookie!
Getting media info: 100%|██████████████████████████████████████████████████████████████| 72/72 [00:28<00:00,  2.12it/s]
Reposting photos:   0%|                                                                          | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\Tom\Downloads\instabot-master\examples\repost_best_photos_from_users.py", line 90, in <module>
    repost_best_photos(bot, users, args.amount)
  File "C:\Users\Tom\Downloads\instabot-master\examples\repost_best_photos_from_users.py", line 26, in repost_best_photos
    repost_photo(bot, media)
  File "C:\Users\Tom\Downloads\instabot-master\examples\repost_best_photos_from_users.py", line 65, in repost_photo
    with open(photo_path[:-3] + 'txt', 'r') as f:
TypeError: 'bool' object is not subscriptable
2018-06-08 12:39:10,002 - INFO - Bot stopped. Worked: 23 days, 22:24:52.461533
2018-06-08 12:39:10,002 - INFO - Total requests: 875
