### ISSUE TITLE
how to auto pass parameter to multi_script_CLI.py without keyboard

### ISSUE THREAD

**Issue by armanlabs** [ohld/igbot#553]
### Before submitting an issue, make sure you have:
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

### Describe your issue

i'm using centos vps server. how to setup supervisor to pass parameter for multi_script_CLI.py ?
I do not have access to the command line. 
Can I automatically pass the parameters without keyboard press?

**Comment by mycryptohustle** [comment]
Why not run individual scripts instead?
