### ISSUE TITLE
stop words.txt in ultimate_schedule

### ISSUE THREAD

**Issue by EightShift** [ohld/igbot#559]
### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

Hi there.

Does anyone know?
If I add to **ultimate.py** in **ultimate_schedule**
this:
```
bot = Bot(comments_file=config.COMMENTS_FILE,
          blacklist_file=config.BLACKLIST_FILE,
          whitelist_file=config.WHITELIST_FILE,
          friends_file=config.FRIENDS_FILE,
          stop_words=config.STOPWORDS_FILE)       <---
```

And in the file **config.py** add **STOPWORDS_FILE = "stop_words.txt"** and create a file **stop_words.txt** in which there will be a stop word in this form:

```
'Dagmar',  
'Dahlgren',  
'Dakine',  
'Dale of Norway',  
'Dan Post',  
'Daniblack',  
'Daniel Barbara',  
'Daniel Green',  
'Danielle Nicole',  
'Danner',  
'Dansk',  
```

Will all this work?
I ask because I did it and I can't understand how correctly the accounts are filtered.

Thx!

**Comment by basnijholt** [comment]
> Will all this work?

This will definitely not work, it's no magic.

OTOH this is not hard to implement yourself ;)

**Comment by callum8004** [comment]
its seems mad that the ultimate and ultimate-schedule vary so much. surely ultimate schedule should be a duplicate of ultimate.py but with the schedule module added in.
