### ISSUE TITLE
Like and follow from user followers 

### ISSUE THREAD

**Issue by bkxwy** [ohld/igbot#565]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [X] Updated to the latest version
- [X] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [X] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [X] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Like and follow user followers 

Hi, I was trying to do my bot follow and like by adapting the multi_script_CLI.py with some codes from like_and_follow_your_last_media_likers.py example.

**I take this code:**
```python
elif ans == "2":
            print("""
            1.Insert username
            2.Use username database
            """)
            if "1" in sys.stdin.readline():
                user_id = input("who?\n").strip()
            else:
                user_id = random.choice(bot.read_list_from_file(users_file))
            bot.follow_followers(user_id)
            menu_follow()
```
**And change to this:**
```python
elif ans == "2":
            print("""
            1.Insert username
            2.Use username database
            """)
            if "1" in sys.stdin.readline():
                user_id = input("who?\n").strip()
            else:
                user_id = random.choice(bot.read_list_from_file(users_file))
            followers = bot.get_user_followers(user_id)
	    for follows in tqdm(followers):
			bot.like_user(follows, amount=2)
			bot.follow(follows)
```
but when i try to run it says:

*C:\Users\Robson\Downloads\instabot\examples>python multi_script_CLI.py*
  *File "multi_script_CLI.py", line 241*
    *for follows in tqdm(followers):*
                                                 *^*

So, someone already put the bot to follow and like from user followers? thanks

**Comment by basnijholt** [comment]
You are mixing tabs and spaces.

**Comment by diorox** [comment]
Use filtration false
`bot.like_user(follows, amount=2, filtration=False)`
