### ISSUE TITLE
DEVELOPERS: time delays control

### ISSUE THREAD

**Issue by ohld** [ohld/igbot#57]
We should think about time delays in a project: 
 * Where we should put delays in code? (in like/follow or in more higher level functions)
 * How we can control delays throw code? (fast and dangerous / slow and comfort) 

And ideas?

**Comment by DrCherry** [comment]
Good question.  I though maybe in the future we could have queues that know how long to wait for each type of action.  The queues could start before the code that populates them and run as threaded workers.   Each thread would be smart enough not to make too many requests.

**Comment by ohld** [comment]
Added this in 0.3.2.2. Read Readme.md for details.
