### ISSUE TITLE
Follow Users & allow Business + private acc 

### ISSUE THREAD

**Issue by imachref** [ohld/igbot#574]
guys i want to stop bot filltre of business accounts& private acc , i edited bot_filtre & bot.py but still noth !
im still getting info: is BUSINESS, skipping! 
im trying to use like_and_follow_last_user_media_likers.py 
i really need to make this done

**Comment by basnijholt** [comment]
Did you try to search for this at all?

https://github.com/instagrambot/instabot/issues/572

**Comment by imachref** [comment]
i did & i tryed every solution they said it worked but i didnt work for me , even desabling the hole user_filtre & make it False , still not working

**Comment by basnijholt** [comment]
Could you post what exactly you tried?

**Comment by imachref** [comment]
urs https://github.com/instagrambot/instabot/blob/master/instabot/bot/bot.py#L69

instabot.Bot(filter_business_accounts=False) 
that didnt work ,

**Comment by imachref** [comment]
alter "filter_users" to False in bot.py 
still didnt work

**Comment by basnijholt** [comment]
Duplicate of https://github.com/instagrambot/instabot/issues/572.
