### ISSUE TITLE
Account banned

### ISSUE THREAD

**Issue by nim444** [ohld/igbot#588]
Your account has been disabled for violating our terms: http://instagram.com/about/legal/terms/ (403) (/accounts/login/ajax/)

Any one can explain this issue how happen ?

**Comment by Niall7459** [comment]
Making to many requests to fast.

**Comment by kintaro1981** [comment]
Same problem with an account of mine. I was doing all within the default limits.

Is there anything I can do to make IG revoke the suspension?
