### ISSUE TITLE
DESIGNERS: Logo and Landing page.

### ISSUE THREAD

**Issue by ohld** [ohld/igbot#59]
Current landing page: ohld.github.io/instabot
It is simple but not cool. If someone have possibility to _develop a Logo for Instabot_ and make _better landing page_ that would be **great**! 

I found some services that can help you to create a landing page:
 * https://tilda.ws
 * https://webflow.com

**Comment by penarubah** [comment]
i can do the logo. How do we want the logo look like?

**Comment by DrCherry** [comment]
I like animals.

**Comment by ohld** [comment]
As I see I want big white letters with _INSTABOT_. But you can suggest your ideas.

**Comment by ohld** [comment]
@penarubah Just go to popular GitHub repositories and see how they made their logos.

**Comment by rasperepodvipodvert** [comment]
i make my site from tilda.ws

**Comment by ohld** [comment]
Moved to the separate repository. https://github.com/instagrambot/instagrambot.github.io
