### ISSUE TITLE
follow_users_by_hashtag

### ISSUE THREAD

**Issue by rakshith1997** [ohld/igbot#592]
python follow_users_by_hashtag.py
usage: follow_users_by_hashtag.py [-u U] [-p P] [-proxy PROXY]
                                  hashtags [hashtags ...]
follow_users_by_hashtag.py: error: too few arguments

**Comment by kintaro1981** [comment]
the usage says that you need to write at least a hashtag

`python follow_users_by_hashtag.py hashtag`
