### ISSUE TITLE
Like_hashtags_from_file error

### ISSUE THREAD

**Issue by rainerroesing** [ohld/igbot#599]
When running like_hashtags_from_file I receive this error and would appreciate any help:

2018-07-30 17:15:56,096 - INFO - Logged-in successfully as '******'!
2018-07-30 17:15:56,096 - INFO - Saved cookie!
**coercing to Unicode: need string or buffer, list found**
2018-07-30 17:15:56,097 - INFO - Hashtags: []
2018-07-30 17:15:56,409 - INFO - Bot stopped. Worked: 0:00:14.151062
2018-07-30 17:15:56,409 - INFO - Total requests: 3

**Comment by Areahints** [comment]
hello, i searched on stackoverflow, it seems your error is a python one, what version of python do you have installed and what os are you running?

**Comment by rainerroesing** [comment]
Hey, I have python 2.7.10 running under osx 10.13.5

**Comment by Areahints** [comment]
from what i read here ```https://stackoverflow.com/questions/30653360/python-writing-to-csv-typeerror-coercing-to-unicode-need-string-or-buffer```
the error might be coming from a modification to the file/files been written, id suggest you pull the latest update via `git pull origin master` and be careful of spaces when editing your .py files
