### ISSUE TITLE
unfollow_non_followers.py Error

### ISSUE THREAD

**Issue by BigClunk** [ohld/igbot#600]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [ X] Updated to the latest version
- [ X] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [ X] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ X] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ X] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

Using Python version 3.6 and on Mac OS 10.13.5

Pariss-iMac-2:examples Hunter$ python3 unfollow_non_followers.py
Traceback (most recent call last):
  File "unfollow_non_followers.py", line 13, in <module>
    from instabot import Bot
  File "/Users/Hunter/Desktop/instabot-master/examples/../instabot/__init__.py", line 1, in <module>
    from .api import API
  File "/Users/Hunter/Desktop/instabot-master/examples/../instabot/api/__init__.py", line 1, in <module>
    from .api import API
  File "/Users/Hunter/Desktop/instabot-master/examples/../instabot/api/api.py", line 15, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Pariss-iMac-2:examples Hunter$ 

Every time i try and run any file from the example folder i get this error. Does anyone know how to fix this??? Any help would be appreciated :)

**Comment by kintaro1981** [comment]
have you installed instabot with:

`pip install -U instabot
`

right?

**Comment by BigClunk** [comment]
yes thats the first thing i did when i downloaded python

**Comment by robinbuerkli** [comment]
Did you install the requests module?

`pip install requests`
