### ISSUE TITLE
API CHANGE. I can’t sign any more from a new account today. 

### ISSUE THREAD

**Issue by valentinpompa** [ohld/igbot#604]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [X] Updated to the latest viersion
- [X] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [X] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [X] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

Code:

Error/Debug Log:

```2018-04-11 19:56:02,925 - ERROR - Request return 400 error!
2018-04-11 19:56:02,926 - INFO - Instagram error message: challenge_required
2018-04-11 19:56:02,926 - INFO - Error type: checkpoint_challenge_required
2018-04-11 19:56:02,926 - INFO - Login or password is incorrect
```

---

### Describe your issue

I think that something change in Instagram API. I have like 10 Instagram accounts working good but I try to add 3 new Instagram account to Instabot and I got the same error. 

I did a lot of login confirmation in my Instagram App but It doesn’t working too. There is the same problem. 

I think that Instagram could ask for a SMS code when we login via API now. 

Can somebody help me? Am I right?

**Comment by lukasz00500** [comment]
I think That its related to cookie file and crsftoken try to rename cookie.txt and let bot create new one

**Comment by maykbrito** [comment]
Same here.
This worked  great for me
https://github.com/instagrambot/instabot/issues/491#issuecomment-380574716

**Comment by valentinpompa** [comment]
@lukasz00500 I've already tried.

**Comment by valentinpompa** [comment]
Something is happening... I press "That was me" from another Instagram App and It still ask me the "challenge". I delete Cookie file and anything is working. This could be the end for this script.

I try to login from other phone, then Instagram ask me for a "challege" with SMS Code. I put the SMS Code and It works now, but only with SMS Code and not "That was me"".

**Comment by lukasz00500** [comment]
I also had this problem, after several login attempts I finally managed to log in
