### ISSUE TITLE
Many 404 errors – Normal?

### ISSUE THREAD

**Issue by polzav** [ohld/igbot#605]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

In log file many errors with code 404. This is normal?

p.s. I am use follow_users_by_hashtag.py script.

`2018-08-02 20:01:02,632 Request returns 404 error!`

**Comment by TiasTias** [comment]
I am also getting this issue. It seems to be working alright but in the log many "ERROR - Request returns 404 error!" are popping up. Essentially with every action.
