### ISSUE TITLE
Follow From saved users in file -Help

### ISSUE THREAD

**Issue by nim444** [ohld/igbot#608]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [ ] Updated to the latest version
- [ ] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [ ] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

---

hello 

i saved some users followers in file , now how i can send follow request from that file ? 

i use https://github.com/instagrambot/instabot/blob/master/examples/save_users_followers_into_file.py
thanks

**Comment by kintaro1981** [comment]
With this?
https://github.com/instagrambot/instabot/blob/master/examples/follow_users_from_file.py

or you can do it directly without a source file with this:
https://github.com/instagrambot/instabot/blob/master/examples/follow_user_followers.py

**Comment by Areahints** [comment]
when i try to save users to file i get 404 error


```
python save_users_followers_into_file.py [-u my-username] [-p my-password]

2018-08-09 15:25:02,656 - INFO - Instabot Started
Which account do you want to use? (Type number)
1: *my-username*
2: other account
3: other account
4: other account
5: other account
0: add another account.
-1: delete all accounts.
1
The loaded cookie was for *other account* instead of *my-username*.
2018-08-09 15:25:16,045 - INFO - Logged-in successfully as *'my-username'*!
2018-08-09 15:25:16,051 - INFO - Saved cookie!
2018-08-09 15:25:19,199 - ERROR - Request returns 404 error!
2018-08-09 15:25:23,161 - ERROR - Request returns 404 error!
```
