### ISSUE TITLE
DEVELOPERS: Filter real users / bots / commercials 

### ISSUE THREAD

**Issue by ohld** [ohld/igbot#61]
We need to have the ability to filter bots and commercial accounts (don't like and follow them), so we should interact with real users only. Am i right? 
In `bot_filter.py` i've started to write this function called **check_user(self, user_id)**. We just need to find the way how to define this accounts. 

E.g. conditions based followers / following ratio, based on description, links in account etc.

What conditions can you suggest?

**Comment by andrewsaltanov** [comment]
in commercial accounting have buttons like "contact" and "call"
![223031481_13542315811667954055](https://cloud.githubusercontent.com/assets/25931116/23178084/33252090-f87a-11e6-9328-53173e98a700.jpg)


and in the description have the information from facebook like "personal blog", "fiction charather", "engineering/ construction"

**Comment by maxkrivich** [comment]
I have a guess what a real account probably have more then one photo and followers/following approximately equals 1

**Comment by ohld** [comment]
No. We should collect the list of accounts of real persons and bots / commercials. And only then we can give the approximation of this ratio.

**Comment by andrewsaltanov** [comment]
maybe the ratio of follower and following. In real live we have more followers that following
bots more following the followers

**Comment by ohld** [comment]
Ok, we can use Machine learning to love this problem. If we want to use it we need to have a lists of bots and real users. As big as we can

**Comment by penarubah** [comment]
commercials tend to not follow many account. so the ratio of followers and following will be extreme, right?
i.e: followers 76k following 200 like that.

maybe we need to scrape this kind of account and see what we can do.
