### ISSUE TITLE
Cannot unfollow private accounts(requested).

### ISSUE THREAD

**Issue by e-nicolas** [ohld/igbot#610]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue

I made a script for follow and like some users, based on last media from an specific user. After a while I run another script to unfollow the users followed previously, but only the private accounts not approved (requested) cannot be unfollowed. This is correct? Have another workaround?

**Comment by erfanghlm** [comment]
???
