### ISSUE TITLE
How to add "username" when reposting images

### ISSUE THREAD

**Issue by brain-wash** [ohld/igbot#612]
Hi, I want to use "repost_best_photos_from_users.py" but I want to give credits to the account who originally posted the image. Therefor I want to add their name to the caption, but I am still quite new to python.

I found the username being used for downloading the image in bot_photo.py in line 22:
username = media['user']['username']

Now I tried to add the username to the caption by chaning line 68 in repost_best_photos_from_users.py from this:
text = ''.join(f.readlines())
to this:
text = 'repost from @' + bot_photo.username + ''.join(f.readlines())

I tried different variations but I was not yet able to figure out how to do this corretcly. 
Did anybody already do something similar or could help me how to properly import the variable username?

**Comment by kintaro1981** [comment]
`bot.get_media_owner(media)
`

**Comment by brain-wash** [comment]
@kintaro1981 
Thank you! In the meantime I did a lot of testing and found a solution myself, but this one seems to be easier/cleaner.

**Comment by kantona80** [comment]
is there a way to tag username on the media?
