### ISSUE TITLE
can not get ranked content on hashtags !! 

### ISSUE THREAD

**Issue by zakasmi** [ohld/igbot#613]
when I use getHashtagFeed() or getTotalHashtagFeed . it doesn't get the Top 9 posts , 
how can I get the Top 9 Posts (ranked content ) , I already set ranked_content=true , but it doesn't work 
any help will be much appreciated !!

**Comment by barclaey** [comment]
Getting the top hashtag posts instead of (or in addition to) the most recent ones would be very nice. Is there any documentation on the "unofficial instagram" api? I'm willing to add it if I know how the API looks like...
