### ISSUE TITLE
Ultimate.py error when invoking bot.like_timeline

### ISSUE THREAD

**Issue by chicco785** [ohld/igbot#614]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here: 3.6

Code:

```python
def like_timeline():
    bot.logger.info("like_timeline")
    bot.like_timeline(amount=300 // 24)
```

Error/Debug Log:

```
2018-08-13 15:30:10,494 - INFO - Liking timeline feed:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "conf/ultimate.py", line 51, in like_timeline
    bot.like_timeline(amount=300 // 24)
  File "/opt/app/conf/../instabot/bot/bot.py", line 407, in like_timeline
    return like_timeline(self, amount)
  File "/opt/app/conf/../instabot/bot/bot_like.py", line 59, in like_timeline
    medias = self.get_timeline_medias()[:amount]
  File "/opt/app/conf/../instabot/bot/bot.py", line 300, in get_timeline_medias
    return get_timeline_medias(self)
  File "/opt/app/conf/../instabot/bot/bot_get.py", line 46, in get_timeline_medias
    return self.filter_medias(self.api.last_json["items"], filtration)
KeyError: 'items'
```

---

### Describe your issue

Not sure if I am doing something wrong :) but I suppose no, since there not need for any configuration for this API call

**Comment by chicco785** [comment]
looking at the code is suspect that 'feed_items' is correct rather than 'items'

**Comment by A1exLemesios** [comment]
Having the same issue, the answer of @chicco785  is correct , though i can't edit the source code because is placed in an .egg file . Any ideas how to fix it ?

**Comment by ghost** [comment]
still doesnt work @chicco785

**Comment by putuariepra** [comment]
Has anyone managed to fix this? 
I have changed items to feed_items in bot_get.py (line 46, function get_timeline_medias). The error is gone but the bot always shows "After filtration 0 medias left. Nothing to like.". In fact, there are many medias that have not been liked when I open my timeline in mobile app

**Comment by ghost** [comment]
no one has managed to fix this and its very disappointing @putuariepra

**Comment by A1exLemesios** [comment]
The media retrieved from the  specific api has media_or_ad as main object . After the media are retrieved they are filtered based on their media object which doesn't exist . In bot.filter add a check for media_or_ad in the object and the filtering will work just fine
