### ISSUE TITLE
message users by User_ID

### ISSUE THREAD

**Issue by lukasz00500** [ohld/igbot#623]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

**i Have list of users id and i want to send them a message, but there is no support to do that in bot because it support sending messages by usernames not user_id

**Comment by lukasz00500** [comment]
nevermind this already exist, sorry

**Comment by kintaro1981** [comment]
use the function `get_username_from_user_id`
