### ISSUE TITLE
how can I check if a media is video or photo?

### ISSUE THREAD

**Issue by kintaro1981** [ohld/igbot#628]
### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

How to check if a media is a video or photo?
It happens that in case of reposting the script don't report any error but the repost is not done.
this happens because media selected is a video.

**Comment by doctornuclear** [comment]
You could try:
```

self.media_info(media_id)
self.last_json['items'][0]['media_type'] 

```
this returns 1 for photo and 2 for video
