### ISSUE TITLE
Warning Connection

### ISSUE THREAD

**Issue by Sirman13** [ohld/igbot#637]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:
Python 3.7.0

Code:

```python
# Example code that will produce the error reported
from instabot import Bot

bot = Bot()
bot.login(username="user", password="pass")
followers = bot.get_user_followers(bot.user_id)
```

Error/Debug Log:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: integer division or modulo by zero
```

---

### Describe your issue
I have this error many time and bot stop work
![cattura](https://user-images.githubusercontent.com/42942739/45144042-42a75d00-b1bd-11e8-9a40-079a11fdb9ad.PNG)

**Comment by prakovec** [comment]
I have this error too :(

**Comment by ademaro** [comment]
This happens if the connection to the Internet is not stable...

**Comment by prakovec** [comment]
internet is stable:
![image](https://user-images.githubusercontent.com/10186513/45221830-5b963800-b2bb-11e8-8e2e-69cb0dbd29dd.png)

**Comment by prakovec** [comment]
@ademaro , We can pause when this exception occurs? 

So how is this done here? :
```python
...
try:
                    pbar.update(len(last_json["users"]))
                    for item in last_json["users"]:
                        result.append(item)
                        sleep_track += 1
                        if sleep_track >= 20000:
                            sleep_time = uniform(120, 180)
                            msg = "\nWaiting {:.2f} min. due to too many requests."
                            print(msg.format(sleep_time / 60))
                            time.sleep(sleep_time)
                            sleep_track = 0
                    if not last_json["users"] or len(result) >= total:
                        return result[:total]
                except Exception:
                    return result[:total]
...
```

**Comment by prakovec** [comment]
My error is:
```2018-09-07 16:29:03,267 HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/feed/user/xxxxxxxxx/?max_id=&min_timestamp=None&rank_token=8244695533_f6788d08-f5e5-43a5-82bb-d1c10796b8f8&ranked_content=true (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0394C490>: Failed to establish a new connection: [WinError 10060] Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера'))```

**Comment by ademaro** [comment]
@prakovec if you ping this host (i.instagram.com) — all okay? 
When I have a connection breaks, I get the same error. To handle the error, you can use something like this:
```python
try:
    ...request...
except requests.exceptions.ConnectionError as e:
    bot.logger.info("No response")
```

**Comment by prakovec** [comment]
@ademaro 
![ping](https://user-images.githubusercontent.com/10186513/45320757-3409ce80-b54c-11e8-89a7-c7a630486a00.PNG)
ping is okay

**Comment by alessiofx** [comment]
I have some problem, but only when unfollow
