### ISSUE TITLE
Feedback required-follow_user_following.py (Request turn 400 error)

### ISSUE THREAD

**Issue by oguzhankarabulut** [ohld/igbot#650]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [ x] Updated to the latest version
- [ x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [ x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:
Python 2.7.12
Code:

```python
# Example code that will produce the error reported
import argparse
import os
import sys

sys.path.append(os.path.join(sys.path[0], '../'))
from instabot import Bot

parser = argparse.ArgumentParser(add_help=True)
parser.add_argument('-u', type=str, help="username")
parser.add_argument('-p', type=str, help="password")
parser.add_argument('-proxy', type=str, help="proxy")
parser.add_argument('users', type=str, nargs='+', help='users')
args = parser.parse_args()

bot = Bot(max_follows_per_day=2000, filter_business_accounts=False, max_followers_to_follow=750000, min_followers_to_follow=10000, max_followers_to_following_ratio=750000, max_following_to_followers_ratio=2, max_following_to_follow=100000, filter_verified_accounts=False)
bot.login(username=args.u, password=args.p,
          proxy=args.proxy)

for username in args.users:
    bot.follow_following(username)
```

Error/Debug Log:

- ERROR - Request returns 400 error!
2018-09-20 09:31:43,328 - INFO - Instagram's error message: feedback_required
---
`
Describe your issue

I am running to follow_user_following.py example for the follow someone followings. I added some parametres to bot you can see in in the code. I want to follow 2000 users in a day but bot follows 400-450 people after that this value it startes unfollow somebodys and my account following count decreased and reach 260-310 after that this count starts again increase and than start again decrease like a loop. How can i solve this problem?

**Comment by ikbenignace** [comment]
There is a max to follow 1000 users a day, if your bot follows too fast, instagram will block you, if you want to get the best setting, you need to set the cooldown time on following to 80 seconds. This means it wil follow 45 people per hour, so 1080 per day. This setting will help you to not get banned or blocked.
The 'error' you get, will say you account is blocked for following people.

**Comment by oguzhankarabulut** [comment]
@ikbenignace thanks a lot!

**Comment by chicco785** [comment]
@iamjagjeetubhi how to set cooldown time?

thx

**Comment by oguzhankarabulut** [comment]
@chicco785 if you read the documents you will see how can you set it. I am giving hint now "follow_delay" :)
