### ISSUE TITLE
Is there a gender filter?

### ISSUE THREAD

**Issue by barMperez** [ohld/igbot#653]
Is there a method that can filter the gender of the user?

**Comment by tayfunyasar** [comment]
Twitter API doesn't provide gender data.

You would need some kind of AI to determine it :)

**Comment by barMperez** [comment]
And instagram is?

**Comment by Olcaey** [comment]
I believe @tayfunyasar mentioned about instagram and yes, as far as I see there is no gender information in instagram API.
However, there are some instagram bot services provide this option as a filter. So, it would be interesting to know how they are able to operate this filter.
