### ISSUE TITLE
How do you know if your proxy is working?

### ISSUE THREAD

**Issue by That-Guyy** [ohld/igbot#655]
### Before submitting an issue, make sure you have:
- [ X] Updated to the latest version
- [X ] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [X ] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [X ] Question
- [ ] Other

---

### Describe your issue

I put my proxy into ultimate.py in ultimate_schedule but I don't know how to confirm that it is working. It logs in successfully but does not say anything about the proxy.  I tried entering false proxy information to see if I would get an error but it just logged in all the same. 

How do you know if it's using the proxy or just reverted to your IP? 

Edit: After deleting the cookie I got an error from false proxy information. This is better but is there any way to confirm in the logs that its using the proxy for peace of mind?

**Comment by Olcaey** [comment]
For me, I check it by looking at cookie.txt file. In that file, you can see that IP address that bot uses to log in. If you entered your wrong proxy info when this file was already generated, it still will log in the same information. However, try removing cookie file and logging in again to see if bot logs in with wrong proxy information. If it logs in, check new generated cookie file to see if there is your local IP or proxy IP.

Let us know here as well whether this recommendations works...
