### ISSUE TITLE
'NoneType' object has no attribute 'status_code'

### ISSUE THREAD

**Issue by brain-wash** [ohld/igbot#662]
### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

When I try to run Autopost on python 3 I get following error message: 
INFO - Photo does not have a compatible photo aspect ratio.
'NoneType' object has no attribute 'status_code'

The aspect ratio of the image is 4x5 (1279x1600) which shouldn't be a problem. It used to work just fine, but for the last two days I always get this message and it won't post an image. What could be the problem here?

**Comment by ademaro** [comment]
https://faq.buffer.com/article/951-publish-instagram-image-aspect-ratios
@brain-wash The width of your picture is less by 1 pixel. For such an image height, you need a minimum of 1280 pixels in width.
