### ISSUE TITLE
question about the bot

### ISSUE THREAD

**Issue by mrbahadou** [ohld/igbot#665]
hello 
first thanks for the greatest bot ever
my question is how many instagram account i can oppen with the bot

**Comment by ademaro** [comment]
@mrbahadou How many connect profiles - so much work and will. You just need to connect with a proxy server, if there are a lot of profiles ...

**Comment by mrbahadou** [comment]
I have now 5 connected accounts
And i want to add about 2-3 accounts should i need a proxy !

**Comment by felipexmitz** [comment]
@mrbahadou Did you create a proxy?

**Comment by felipexmitz** [comment]
@ademaro Do you know how to create a proxy server?

**Comment by felipessz** [comment]
@ademaro Do you have an example?
