### ISSUE TITLE
Multi login

### ISSUE THREAD

**Issue by skk71** [ohld/igbot#666]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [X] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

---

Hi,
is it possible to login to more accounts then one in one script?
Example, i login to 5 accounts in multi_script and like with one command a hashtag with all accounts.

Thanks!

**Comment by ademaro** [comment]
@skk71 You yourself will have to make the implementation of such a functional. Bot is capable of this.

**Comment by skk71** [comment]
Can someone help me?
I just want to login from file (like accounts.txt)

> import argparse
> import os
> import sys
> 
> users = "userstofollow.txt"
> accounts = "accounts.txt"
> 
> sys.path.append(os.path.join(sys.path[0], '../'))
> from instabot import Bot
> 
> 
> bot = Bot(filter_users=True)
> users_to_follow = bot.read_list_from_file(userstofollow)
> if not users_to_follow:
>     exit()
> else:
>     print("Found %d users in file." % len(users_to_follow))
> 
> 
> bot.follow_users(users_to_follow)
> 

THANK YOU!

**Comment by jeffbruchado** [comment]
Did you figure out how to do this? If you discovered you could share here with the community?
Thanks

**Comment by skk71** [comment]
no sorry ..

**Comment by oguzhankarabulut** [comment]
hahahaha
