### ISSUE TITLE
max_follows_per_day changed, but not taken into account when running the script

### ISSUE THREAD

**Issue by kalafun** [ohld/igbot#681]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue

When I change the constant in the Bot class, e.g.: **max_follows_per_day** to 1000 even though I restart terminal and the computer, it always follows only 351 users. Am I missing something? Thank you

**Comment by TiasTias** [comment]
I was also experiencing this and when I rebuilt and reinstalled my bot won't run at all because of KeyError: 'items'

**Comment by kalafun** [comment]
So I guess the thing is, all the classes there are examples, I have changed one or two example codes and now I am Instantiating the Bot class with a max_folllows_per_day parameter set to 1000 and it works :)

**Comment by djtroi** [comment]
Could you explain  / post the code please, how did you get it to work? I have the same issue

**Comment by TiasTias** [comment]
I also had this issue and I believe it's because the compiled code is not being updated only in your source. Running the code in a virtual environment seems to work for me. Otherwise try the recommendation posted here... https://github.com/instagrambot/instabot/issues/687
