### ISSUE TITLE
Randomize like_delay

### ISSUE THREAD

**Issue by oguzhankarabulut** [ohld/igbot#698]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x ] Updated to the latest version
- [x ] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [ x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ x] Question
- [ ] Other

---

### Describe your issue

Hi guys, i want to set like_delay randomize i can select random like_delay with python "random" library but i want to set like_delay from like to like not just when starting bot. I want to select random like_delay from list like [45, 12, 96, 130, 190..] per like to like it means if bot like one photo 96 second it should like next photo in example 190 second later. Do u have any idea about this situation?

**Comment by MIKSby** [comment]
````
import random

delay = random.choice([45, 12, 96, 130, 190])
````

**Comment by oguzhankarabulut** [comment]
@MIKSby thank you for your reply but,
i did like it but i think this method start bot with random like delay for once so bot will like photos same like delay until i will stop the bot and start again. I want to chance like delay like to like in one process.
