### ISSUE TITLE
Get user medias key error

### ISSUE THREAD

**Issue by Oyetomi** [ohld/igbot#703]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [ ] Updated to the latest version
- [ ] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [ ] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here: python 3.5

Code:

```medias = bot.get_user_medias((get_random(random_user_file)), filtration=False)
    if len(medias):
        likers = bot.get_media_likers(medias[0])
        for liker in tqdm(likers):
            bot.like_user(liker, amount=2)
            bot.follow(liker)
```

Error/Debug Log:

```File "/usr/local/lib/python3.5/dist-packages/instabot/bot/bot_get.py", line 55, in get_user_medias
    return self.filter_medias(self.api.last_json["items"], filtration, is_comment=is_comment)
KeyError: 'items'
```

---

### Describe your issue

I keep getting this error at intervals , even with schedule the script fails

**Comment by Oyetomi** [comment]
@sudoguy @basnijholt @ohld

**Comment by oguzhankarabulut** [comment]
#686
