### ISSUE TITLE
follow after a certain number of follower

### ISSUE THREAD

**Issue by nvirin** [ohld/igbot#704]
Hello, 
The context: I want to follow followers of Mr X. He has 1000 followers.
I want the script start following from the 500 th  follower. (the script now start following from the first follower)

Is it possible?

**Comment by oguzhankarabulut** [comment]
yes possible

**Comment by nvirin** [comment]
Can you explain me how please?

**Comment by oguzhankarabulut** [comment]
a = bot.get_user_followers(mr X)
for x in range (500, len(a))
    bot.follow(a[x])
