### ISSUE TITLE
A lot of 404 Errors

### ISSUE THREAD

**Issue by TiasTias** [ohld/igbot#706]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here: Python 2.7.10

Error/Debug Log:

<img width="348" alt="screenshot 2018-11-14 at 10 27 28" src="https://user-images.githubusercontent.com/43808248/48473191-4af0c980-e7f8-11e8-9cfe-e5bad5636194.png">

---

### Describe your issue

I am getting a lot of 404 errors but the code seems to be still working. I have found two other bug reports of this but no answers yet! What does this mean and what can be done to fix it?!

**Comment by djtroi** [comment]
Which script do you have running?

**Comment by TiasTias** [comment]
```python
# -*- coding: utf-8 -*-

from glob import glob
import os
import sys
import threading
import time

sys.path.append(os.path.join(sys.path[0], '../../'))
import schedule
from instabot import Bot, utils

import config

from random import randint
from random import sample
from tqdm import tqdm

bot = Bot(comments_file=config.COMMENTS_FILE,
          blacklist_file=config.BLACKLIST_FILE,
          whitelist_file=config.WHITELIST_FILE,
          friends_file=config.FRIENDS_FILE,
          skipped_file=config.SKIPPED_FILE)
bot.login()
bot.logger.info("ULTIMATE script. Safe to run 24/7!")

random_user_file = utils.file(config.USERS_FILE)
random_hashtag_file = utils.file(config.HASHTAGS_FILE)
photo_captions_file = utils.file(config.PHOTO_CAPTIONS_FILE)
posted_pic_list = utils.file(config.POSTED_PICS_FILE).list

pics = sorted([os.path.basename(x) for x in
               glob(config.PICS_PATH + "/*.jpg")])		 
			   
def stats():
    bot.save_user_stats(bot.user_id)


def like_hashtags():
    amount=randint(20, 80)
    bot.like_hashtag(random_hashtag_file.random(), amount)
    

def like_timeline():
    bot.like_timeline(amount=randint(13, 47))


def follow_followers():
    bot.follow_followers("thisistias", nfollows=randint(15, 35))


def unfollow_non_followers():
    bot.unfollow_non_followers(n_to_unfollows=randint(400, 500))


def unfollow_all():
    bot.unfollow_everyone()


def like_location_feed():
    bot.api.search_location("Berlin, Germany")
    finded_location = bot.api.last_json['items'][0]
    amount=randint(20, 80)
    counter = 0
    max_id = ''
    with tqdm(total=amount) as pbar:
        while counter < amount:
            if bot.api.get_location_feed(finded_location['location']['pk'], max_id=max_id):
                location_feed = bot.api.last_json
                for media in bot.filter_medias(location_feed["items"][:amount], quiet=True):
                    if bot.like(media):
                        counter += 1
                        pbar.update(1)
                if location_feed.get('next_max_id'):
                    max_id = location_feed['next_max_id']
                else:
                    return False


def put_non_followers_on_blacklist():  # put non followers on blacklist
    try:
        bot.logger.info("Creating non-followers list")
        followings = set(bot.following)
        followers = set(bot.followers)
        friends = bot.friends_file.set  # same whitelist (just user ids)
        non_followers = followings - followers - friends
        for user_id in non_followers:
            bot.blacklist_file.append(user_id, allow_duplicates=False)
        bot.logger.info("Done.")
    except Exception as e:
        bot.logger.error("Couldn't update blacklist")
        bot.logger.error(str(e))


def run_threaded(job_fn):
    job_thread = threading.Thread(target=job_fn)
    job_thread.start()

def like_and_follow_last_user_media_likers():
    x = randint(200, 300)
    # Select one username from username_database
    #for username in random_user_file.random():
    username = random_user_file.random()
    bot.logger.info("Going to like and follow recent post likers of {}.".format(username))
    medias = bot.get_user_medias(username, filtration=False) # if this fails then it gets my recent media
    if len(medias):
        likers = set(bot.get_media_likers(medias[0]))
        # likers = likers - myfollowers - myfollowing - skipped - blacklist
        followings = set(bot.following)
        followers = set(bot.followers)
        blacklist = bot.blacklist_file.set
        skipped = bot.skipped_file.set
        likers = likers - followers - followings - blacklist - skipped
        likers = sample(likers, x)
        for liker in tqdm(likers):
            bot.like_user(liker, amount=2)
            bot.follow(liker)

			
# def comment_hashtag():
#     hashtag = random_hashtag_file.random()
#     bot.logger.info("Commenting on hashtag: " + hashtag)
#     bot.comment_hashtag(hashtag)

# def comment_medias():
#     bot.comment_medias(bot.get_timeline_medias())


schedule.every(1).hour.do(run_threaded, stats) 

schedule.every().day.at("9:00").do(run_threaded, like_hashtags) 
schedule.every().day.at("10:00").do(run_threaded, like_location_feed) 
schedule.every().day.at("11:00").do(run_threaded, like_hashtags) 
schedule.every().day.at("12:00").do(run_threaded, like_and_follow_last_user_media_likers) 
schedule.every().day.at("13:00").do(run_threaded, like_location_feed)               
schedule.every().day.at("14:00").do(run_threaded, like_and_follow_last_user_media_likers) 
schedule.every().day.at("15:00").do(run_threaded, like_hashtags)   
schedule.every().day.at("17:39").do(run_threaded, like_and_follow_last_user_media_likers) 
schedule.every().day.at("1:00").do(run_threaded, like_location_feed)       
schedule.every().day.at("18:00").do(run_threaded, like_and_follow_last_user_media_likers)  
schedule.every().day.at("19:00").do(run_threaded, like_and_follow_last_user_media_likers)  
schedule.every().day.at("20:00").do(run_threaded, like_and_follow_last_user_media_likers)
schedule.every().day.at("21:00").do(run_threaded, like_hashtags) 
schedule.every().day.at("22:00").do(run_threaded, like_location_feed)     
schedule.every().day.at("23:00").do(run_threaded, like_hashtags)         

schedule.every().day.at("1:00").do(run_threaded, put_non_followers_on_blacklist)
schedule.every().day.at("03:00").do(run_threaded, unfollow_non_followers)
schedule.every().sunday.at("06:00").do(run_threaded, follow_followers)


while True:
    schedule.run_pending()
    time.sleep(1)

```

**Comment by djtroi** [comment]
I get this Problem when I Change the attributes for the follow and like amount. so practically I get 350 follows without 404 error and the others with error (but it still works).

I don't know what causes this Problem, sorry

**Comment by TiasTias** [comment]
Would be nice if we could get a solution to this!

**Comment by ldrolez** [comment]
I get this error after an unfollow

**Comment by ldrolez** [comment]
Ok I added some debug in api.py, and found that it was caused by a non existing user in whitelist.txt

**Comment by myflashflow** [comment]
> Ok I added some debug in api.py, and found that it was caused by a non existing user in whitelist.txt

Very helpful, thank you! I had the same error and solved it removing the while list :D

**Comment by TiasTias** [comment]
I checked my whitelist.txt and all the users there exist. Could it be a user in the blacklist?

**Comment by TiasTias** [comment]
2019-01-23 10:12:16,464 - INFO - Going to like and follow recent post likers of robbiel1.

`bot.following` is empty, will download.
Getting followings of 7631727420: 2814it [00:04, 648.31it/s]                                              

`bot.followers` is empty, will download.
Getting followers of 7631727420: 4250it [00:08, 512.74it/s]                                               
  0%|                                                                             | 0/211 [00:00<?, ?it/s]2019-01-23 10:12:44,669 - ERROR - Request returns 404 error!

USER_NAME: djuna4, FOLLOWER: 150, FOLLOWING: 326

info: account is PRIVATE, skipping! 
Adding '302102043' to `skipped.txt`.

 ===> Going to follow `user_id`: 302102043.
2019-01-23 10:12:48,780 - ERROR - Request returns 404 error!

USER_NAME: djuna4, FOLLOWER: 150, FOLLOWING: 326

info: account is PRIVATE, skipping! 
Adding '302102043' to `skipped.txt`.
'302102043' already in `skipped.txt`.
  0%|▎                                                                    | 1/211 [00:16<59:05, 16.88s/it]2019-01-23 10:12:51,211 - ERROR - Request returns 404 error!

USER_NAME: stellaamargot, FOLLOWER: 24, FOLLOWING: 32
2019-01-23 10:12:52,042 - INFO - Liking user_8893302987's feed:
2019-01-23 10:12:52,851 - INFO - Received 4 medias.
2019-01-23 10:12:52,851 - INFO - After filtration 0 medias left.
2019-01-23 10:12:52,851 - INFO - None medias received: account is closed or medias have been filtered.

 ===> Going to follow `user_id`: 8893302987.
2019-01-23 10:12:54,120 - ERROR - Request returns 404 error!

USER_NAME: stellaamargot, FOLLOWER: 24, FOLLOWING: 32

===> FOLLOWED <==== `user_id`: 8893302987.
Adding '8893302987' to `followed.txt`.
  1%|▋                                                                    | 2/211 [00:22<47:29, 13.63s/it]2019-01-23 10:12:58,185 - ERROR - Request returns 404 error!

USER_NAME: delphoe, FOLLOWER: 170, FOLLOWING: 601

following_count / follower_count > bot.max_following_to_followers_ratio, skipping!
Adding '29290609' to `skipped.txt`.

 ===> Going to follow `user_id`: 29290609.
2019-01-23 10:13:00,614 - ERROR - Request returns 404 error!

USER_NAME: delphoe, FOLLOWER: 170, FOLLOWING: 601

following_count / follower_count > bot.max_following_to_followers_ratio, skipping!
Adding '29290609' to `skipped.txt`.
'29290609' already in `skipped.txt`.
  1%|▉                                                                    | 3/211 [00:28<39:02, 11.26s/it]2019-01-23 10:13:04,126 - ERROR - Request returns 404 error!

USER_NAME: the_nrthrn_lights, FOLLOWER: 1500, FOLLOWING: 3806

following_count > bot.max_following_to_follow, skipping!
Adding '212637364' to `skipped.txt`.

 ===> Going to follow `user_id`: 212637364.
2019-01-23 10:13:06,928 - ERROR - Request returns 404 error!

USER_NAME: the_nrthrn_lights, FOLLOWER: 1500, FOLLOWING: 3806

following_count > bot.max_following_to_follow, skipping!
Adding '212637364' to `skipped.txt`.
'212637364' already in `skipped.txt`.
  2%|█▎                                                                   | 4/211 [00:34<33:18,  9.65s/it]2019-01-23 10:13:10,863 - ERROR - Request returns 404 error!

USER_NAME: darkergarden, FOLLOWER: 75, FOLLOWING: 88
2019-01-23 10:13:11,829 - INFO - Liking user_9146482719's feed:
2019-01-23 10:13:12,283 - INFO - Received 18 medias.
2019-01-23 10:13:12,284 - INFO - After filtration 9 medias left.
2019-01-23 10:13:12,284 - INFO - Going to like 2 medias.
                                                                                                         2019-01-23 10:13:16,099 - ERROR - Request returns 404 error!                         | 0/2 [00:00<?, ?it/s]

**Comment by TiasTias** [comment]
OHH I think I realised what I was doing wrong. In the whitelist I had put the usernames instead of the user IDs.
