### ISSUE TITLE
500 Error (even with differents accounts and proxies)

### ISSUE THREAD

**Issue by valentinpompa** [ohld/igbot#711]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [ ] Updated to the latest version
- [ ] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [ ] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [X ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here: 3.7.0

Code:

```import argparse
import os
import sys

sys.path.append(os.path.join(sys.path[0], '../'))
from instabot import Bot

parser = argparse.ArgumentParser(add_help=True)
parser.add_argument('-u', type=str, help="username")
parser.add_argument('-p', type=str, help="password")
parser.add_argument('-proxy', type=str, help="proxy")
args = parser.parse_args()

bot = Bot(filter_users=False, like_delay=200, max_likes_to_like=80)
bot.login(username=args.u, password=args.p, proxy="")

users_to_like = bot.read_list_from_file("1_like_user_list.txt")
if not users_to_like:
    exit()
else:
	print("Found %d users in file." % len(users_to_like))

bot.like_users(users_to_like, nlikes=2)
```

Error/Debug Log:

```
ERROR - Request returns 500 error
```

---

### 

I don't know if this new "500 Error" (new for me, and I working with this more than 3 months) is because the new changes of Instagram to attack the fake accounts for selling followers.

Is somebody also with this same issue?

**Comment by howhigh1337** [comment]
There is an issue with API on their end, you can refer here for the updates: https://developers.facebook.com/status/issues/317603295743499/
