### ISSUE TITLE
Can't comment; feedback_required

### ISSUE THREAD

**Issue by sometimescool22** [ohld/igbot#715]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

Paste the output of ``python -V`` here:

Python 3.6.7

Code:

```python
# 
import instabot.instabot.api as api

ig = api.API()
ig.login(username="username", password="password")
c = ig.comment(media_id="1921277344526644259_1067259270"), comment_text="I like tacos")
```

Error/Debug Log:

```python
The cookie is not found, but don't worry `instabot` will create it for you using your login details.
2018-11-26 21:55:07,975 - INFO - Logged-in successfully as '[username]'!
2018-11-26 21:55:07,976 - INFO - Saved cookie!
2018-11-26 21:55:08,543 - ERROR - Request returns 400 error!
2018-11-26 21:55:08,543 - INFO - Instagram's error message: feedback_required
```

### Describe your issue

I'm not able to comment on Instagram (including the web UI) after running this and commenting on other posts. I was using multiple sessions (deleting the cookie) so maybe that's why. I've tried from different IP's as well. Is my account blocked forever? If not how long do I have to wait? I've looked at other issues like this but most have went inactive. I can log in fine. The account is new (created a few days ago) and doesn't have any posts.

Thanks

**Comment by mamazary** [comment]
I have the same error as this, but only on like action, but for comment, follow, it does fine.
I though this one is feedback for giving the apps feedback, like if you are new account and just download and login to instagram apps, then it will asking you for feedback about the instagam apps, but we can't answer it since it using CLI. It's just my opinion, need to inspect the problem more depth and serching the solution.

**Comment by maxdevblock** [comment]
`feedback_required` means your action has been blocked because you exceeded API limits.
This is returned if like or comment is blocked. No error is returned when follow or unfollow are blocked.
If you get this error, stop at least 24h to let instagram unblock your action.

**Comment by zeing** [comment]
why i can use in localhost but when i pull to aws( ec2 ) it don't work 
![image](https://user-images.githubusercontent.com/20161393/57980403-6bbf0380-7a55-11e9-854a-2e6ce9221ba8.png)
