### ISSUE TITLE
Which proxy seller website do you prefer?

### ISSUE THREAD

**Issue by oguzhankarabulut** [ohld/igbot#716]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [ x] Updated to the latest version
- [x ] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [ x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

### Describe your issue

Hi guys i wanna run multiple account in one machine. Which proxy seller website do you prefer for buy?

Thanks much!

**Comment by notahooper15** [comment]
Hello @oguzhankarabulut did you ever test this out? Was wondering if you figured anything out. Thanks
