### ISSUE TITLE
Can't follow private accounts

### ISSUE THREAD

**Issue by f4depo** [ohld/igbot#719]
- [x ] Updated to the latest version
- [x ] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x ] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

---

Paste the output of ``python -V`` here:  Python 2.7.15rc1, Python 3.6.5

I've changed:

```python
 filter_users=True,
                 filter_private_users=**False**,
                 filter_users_without_profile_photo=True,
                 filter_previously_followed=False,
```
### Describe your issue

Hello all. I want to send follow request to private accounts. I've changed this code but I can't send and terminal says "info: account is PRIVATE, skipping!".

How can I solve this problem?

**Comment by ademaro** [comment]
@Fers4t hi!
When creating a bot, you need to turn off filtering via the parameter:
```python
bot = Bot(filter_users=False)
[your code]
```
