### ISSUE TITLE
Make ultimate_schedule Bot behave more naturally (rest at night / work on day)

### ISSUE THREAD

**Issue by sebastian-muthwill** [ohld/igbot#720]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x ] Updated to the latest version
- [ x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [ x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Describe your issue (feature request)
On running the bot with ultimate_schedule 24/7 it would be good to let the bot act more "naturally" (like a human). Therefore it is necessary to prevent the bot from working during night times. 

I overcome this with my own function where i check if it is nighttime and let the bot skip the execution of a task, which usually would run every e.g. 2h, during night time. 

function in ultimate_schedule/tools.py:
(it is currently only working with a 24h setup and musst be adapted to 12 h systems)
```
from datetime import datetime

def is_nighttime():
    # returnes true if nighttime (between 22:00 and 07:00)
    TIME_HOUR = int(datetime.now().strftime('%H'))
    if TIME_HOUR >= 22 or TIME_HOUR < 7:
        return True
    print("It´s nighttime! Bot will skipp this task.")
    return False
```

and within ultimate_schedule/ultimate.py I add:
```
def like_timeline():
    #CHANGE: NaturalBot
    if tools.is_nighttime():
        exit(0)
    bot.like_timeline(amount=30)
```

Suggestion:
It would be good to have the function is_nighttime() available within bot.utils and times configurable thru configuration.

**Comment by EightShift** [comment]
I did this one:

`import datetime`

```
def follow_users_from_hastag_file(): #Following 06:00 - 02:00
	current_time = datetime.datetime.now().strftime("%H:%M")
	if current_time >= "05:59" and current_time <= "23:59" or current_time >= "00:00" and current_time <= "01:59":		
	
		bot.follow_users(bot.get_hashtag_users(random_hashtag_file.random()))
	
	else:
		print ("I don't want to follow. I'm sleeping...")
```

`schedule.every(5).to(15).minutes.do(run_threaded, follow_users_from_hastag_file)`
