### ISSUE TITLE
like_user not working

### ISSUE THREAD

**Issue by tobeyond** [ohld/igbot#723]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Code:

```python

bot = instabot.Bot(filter_users=False, filter_verified_accounts=False, min_likes_to_like=0, filter_private_users=False, min_media_count_to_follow=0, filter_business_accounts=False, follow_delay=30)
bot.like_user(USER, amount=AMOUNT, filtration=False)
```

Error/Debug Log:

```python
2018-12-16 20:08:33,361 - INFO - Going to like 1 medias.
2018-12-16 20:08:33,361 INFO Going to like 1 medias.
100%|█████████████████████████████████████████████████████████████████████████████████| 1/1 [00:12<00:00, 12.29s/it]
2018-12-16 20:08:45,659 - INFO - DONE: Total liked 0 medias.
2018-12-16 20:08:45,659 INFO DONE: Total liked 0 medias.
```

---

### Describe your issue

I'm using the latest version available with pip.
I tried to prevent everything from filtering the profile/media to like but still it's not working.
It lists the medias to like but it doesn't do it. Any ideia to fix it?

Also this double info is kind of bothering me. Does anyone know how to stop it?

Thanks

**Comment by smolyakov26** [comment]
same here ) no idea looking for solution

**Comment by tobeyond** [comment]
I found out the min_likes_to_like=0 is not working.
After the medias have at least 1 like, it works after all.

**Comment by ohld** [comment]
Mass liking works here: 

https://github.com/instagrambot/web
