### ISSUE TITLE
Screen killed on SSH

### ISSUE THREAD

**Issue by tobeyond** [ohld/igbot#725]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here: 
Python 3.6.8rc1 on Debian 9 SSH

---

### Describe your issue

So I'm using a SHH VM to have the code working 24/7.
I'm using SCREEN to detach them.
When I come back to check it out (screen -r), either it was killed (literally there is killed written and the code was stopped) or it is just frozen (apparently it's working but if you wait to see, nothing has been happening for hours).
When I leave others scripts running (using selenium, for example), it doesn't happen.
Also, if I leave several screens in one SHH, it stops it, saying I'm mining cryptocurrency. 
Any idea of what is happening?

**Comment by kifirkin** [comment]
I guess there is a problem with your environment.
I’m successfully using screen to run instabot through ssh.
