### ISSUE TITLE
error 403 404 on any script

### ISSUE THREAD

**Issue by postaspat62** [ohld/igbot#727]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here: Python 3.7.1

Error/Debug Log:

 ===> Start unfollowing non-followers <===

`bot.following` is empty, will download.
2018-12-25 09:27:44,303 - ERROR - Request returns 403 error!

`bot.followers` is empty, will download.
2018-12-25 09:27:44,461 - ERROR - Request returns 403 error!
0it [00:00, ?it/s]

 ===> Unfollow non-followers done! <===
2018-12-25 09:27:44,668 - INFO - Bot stopped. Worked: 0:22:09.433930
2018-12-25 09:27:44,668 - INFO - Total requests: 3282

follow_user_followers script:
2018-12-25 10:01:13,055 - INFO - Follow followers of: *user*
2018-12-25 10:01:13,342 - ERROR - Request returns 403 error!
2018-12-25 10:01:14,398 - ERROR - Request returns 404 error!
2018-12-25 10:01:14,399 - INFO - *user* not found / closed / has no followers.
2018-12-25 10:01:14,569 - INFO - Bot stopped. Worked: 0:55:39.334866
2018-12-25 10:01:14,570 - INFO - Total requests: 3286
---

### Describe your issue

I am using the original unfollow_non_followers script, I did not make any changes to the code. It used to work, but suddenly I got the error above. Can anyone help me fixing it?  p.s.: I tried running many other scripts and get the same error.

**Comment by lenivyi** [comment]
> ## Please follow the guide below
> * Issues submitted without this template format will be **ignored**.
> * You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
> * Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
> * Use the _Preview_ tab to see how your issue will actually look like.
> 
> ### Before submitting an issue, make sure you have:
> * [x]  Updated to the latest version
> * [x]  Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
> * [x]  [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones
> 
> ### Purpose of your issue?
> * [x]  Bug report (encountered problems/errors)
> * [ ]  Feature request (request for a new functionality)
> * [ ]  Question
> * [ ]  Other
> 
> ### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.
> ### For a _bug report_, you **must** include the Python version used, _code_ that will reproduce the error, and the _error log/traceback_.
> Paste the output of `python -V` here: Python 3.7.1
> 
> Error/Debug Log:
> 
> ===> Start unfollowing non-followers <===
> 
> `bot.following` is empty, will download.
> 2018-12-25 09:27:44,303 - ERROR - Request returns 403 error!
> 
> `bot.followers` is empty, will download.
> 2018-12-25 09:27:44,461 - ERROR - Request returns 403 error!
> 0it [00:00, ?it/s]
> 
> ===> Unfollow non-followers done! <===
> 2018-12-25 09:27:44,668 - INFO - Bot stopped. Worked: 0:22:09.433930
> 2018-12-25 09:27:44,668 - INFO - Total requests: 3282
> 
> ## follow_user_followers script:
> 2018-12-25 10:01:13,055 - INFO - Follow followers of: _user_
> 2018-12-25 10:01:13,342 - ERROR - Request returns 403 error!
> 2018-12-25 10:01:14,398 - ERROR - Request returns 404 error!
> 2018-12-25 10:01:14,399 - INFO - _user_ not found / closed / has no followers.
> 2018-12-25 10:01:14,569 - INFO - Bot stopped. Worked: 0:55:39.334866
> 2018-12-25 10:01:14,570 - INFO - Total requests: 3286
> ### Describe your issue
> I am using the original unfollow_non_followers script, I did not make any changes to the code. It used to work, but suddenly I got the error above. Can anyone help me fixing it? p.s.: I tried running many other scripts and get the same error.

Just remove file "cookie.txt" and run the script again, bro.

**Comment by postaspat62** [comment]
It's working now, thanks a lot.
