### ISSUE TITLE
How to save my session ?

### ISSUE THREAD

**Issue by deounix** [ohld/igbot#728]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x ] Updated to the latest version
- [x ] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x ] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

---

### Describe your issue

How to save my session to re use it again with out re-login !

(uuid, device_id, cookies, csrf ...etc)

**Comment by ademaro** [comment]
Hi! If the login is successful, the default information is added to the `cookie.txt` file. On the next login attempt, the bot will look at this file and use it if the login matches the one that is stored in the file.

**Comment by ayush3298** [comment]
You can picle the bot, I haven't tried it but should work
