### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by alblz** [ohld/igbot#729]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

Code:

```python
# Example code that will produce the error reported
from instabot import Bot

bot = Bot()
bot.login(username="user", password="pass")
followers = bot.get_user_followers(bot.user_id)
```

Error/Debug Log:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: integer division or modulo by zero
```

---

### Describe your issue
Like_user_following.py no working.Any idea??

2018-12-28 23:55:54,279 - INFO - Logged-in successfully as 'mr.albrech' using the cookie!
2018-12-28 23:55:54,280 - INFO - Like following of: nacho.
2018-12-28 23:55:54,488 - ERROR - Request returns 403 error!
2018-12-28 23:55:55,326 - ERROR - Request returns 404 error!
2018-12-28 23:55:55,326 - INFO - nacho not found / closed / has no following.
2018-12-28 23:55:55,467 - INFO - Bot stopped. Worked: 1:43:43.432013
2018-12-28 23:55:55,468 - INFO - Total requests: 122454

**Comment by lenivyi** [comment]
just remove your "cookie.txt" and run again
