### ISSUE TITLE
Logging error when liking users from file.

### ISSUE THREAD

**Issue by penarubah** [ohld/igbot#73]
updated instabot and try run like users from file and show logging error.
run this script by: `python penarubah_like_3_media_from_file.py user_to_like.txt`

the code is:
``` python
import sys
import os

sys.path.append(os.path.join(sys.path[0],'../'))
from instabot import Bot

users_list = "users_to_like.txt"

bot = Bot()
users_to_like = bot.read_list_from_file(users_list)
if not users_list:
    exit()
bot.login()
print ("session 1")
bot.like_users(users_to_like, nlikes=1)
print ("session 2")
bot.like_users(users_to_like, nlikes=1)
print ("session 3")
bot.like_users(users_to_like, nlikes=1)
bot.logout()
``` 

i atttach file, and screenshoot
[users_to_like.txt](https://github.com/ohld/instabot/files/800758/users_to_like.txt)
![screenshot_8](https://cloud.githubusercontent.com/assets/25403367/23325730/26385656-fb2a-11e6-9718-9c0f3981c3c2.png)

**Comment by ohld** [comment]
fixed
