### ISSUE TITLE
2FA solutions/options? 

### ISSUE THREAD

**Issue by kapsolas** [ohld/igbot#730]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [ x] Updated to the latest version
- [ x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [ x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

Two factor authentication approaches:
* **Disable 2FA** -  on mobile app and then sign into the bot, this is the easiest, but does require configuration changes on the device/app.
* **Cookie** - I would imagine that we can capture the cookie between the mobile app and the instagram service and format it (JSON) so that the instabot engine can read the cookie. This approach is an easy one because it does not require any code changes and an be done outside the bot
* **Update api.py** - The bot's login method can be updated to check the response. If it detects in the response "two_factor_required": true, then the bot can send the next request with the PIN embedded. 

The pin can be read from a text file after X seconds. 

What I was thinking was the following:
1. Send the login request as the bot does today, if it detects 2fa in place, put a sleep for 30-60 seconds
2. The user needs to populate a text file with the pin number.
3. The bot comes out of sleep, reads the text file and sends the pin

I'm not a python developer, thus it would take me quite some time to implement this, but for any experts in python here, I believe this is a pretty simple modification to make. 

The code change would be required in the area of 

  if self.send_request('accounts/login/', data, True):
                    self.is_logged_in = True
                    self.logger.info("Logged-in successfully as '{}'!".format(self.username))
                    if use_cookie:
                        self.save_cookie(cookie_fname)
                        self.logger.info("Saved cookie!")
                    return True
                else:
                    self.logger.info("Username or password is incorrect.")
                    delete_credentials()
                    return False

Anyone willing to take this modification on?

**Comment by ohld** [comment]
Feel free to code it by yourself and make a pull request.

**Comment by kapsolas** [comment]
> Feel free to code it by yourself and make a pull request.

I'm not a python developer. I'll take a stab at it at some point when I have an opportunity to sit down and learn a bit more about python.

**Comment by skareemoff** [comment]
I added a pull request for a workaround (https://github.com/instagrambot/instabot/pull/857)
When starting the bot it will ask for the code with a prompt and then login using that code and continue the rest of the execution.
This is not proper solution for full automation but it works. I have been using it for a couple of weeks before deciding to contribute it here.
Hope this helps.

**Comment by squelix** [comment]
2fa is still not working for me ..... I don't know why, i must disable 2FA on my Instagram account to make the bot works :/
