### ISSUE TITLE
Increase test coverage of the module

### ISSUE THREAD

**Issue by ohld** [ohld/igbot#742]
We really need to increase the test converse for instabot python module. This will definitely helps with new pull requests improvements and additions. We already test some functionallity but the coverage itself is very poor. 

Can someone help with this?
@maxdevblock?

**Comment by maxdevblock** [comment]
@ohld I see. Yes I can work on it.

**Comment by maxdevblock** [comment]
> Can someone help with this?
> @maxdevblock?

Sending now pull req for new get tests.

**Comment by ohld** [comment]
Great! Thanks!

BTW, It is a good practice to add tests to all new functionality that was added on pull requests. This will ensure that nothing old was broken. 

You are doing a great job with your pull requests and improvements! But can you also add tests for your new functionality? 

Current 37% test coverage is good but it should be bigger if we want to build a stable reliable module.

**Comment by maxdevblock** [comment]
> You are doing a great job with your pull requests and improvements! But can you also add tests for your new functionality?

YVW!!! Instagrambot is a real great job!
Yes I'm trying to gain confidence with tests, then I'll pull reqs with tests too :-)
