### ISSUE TITLE
Add Bot to auto publish on PIP

### ISSUE THREAD

**Issue by ohld** [ohld/igbot#749]
I've seen some bots on GitHub that can auto-publish master branch to PIP. I think it will be very useful for us because we always forget to do that. 

Take a look at this library: https://github.com/ccxt/ccxt
It has all the bots that we may need.

**Comment by maxdevblock** [comment]
Travis can do it
https://docs.travis-ci.com/user/deployment/pypi/

**Comment by ohld** [comment]
I've added PYPI_USERNAME and PYPI_PASSWORD to Travis-CI environment variables, so we can update travis convig to use it. Let's release a new version for every commit to master.

We need something to generate new version number and changelog text. @maxdevblock @sudoguy

**Comment by ohld** [comment]
First try failed: https://travis-ci.org/instagrambot/instabot/jobs/481490003

**Comment by maxdevblock** [comment]
I'll run some test next days on a test repo

**Comment by maxdevblock** [comment]
@ohld it says already `up to date`. Need to understand whta's checking for updating or not

**Comment by maxdevblock** [comment]
> First try failed: https://travis-ci.org/instagrambot/instabot/jobs/481490003

Maybe I got it.
In `484` says
```
HTTPError: 400 Client Error: File already exists. See https://pypi.org/help/#file-name-reuse for url: https://upload.pypi.org/legacy/
```
Looking there it says

> PyPI does not allow for a filename to be reused

It was trying to upload `instabot-0.4.5.tar.gz` but this `name-version.tar.gz` is already in PyPi, so it can't upload it.
The version, and so the package name with version, should change at each push for the new master branch to get published...

**Comment by ohld** [comment]
@sudoguy Waiting for the PIP autopost, guys from our telegram chat going bananas on bugs ....
