### ISSUE TITLE
Why I can't use .reply_to_comments

### ISSUE THREAD

**Issue by WalrusPUNCH** [ohld/igbot#767]
- [ ] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [+ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

Code:

```python
# Example code that will produce the error reported
from instabot import Bot

bot = Bot()
bot.reply_to_comments()
```

Error/Debug Log:

```python
AttributeError: 'Bot' object has no attribute 'reply_to_comments'
```

---

### Describe your issue

I can't use bot.reply_to_comments() function. Help please

**Comment by ohld** [comment]
have you updated the instabot? 
```
pip install -U instabot
```
