### ISSUE TITLE
How I can leave more than 1 comment under post?

### ISSUE THREAD

**Issue by WalrusPUNCH** [ohld/igbot#768]
How I can leave more than 1 comment under post?

**Comment by skynextindia** [comment]
walrus help me to setup bot

**Comment by WalrusPUNCH** [comment]
How I can help you?
Write me here: lamborghini43346@gmail.com

**Comment by ayush3298** [comment]
Bot.comment(media_id, '' cmnt")
Bot.comment(media_id, '' cmnt") 

Write it as many times as you want to comment on single media id

**Comment by WalrusPUNCH** [comment]
> Bot.comment(media_id, '' cmnt")
> Bot.comment(media_id, '' cmnt")
> 
> Write it as many times as you want to comment on single media id

This method doesn't work. I think because  use bot.comment()  works as:

**Comment by WalrusPUNCH** [comment]
def comment(self, media_id, comment_text):
    if self.is_commented(media_id):
        return True
So, first this methon checks is the post already commented because of code on the top. How I can change this thing?

**Comment by ayush3298** [comment]
Head to filter.py and change the file as you want, like you can remove the some filter code

**Comment by WalrusPUNCH** [comment]
Where I can find this file ?

**Comment by ohld** [comment]
![image](https://user-images.githubusercontent.com/5613295/52168100-956a4e00-2736-11e9-8925-95145b73d133.png)

**Comment by WalrusPUNCH** [comment]
Thanks!
