### ISSUE TITLE
cannot upload photos

### ISSUE THREAD

**Issue by roncam82** [ohld/igbot#769]
im trying to post photos on instagram and im getting:

ERROR - Couldn't upload pic
ERROR - 'NoneType' object has no attribute 'status_code'

is there a particular size I need to resize the photos ?
what is this error please ?

thanks

**Comment by roncam82** [comment]
Analizing `C:/Users/Administrator/Downloads/instabot-master/instabot-master/examples/ultimate_schedule/photos/0001-test.jpg`
No exif info found (ERR: 'NoneType' object has no attribute 'items')
FOUND w:864, h:1080, ratio=0.8
Vertical image
Saving new image w:864 h:1080 to `C:/Users/Administrator/Downloads/instabot-master/instabot-master/examples/ultimate_schedule/photos/0001-test.jpg.CONVERTED.jpg`
2019-01-21 02:55:02,992 - ERROR - Couldn't upload pic
2019-01-21 02:55:02,992 - ERROR - Unsupported format

**Comment by maxdevblock** [comment]
`git clone` to latest update

**Comment by roncam82** [comment]
Still unsupported format

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by maxdevblock** [comment]
Try examples/photos example and tell me if u got the same error

**Comment by muh-bazm** [comment]
Hi
I'm trying to upload a photo a correct format and size but I get "photo [photo-address] is not uploaded photo" error. I even tried photos in examples/photos location but it didn't work as well. Could any one please let me know how to correct this? 
Thanks
