### ISSUE TITLE
help please!! Error 405

### ISSUE THREAD

**Issue by alblz** [ohld/igbot#774]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [ ] Updated to the latest version
- [ ] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [ ] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

Code:

```python
# Example code that will produce the error reported
from instabot import Bot

bot = Bot()
bot.login(username="user", password="pass")
followers = bot.get_user_followers(bot.user_id)
```

Error/Debug Log:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: integer division or modulo by zero
```

---

### Describe your issue

Explanation of your issue goes here. Please make sure the description is worded well enough to be understood with as much context and examples as possible.

USER_NAME: dennis_prs, FOLLOWER: 1276, FOLLOWING: 470
2019-01-21 19:48:58,263 - INFO - Liking user_14789422's feed:
2019-01-21 19:48:58,582 - INFO - Received 18 medias.
2019-01-21 19:48:58,583 - INFO - After filtration 1 medias left.
2019-01-21 19:48:58,583 - INFO - Going to like 1 medias.
  0%|                                                     | 0/1 [00:00<?, ?it/s]2019-01-21 19:48:58,713 - ERROR - Request returns 405 error!

Media ID error!
^Z
[5]+  Stopped                 python3 like_user_following.py

**Comment by ohld** [comment]
@maxdevblock @sudoguy Looks very strange to me

**Comment by aferook** [comment]
I have 405 error for likes, but I do not have ZeroDivisionError.

Server returns 405 after request to https://i.instagram.com/api/v1/media/1961945502573753372/info/

**Comment by aferook** [comment]
https://github.com/instagrambot/instabot/pull/776 solves the issue for me

**Comment by alblz** [comment]
any solution to this problem?

**Comment by TiasTias** [comment]
I am also getting this now. I used to get 403 and 404 errors until I deleted my cookies.txt and retried it but now I get this: 

2019-01-22 21:56:33,157 - INFO - Logged-in successfully as 'thisistias'!
2019-01-22 21:56:33,158 - INFO - Saved cookie!
2019-01-22 21:56:33,158 - INFO - ULTIMATE script. Safe to run 24/7!
  0%|                                                                               | 0/35 [00:00<?, ?it/s]2019-01-22 22:00:04,283 - ERROR - Request returns 405 error!

Media ID error!
2019-01-22 22:00:15,644 - ERROR - Request returns 405 error!

Media ID error!
2019-01-22 22:00:26,769 - ERROR - Request returns 405 error!

.... IT GOES ON.

I was running the ultimate scheduler this function: 
schedule.every().day.at("22:00").do(run_threaded, like_location_feed)

**Comment by maxdevblock** [comment]
Uninstall `pip` installed version and `git clone` from latest update

**Comment by alblz** [comment]
thank guys!! Is working!! @maxdevblock

**Comment by MrMdR** [comment]
@maxdevblock @alblz I'm fairly new to git. Could you explain what is meant?

I've installed python and downloaded the ZIP from the project page. I run instabot trough cmd.exe
