### ISSUE TITLE
0 medias liked

### ISSUE THREAD

**Issue by imim332** [ohld/igbot#775]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)] on win32

Code:

```python
import argparse
import os
import sys
import time

sys.path.append(os.path.join(sys.path[0], '../'))
from instabot import Bot

parser = argparse.ArgumentParser(add_help=True)
parser.add_argument('-u', type=str, help="username")
parser.add_argument('-p', type=str, help="password")
parser.add_argument('-proxy', type=str, help="proxy")
args = parser.parse_args()

bot = Bot()
bot.login(username=args.u, password=args.p,
          proxy=args.proxy)

wait = 5 * 60  # in seconds

while True:
    bot.like_timeline()
time.sleep(wait)
```

Error/Debug Log:

```python
2019-01-21 20:54:35,966 - INFO - Saved cookie!
2019-01-21 20:54:35,971 - INFO - Liking user_zuck's feed:
2019-01-21 20:54:37,099 - INFO - Going to like 12 medias.
100%|██████████████████████████████████████████████████████████████████████████████████| 12/12 [02:07<00:00, 10.59s/it]
2019-01-21 20:56:44,469 - INFO - DONE: Total liked 0 medias.
2019-01-21 20:56:44,686 - INFO - Bot stopped. Worked: 0:38:40.774473
2019-01-21 20:56:44,686 - INFO - Total requests: 103
```

---

### Describe your issue
It says it's going to like 12 medias, but then none are liked.

**Comment by maxdevblock** [comment]
This is not an issue. Medias are filtered out. Set your filters in `bot = Bot()` instance and close the issue or ask for help in Telegram group.
