### ISSUE TITLE
DEVELOPERS: posting multiple photos

### ISSUE THREAD

**Issue by ppleskov** [ohld/igbot#78]
New feature of instagram:
http://www.imore.com/you-can-include-multiple-photos-instagram-post-heres-how

Any ideas on API?

**Comment by ppleskov** [comment]
`'media_type': 8,
'carousel_media'`

**Comment by ppleskov** [comment]
https://github.com/mgp25/Instagram-API/blob/master/examples/uploadAlbum.php

**Comment by ohld** [comment]
@ppleskov - can you add this to API class?

**Comment by ppleskov** [comment]
Ill try to test this method

**Comment by ohld** [comment]
Done by @sudoguy
