### ISSUE TITLE
Help! 403 Error on any script..

### ISSUE THREAD

**Issue by yantxs** [ohld/igbot#782]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

Code:

```python

from instabot import Bot

def listSeg(username, password):

	bot = Bot()
	bot.login(username=username, password=password)
	follows=bot.get_user_followers("lego")
	print (follows)```

Error/Debug Log:

```python
2019-01-22 17:42:28,186 - INFO - Instabot Started
2019-01-22 17:42:28,189 - INFO - Logged-in successfully as 'yantxs' using the cookie!
2019-01-22 17:42:28,765 - ERROR - Request returns 403 error!
2019-01-22 17:42:28,766 - WARNING - Error while getting hashtag feed.
[]
MediaID: 
```

---

### Describe your issue

I getting this error on any script of bot, i've already tried everything to fix it.
Any solutions? I need to list followers by user

**Comment by maxdevblock** [comment]
`bot.login(use_cookie=False)`

**Comment by yantxs** [comment]
> `bot.login(use_cookie=False)`

That worked, thx :heart: :heart:

**Comment by mattjones1122** [comment]
Where in the code do I add bot.login(use_cookie=False) I am new to code and I am wondering if this goes somewhere in the code or if  I add it into the command prompt? Thanks

**Comment by ohld** [comment]
@mattjones1122 Find the `bot.login()` line in the code that you are launching and change it to `bot.login(use_cookie=False)`
