### ISSUE TITLE
 like_medias_by_location / like_location_feed NOT WORKING 

### ISSUE THREAD

**Issue by TiasTias** [ohld/igbot#783]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here: Python 2.7.10

```python
def like_location_feed():
    bot.api.search_location("Berlin, Germany")
    bot.logger.info("Going to like Berlin location.")
    finded_location = bot.api.last_json['items'][0]
    amount=randint(20, 80)
    counter = 0
    max_id = ''
    with tqdm(total=amount) as pbar:
        while counter < amount:
            if bot.api.get_location_feed(finded_location['location']['pk'], max_id=max_id):
                location_feed = bot.api.last_json
                for media in bot.filter_medias(location_feed["items"][:amount], quiet=True):
                    if bot.like(media):
                        counter += 1
                        pbar.update(1)
                if location_feed.get('next_max_id'):
                    max_id = location_feed['next_max_id']
                else:
                    return False
```

Error/Debug Log:

```python
2019-01-23 17:10:28,147 - INFO - Going to like Berlin location.
  0%|                                                    | 0/24 [00:00<?, ?it/s]2019-01-23 17:10:43,537 - ERROR - Request returns 404 error!

`bot.following` is empty, will download.

USER_NAME: lc.nou, FOLLOWER: 11803, FOLLOWING: 493819.07it/s]                   

follower_count > bot.max_followers_to_follow, skipping!
Adding '1002827858' to `skipped.txt`.
2019-01-23 17:10:49,710 - ERROR - Request returns 404 error!

USER_NAME: _caterinaferrari_, FOLLOWER: 1212, FOLLOWING: 589
2019-01-23 17:10:51,304 - INFO - Liked media 1963261982014920627.
  4%|█▊                                          | 1/24 [00:23<08:52, 23.16s/it]2019-01-23 17:10:55,888 - ERROR - Request returns 404 error!

USER_NAME: berrehouma_youssef, FOLLOWER: 23717, FOLLOWING: 5665

follower_count > bot.max_followers_to_follow, skipping!
Adding '774545368' to `skipped.txt`.
'774545368' already in `skipped.txt`.

^CTraceback (most recent call last):
  File "ultimate.py", line 160, in <module>
    time.sleep(1)
KeyboardInterrupt

```

---

### Describe your issue

I think there is an issue with the underlying code. I have posted my code from my ultimate scheduler above, which is an adaptation of one of the examples like_medias_by_location.py but the problem is it just hangs without completing the full amount. 

I double checked the  like_medias_by_location.py in the examples and that also does not work. It filters through two users and then it just stops.

**Comment by maxdevblock** [comment]
Users are filtered out ans skipped. Set your filters in `bot = Bot()`

**Comment by TiasTias** [comment]
Does like_location_feed() get the TOP feed or RECENT feed? 

Shouldn't this method like_location_feed() keep running until it reaches _amount_ anyway? Rregardless how many people it has skipped/filtered out?

I have set my filters but still when I run it I get this...

2019-01-25 11:38:44,226 - INFO - Going to like Berlin location.
  0%|                                                                                             | 0/41 [00:00<?, ?it/s]2019-01-25 11:38:45,181 - INFO - Received 1 medias.
2019-01-25 11:38:45,181 - INFO - After filtration 1 medias left.

`bot.following` is empty, will download.

Already following, skipping!7420: 100%|███████████████████████████████████████████▉| 2848/2849 [00:01<00:00, 1617.58it/s]
2019-01-25 11:38:51,811 - INFO - Received 1 medias.
2019-01-25 11:38:51,812 - INFO - After filtration 1 medias left.

Already following, skipping!
2019-01-25 11:38:58,775 - INFO - Received 0 medias.
2019-01-25 11:38:58,775 - INFO - After filtration 0 medias left.

... and then it hangs.

**Comment by maxdevblock** [comment]
location_feed returns a small amount of items, just like old instagram app did.
If you want to find more you have to loop through all found locations.

**Comment by TiasTias** [comment]
Can this be fixed then please. I am unable to fix it by myself.

**Comment by dpereirasilva** [comment]
@maxdevblock Unfortunately its not working the like by location. I'm getting the following error below:
Traceback (most recent call last):
```
   File "like_medias_by_location.py", line 89, in <module>
     for n, location in enumerate (bot.api.last_json ["items"], start = 1):
KeyError: 'items'
```

**Comment by TiasTias** [comment]
BUMP

**Comment by TiasTias** [comment]
BUMP BUMP

**Comment by dishkakrauch** [comment]
Are you gonna fix this or something?

**Comment by Quentin-M** [comment]
The location feed API is currently real broken. A location that has thousand of pictures will only return a handful of items; then start returning a single item with a new max if that constantly changes but will always return the same last item - without ever returning an empty next id - so no stop condition.
