### ISSUE TITLE
ERROR - 'NoneType' object has no attribute 'status_code'

### ISSUE THREAD

**Issue by roncam82** [ohld/igbot#786]
i have the below error:

ERROR - 'NoneType' object has no attribute 'status_code'

thanks

**Comment by maxdevblock** [comment]
Need more details

**Comment by roncam82** [comment]
Tell me what details you want please

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by maxdevblock** [comment]
It was all written in the issue form.

**Comment by smolyakov26** [comment]
0: add another account.                                                                             
-1: delete all accounts.                                                                            
1                                                                                                   
2019-01-31 19:24:40,778 - INFO - Logged-in successfully as 'tipich_parashytist' using the cookie!   
upload:                                                                                             
Analizing `./pics\3.jpg`                                                                            
FOUND w:2048, h:1365, ratio=1.5003663003663004                                                      
Horizontal image                                                                                    
Resizing image                                                                                      
Saving new image w:1080 h:720 to `./pics\3.jpg.CONVERTED.jpg`                                       
FOUND: w:1080 h:720 r:1.5                                                                           
2019-01-31 19:24:46,356 - INFO - Photo './pics\3.jpg' is not uploaded.                              

any fix for this error

**Comment by ohld** [comment]
Send the pic also please

**Comment by smolyakov26** [comment]
i tried 10 different pics and always getting same error

**Comment by maxdevblock** [comment]
Try logging in with `bot.login(use_cookie=False)`

**Comment by smolyakov26** [comment]
no help ) ive tried it already((

**Comment by maxdevblock** [comment]
OS?

**Comment by smolyakov26** [comment]
windows (((

**Comment by maxdevblock** [comment]
Which script are you using to upload?

**Comment by smolyakov26** [comment]
Autopost.py

чт, 31 янв 2019 г., 21:08 MaxDevBlock notifications@github.com:

**Comment by maxdevblock** [comment]
Try with `upload_photos.py` in `photos` folder.

**Comment by maxdevblock** [comment]
Instruction here
[https://github.com/instagrambot/instabot/tree/master/examples/photos](url)

**Comment by lmgtrigo** [comment]
same problem...
[41mERROR...[0m
[WinError 32] The process cannot access the file because it is being used by another process:
Bot stopped. Worked

**Comment by roncam82** [comment]
still the same error

**Comment by roncam82** [comment]
![image](https://user-images.githubusercontent.com/46320963/52909525-1aeb1380-328a-11e9-9c94-8224f438d871.png)

**Comment by roncam82** [comment]
the first time it uploaded a photo but the second time I got the above errors
