### ISSUE TITLE
add filtration to liked users, not only to followed users

### ISSUE THREAD

**Issue by rasperepodvipodvert** [ohld/igbot#80]
Фильтрация пользователей действия над которыми применяются.
Например хочу залайкать по хэштегу только тех у кого от 1 до 30 лайков на последние фотки....

Фильтры:

- [x] - по количеству у них фоловеров
- [x] - по количеству у них лайков на последние фотки
- [ ] - по количеству у них коментариев на последние фотки
- [x] - по количеству у них тех кого они фоловят
- [ ] - по гео (было бы здорово)

**Comment by ohld** [comment]
Данный функционал легко допрогать. Сделай пуллреквест, посмотрим.
