### ISSUE TITLE
429 error in message_users.py

### ISSUE THREAD

**Issue by ohnobudidnt** [ohld/igbot#809]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x ] Updated to the latest version
- [x ] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x ] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

---
error:

what page likers do you want to message? :@nojumper
succesfully written latest medialikers of['@nojumper']
Reading from medialikers.txt
2019-02-01 21:48:53,792 - ERROR - Request returns 429 error!
2019-02-01 21:48:53,792 - WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes.
Traceback (most recent call last):
  File "message_users.py", line 84, in <module>
    f.write(username + "\n")
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
2019-02-01 21:53:54,282 - INFO - Bot stopped. Worked: 0:15:42.270413
2019-02-01 21:53:54,282 - INFO - Total requests: 107
PS C:\Users\yoshi\Documents\instabot-master\examples>

---

### Describe your issue

message_users.py was working perfectly fine the first time i ran the script, then i keyboard interupted it. it then gave me error 403 and 404. So uninstalled, deleted and reinstalled all instances of instabot-master. Its now just giving me error 429, I'm assuming because i kept on trying to run the same script over and over because im completely new to this. I'm not sure what to do, I've uninstalled and updated to the most recent instabot.

**Comment by ehsunoo** [comment]
same problem!
no solution?
