### ISSUE TITLE
404 error in bot.get_user_info

### ISSUE THREAD

**Issue by ETUN4** [ohld/igbot#810]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

> Python 3.7.0

Code:
```
bot = Bot()
bot.login(username="user11", password="pass")
info = bot.get_user_info(user_id=**3104986655**)
```

Error/Debug Log:

> 2019-02-08 20:36:30,676 - INFO - Logged-in successfully as 'user11' using the cookie!
> 2019-02-08 20:36:31,166 - ERROR - Request returns 404 error!
> Traceback (most recent call last):
>   File "_temp.py", line 12, in <module>
>     print(bot.get_user_info(user_id=3104986655))
>   File "E:\Python37-32\lib\site-packages\instabot\bot\bot.py", line 381, in get_user_info
>     return get_user_info(self, user_id, use_cache)
>   File "E:\Python37-32\lib\site-packages\instabot\bot\bot_get.py", line 183, in get_user_info
>     self.api.get_username_info(user_id)
>   File "E:\Python37-32\lib\site-packages\instabot\api\api.py", line 339, in get_username_info
>     return self.send_request(url)
>   File "E:\Python37-32\lib\site-packages\instabot\api\api.py", line 184, in send_request
>     response_data = json.loads(response.text)
>   File "E:\Python37-32\lib\json\__init__.py", line 348, in loads
>     return _default_decoder.decode(s)
>   File "E:\Python37-32\lib\json\decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "E:\Python37-32\lib\json\decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 2019-02-08 20:36:31,521 - INFO - Bot stopped. Worked: 2:10:08.152601
> 2019-02-08 20:36:31,523 - INFO - Total likes: 9/1000
> 2019-02-08 20:36:31,524 - INFO - Total requests: 247

### Describe your issue
When trying to get information about the user (the page of which is most likely deleted), an error 404 occurs. The ID at which the error occurs: 4403346977 and 3104986655.

**Comment by ohld** [comment]
These users were deleted, right? That means that no users with that IDs - 404 error

**Comment by ETUN4** [comment]
> These users were deleted, right? That means that no users with that IDs - 404 error

Yes, these users are removed. But I can get the ID of these users by the function get_user_followers. The fact that the page is deleted and inaccessible I can only learn that I received an error. This error is not processed in any way.
