### ISSUE TITLE
'Bot' object has no attribute 'send_request'

### ISSUE THREAD

**Issue by iamdublex** [ohld/igbot#813]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [ x] Updated to the latest version
- [ x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [ x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here: Python 3.7.2

Code:

```
# Example code that will produce the error reported
#Check the description.
from instabot import Bot
import os
import sys
from time import sleep
import json
import pprint

from instabot import Bot
def _solve_checkpoint_challenge(_bot):
   # sleep(3)
    challenge_url = _bot.last_json['challenge']['api_path'][1:]
    try:
        _bot.send_request(
            challenge_url, None, login=True, with_signature=False)
    except Exception as e:
        _bot.logger.error(e)
        return False
bot = Bot()
try:
    bot.login()
    bot.follow_users("instagram")
except:
    if bot.last_json.get('error_type', '') == "checkpoint_challenge_required":
        var = _solve_checkpoint_challenge(bot)
else:
    print("Logged in without error.")

```

Error/Debug Log:

```
2019-02-10 00:29:05,030 Instabot Started
2019-02-10 00:29:21,773 Request returns 400 error!
2019-02-10 00:29:21,789 Instagram's error message: challenge_required
2019-02-10 00:29:21,789 Error type: checkpoint_challenge_required
2019-02-10 00:29:21,789 Username or password is incorrect.
2019-02-10 00:29:21,789 Going to follow 9 users.
2019-02-10 00:29:21,804 Not logged in!
2019-02-10 00:29:21,804 'Bot' object has no attribute 'send_request'

```

---

### Describe your issue

The except:  won't trigger on only checkpoint_challenge_required, so the bot.follow_users() is necessary. If you're wondering how exactly the code surpasses the challenge, I didn't include the full code, because I'm only interested in why the bot.send_request is not defined. Don't bother about the unnecessary imports, they are essential for the rest of the code.

**Comment by ohld** [comment]
```bot.api.send_request```
