### ISSUE TITLE
Request returns 500 error!

### ISSUE THREAD

**Issue by slabza** [ohld/igbot#817]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

Code:

```python
ERROR - Request returns 500 error!
INFO - Photo './pics/1.jpg' is not uploaded.
<Response [500]>
```

Error/Debug Log:

```python

```

---

### Describe your issue

I have an issue with autopost during upload pic. It's 500 Erorr. Could you help me, please?

**Comment by ohld** [comment]
send the pic that you are trying to send, the screenshots of your terminal and the command that you are trying to launch.

**Comment by slabza** [comment]
![autopost](https://user-images.githubusercontent.com/37632565/52896324-72c04680-31c6-11e9-8f8e-f57fef06f2a2.PNG)

**Comment by roncam82** [comment]
same error but the photo is actually uploaded but nothing is written in pics.txt

**Comment by not-eexto** [comment]
Same error but with videos

**Comment by gsdeabr** [comment]
Same error, and the photo is not uploaded.

**Comment by ldrolez** [comment]
same error. Tried with a 2200x2200 jpeg, then resized to 1100x1100, and even removed exif data.

**Comment by maxvinters** [comment]
So what's the solution?)

**Comment by AKwoKWH** [comment]
instagram blocking?
do you have the full response data?

**Comment by AKwoKWH** [comment]
https://github.com/instagrambot/instabot/pull/934

I updated this pull request to show full response msg in error log
after merged, update to latest version then rerun to see the full error msg

**Comment by Abassina** [comment]
Is there a solution????

I tryed it with python 2.7 and it work but it upload every pic whitch is stored in pic folder.
There is no delay...

But if i try it with python 3.6 it does the same like above.

**Comment by slabza** [comment]
Do you have any idea how to fix 500 error?
