### ISSUE TITLE
RESEARCH: get media by geotag

### ISSUE THREAD

**Issue by ohld** [ohld/igbot#82]
We should find the way to get medias by geotag. We can search in other API Wrappers on github for solution. Example https://github.com/mgp25/Instagram-API

**Comment by ohld** [comment]
Done

**Comment by anisayari** [comment]
Any news ? As the function stay in a TODO tag :) 

```
def get_geotag_medias(self, geotag, filtration=True):
    # TODO: returns list of medias from geotag
    pass
```
