### ISSUE TITLE
return username instead id

### ISSUE THREAD

**Issue by alexshavelev44** [ohld/igbot#824]
function [get_media_likers](https://github.com/instagrambot/instabot/blob/f562976613f15dd7496e77cf13673a43c438c2d5/instabot/bot/bot_get.py#L212)

could you return also username?

**Comment by ohld** [comment]
@alexshavelev44 

Yes, if you take a look at the function you can change it to return not only `user['pk']`


Just add to your script the rewritten function and use it as you wish. 
``` python
def get_likers(bot, media_id):
    bot.api.get_media_likers(media_id)
    if "users" not in bot.api.last_json:
        return []
    return bot.api.last_json["users"]
```

**Comment by alexshavelev44** [comment]
of course, i can. but it strange some funcs return the only id, other whole object

**Comment by ohld** [comment]
feel free to open a pull requests, this library contains a lof of shitcode

**Comment by KazemRahimzadeh** [comment]
@ohld How can I use 'get_user_id_from_username — Get user_id by username' in a script exactly?
would you put an example in a script?
I couldn't get it as I followed the available examples on the website and docs.
Thanks in advance.

**Comment by steffanjensen** [comment]
@KazemRahimzadeh  Here is an example where I scrape the userid from "username" and then print the username and userid. 
```python 
user_id = bot.get_user_id_from_username("yourusername")
username = bot.get_username_from_user_id(user_id)
print(f"Welcome {username} your userid is {user_id}")
