### ISSUE TITLE
(question) how to save results temporarily?  (Save users followers to file)

### ISSUE THREAD

**Issue by jeffsnow88** [ohld/igbot#826]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

Hello,

When calling the python save_users_followers_to_file, and the user contains a lot of followers (in my case 1M), the function suggest to save the results in a temporary file, due a big operation.

How can I save it temporary? As it stops ~40% with the message "Dead".

I tried to discover how to save it temporarily, but I didn't find the answer.

**Comment by jeffsnow88** [comment]
Bump

**Comment by caffeinum** [comment]
In the instabot web version (Chrome extension), any stopped queue still returns results that were already downloaded, even if stopped manually. 

https://github.com/instagrambot/web#tasks

Warning, alpha version: https://chrome.google.com/webstore/detail/instagram-yourself/njonkbhnmmjgancfbncekpgkmidhbbpo

Edit: Disclaimer: During testing, I tried downloading 4000 followers max. Not sure about 1M, but that should be pretty similar 😬
