### ISSUE TITLE
get_user_medias limit

### ISSUE THREAD

**Issue by alexshavelev44** [ohld/igbot#827]
func [get_user_medias](https://github.com/instagrambot/instabot/blob/f562976613f15dd7496e77cf13673a43c438c2d5/instabot/bot/bot_get.py#L55) return only last 18 medias. how to get more? func doesn't have any offset.

or it is IG limitation?

**Comment by ohld** [comment]
https://github.com/instagrambot/instabot/blob/f562976613f15dd7496e77cf13673a43c438c2d5/instabot/bot/bot_get.py#L64
