### ISSUE TITLE
SOCKS5 Proxy for Instabot

### ISSUE THREAD

**Issue by alexskyfleet** [ohld/igbot#829]
### Purpose of your issue?
- [X] Bug report (encountered problems/errors)
- [X] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

### Describe your issue

How do I add a SOCKS5 proxy for Instabot?
![image](https://user-images.githubusercontent.com/47344642/53540808-e9d2d480-3b0e-11e9-90ae-5360336b920b.png)
I tried to change the highlighted code to 'socks5' but it still gives the error:
"WARNING - ('Connection aborted.', BadStatusLine("''",))"
I've also already done:
pip/pip3 install requests[socks]

**Comment by ohld** [comment]
Was it `socks5://.....`?

**Comment by alexskyfleet** [comment]
> 
> 
> Was it `socks5://.....`?

I did:
def set_proxy(self):
	if self.proxy:
		scheme = 'socks5://'
		self.session.proxies['http'] = scheme + self.proxy
		self.session.proxies['http'] = scheme + self.proxy
