### ISSUE TITLE
How to like a photo from at account business?

### ISSUE THREAD

**Issue by gugahb** [ohld/igbot#832]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [X] Updated to the latest version
- [ ] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [ ] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here: Python 2.7.13

### Describe your issue

I would like the function like_hashtag.py also like the photos of business accounts, how can I disable the function that is blocking this?

**Comment by gugahb** [comment]
info: is BUSINESS, skipping!

**Comment by JudeMurphy** [comment]
@gugahb - I went into bot_filter.py and commented out the following:

    if "is_business" in user_info and self.filter_business_accounts:
        if user_info["is_business"]:
            self.console_print('info: is BUSINESS, skipping!', 'red')
            skipped.append(user_id)
            return False

**Comment by ohld** [comment]
You can just set in your script:
`bot.filter_business_accounts = False`

**Comment by JudeMurphy** [comment]
For some reason, I had tried what @ohld had suggested at first, and it didn’t work. So I ended up doing my suggestion. Whatever works for you!

**Comment by gugahb** [comment]
Many thanks to everyone, it worked
