### ISSUE TITLE
Unable to login: 400 Error checkpoint challenge required

### ISSUE THREAD

**Issue by blazephoenix** [ohld/igbot#838]
### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

Code:

```python 3.7.2
# Example code that will produce the error reported

from instabot import Bot


bot = Bot()
bot.login(username="USERNAME", password="PASSWORD")
user_id = bot.get_user_id_from_username("lego")
user_info = bot.get_user_info(user_id)
print(user_info['biography'])
```

Error/Debug Log:

```
2019-03-11 13:46:10,526 Instabot Started
2019-03-11 13:46:11,780 Request returns 400 error!
2019-03-11 13:46:11,780 Instagram's error message: challenge_required
2019-03-11 13:46:11,781 Error type: checkpoint_challenge_required
2019-03-11 13:46:11,782 Username or password is incorrect.
2019-03-11 13:46:11,782 Not logged in!
```

---

### Describe your issue

I downloaded the bot just a few hours ago and I'm unable to login from my home IP without a proxy. I'm using the sample code given in the developer documentation.

**Comment by arlidge** [comment]
Are you also logged in with your phone from the same ip?

**Comment by JudeMurphy** [comment]
I'm also having a problem with this as well, with two accounts. Not on the same IP. Keeps saying unusual activity, and unable to login with the bot. @Blazephoenix

**Comment by blazephoenix** [comment]
@arlidge I logged out from the phone and tried with the same IP, the issue still persists

**Comment by arlidge** [comment]
@Blazephoenix - The "challenge required" is when Instagram detects suspicious activity on your account, ie a device that has never logged in. Did Instagram send you an email? Try logging into instagram from your computer, it might then offer the challenge - Which is usually a code they will txt you. Once you are in on your computer, sign out again, then try running the bot from the same IP you used for your computer, ie your home IP. Don't try and run this on a remote server unless that IP will be the only IP you use for it, otherwise it will constantly trigger the challenge. I had this issue at first. @JudeMurphy This might also help you out. If you get the Challenge you have to go through the steps on the same IP you use the bot on. That appears to be the trick. Also - if there is a cookie associated with the failed login, delete it then start the bot to get a new cookie.

**Comment by blazephoenix** [comment]
@arlidge That worked. Thanks!

**Comment by TheGlobalist** [comment]
I am experiecing the same issue but the comment by @arlidge didn't help me

**Comment by arlidge** [comment]
Hi @TheGlobalist - Please start from beginning. Are you logged out of instagram on all devices? Have you completed the instagram challenge request? Then logged out again? then delete cookie from directory you ran the bot from? Then attempt to run bot again?

**Comment by AKwoKWH** [comment]
Same issue
I run my script on my PC getting the the challenge.
On my phone, there is a popup asking if the login attempt is me or not.
I clicked "it was me" , but still , I cant login from my PC terminal

**Comment by TheGlobalist** [comment]
> Hi @TheGlobalist - Please start from beginning. Are you logged out of instagram on all devices? Have you completed the instagram challenge request? Then logged out again? then delete cookie from directory you ran the bot from? Then attempt to run bot again?

Hey arlidge, sorry this took forever to reply.
Yes I tried everything, also with accounts that were never on bot services but I still get the problem

**Comment by nandezer** [comment]
> Hi @TheGlobalist - Please start from beginning. Are you logged out of instagram on all devices? Have you completed the instagram challenge request? Then logged out again? then delete cookie from directory you ran the bot from? Then attempt to run bot again?

Where do I find the file with the cookie? I can't seem to find it.
I have try everything mentioned above and still not working

**Comment by arlidge** [comment]
Hi @nandezer you should be able to "pip3 install -U instabot" and then jun an example script from the instabot git repo. Then first time running it should ask for login and password. It does not store the cookie in the same place it used to.... sorry.

**Comment by nandezer** [comment]
> Hi @nandezer you should be able to "pip3 install -U instabot" and then jun an example script from the instabot git repo. Then first time running it should ask for login and password. It does not store the cookie in the same place it used to.... sorry.

Hey @arlidge thanks for the reply. After much going around I manage to insert an email code confirmation through the cmd and get log in thanks!

My problem now is that I get the "feedback_required" error, and all my actions get blocked.

**Comment by arlidge** [comment]
Hi @nandezer are you signed in to the same account with another device on the same network?

**Comment by nandezer** [comment]
> Hi @nandezer are you signed in to the same account with another device on the same network?

Hey, I am signed up on an IG app on my phone (via wifi), IG app & IG website on my laptop
