### ISSUE TITLE
Login without username/ password

### ISSUE THREAD

**Issue by tobeyond** [ohld/igbot#839]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:
Python 3.7.1

---

### Describe your issue

I would like to login to my account using only the session id (I've seen it in a website and a goland script, but I don't know how to translate it to Python), without my username and password informations. 
Is it possible to add this feature? So I start the script like ;

bot = Bot(proxy=PROXY)
bot.login(sessionid=SESSIONID).

Thank you.

**Comment by ohld** [comment]
Can you please make a reference to the library that already does that?

**Comment by tobeyond** [comment]
Well, this script in go does that: https://github.com/tducasse/go-instabot
And there's this website, not sure how they work: https://phantombuster.com

(to use the first one we set the username and password, but it's used only once. So I guess we can skip this part, using the session id directly, as the second one)

**Comment by ohld** [comment]
Sessions tend to die after some time. To prevent session stealing

**Comment by tobeyond** [comment]
They're usually valid for a couple of months or even a year.

**Comment by nkwsy** [comment]
This likebot uses session mgmt in python. They work for a very long time. Also has method to overcome login challenges.

https://github.com/instabot-py/instabot.py/search?q=session&unscoped_q=session

**Comment by shellx86** [comment]
Hi, there are a news for this feature?

**Comment by KazemRahimzadeh** [comment]
Is there actually a way to make your own session based on a device info(IMEI and Device Model) that you provide?
Please describe the process in a detailed way, as I am a newbie to InstaBot and also new to Python.
Kind regards.

**Comment by AKwoKWH** [comment]
Do you mean cookie?
There is a parameter in bot.login that you can login using cookie

**Comment by AKwoKWH** [comment]
@KazemRahimzadeh @shellx86 @tobeyond 
Maybe you can try bot.login(username=***, password=***,use_cookie=True)
I can login successfully
However having some issues uploading pic if I login using cookie.
Let me know if you can do it too?
