### ISSUE TITLE
Like by hashtag not working

### ISSUE THREAD

**Issue by jeffsnow88** [ohld/igbot#842]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x ] Updated to the latest version
- [ x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x ] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

Code:

```python
# Example code that will produce the error reported
from instabot import Bot

bot = Bot()
bot.login(username="user", password="pass")
followers = bot.get_user_followers(bot.user_id)
```

Error/Debug Log:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: integer division or modulo by zero
```

---

### Describe your issue

Explanation of your issue goes here. Please make sure the description is worded well enough to be understood with as much context and examples as possible.

Hello everyone. When I call like by hashtag python script, the console shows it is likeing the media's, but if you check user activity in the user account on Instagram app or website (post I have liked) it doesn't show up. I understand that then it's not working?
I'm using default configuration of Instagram bot, I also tried to clone a very fresh installation in a new folder and it's also not working . No errors are showing on console. What should I do?

**Comment by jeffsnow88** [comment]
Up

**Comment by joelquek** [comment]
I am having the same problem. 
The script runs without any problems but on Instagram "Post You've Liked" no new post is being liked.

```
2019-04-11 23:25:21,716 - INFO - Logged-in successfully as '*********'!
2019-04-11 23:25:21,718 - INFO - Going to like media with hashtag #****.
2019-04-11 23:25:25,079 - INFO - Going to like 85 medias.
 18%|███████▍                                  | 15/85 [02:43<12:42, 10.89s/it]
```

**Comment by reslus** [comment]
Same issue ^^

**Comment by reslus** [comment]
Not even sure how to troubleshoot the issue as there isn’t any errors. Just no likes occur even though bot seems to function

**Comment by karlmbagna** [comment]
is no one ever going to fix this?

**Comment by reslus** [comment]
anyone going to address this?

**Comment by reslus** [comment]
bump

**Comment by reslus** [comment]
I have somewhat figured it out: don't use hashtags that rank in the millions. A good choice is in the 200k range. Not sure what the difference is maybe the bot gets overwhelmed somehow but that actually allows for images to be liked rather than cycling through.
