### ISSUE TITLE
Unfollow Not Working 500 error

### ISSUE THREAD

**Issue by notahooper15** [ohld/igbot#843]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [ x] Updated to the latest version
- [x ] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x ] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*. 

Using Python 3

Paste the output of ``python -V`` here:

ERROR - Requests returns 500 error!
json.decoder.JSONDecodeError: Expecting Value: line 1 column 1 (char 0)

Code:

bot = Bot()
bot.login(username="xxxxxxx", password="xxxxxx",
          proxy=args.proxy)
bot.unfollow_everyone()
Error/Debug Log:

---

### Describe your issue

I have ran the unfollow_everyone() function and it keeps giving me the same 500 error. It stops after about unfollowing 25 people.

**Comment by steffanjensen** [comment]
Issues with the API
https://developers.facebook.com/status/issues/

**Comment by notahooper15** [comment]
@reliefs Thanks
