### ISSUE TITLE
Fetching more than 20 direct message conversations

### ISSUE THREAD

**Issue by jackdellis** [ohld/igbot#844]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x ] Updated to the latest version
- [ x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [ x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here: Python 2.7.10

Code: 

```python
import os
import sys

from tqdm import tqdm
from instabot import Bot

bot = Bot()
bot.login(username="user", password="pass")
data = bot.get_messages()
```

### Describe your issue

I'm wondering if there is a way to fetch more than 20 usernames that i've been messaging. I'd like to fetch as many usernames from my direct messages as possible. Perhaps the past 100 conversations. I've been using bot.get_messages() but it seems like it only fetches the most recent 20 conversations. I've noticed theres a cursor value in the json output. But i'm not sure how you use it (if it is in fact related to the next page). 

Hope that you can help! 

Regards, Jack

**Comment by reliefs** [comment]
Yes you can do it by putting it inside a loop function


```python
import os
import sys

from tqdm import tqdm
from instabot import Bot

bot = Bot()
bot.login(username="user", password="pass")
while True:
    try:
        data = bot.get_messages()
    except:
        print("get next 20 messages")
```

**Comment by steffanjensen** [comment]
https://github.com/instagrambot/instabot/issues/1126

**Comment by Limule** [comment]
Can we get pagination ?
