### ISSUE TITLE
Duplicated Following after unfollowing

### ISSUE THREAD

**Issue by notahooper15** [ohld/igbot#848]
### Before submitting an issue, make sure you have:
- [x ] Updated to the latest version
- [x ] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x ] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### Describe your issue

Not really an issue. I was just wondering about duplicated following. I have searched through the issues and found there have been things to stop duplicated following, but how does this work exactly? For example, I have using follow_user_followers.py and then I am using the unfollow_everyone.py scripts. If I am following the same users followers, won't I be redundant in the followers I am following? Any answers would be appreciated thank you.

**Comment by ohld** [comment]
Should not.
