### ISSUE TITLE
Api follow_users not work

### ISSUE THREAD

**Issue by marcolezuza** [ohld/igbot#849]
hi, When you perform follows, the api returns a 200, but the user does not really stay as followed.

I have obtained these traces:
https://i.instagram.com/api/v1/friendships/create/1514515892/
{"friendship_status": {"following": false, "followed_by": false, "blocking": false, "muting": false, "is_private": false, "incoming_request": false, "outgoing_request": false, "is_bestie": false}, "status": "ok"}
<Response [200]>

If I go to Instagram for that user, I'm not following him.

Do you know what may be happening?

**Comment by ohld** [comment]
send the script to reproduce the error

**Comment by marcolezuza** [comment]
I have the scripts that are in the master branch, and I have executed the command
pip install -U instabot

exectue the py "python follow_user_followers.py"

Until a few days ago I worked properly.

however, the python unfollow_everyone.py script continues to work correctly

**Comment by marcolezuza** [comment]
any ideas?
