### ISSUE TITLE
bot.comment_user uses invalid argument

### ISSUE THREAD

**Issue by drallcom3** [ohld/igbot#853]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here: Python 3.7.2

Code:

Error/Debug Log:

---

### Describe your issue

```python
user_id = self.convert_to_user_id(12099388359)
bot.comment_user(user_id, amount=1)
```

```python
Traceback (most recent call last):
  File "ultimate.py", line 214, in <module>
    bot.comment_user(12099388359, amount=1)
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instabot\bot\bot.py", line 587, in comment_user
    return comment_user(self, user_id, amount)
  File "C:\Users\Me\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instabot\bot\bot_comment.py", line 93, in comment_user
    if not self.check_user(user_id, filter_closed_acc=True):
TypeError: check_user() got an unexpected keyword argument 'filter_closed_acc'`
check_user doesn't have the argument filter_closed_acc, but comment_user tries to use it.
```

Doesn't work in bot.comment_user:
```python
if not self.check_user(user_id, filter_closed_acc=True):
        return False
```

Works in bot.comment_user:
```python
if not self.check_user(user_id):#, filter_closed_acc=True):
        return False
```

**Comment by AKwoKWH** [comment]
yes, 
I have the same issue
"check_user() got an unexpected keyword argument 'filter_closed_acc'"
need to manually remove the argument

Can we also update the repo?
Thanks

**Comment by AKwoKWH** [comment]
I hv made a pull request related to this.
Just disabled the 2nd argument in the code
Also I added check_medias() , same as what we hv when doing like which exclude some post not to do action (eg. Blacklist hashtag)

https://github.com/instagrambot/instabot/pull/920
