### ISSUE TITLE
Some inspiration for enchance our autopost and ultimate schedule script

### ISSUE THREAD

**Issue by penarubah** [ohld/igbot#86]
i found this one:
`https://github.com/dbader/schedule`

**Comment by stasfilin** [comment]
@penarubah Hi, I think we can use this.
Do you want to do this?

**Comment by penarubah** [comment]
No, i'm still noob @stasfilin
Please, if you can do  :)

**Comment by stasfilin** [comment]
@penarubah do this, if you need to help - just ping me or @ohld. We can help you if you have questions :) Feel Free

**Comment by penarubah** [comment]
well, i'll try my best then @stasfilin
