### ISSUE TITLE
Bot dont have delay

### ISSUE THREAD

**Issue by Raul1231** [ohld/igbot#865]
I have used the bot and it works great, but how can I put ir some delay.

For instance, follow_user_followers.py is following users really fast, how can I change that?

Thank you

**Comment by jonhenshaw** [comment]
The bot already has a delay implemented if you look at the Bot() class declaration in the Bot.py file. If you would like to increase the delay, simply overwrite the default value by setting a new parameter when you instantiate a new Bot() object in whatever script you're running.

Look at the top of the source code for the script you're running and change 

`bot = Bot()`

to something like

`bot = Bot(follow_delay=200)`

I am not sure if a 200 delay is what you want, it is just an example. The default delay is 30. You can add in all sorts of new parameters if you're unhappy with the default settings found in Bot.py.

**Comment by MacroAnarchy** [comment]
Yes, that’s how It should work, but doesn’t I feel!? 

If I use any future, the bot runs it as fast as possible! Directly from CLI script or other examples. No wait time before likes or comments! 

There might be something wrong with the reading of config file? Like the wrong line numbers?

**Comment by MacroAnarchy** [comment]
Ok, it’s not as fast as possible, but it averages way below the set delay.

The reason I think is Line 330 in the bot file:

time.sleep(t_remaining * random.uniform(0.25, 1.25))

This makes 25% of set delay possible, and it only averages at 75% of the set delay.
I don’t think this is wise ...
It should probably be 0,75 and 1.25

What do you think @Jon309 ?

**Comment by MacroAnarchy** [comment]
@ohld can you have a look at this? If I’m right this means the bot can be 4 times as fast as one would think from the set delays. Since it’s the main function, this affects all delays for all actions!

**Comment by steffanjensen** [comment]
The delays are already working, if you need to implement more delay, it's one of the first features a programmers learn while using python. No need to implement extra for such a simple feature.

**Comment by MacroAnarchy** [comment]
@reliefs no need for extra delay. The implemented delay should work as described though, which it does not. 

The reason I think is Line 330 in the bot file:

time.sleep(t_remaining * random.uniform(0.25, 1.25))

This makes 25% of set delay possible, and it only averages at 75% of the set delay.
I don’t think this is wise ...
It should probably be 0,75 and 1.25

Right now, bot can make 10 comments within 150 seconds with preconfigured settings. Same for follows and likes, bot can be 4X as fast as your set delay is.

This should be fixed!?

**Comment by MacroAnarchy** [comment]
No one interested?? 
I changed the above to be 0.95 and 1.3 and it works like expected (-> it actually waits for the configure time) 
This should be implemented in the code
