### ISSUE TITLE
Repost feature enhancement

### ISSUE THREAD

**Issue by penarubah** [ohld/igbot#87]
I find this feature in instadub.

for the one who grow repost and paid promote account, this is very useful to steal followers.
the idea is to download tagged images from another account

![photo_2017-03-01_20-28-09](https://cloud.githubusercontent.com/assets/25403367/23461923/6b923f2c-febe-11e6-8f97-5683b684a47d.jpg)

and upload it in ours. include caption and tag or mention to the owner of image.

![photo_2017-03-01_20-40-48](https://cloud.githubusercontent.com/assets/25403367/23462204/697fb9a2-febf-11e6-99fb-1d5b79042ea7.jpg)

**Comment by ohld** [comment]
Done in current version.
