### ISSUE TITLE
posts photo/video without caption

### ISSUE THREAD

**Issue by alexshavelev44** [ohld/igbot#878]
seems like bot now posts photos/videos without caption.
any suggestions where to look?

**Comment by ohld** [comment]
You can find the inspiration from another Instagram API wrappers like https://github.com/ping/instagram_private_api

**Comment by alexshavelev44** [comment]
@ohld i found out it happens after i bot 5 photos in 2-3 mins via bot. if i log in and post with different account - captions exists. but with broken, not. strange that update media requests doesn't return error

**Comment by AKwoKWH** [comment]
Because you got blocked by Instagram.
If you try to upload the pic manually, you will get the same result, no captions is included in the pic after you hv published.

Just wait a few days

**Comment by alexshavelev44** [comment]
@AKwoKWH you are right. (it took 7-10 days to be unblocked)
