### ISSUE TITLE
Cookie.txt not created

### ISSUE THREAD

**Issue by reslus** [ohld/igbot#880]
The bot seems to log in just fine but cookie.txt is no longer being created. Has there been a change to the functionality?

**Comment by notahooper15** [comment]
+1

**Comment by notahooper15** [comment]
Figured this out in your bot.login() just set a parameter of use_cookie=True.
So bot.login(use_cookie=True) then it should generate your cookie file.

**Comment by reslus** [comment]
Thank you @notahooper15 ! If anyone is wondering, this is in api.py file.
