### ISSUE TITLE
How to avoid repeated user's followers in follow_user_followers?

### ISSUE THREAD

**Issue by rodrigosnader** [ohld/igbot#882]
Hi guys, please excuse me if there's anything wrong with this question, but it's one of my first questions/issues here in GitHub.

I'm trying to schedule to follow 100 user followers every hour. The problem is that after the first hour I get:

"After filtering followed, unfollowed and skipped, 0 user_ids left to follow."

How do I get followers from a certain checkpoint instead of getting always the same user's followers?

Thank you in advance.

**Comment by AKwoKWH** [comment]
same issue,
I think the code is just to get the latest n-followers.
if the account dont have any new followers, you get nothing.
it means that any follower who listed in the n+1 position can never be extracted.

My work around is :
Trying to get latest 2000 followers every hour and then save it into the file 
shuffle the list and then follow 100 of them randomly.

but the workflow is stupid and I am not sure if there are issue to get 2000 followers every hour
it might get flagged by instagram.
