### ISSUE TITLE
ImportError: cannot import name 'Bot'

### ISSUE THREAD

**Issue by alirezaetedadi** [ohld/igbot#886]
I create new project in pycharm and install instabot package.
Install successfully and  I write `from instabot import Bot
` 
pycharm suggestion suggest me write `Bot`. but when run I get this error:
```
    from instabot import Bot
ImportError: cannot import name 'Bot'
```
how to fix this problem?

**Comment by alirezaetedadi** [comment]
I create new project in pycharm and install instabot package.
Install successfully and  I write `from instabot import Bot
` 
pycharm suggestion suggest me write `Bot`. but when run I get this error:
```
    from instabot import Bot
ImportError: cannot import name 'Bot'
```
how to fix this problem?

**Comment by alex-grover** [comment]
it's most likely because your environment is not set up correctly. are you running through pycharm as well?

**Comment by MrCanan** [comment]
Hi,

I am under Debian (and you @alirezaetedadi ?) and I never install PyCharm (@ajgrover I never need it to this)!
I make the update today (like all time when I see one new), and I get the same error as you @alirezaetedadi 
Everything works like a charm before this update...

Have you found a solution? =)

Thank you in advance,
Best regards.

**Comment by ohld** [comment]
Have you tried

`pip install -U instabot`

?

**Comment by MrCanan** [comment]
Hi @ohld ,

For sure, I already use : 
`python3 -m pip install instabot --no-cache-dir --upgrade`

As I said, I never have error after update (and I made a lot, as there is a lot on this repo) until now.

Have you found a real solution? =)

Thank you in advance,
Best regards.

**Comment by hamdyaea** [comment]
Traceback (most recent call last):
  File "./instabot.py", line 3, in <module>
    from instabot import Bot
  File "/home/hamdy/Documents/SolarSystemPercentage/instagram/instabot.py", line 3, in <module>
    from instabot import Bot
ImportError: cannot import name 'Bot' from partially initialized module 'instabot' (most likely due to a circular import) (/home/hamdy/Documents/SolarSystemPercentage/instagram/instabot.py)


my version of instabot is : 

instabot==0.88.0
