### ISSUE TITLE
Is it possible to follow private accounts using the Multi Script?

### ISSUE THREAD

**Issue by keempoo** [ohld/igbot#894]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue

I am using the multi_script_CLI.py and would like to add followers of a user I am following that are private. I have tried to update the below files:
- multi_sript_CLI
- bot.py
- filter_private_profiles.py

with:
```
filter_users=False,
filter_private_users=False
```

I don't understand exactly what I'm doing or where the multi script is grabbing the parameter from. Any help would be appreciated!

**Comment by keempoo** [comment]
Happy to [buy a coffee](https://www.buymeacoffee.com/okhlopkov)  to anyone who could help. Instabot has been amazing otherwise!

**Comment by jonhenshaw** [comment]
At the bottom of the multi script, it created its own instance of the Bot class. In that initialization is where you want to add:

`filter_private_users=False`

It looks like this 

`bot = Bot(
    max_likes_per_day=setting_0,
    max_unlikes_per_day=setting_1,
    max_follows_per_day=setting_2,
    max_unfollows_per_day=setting_3,
    max_comments_per_day=setting_4,
    max_likes_to_like=setting_5,
    max_followers_to_follow=setting_6,
    min_followers_to_follow=setting_7,
    max_following_to_follow=setting_8,
    min_following_to_follow=setting_9,
    max_followers_to_following_ratio=setting_10,
    max_following_to_followers_ratio=setting_11,
    min_media_count_to_follow=setting_12,
    like_delay=setting_13,
    unlike_delay=setting_14,
    follow_delay=setting_15,
    unfollow_delay=setting_16,
    comment_delay=setting_17,
    whitelist_file=whitelist,
    blacklist_file=blacklist,
    comments_file=comment,
    stop_words=[
        'order',
        'shop',
        'store',
        'free',
        'doodleartindonesia',
        'doodle art indonesia',
        'fullofdoodleart',
        'commission',
        'vector',
        'karikatur',
        'jasa',
        'open'])`

Change it to

`bot = Bot(
    max_likes_per_day=setting_0,
    max_unlikes_per_day=setting_1,
    max_follows_per_day=setting_2,
    max_unfollows_per_day=setting_3,
    max_comments_per_day=setting_4,
    max_likes_to_like=setting_5,
    max_followers_to_follow=setting_6,
    min_followers_to_follow=setting_7,
    max_following_to_follow=setting_8,
    min_following_to_follow=setting_9,
    max_followers_to_following_ratio=setting_10,
    max_following_to_followers_ratio=setting_11,
    min_media_count_to_follow=setting_12,
    like_delay=setting_13,
    unlike_delay=setting_14,
    follow_delay=setting_15,
    unfollow_delay=setting_16,
    comment_delay=setting_17,
    whitelist_file=whitelist,
    blacklist_file=blacklist,
    comments_file=comment,
    stop_words=[
        'order',
        'shop',
        'store',
        'free',
        'doodleartindonesia',
        'doodle art indonesia',
        'fullofdoodleart',
        'commission',
        'vector',
        'karikatur',
        'jasa',
        'open'],
    filter_private_users=False)
 `
Do not mess with the original bot.py file. If you have any questions feel free to ask me.

**Comment by keempoo** [comment]
Amazing! Thank you!

**Comment by tamerlanhtm** [comment]
Hi Jon309,

I have added filter_private_users=False) to the bottom of multi_script_CLI.py script and then run follow_user_followers.py, but it is still skipping private profiles. Any ideas how to follow private users instead of business profiles?

Thank you

**Comment by keempoo** [comment]
I can actually answer this one!

Since you made the changes to the multi script, you need to run the multi_script_CLI.py not the follower_users_followers.py. Use the menu prompts to follow, then follow user, then insert name.
