### ISSUE TITLE
Send Direct Message is slow

### ISSUE THREAD

**Issue by mohamad171** [ohld/igbot#907]
Hi , I want to send Direct Message to some of followers , but it is very slow , How can speed up this? send direct message in parallel bots is correct?

**Comment by steffanjensen** [comment]
the function takes around 5-10 seconds to execute, if you have a longer wait time, you should update instabot.

I keep the wait time around 40-60 sec per message or else instagram will block me for doing that function.

Here is how I implemented it. 
https://github.com/instagrambot/instabotai/blob/master/examples/reply_pending_inbox.py
