### ISSUE TITLE
Run 2 scripts at once

### ISSUE THREAD

**Issue by joost-heijden** [ohld/igbot#908]
Is it possible to run 2 scripts at once? And then i mean, can i run 2 scripts with 2 different accounts?

**Comment by ohld** [comment]
You can easily just open two terminals or open two terminals from different copies of the bot.

**Comment by joost-heijden** [comment]
@ohld, thanks for ya fast reply! I'm gonna give it a try.

**Comment by AKwoKWH** [comment]
try this:

from multiprocessing import Pool
pool = Pool(2)
pool.starmap(_[your function here]_,[_paraForAcc1,paraForAcc2_])
