### ISSUE TITLE
ImportError: cannot import name "limits"

### ISSUE THREAD

**Issue by Zelda00010** [ohld/igbot#91]
Hello Guys,

Like the title says, i tried to start the bot_follow.py but there is always this error: ImportError: cannot import name "limits". Please help me.

Thanks, Zelda00010

**Comment by ohld** [comment]
Have you use the last Instant version? 
To update type in terminal:
```
pip install -U instabot
```

We don't have the example with title "bot_follow.py". Can you provide us with your code?

If you run the script that is in `instabot/bot/` folder you shouldn't do that - this _not_ the example but source code for Instabot's methods.

**Comment by Zelda00010** [comment]
Well, i used the source i think, what should i use instead?

[](http://prntscr.com/ef7lpi)

```
from tqdm import tqdm

from . import limits
from . import delay

__all__ = ('follow', 'follow_users', 'follow_followers', 'follow_following',)


def follow(cedukeodeath):
    user_id = self.convert_to_user_id(user_id)
    if not self.check_user(user_id):
        return True
    if self.following == []:
        self.following = self.get_user_following(self.user_id)
    if user_id in self.following:
        return True  # already following
    if limits.check_if_bot_can_follow(self):
        delay.follow_delay(self)
        if super(self.__class__, self).follow(user_id):
            self.total_followed += 1
            return True
    else:
        self.logger.info("Out of follows for today.")
    return False


def follow_users(self, user_ids):
    self.logger.info("Going to follow %d users." % len(user_ids))
    for user_id in tqdm(user_ids):
        if not self.follow(user_id):
            delay.error_delay(self)
            while not self.follow(user_id):
                delay.error_delay(self)
    self.logger.info("DONE: Total followed %d users." % self.total_followed)
    return True


def follow_followers(self, user_id, nfollows=None):
    self.logger.info("Follow followers of: %s" % user_id)
    if not user_id:
        self.logger.info("User not found.")
        return
    follower_ids = self.get_user_followers(user_id)
    if not follower_ids:
        self.logger.info("%s not found / closed / has no followers." % user_id)
    else:
        self.follow_users(follower_ids[:nfollows])


def follow_following(self, user_id, nfollows=None):
    self.logger.info("Follow following of: %s" % user_id)
    if not user_id:
        self.logger.info("User not found.")
        return
    following_ids = self.get_user_following(user_id)
    if not following_ids:
        self.logger.info("%s not found / closed / has no following." % user_id)
    else:
        self.follow_users(following_ids[:nfollows])

```

**Comment by ohld** [comment]
Go to examples folder and choose any script to run.

**Comment by Zelda00010** [comment]
i started this one:

"""
    instabot example

    Workflow:
        Follow user's following by username.
"""

import sys
import os
import time
import random
from tqdm import tqdm

sys.path.append(os.path.join(sys.path[0],'../'))
from instabot import Bot

if len(sys.argv) < 2:
    print ("USAGE: Pass username / usernames.")
    print ("Example: python %s ohld lenakolenka" % sys.argv[0])
    exit()

bot = Bot()
bot.login()
for username in sys.argv[1:]:
    bot.follow_following(cedukeodeath)


and it just writes in that: http://prntscr.com/ef8rrz

**Comment by ohld** [comment]
Read what did it write to you. In USAGE is the correct way to run this example. So, as an example, it will follow following of users: ohld and lenakolenka.

**Comment by Zelda00010** [comment]
ohhh, nice, ive got it now, but its just my account adding others, can i make it giving me followers?

**Comment by ohld** [comment]
You can't control other accounts
