### ISSUE TITLE
Cant type in password in cmd 

### ISSUE THREAD

**Issue by wira95** [ohld/igbot#919]
Hi! 

Sorry for my maybe stupid question but i cant figrue out whats the problem.

When I try to start the bot i have to type in my login and my password. 
it is possible to type in my log in, but i cant type in the password. When i press the keys of the  password - nothing appears on the screen. 

i downloaded the files several hours ago so it should be no update problem. 

Does anyone know whats the problem ? 

with kind regards

**Comment by ohld** [comment]
password is just not shown for the security reasons. Just type it blindly and press enter
