### ISSUE TITLE
[NEW Feature Suggestion]: Share post to Story 

### ISSUE THREAD

**Issue by AKwoKWH** [ohld/igbot#921]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Describe your issue

Explanation of your issue goes here. Please make sure the description is worded well enough to be understood with as much context and examples as possible.

Possible to share someone post on story?

**Comment by steffanjensen** [comment]
yea use the bot to download user media, then put the image location output inside the function upload_story_photo.

**Comment by AKwoKWH** [comment]
> yea use the bot to download user media, then put the image location output inside the function upload_story_photo.

Can it reference to the post link?
If you just download the photo and then re-upload to story, then it is just a story posting.
Any idea to share the post via story so people viewing the story can click and being re-directed to the post?

**Comment by steffanjensen** [comment]
No, i haven't seen that function in instabot yet.

**Comment by steffanjensen** [comment]
Also looking for this feature now. 
Also the extra features share post with Photo layout + "see post" option. 
Will look into it.
