### ISSUE TITLE
Cookies Not working

### ISSUE THREAD

**Issue by AKwoKWH** [ohld/igbot#922]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

Code:

```python
# Example code that will produce the error reported
bot = Bot()
bot.login(username=userName, password=password,proxy=proxy, use_cookie=True, cookie_fname=COOKIE_FNAME)
bot.like_user(user_id=userName, amount=1, filtration=False)
```

Error/Debug Log:

```
2019-06-01 19:01:01,805 - INFO - Instabot Started
2019-06-01 19:01:01,806 - INFO - Logged-in successfully as 'XXXXXXX' using the cookie!
2019-06-01 19:01:01,806 - INFO - Liking user_XXXXXX's feed:
2019-06-01 19:01:03,205 - ERROR - Request returns 403 error!
2019-06-01 19:01:04,806 - ERROR - Request returns 403 error!
2019-06-01 19:01:06,260 - ERROR - Error checking for `feedback_required`, response text is not JSON
```

---

### Describe your issue

Explanation of your issue goes here. Please make sure the description is worded well enough to be understood with as much context and examples as possible.

When using cookies to login, 
I cannot like others' pictures and having request 403 error.

**Comment by AKwoKWH** [comment]
it is the cookies causing the error, 
disable it can solve the issue.

However, if anyone can help to fix the cookies so that we dont need to login-relogin all the time causing the account high risk being ban / shadowban or action block?

**Comment by ohld** [comment]
That is why we disabled cookies by default - we have not had a chance to fix it

**Comment by JuanSpada** [comment]
> That is why we disabled cookies by default - we have not had a chance to fix it



> it is the cookies causing the error,
> disable it can solve the issue.
> 
> However, if anyone can help to fix the cookies so that we dont need to login-relogin all the time causing the account high risk being ban / shadowban or action block?

How can i disable cookies?

**Comment by elmissouri16** [comment]
the previous version the cookies are working  on it but the new one not

**Comment by Rayanox** [comment]
> the previous version the cookies are working on it but the new one not

Could you tell me the commit ID of the version that works please ?

**Comment by Rayanox** [comment]
It seems that some contributors have fixed the cookies issues. Update the pip packages and try once, for my part the 403 error is fixed.

**Comment by ohld** [comment]
@Rayanox 
I've merged your pull requests. Please update *instabot* as well:
```
pip install -U instabot
````

**Comment by Rayanox** [comment]
Great, thanks !
