### ISSUE TITLE
Action Block Immediately

### ISSUE THREAD

**Issue by AKwoKWH** [ohld/igbot#926]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [x] Other

---

### Describe your issue

Explanation of your issue goes here. Please make sure the description is worded well enough to be understood with as much context and examples as possible.

I am getting like block right after the 1st like request. I have this issue for a few days already, which it got like blocked then I waited 24 hours and restarted , but still getting the like block.

In the attachment
You can see my record log that the bot has just like 1 pic then it get block.

Anyone have the same issue?
I am hosting a VM on Google and using a VPN
![Screenshot_20190603-132038](https://user-images.githubusercontent.com/23435188/58778131-ebc39c80-8603-11e9-8f90-8a6fda29fa37.jpg)

**Comment by AKwoKWH** [comment]
Let me also include my code here:

```python

stopWord = ['stopWord1','stopWord2']
stopTag = ['stopTag1','stopTag2']
acctDir = 'path_to_the_directory'
username='userName'
password='password'
proxy = 'proxy_address'
targetAccounts = ['accountID1','accountID2','accountID3']

bot = Bot(	
		whitelist_file='whitelist.txt',
		blacklist_file='blacklist.txt',
		comments_file='comments.txt',
		followed_file='followed.txt',
		unfollowed_file='unfollowed.txt',
		skipped_file='skipped.txt',
		friends_file='friends.txt',
		base_path=acctDir,
		proxy=proxy,
		max_likes_per_day=450,
		max_unlikes_per_day=0,
		max_follows_per_day=300,
		max_unfollows_per_day=300,
		max_comments_per_day=250,
		max_blocks_per_day=100,
		max_unblocks_per_day=100,
		max_messages_per_day=35,
		max_likes_to_like=100,
		min_likes_to_like=0,
		filter_users=True
		filter_private_users=False,
		filter_users_without_profile_photo=True,
		filter_previously_followed=False,
		filter_business_accounts=True,
		filter_verified_accounts=True,
		max_followers_to_follow=3000,
		min_followers_to_follow=50,
		max_followers_to_following_ratio=20,
		max_following_to_followers_ratio=5,
		min_media_count_to_follow=3,
		max_following_to_block=7000,
		like_delay=35,
		unlike_delay=35,
		follow_delay=52,
		unfollow_delay=52,
		comment_delay=70,
		block_delay=70,
		unblock_delay=70,
		message_delay=135,
		stop_words=stopWord,						
		blacklist_hashtags=stopTag,
		blocked_actions_protection=True,
		verbosity=True,
		device=None
	)

bot.login(username=userName, password=password,proxy=proxy)

skippedAccount = bot.read_list_from_file(acctDir + 'skipped.txt')
followedAccount = bot.read_list_from_file(acctDir + 'followed.txt') #Not interact with account previously followed even the bot unfollowed them later

targetAccounts = list(set(targetAccounts)-set(skippedAccount) - set(followedAccount))
random.shuffle(targetAccounts)

print("Found %d users in targetAccounts file." % len(targetAccounts))
for i in range(0,len(targetAccounts)-1):
	bot.like_user(user_id=targetAccounts[i], amount=2, filtration=True)
	bot.follow(user_id=targetAccounts[i])

```

**Comment by AKwoKWH** [comment]
![Screenshot_2019-06-05-12-36-42](https://user-images.githubusercontent.com/23435188/58930641-d29b2700-878e-11e9-87ea-943905f75c1f.png)

Is this a new type of block
It didn't mention the unblock time

**Comment by steffanjensen** [comment]
Yeah you have been blocked by instagram, i also have started to see this happen to me many times over the last week(I am even blocked now). I have seen others having the same issue. Instagram has a better bot protection system right now, they started to really unroll it a few weeks ago and it started to be implemented november 2018. It's machine learning, so now the algorithm is starting to catch up.

I looks like instagram is doing "block likes and comments" as a first punishment, even if you used a bot to do something completely different than likes and comments.

I did 12 likes on and old account today and got restricted for doing "too many likes", but what i was really restricted for was doing to many DM and other stuff.

**Comment by AKwoKWH** [comment]
Seem they have a smart way to do it.
I don't get action Block on my phone. 
Only on the server with proxy I get 400 msg.

They blocked all of my action: comments like follow

I am trying to get away from Instagram detection.
Here is sth that I plan to do:
1) update device info ( the device in this repository is old, Samsung s7 is in 2016. And the Instagram version is 26, while I just checked , the latest one is 98)
2) try to change my proxy

**Comment by AKwoKWH** [comment]
new device added in to repo.
please use device="samsung_galaxy_s9_plus' if needed

**Comment by AKwoKWH** [comment]
> Yeah you have been blocked by instagram, i also have started to see this happen to me many times over the last week(I am even blocked now). I have seen others having the same issue. Instagram has a better bot protection system right now, they started to really unroll it a few weeks ago and it started to be implemented november 2018. It's machine learning, so now the algorithm is starting to catch up.
> 
> I looks like instagram is doing "block likes and comments" as a first punishment, even if you used a bot to do something completely different than likes and comments.
> 
> I did 12 likes on and old account today and got restricted for doing "too many likes", but what i was really restricted for was doing to many DM and other stuff.

Thanks @reliefs
I think so too. Instagram should have a large scale of block over the 2 weeks
I see my account have a drop in followers (seem the drop from bot followers which get blocked)

**Comment by AKwoKWH** [comment]
Can we also check if the request header completed?
I think this might be related to instagram block too.

I am not an expert in this area
Appreciate if someone can help on this.

**Comment by steffanjensen** [comment]
I just remembered something and i saw you commented the post:
https://github.com/rarcega/instagram-scraper/issues/377

The bann started around this time, maybe a week after.

It's maybe related i will try to find other info online, inside other repos and threads.. 

More with same issues:
https://github.com/timgrossmann/InstaPy/issues/4516
https://github.com/timgrossmann/InstaPy/issues/4519
https://github.com/timgrossmann/InstaPy/issues/4490

I have known about this bann hammer for months now, so i am not suprised, that is why i created instabotai, so i could implement machine learning to beat their machine learning bot detection they would unroll, but i haven't had time :(

**Comment by keempoo** [comment]
I am getting an "Action Blocked" warning on my phone both on wifi and on data for following but nothing else (I can like and comment without a problem). Following and unfollowing is what I primarily use the bot for.

**Comment by wanlorn75** [comment]
On my windows machine I can't follow and like but unfollow work just fine.
All actions are fully functional on the smartphone in the instagram app with same accounts and from the same ip address.

**Comment by AKwoKWH** [comment]
> On my windows machine I can't follow and like but unfollow work just fine.
> All actions are fully functional on the smartphone in the instagram app with same accounts and from the same ip address.

Yes. Same case before my account got banned.
They are probably hv a algorithm to detect to identify which action is set from real phone and which action is sent using bot over the HTTP request.

**Comment by wanlorn75** [comment]
Today I've dove some tests like using different IP and declare a different device but I'm still stuck :(

**Comment by reslus** [comment]
Anyone figure out a fix for this "issue"?

**Comment by keempoo** [comment]
I stopped using the bot for 3 weeks and I still can't follow, including
manually, without getting a warning.

**Comment by Oyetomi** [comment]
@AKwoKWH Could you fix the error , I also have this problem

**Comment by AKwoKWH** [comment]
@virginsince1997 @keempoo @reslus @wanlorn75 
Waited for 3 weeks
Then restart my script
It worked fine for a day then being action block again.

**Comment by AKwoKWH** [comment]
I just wondering why some people didn't get affected by the action block.
All my accounts are blocked while some other people seems have no issues at all
If you check the discussion thread, there are not much discussions on the block

**Comment by keempoo** [comment]
I was using the script every day since I have a fairly new account. I
assumed that had something to do with it.

**Comment by wanlorn75** [comment]
One of my accounts is still blocked after more than 3 weeks. For the others I can follow but I get blocked again after around 100 follow actions. I've tested with ultimate and ultimate schedule scripts and with some different custom scripts I've made just for test.

**Comment by AKwoKWH** [comment]
@wanlorn75 
similar, I am in the "block > stop script > unblock > run script > block again" loop

do you use proxy?
not sure if instagram check by Ip address
Iike and follow working charm on my phone, but not my cloud machine

**Comment by dangell7** [comment]
I built my own scrapper and I then saw this one. I'm wanting to implement a few things from this repo, but this issue scares me. My scraper is not blocked because I created similar human patterns.

But... what if, you init the bot, from the same IP address you login with your phone, then run the bot? 

ML is tricky and its hard to know for sure what they are checking for. But off the cuff, I would go IP address, matched with IP from ANY VPN. Block. If first time login from new IP, monitor activity for x,y,z. I would also look for discrepancies in login/logout time. They have BIG DATA on login/logout patterns and I would assume that is another area they focused on. I would also check to see when last login was and from what device. This could also red flag if you logged in on your phone, and logged in 20 mins later from another device/bot, and then logged in on your phone again. That would be pretty easy to pick up. Then you also have liking, commenting, following and story viewing patterns. ML will be able to easily detect anomalies or outliers. These are just a few of the things I would do if Instagram was my app and I wanted to block users. ML Patterns....

**Comment by dangell7** [comment]
@AKwoKWH not sure if this will help. But in my scraper, I don't EVER like or comment without a "stack trace" meaning.... If I want to like a media, I go to the profile first, then like the media. I haven't read the documentation in detail, but thats sort of one example of how I create "human patterns" in my scraper. I also init from the same IP address, as my phone, and I have timers in between every like, follow, comment. For following someone, I have to again go to their profile before following the user. IDK if this would help I just wanted to share my experience with you.

**Comment by wanlorn75** [comment]
> @wanlorn75
> similar, I am in the "block > stop script > unblock > run script > block again" loop
> 
> do you use proxy?
> not sure if instagram check by Ip address
> Iike and follow working charm on my phone, but not my cloud machine

I usually don't use a proxy but I've done some test on a different ip address and I get blocked anyway.

**Comment by Tkd-Alex** [comment]
Same for me :( 
I use a 4G proxies maded by my self, but the action blocked coming very fast. 
Somethimes help a new login.....

I've build also a human pattern, but I don't see any benefits

**Comment by AKwoKWH** [comment]
I run 2 hours then action blocked

**Comment by AKwoKWH** [comment]
I guess it is caused by the log-in and log-out patten
who will bother to click "logout" on their instagram app
this is definitely not a human pattern

**Comment by Tkd-Alex** [comment]
@AKwoKWH 
You can try to disable the logout method and do a new login every time without logout the previous session

**Comment by deopard** [comment]
Same here. Used different proxy and got blocked after three likes. I Tried several times after taking few days of break. But it blocks me right away.
I use Gram Up too but that doesn't get blocked easily. What's the difference between these two?
