### ISSUE TITLE
Error Files

### ISSUE THREAD

**Issue by abdoach** [ohld/igbot#935]
I was using the program without any problem, But when I format my computer and I installed it again I cannot open any file!! Please Check this link to see the problem: https://www.youtube.com/watch?v=f-07tyKiCVk
Please Help! I really need to solve this problem

**Comment by steffanjensen** [comment]
Do 
Pip install -U instabot

or move the examples files, back one folder..

**Comment by abdoach** [comment]
@reliefs Thank you so much🙏 The problem is solved✔

**Comment by steffanjensen** [comment]
No problem, please close this issue.
