### ISSUE TITLE
bug on see_reels function 

### ISSUE THREAD

**Issue by elmissouri16** [ohld/igbot#938]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x ] Updated to the latest version
- [x ] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x ] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

Code:

```python
# Example code that will produce the error reported
from instabot import Bot

bot = Bot()
bot.login(username="user", password="pass")
user_id = bot.get_user_id_from_username('inna')
stories = bot.api.get_users_reel([user_id])
bot.api.see_reels(stories)
```

Error/Debug Log:

```python
Traceback (most recent call last):
  File "bot.py", line 8, in <module>
    bot.api.see_reels(stories)
  File "C:\Users\elmis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instabot\api\api.py", line 905, in see_reels
    for i, story in enumerate(sorted(reels, key=lambda m: m['taken_at'], reverse=True)):
  File "C:\Users\elmis\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instabot\api\api.py", line 905, in <lambda>
    for i, story in enumerate(sorted(reels, key=lambda m: m['taken_at'], reverse=True)):
KeyError: 'taken_at'
```

---

### Describe your issue
 I was just checking the API functions and I find this problem

**Comment by EightShift** [comment]
Similar error ...
Only I have a list of id instead of a single id.

```
bot = Bot()

bot.login(username=username,
		  password=password)
random_hashtag_file = utils.file(HASHTAGS_FILE)
while True:
	random_hashtag = random_hashtag_file.random()
	print (random_hashtag)

	users_list = bot.get_hashtag_users(random_hashtag)
	print (users_list)

	reels = bot.api.get_users_reel(users_list)
	print (reels)

	bot.api.see_reels(reels)

	time.sleep(1)
```

**Comment by elmissouri16** [comment]
#929
