### ISSUE TITLE
Request : Custom Delay on unlikes/likes

### ISSUE THREAD

**Issue by maxupfcc** [ohld/igbot#94]
Hi

I was testing the bot unlike feature using media_id from text file. 

Noticed the delay is a bit too long as where as manually I can do more in one minute. 
So would like to have some custom delay option.

is it possible ?

Regards

**Comment by ohld** [comment]
Done on #95

**Comment by maxupfcc** [comment]
Hi the unlike delay has begun approx 10 seconds between each unlikes.

Issue now is it unlikes 10 media_id and then pauses for a while and then starts again to unlike more 5-10 media_id and pause again.

So is there a way where the bot will not pause after unliking 10 media_id,

It should just wait 10 seconds for each unlike. so 6 unlike in 1 minute and 360 unlike in an hour we can get if we dont get temp banned,.

Regards

**Comment by ohld** [comment]
Fixed in 0.3.3.4
