### ISSUE TITLE
Time between like

### ISSUE THREAD

**Issue by Damny89** [ohld/igbot#949]
- [x ] Updated to the latest version
- [x ] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x ] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x ] Question

How do you set a time between one like and another?

How do you put the like to the last post of each user in the list?

"""
    instabot example
    Workflow:
        Like last medias by users.
"""

import argparse
import os
import sys

sys.path.append(os.path.join(sys.path[0], '../'))
from instabot import Bot

parser = argparse.ArgumentParser(add_help=True)
parser.add_argument('-u', type=str, help="username")
parser.add_argument('-p', type=str, help="password")
parser.add_argument('-proxy', type=str, help="proxy")
parser.add_argument('users', type=str, nargs='+', help='users')
args = parser.parse_args()

bot = Bot()
bot.login(username=args.u, password=args.p,
          proxy=args.proxy)

for username in args.users:
    bot.like_user(username, filtration=False)

**Comment by RouxpiTech** [comment]
Hi, here is how you set a time between one like and another:
```
from instabot import Bot
bot = Bot(like_delay=60) # Replace 60 with the amount of seconds you wish!
```
or 
```
from instabot import Bot
import time

bot = Bot()
bot.login(username=args.u, password=args.p,
proxy=args.proxy)

for username in args.users:
      bot.like_user(username, filtration=False)
      time.sleep(60) # Replace 60 with the amount of seconds you wish!
```
You're welcome

**Comment by ohld** [comment]
![image](https://user-images.githubusercontent.com/5613295/64418519-d5662a80-d0a3-11e9-8f08-edecee7c6c85.png)
