### ISSUE TITLE
Adding sleep time between follow/like

### ISSUE THREAD

**Issue by lidoramrani** [ohld/igbot#951]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [ x] Updated to the latest version
- [ ] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [ ] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

Code:

```python
# Example code that will produce the error reported
from instabot import Bot

bot = Bot()
bot.login(username="user", password="pass")
followers = bot.get_user_followers(bot.user_id)
```

Error/Debug Log:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: integer division or modulo by zero
```

---

### Describe your issue

Hello,
I'd like to add a sleep time of 120 seconds between each follow or like.
I have tried to edit the follow_delay in bot.py file but it seems not to have any effect on the bot itself when I use the follow_users_from_file.py code.
Any ideas on how to do so?

**Comment by EightShift** [comment]
Like this?

```
import os
import sys

sys.path.append(os.path.join(sys.path[0], '../'))
from instabot import Bot
import time

username = "USERNAME"
password = "PASSWORD"
user_to_get_followers = "USERNAME_TO_GET_FOLLOWERS"

bot = Bot()
bot.login(username=username, password=password)

user_id = bot.get_user_id_from_username(user_to_get_followers)
followers = bot.get_user_followers(user_id)
print (followers)
for follower in followers:
    bot.follow(follower)
    time.sleep(120)
```
