### ISSUE TITLE
Liking not working error 405

### ISSUE THREAD

**Issue by sudo-judo** [ohld/igbot#963]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [ ] Updated to the latest version
- [ ] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [ ] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

Code:

```python
# Example code that will produce the error reported
from instabot import Bot

bot = Bot()
bot.login(username="user", password="pass")
followers = bot.get_user_followers(bot.user_id)
```

Error/Debug Log:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: integer division or modulo by zero
```

---

### Describe your issue

Explanation of your issue goes here. Please make sure the description is worded well enough to be understood with as much context and examples as possible.

**Comment by sudo-judo** [comment]
Hello...my inifinity_feedliker has stopped by error 405. Im running on VPS, does anyone know how to fix it?

**Comment by zeing** [comment]
me too

**Comment by stas2z** [comment]
api.py
```
    def get_timeline_feed(self):
        """ Returns 8 medias from timeline feed of logged user."""
        data = self.json_data({'is_prefetch': '0','is_pull_to_refresh': '0'})
        return self.send_request('feed/timeline/', data, with_signature=False)

```

**Comment by sudo-judo** [comment]
I edited api.py as you provided but still no joy, my bot still not working since the last update. I tried to uninstall pip and even delete instabot folder then re-git clone on my VPS but still doesnt work.... Somebody help please

**Comment by sudo-judo** [comment]
It say 405, error while getting timeline feed

**Comment by stas2z** [comment]
> I edited api.py as you provided but still no joy, my bot still not working since the last update. I tried to uninstall pip and even delete instabot folder then re-git clone on my VPS but still doesnt work.... Somebody help please

if you are using it installed by pip, try to modify api.py as i shown above at somewhere like /usr/local/lib/python*/dist-packages/instabot or /usr/lib/python*/dist-packages/instabot, use search to find where it exactly located

`find /usr -name "instabot*"
`

**Comment by sudo-judo** [comment]
And my bots back to bussiness, thanks!!!
Now i get nothing to like after filteration, can u tell me where to add comment? I want to like every single post on my feed, even if those post are get 0 liked. Thanls in advance

**Comment by stas2z** [comment]
> And my bots back to bussiness, thanks!!!
> Now i get nothing to like after filteration, can u tell me where to add comment? I want to like every single post on my feed, even if those post are get 0 liked. Thanls in advance

fetching more than default amount of timeline items require some api researching and doesn't implemented yet as far as i know

**Comment by ghost** [comment]
>         data = self.json_data({'is_prefetch': '0','is_pull_to_refresh': '0'})
>         return self.send_request('feed/timeline/', data, with_signature=False)

This fixed it for me. Thank you so much.

**Comment by doctornuclear** [comment]
>         data = self.json_data({'is_prefetch': '0','is_pull_to_refresh': '0'})
>         return self.send_request('feed/timeline/', data, with_signature=False)

can we not change this in the repo?

**Comment by JudeMurphy** [comment]
I did all of the changes discussed above and am still getting a 405.

**Comment by reslus** [comment]
> api.py
> 
> ```
>     def get_timeline_feed(self):
>         """ Returns 8 medias from timeline feed of logged user."""
>         data = self.json_data({'is_prefetch': '0','is_pull_to_refresh': '0'})
>         return self.send_request('feed/timeline/', data, with_signature=False)
> ```

Does not fix the issue for me.

**Comment by JudeMurphy** [comment]
Bump - This still isn't working for me either.

**Comment by MrMdR** [comment]
Same for me. 
I'll get a 405 error with all the examples, not only liking.
