### ISSUE TITLE
DOCUMENTATION: Add text about Instabot's filtration.

### ISSUE THREAD

**Issue by ohld** [ohld/igbot#97]
We should add a **doc file** with text **how our bot filter the users and medias** to follow and like. 
All the code here https://github.com/instagrambot/instabot/blob/master/instabot/bot/bot_filter.py should be converted to the understandable words. Also the `bot = Bot()` constructor arguments should be added in this doc file. 

Any volunteers?

**Comment by penarubah** [comment]
want me to do this?

**Comment by ohld** [comment]
@penarubah Do this if you want.
