### ISSUE TITLE
Interface Web

### ISSUE THREAD

**Issue by LeandroLimaPRO** [ohld/igbot#971]
Okay, well, is there any visual interface to the bot? Without being a CLI? Maybe WebSite?

Well, if I do not intend on a FORK and start developing in DJANGO, I'm new with such modules.

I tried GramUp, but it needs the open chrome, and the automatic part (schedule), just like the example, is not implemented.

**Comment by malakhov-dmitrii** [comment]
Maybe something like REST API would be more preferable solution?

**Comment by djtroi** [comment]
Check out GramUp. It's from the same Developer as this Repo, probably the same script too. 

You can use GramUP on the python too.

**Comment by ohld** [comment]
yep, the same developers, the same organization.

https://gramup.me
