### ISSUE TITLE
"file is broken" when running multi_script_CLI.py

### ISSUE THREAD

**Issue by maxiwebb** [ohld/igbot#973]
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [] Question
- [ ] Other

---

### The following sections requests more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:

Code:

I'm trying to install and run the instabot with the following commands:
```
easy_install pip
pip install -U instabot
git clone https://github.com/instagrambot/instabot --recursive
cd instabot/examples
python3 multi_script_CLI.py
```

Error/Debug Log:

```
Your file is broken. We will delete it and try again.
We need to create a text file 'secret.txt' where we will store your login and password from Instagram.
```

---

### Describe your issue

The configuration guide is started and I can set the follower-values and so on. But when I have to type in my login values I get the error message that my file is broken. 
Did I miss something? The login credentials are right and every time when I try to type it again I get the same error. I also deleted everything and tried it again. The secret.txt file exists but is empty.

**Comment by maxiwebb** [comment]
push

**Comment by ghammari968** [comment]
uppp
