### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'get'

### ISSUE THREAD

**Issue by AldoMan93** [ohld/igbot#977]
### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### Describe your issue
Error on UNFOLLOW
line 7, in unfollow
username = user_info.get("username")
AttributeError: 'bool' object has no attribute 'get'

**Comment by ohld** [comment]
Just solved with latest changes! Update instabot to get the updated instabot:

``` bash
pip install -U instabot
```
