### ISSUE TITLE
function that blocks inactive users - who don't like your last medias

### ISSUE THREAD

**Issue by rasperepodvipodvert** [ohld/igbot#98]
Как почистить профиль от ботов в Instagram и не убить при этом охват

Одна из самых обсуждаемых тем в продвижении Instagram - блокировка ботов для повышения ER. Все понимают, что этим нужно заниматься, но как делать это правильно?

Статья содержит топ ключевых ошибок при блокировке ботов и небольшой чек-лист для правильной очистки профиля. 

https://dnative.ru/instagram/kak-pochistit-profil-ot-botov-v-instagram-i-ne-ubit-profil/

**Comment by rasperepodvipodvert** [comment]
http://blog.instagram.com/post/141107034797/160315-news

**Comment by antonsharov** [comment]
So does anyone has a code receipt?

**Comment by stasfilin** [comment]
@antonsharov not now, if you want you can do this

**Comment by ohld** [comment]
That was introduced in 0.3.3.4 and added by @ppleskov. See block_bots.py example.
