### ISSUE TITLE
bot.api.get_location_feed always getting empty items

### ISSUE THREAD

**Issue by A-Iskakov** [ohld/igbot#984]
### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Paste the output of ``python -V`` here:
Python 3.7.3 (default, Apr  9 2019, 04:56:51) 
[GCC 8.3.0] on linux

Code:

```python
# Example code that will produce the error reported
from instabot import Bot

bot = Bot()
bot.login(username="user", password="pass")
bot.api.get_location_feed(finded_location)
location_feed = self.api.last_json
photos = location_feed.get('items')
print(photos)

```

Error/Debug Log:

```python
None
```

---

### Describe your issue

`get_location_feed` always returns only stories but not the photos (items) of a location

**Comment by A-Iskakov** [comment]
as I noticed, to get photos you have to pass `max_id` argument with an integer

**Comment by AKwoKWH** [comment]
@A-Iskakov , did you solve it?
I used to able to get the items, but got nothin recently
