### ISSUE TITLE
ERROR - Error checking for `feedback_required`, response text is not JSON

### ISSUE THREAD

**Issue by efaria** [ohld/igbot#985]
I GET THIS ERROR ON UBUNTU 

but on windows works fine, someone knows why ?
```

2019-07-28 13:54:04,183 - INFO - Unfollowing non-followers.

 ===> Start unfollowing non-followers <===

`bot.following` is empty, will download.
Getting followings of 5906787256: 100%|██████████| 825/825 [00:00<00:00, 1007.51it/s]

`bot.followers` is empty, will download.
Getting followers of 5906787256: 100%|██████████| 369/369 [00:00<00:00, 513.28it/s]
  0%|          | 0/350 [00:00<?, ?it/s]
===> Going to unfollow `user_id`: 638005949 with username: XXXXXXXXX
2019-07-28 13:54:10,065 - ERROR - Error checking for `feedback_required`, response text is not JSON
2019-07-28 13:54:10,708 - ERROR - Error checking for `feedback_required`, response text is not JSON
2019-07-28 13:54:11,337 - ERROR - Error checking for `feedback_required`, response text is not JSON
2019-07-28 13:54:11,689 - ERROR - Error checking for `feedback_required`, response text is not JSON
```

**Comment by sitems** [comment]
I have the same error with save_users_followers_into_file.py

**Comment by ElliotPadfield** [comment]
Could you use the issue template because this is pretty hard to diagnose without the info in the template?

**Comment by maryamkhidir** [comment]
I am currently facing the same error running save_users_following_into_file.py. Any solution yet?

**Comment by ghost** [comment]
The same error with welcome_message.py T_T help anyone

**Comment by lxknvlk** [comment]
same with bot.unfollow(). Probably this error appears when i try to unfollow a user that i am not following

**Comment by aleeepp** [comment]
same here

**Comment by TronFortyTwo** [comment]
Same when trying to create a new post

**Comment by saifullah9002** [comment]
Request returns 415 error!
Error checking for `feedback_required`, response text is not JSON
2019-12-03 14:30:14,120 - INFO - Photo 'C:\Users\user\Desktop\images\image_11.png' is not uploaded.

same here. any fix for this issue
i am using windows

**Comment by mehranj73** [comment]
yeah mine too, auto post gives this error

**Comment by bruvv** [comment]
Closing this since its a very old issue. If this is still an issue please open a new one.
