### ISSUE TITLE
Not possible to log in. Reset and try again

### ISSUE THREAD

**Issue by disayner** [ohld/igbot#988]
- [ x] Updated to the latest version
- [ x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [ x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

```python
# Example code that will produce the error reported
from instabot import Bot

bot = Bot()
bot.login(username="user", password="pass")
followers = bot.get_user_followers(bot.user_id)
```

Error/Debug Log:

2019-07-31 15:47:08,958 - INFO - Instabot Started
2019-07-31 15:47:11,670 - ERROR - Request returns 400 error!
2019-07-31 15:47:11,671 - INFO - Instagram's error message: challenge_required
2019-07-31 15:47:11,672 - INFO - Error type: checkpoint_challenge_required
2019-07-31 15:47:11,672 - INFO - Checkpoint challenge required...
Checkpoint challenge received
0 - Phone
1 - Email
Insert choice: 0
A code has been sent to the method selected, please check.
Insert code: 675948
2019-07-31 15:47:44,611 - ERROR - Not possible to log in. Reset and try again
2019-07-31 15:47:44,612 - INFO - Username or password is incorrect.

Hello. Whatever I do does not allow to enter. I tried the code from the phone, the code from the e-mail, went to the web version and chose it, I went. I went to the browser before entering. I went out with a browser before entering. I tried a bunch of variations and nothing fits... IP is the same as in the web version, bought it specifically for this account. The web version is working fine. Please tell me how to log in to the account from the instabot?
```

**Comment by disayner** [comment]
I found this solution, first run the script:

```
import glob
import os
import sys
import time

sys.path.append(os.path.join(sys.path[0], '../../'))
from instabot import Bot

bot = Bot()
try:
	bot.login(username='user', password='pass', proxy='proxy', use_cookie=True)
except Exception as e:
    bot.logger.error("error")
    bot.logger.error(e)

time.sleep(60)
bot.logout()
```

After this, a file with cookies is created which allows other scripts to log in correctly. If you disable cookies, instagram again asks to enter the phone. I'm not sure that all scripts work correctly with the included cookies. Perhaps you know a better solution?

**Comment by mrallanodreman** [comment]
How can i run this script?

**Comment by disayner** [comment]
> 
> 
> How can i run this script?

Just copy another script. Rename it. Paste the code that I wrote inside with a notepad. Change the username and password to yours. If a proxy is used, replace it too; if not, just remove it (", proxy='proxy'"). Save and run by double tapping. The folder with cookies will be the current folder of the script (all scripts that will also need to be run from this folder).
If an error still occurs, go in from a web browser and enter a confirmation code if necessary. Close your browser and wait a day. Delete all the files created around the script and try to run it again.

**Comment by disayner** [comment]
> 
> 
> > How can i run this script?
> 
> Just copy another script. Rename it. Paste the code that I wrote inside with a notepad. Change the username and password to yours. If a proxy is used, replace it too; if not, just remove it (", proxy='proxy'"). Save and run by double tapping. The folder with cookies will be the current folder of the script (all scripts that will also need to be run from this folder).
> If an error still occurs, go in from a web browser and enter a confirmation code if necessary. Close your browser and wait a day. Delete all the files created around the script and try to run it again.

Unfortunately, the method does not give anything. All actions are not available ...

**Comment by mrallanodreman** [comment]
Well whe cant log, because instagram improve another update,

**Comment by disayner** [comment]
Are you offered to enter the code through instabot?
