### ISSUE TITLE
getting russian hashtags issue

### ISSUE THREAD

**Issue by yoshkin** [ohld/igbot#989]
### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
➜  examples git:(master) ✗ python get_hashtags_from_keywords.py яхты яхта
2019-07-31 22:17:03,327 - INFO - Instabot Started
Which account do you want to use? (Type number)
1: hidden
0: add another account.
-1: delete all accounts.
1
2019-07-31 22:17:05,935 - INFO - Logged-in successfully as 'hidden'!
Generating dispositions...
Traceback (most recent call last):
  File "get_hashtags_from_keywords.py", line 35, in <module>
    for i in tqdm(dispositions(sys.argv[1:])):
  File "get_hashtags_from_keywords.py", line 28, in dispositions
    res += [' '.join(c) for c in p]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 0: ordinal not in range(128)

```

### Describe your issue

When i run python script in examples folder "get_hashtags_from_keywords.py" whit passing russian hashtags - i getting error about " 'ascii' codec can't decode byte 0xd1 in position 0: ordinal not in range(128)"
How can i fix it ?
Thanks!

**Comment by ohld** [comment]
Have you used python3 instead of python2?

**Comment by yoshkin** [comment]
@ohld yes, python 3
