### ISSUE TITLE
ERROR - Request returns 405 error!

### ISSUE THREAD

**Issue by MrMdR** [ohld/igbot#990]
### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

Code:

```python
"""
    instabot example

    Workflow:
    1) Downloads your medias

"""

import os
import sys

sys.path.append(os.path.join(sys.path[0], '../'))
from instabot import Bot

bot = Bot()
bot.login()
medias = bot.get_total_user_medias(bot.user_id)
bot.download_photos(medias)

```

Error/Debug Log:

```python

2019-08-01 13:22:08,132 - INFO - Logged-in successfully as '[instaname]'!
2019-08-01 13:22:08,134 - INFO - Saved cookie!
2019-08-01 13:22:08,574 - INFO - Going to download 8 medias.
  0%|                                                                                            | 0/8 [00:00<?, ?it/s]2019-08-01 13:22:11,601 - ERROR - Request returns 405 error!
 12%|██████████▌                                                                         | 1/8 [00:03<00:23,  3.36s/it]2019-08-01 13:22:13,578 - ERROR - Request returns 405 error!
 25%|█████████████████████                                                               | 2/8 [00:05<00:17,  2.85s/it]2019-08-01 13:22:17,205 - ERROR - Request returns 405 error!
 38%|███████████████████████████████▌                                                    | 3/8 [00:08<00:15,  3.09s/it]2019-08-01 13:22:19,495 - ERROR - Request returns 405 error!
 50%|██████████████████████████████████████████                                          | 4/8 [00:10<00:11,  2.85s/it]2019-08-01 13:22:23,223 - ERROR - Request returns 405 error!
 62%|████████████████████████████████████████████████████▌                               | 5/8 [00:14<00:09,  3.11s/it]2019-08-01 13:22:26,804 - ERROR - Request returns 405 error!
 75%|███████████████████████████████████████████████████████████████                     | 6/8 [00:18<00:06,  3.25s/it]2019-08-01 13:22:29,800 - ERROR - Request returns 405 error!
 88%|█████████████████████████████████████████████████████████████████████████▌          | 7/8 [00:21<00:03,  3.18s/it]2019-08-01 13:22:33,235 - ERROR - Request returns 405 error!
100%|████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:24<00:00,  3.25s/it]
2019-08-01 13:22:33,456 - ERROR - Request returns 405 error!
2019-08-01 13:22:33,457 - INFO - Bot stopped. Worked: 0:00:42.477759
2019-08-01 13:22:33,462 - INFO - Total requests: 12

```

---

### Describe your issue

For almost all the scripts I get a 405 error.
I've tried to reinstall python and re-downloaded the Git repo (zip) multiple times.
The error occurs with a lot of scripts (eg liking, commenting, following) but not all (eg 'collect_stats.py'). 
I've searched for the issue and I'm not the only one having this problem. However, no solutions have been found in these (old) issues. 

I've installed python and downloaded the ZIP from the project page. I run instabot trough cmd.exe (I'm fairly new to git)

Thanks in advance!
Mark :)

**Comment by disayner** [comment]
You reinstalled python.
After that, how to remove instabot? And how to install instabot?

**Comment by MrMdR** [comment]
I don't completely understand your comment but I removed python and the Instabot files. I reinstalled python and downloaded the Instabot files again. 
Sadly this I still got the error.

These are my steps:
1) open cmd.exe
2) type`cd downloads\instabot\examples`
3) type `python download_your_photos.py`
opt: 4) give the credentials of my Instagram account

**Comment by disayner** [comment]
You can try it:
1. open cmd.exe
2. pip uninstall instabot
3. Checked that it was deleted by re-entering the command for deletion pip uninstall instabot
4. Downloaded the latest version instabot:
https://github.com/instagrambot/instabot/archive/master.zip
5. unpacked, moved to the instabot-master folder (by CMD) and executed the command
setup.py install
6. after installation try running the script again (download_your_photos.py)

**Comment by MrMdR** [comment]
Thank you @disayner ! Everything seems to work fine now :)
