### ISSUE TITLE
Limits on actions

### ISSUE THREAD

**Issue by VooDooPumpkin** [ohld/igbot#993]
### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Describe your issue

What caused the restrictions on the number of actions per day?

**Comment by disayner** [comment]
Identified empirically by other users. Since Instagram does not give official restrictions. Look for current restrictions on the servers involved in the promotion. And choose at your discretion.

**Comment by VooDooPumpkin** [comment]
> 
> 
> Identified empirically by other users. Since Instagram does not give official restrictions. Look for current restrictions on the servers involved in the promotion. And choose at your discretion.

Thx )
