### ISSUE TITLE
Send more than one message to one user

### ISSUE THREAD

**Issue by VooDooPumpkin** [ohld/igbot#994]
### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

### Describe your issue

Why bot cant send more than one message per user?

**Comment by disayner** [comment]
Does running a script with new parameters not help?

**Comment by VooDooPumpkin** [comment]
> 
> 
> Does running a script with new parameters not help?

I want to send several messages to one user per one bot session (one script run/ bot initialization), is it possible?

**Comment by VooDooPumpkin** [comment]
May be it was my fault, now it works nice. Thx

**Comment by ohld** [comment]
Welcome
