### ISSUE TITLE
comments: Already following, skipping ?

### ISSUE THREAD

**Issue by MrMdR** [ohld/igbot#995]
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

Code:

```python
import sys
import os

sys.path.append(os.path.join(sys.path[0], '../../'))
from instabot import Bot

if len(sys.argv) != 2:
    print("USAGE: Pass a path to the file with comments")
    print("Example: %s comments_emoji.txt" % sys.argv[0])
    exit()

comments_file_name = sys.argv[1]
if not os.path.exists(comments_file_name):
    print("Can't find '%s' file." % comments_file_name)
    exit()

bot = Bot(comments_file=comments_file_name)
bot.login()
bot.comment_medias(bot.get_timeline_medias())
bot.logout()
```

Error/Debug Log:

```python
C:\Users\[[name]]\Downloads\instabot\examples\comment>python comment_your_feed.py comments.txt
2019-08-04 21:12:02,815 - INFO - Instabot Started
Which account do you want to use? (Type number)
1: [[name]]
0: add another account.
-1: delete all accounts.
1
2019-08-04 21:12:05,390 - INFO - Logged-in successfully as '[[name]]'!
2019-08-04 21:12:06,790 - INFO - Received 7 medias.
2019-08-04 21:12:06,790 - INFO - After filtration 4 medias left.
2019-08-04 21:12:06,791 - INFO - Going to comment 4 medias.
  0%|                                                                                            | 0/4 [00:00<?, ?it/s]
`bot.following` is empty, will download.

Already following, skipping!66593: 100%|██████████████████████████████████████████████| 86/86 [00:00<00:00, 330.84it/s]
 25%|█████████████████████                                                               | 1/4 [00:04<00:12,  4.32s/it]
Already following, skipping!
 50%|██████████████████████████████████████████                                          | 2/4 [00:07<00:07,  3.84s/it]
Already following, skipping!
 75%|███████████████████████████████████████████████████████████████                     | 3/4 [00:09<00:03,  3.29s/it]
Already following, skipping!
100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:12<00:00,  3.29s/it]
2019-08-04 21:12:19,146 - INFO - DONE: Total commented on 0 medias.
2019-08-04 21:12:19,444 - INFO - Bot stopped. Worked: 1 day, 6:48:24.606202
2019-08-04 21:12:19,446 - INFO - Total requests: 70
2019-08-04 21:12:19,450 - INFO - Bot stopped. Worked: 1 day, 6:48:24.611142
2019-08-04 21:12:19,452 - INFO - Total requests: 70
```

---

### Describe your issue

Hi, when I run comment_your_feed.py I expect it to put comments under the media on my feed. However, when I run it It does not so because it says 'Already following, skipping!'. What is happening here?

**Comment by ohld** [comment]
set param `filter_users=False`

**Comment by MrMdR** [comment]
This seems to work (y).
However, I would like it to filter out business accounts etc.
Could you explain why it would give this following error?

**Comment by MrMdR** [comment]
And how can I turn filtration completely off?

I still get
 `2019-08-04 23:46:08,515 - INFO - Received 7 medias.
2019-08-04 23:46:08,515 - INFO - After filtration 0 medias left.`
sometimes

Thanks in advance!
:)

**Comment by disayner** [comment]
You can set parameters according to which almost all accounts will be suitable.
More details here:
[https://instagrambot.github.io/docs/en/For_developers.html](url)

Parameters can be set in the same way as you installed the comment file:
bot = Bot(comments_file=comments_file_name, parameter_name1=value,  parameter_name2=value)

**Comment by disayner** [comment]
If you don’t follow the link to the desired document. Copy it and paste it into the browser manually.

**Comment by MrMdR** [comment]
Hi @disayner Sadly that page is incomplete and not helpful. 

Could you please explain what is happening? :)

**Comment by disayner** [comment]
Why do you find this page useless? I suggested you set the filtering options that suit you ( Bot Parameters). All (almost) are described in this document.
For example, you would like to filter business accounts. This parameter is described in the documentation. I showed you how to add it. All together would look like this:
`bot = Bot(comments_file=comments_file_name, filter_business_accounts = True)`
Just select the parameters for your filtering, indicate their names and values.
