### ISSUE TITLE
no 'comment' documentation exists in the developer doc!

### ISSUE THREAD

**Issue by MrMdR** [ohld/igbot#996]
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

### Describe your issue

I noticed the developer documentation of instabot is incomplete. In the table of contents, a whole section on _comment_ exists but none can be found in the actual documentation page - the link is dead/no text exists.

**Comment by MrMdR** [comment]
I don't think commeting works at all. When I use comment by hastag, enter a wierd hashtag only used by a photo of me - instabot says it commeting on like 7 medias but I dont see a comment under my photo

**Comment by disayner** [comment]
Instructions for use
[https://instagrambot.github.io/docs/en/How_to_use.html](url)

Documentation for Developers
[https://instagrambot.github.io/docs/en/For_developers.html](url)

+ Search for previously asked questions

**Comment by disayner** [comment]
Instructions for use
[https://instagrambot.github.io/docs/en/](url)

Documentation for Developers
[https://instagrambot.github.io/docs/en/For_developers.html](url)

+ Search for questions that were previously asked

+ Comments in the script files themselves

If you don’t follow the link to the desired document. Copy it and paste it into the browser manually.

**Comment by MrMdR** [comment]
Hello @disayner ,

This is not what u mean. I know how to use instabot but the effects of some example scripts are not so clear to me. An overview with a better explanation would be helpfull.

Sadly the documentation page does not explain this. (also, I fount it to be incomplete)

**Comment by mrallanodreman** [comment]
@MrMdR suggest the improve....

**Comment by disayner** [comment]
@MrMdR Now I understand. Yes, unfortunately there is no complete documentation. But there are basic documents, having studied which you can solve many issues.
