### ISSUE TITLE
How can I do more than 1000 actions? (like_and_follow_last_user_media_likers.py)

### ISSUE THREAD

**Issue by lidoramrani** [ohld/igbot#998]
I wonder how can I set instabot to do more than a certain numebr of  actions?
You can see in the picture a framework from a session, which is now in the 41/1002 action.
How can I change this number to something I choose?

![Inkedfollow_LI](https://user-images.githubusercontent.com/48685368/62581813-fbd15400-b8b2-11e9-8089-90f0a51811a1.jpg)

**Comment by ElliotPadfield** [comment]
I believe that the number you are talking about is the number of potential users found by the script. If you want to decrease it, change your max like settings. That number will still appear but it will stop when it reaches your custom value. To increase it, it depends on what method you are using to find those users. If you are liking the posts of all followers of an account, the number represents the number of followers. If it is by hashtag, I would imagine that it has something to do with the mobile API. Please follow the issue template and post the code for your script and I'll be able to help further.
